fecgov/fec-cms

fec/fec/templates/base.html

The Wagtail admin user bar is rendered in an iframe, which is blocked by
our Cloud Foundry nginx configuration (via the `x-frame-options`
header). As a result, all scripts loaded after the iframe is inserted
fail for logged-in admin users. As a temporary fix, this patch disables
the admin user bar. In the future @dlapiduz may update the nginx
configuration to let us override `x-frame-options`, in which case we can
revert this change.

Disable admin user bar.

---

fec/home/templates/home/checklist_page.html

Small edit: 48-Hour Notices is the proper noun and should be capitalized.

Capitalization

---

fec/home/templates/home/home_page.html

Adds section for the API docs on the home page. 
Depends on https://github.com/18F/fec-style/pull/88

Adding api doc section

---

fec/home/templates/home/options_page.html

Makes "financial" into "finance"

Eliminates typo

---

.gitignore
fec/fec/static/js/fec.js
fec/fec/templates/base.html
fec/home/templates/home/home_page.html

And adding it to the icon on the glossary card on the home page to open
the glossary.
Requires https://github.com/18F/fec-style/pull/102
Resolves https://github.com/18F/fec-cms/issues/47

Switching to a class for glossary toggle

---

fec/fec/static/js/fec.js
fec/fec/templates/base.html

Apparently the site nav was never implemented on the CMS. So this does it.

Actually implementing site nav

---

fec/fec/settings/base.py

Necessary for URL redirects to work behind the proxy.

Respect x-forwarded-host header.

---

fec/home/models.py
fec/home/templates/home/checklist_page.html
fec/home/templates/home/contact_page.html
fec/home/templates/home/home_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/options_page.html

Adds a new contact page template, though there's no map yet:
I'm thinking we may wait on the map while we figure out our long term map solution. This is the kind of thing we could use our custom map tiles for (if we get them) rather than introducing a third map style.
Thoughts?
Depends on https://github.com/18F/fec-style/pull/135

Adding contact page

---

fec/fec/templates/base.html

This cuts down on candidates like AAAAAAAAAAAAA cluttering the results.
(My Sublime settings also delete trailing whitespace on save.)
Dependent on 18f/openFEC-web-app#795

Linking to candidates that have raised more than $5000

---

fec/fec/settings/base.py
manifest_prod.yml

To be used to control dev banner, among other things.
@noahmanger: use in templates like this
```
{% if not settings.FEC_CMS_PRODUCTION %}
...
{% endif %}
```

Add production flag.

---

fec/fec/static/js/fec.js
fec/fec/templates/base.html
fec/gulpfile.js
package.json

* Add feedback widget to fec.js
* Install and apply stringify transform
* Add app URL globally to base template
Note: this should work locally if the CMS is run with `FEC_APP_URL=http://localhost:3000`. It *will not* work on develop or production until we take the password off. I can work around this if necessary, but I'm not sure it's worth the time. The only caveat is that we'll have to manually check this as soon as the password comes down.
cc @noahmanger

Add feedback widget to base template.

---

fec/fec/templates/base.html

No longer adding `.has-banner` to the body.

Removing has-banner class

---

fec/fec/templates/404.html
fec/fec/templates/500.html
fec/fec/templates/base.html
fec/home/templates/home/home_page.html

Per FEC style request, we're making all beta.FEC.gov and FEC.gov capital `FEC`.
[ci skip]

Content update

---

fec/fec/templates/base.html
fec/home/templates/home/custom_page.html

This removes the previous and next navigation from articles while we wait to figure out how exactly we want it to work (https://github.com/18F/fec-cms/issues/144)
Resolves https://github.com/18F/fec-style/issues/194

Removing next / prev nav

---

fec/home/templates/home/home_page.html

- Un-grays out the registration and reporting card on the home page
- Makes the icon and words a link to /registration-and-reporting
@emileighoutlaw : we want to do this, right?

Enabling registration card on home

---

fec/home/templates/home/checklist_page.html

Noticed today that "File by paper" was under the "File electronically" <ul>. This should pull it back out.
Unless I messed it up, this should be a fast review. :)
cc @noahmanger @jenniferthibault

Fixes parent/child relationship

---

fec/home/templates/home/checklist_page.html

I learned from GOV.UK that headers with verbs that sound like an imperative (something you can do right here and now) are confusing when websites are just providing content about the thing. For example, "Register now" just tells people *how* to register. It doesn't provide the service.
Have updated verb tenses in the checklist items to gerunds (-ing verbs) to clarify that we're just providing content around "Registration and reporting" in this section. 
Resolves: https://github.com/18F/fec-cms/issues/190

Updates verb tenses

---

fec/fec/constants.py
fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html

- Removes the disabled state for the cards on reporting and
registration pages
- Adds links to the calendar filtered down to monthly, quarterly and
pre-and-post-election reporting deadlines
Resolves https://github.com/18F/fec-cms/issues/217
Resolves #212

Enabling calendar cards

---

fec/fec/static/js/calendar.js
fec/fec/tests/js/calendar.js

* Fix width-dependent tests
* Fix order-dependent tests
* Split up tests by category
* Delete unused imports
* Fix linter errors
@noahmanger: do you have a linter running in your editor? I fixed some linter errors in this patch.

Clean up calendar tests.

---

fec/home/templates/home/calendar_page.html

Because I closed a `<div>` in the wrong place. Targeting the release branch so we don't release the wrong markup.

Fix calendar markup.

---

fec/home/templates/home/calendar_page.html

Although the category checkboxes are grouped into several categories,
they all link to the same query parameter and should be represented by
the same filter.
Looks like this regressed in 11418fa79292e8d6cf7669c351ab66d199160560.
[Resolves #248]

Re-consolidate category checkboxes.

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/ssf_checklist_page.html
package.json

Adjusts the breadcrumbs so that essentials pages that may be referenced from the new SSF checklist don't appear nested under the candidate committee essentials list.
- Fixes the link to the campaign guide to go to the SSF guide [Resolves https://github.com/18F/fec-cms/issues/246]
- Resolves https://github.com/18F/fec-cms/issues/245

new breadcrumbs

---

package.json

This changeset updates the dependency to `fec-style` to allow for retrieving the latest patch level.
/cc @noahmanger

Updating the pinned version of fec-style

---

fec/home/templates/home/home_page.html

Now that everything we've previewed as new features is live, we can reinstate the original order of the glossary and registration and reporting cards in the new features section of the home page.
**How it was before:**
**How it was originally, and the order it will be now:**
This alternates the icon colors, and puts the most important content at the front of the list
Note: this doesn't actually change any content, it just rearranges it.

Reinstating the correct order of the new features list

---

README.rst
fec/fec/context.py
fec/fec/settings/base.py
fec/fec/templates/base.html
fec/fec/templates/partials/search-hero.html
fec/fec/urls.py
fec/legal/templates/legal/home.html
fec/legal/views.py

This adds a new `legal` module and page for the [legal resources work](https://projects.invisionapp.com/share/5N6NL76QM#/screens/145835129). This serves as a placeholder where we can put functionality until we figure out where they should live permanently.
This adds a Legal Resources tab in the nav, hidden behind a feature flag. This won't show up on production, but the plan is to have it show in a staging environment so we can get some feedback from clients.
cc @anthonygarvan

Legal resources placeholder page

---

fec/fec/templates/partials/glossary.html

Content only change: 
We've been talking about naming and branding with regards to the 18F site, and so this content piece stuck out to me when we were doing design demo today.
There's lots of available branding and visual clues that people are on the FEC website. So having the glossary called "FEC Glossary" rather than "Glossary," feels a little redundant. And any word we can remove is one less word we to distract site visitors who don't want the cognitive burden of reading. 
Anyone have any objections to this change?
This PR also adds a needed comma after "e.g.," and changes the exampled to "authorized committee" (which is in the glossary, unlike the current "committee," which is not)

Removes "FEC"

---

bin/run.sh

This changeset adds the notification hook that is currently missing in the `run` script.  Closes #272.
/cc @LindsayYoung, @anthonygarvan, @adborden, @noahmanger

Add Notification Support

---

fec/home/templates/home/calendar_page.html
fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/ssf_checklist_page.html

Adds breadcrumbs to the CMS pages following the new designs:

Adding breadcrumbs to CMS

---

fec/home/migrations/0011_ssfchecklistpage.py
fec/home/migrations/0012_auto_20160427_2133.py
fec/home/migrations/0012_partychecklistpage.py
fec/home/migrations/0013_auto_20160427_2133.py
fec/home/models.py
fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/party_checklist_page.html

Adds the static content for political party content.
@ccostino or @LindsayYoung can you review this in the morning and merge to develop so partners can review for an end-of-day release?
Requires adding a new page using the "Party checklist page" template. The page should be titled "Essentials for political party committees".

Adding checklist and landing page content for party committees

---

fec/home/templates/home/landing_page.html

Content only: 
- Updates subhead to clarify what this page is _about_ 
- Shortens and clarifies section on "What does it mean to register and report?"
- Removes arrow for "view registration categories" because content is shortened
Resolves: https://github.com/18F/fec-cms/issues/283#issuecomment-213586159 (and discussion here)
Resolves: https://github.com/18F/fec-cms/issues/282#issuecomment-214481549 (and discussion here)

Updates content for Registration landing page

---

package.json

This changeset brings the `fec-style` dependency up to date with the latest release.

Bump fec-style version to support ~1.10

---

bin/run.sh

This changeset disables any input prompts when running the migrations automatically (e.g., during deployment).  These need to be turned off because our deployments happen automatically and remotely, so we are not on the server actively managing them.
Please refer to http://stackoverflow.com/a/35250116 and https://code.djangoproject.com/ticket/25036 for more details.
There is also the caveat that stale content types won't be deleted with this (as noted in the Django ticket), but I don't believe this is an issue for us right now.

Disable migration prompts

---

fec/home/templates/home/landing_page.html

- Style: https://github.com/18F/fec-style/pull/345
- Web app: https://github.com/18F/openFEC-web-app/pull/1210
- Resolves https://github.com/18F/fec-style/issues/336
- Resolves https://github.com/18F/fec-style/issues/311
Changes style to `h4`:
Removes `t-bold` and uses `h4` without customization
cc @noahmanger

Typesetting

---

fec/fec/constants.py

Spelled out labeling in the left rail of the calendar for the Legal and Advisory Opinions accordions. 
cc: @emileighoutlaw @ccostino

Plain Language updates to calendar filters

---

fec/fec/templates/partials/search-hero.html

Avoids a 301 redirect from openFEC-web-app

Use canonical url for legal search

---

fec/fec/static/hbs/calendar/details.hbs

Changes the name of the close button class to use the new names from the Sass SVG work.

Changing class name to go with new svg stuff

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/ssf_checklist_page.html

We wrote the `party committee termination page` so that it could apply to *all* committees (i.e., be re-used). 
This PR redirects the candidate and SSF termination pages to the reusable one. Once it's live, I'll remove from the other pages from Wagtail. 
cc @ccostino 
This change isn't urgent, but I'd love to get it released as soon as possible. :)

Cms link update

---

.buildpacks
.cfignore
.travis.yml
bin/run.sh
manifest_base.yml

* Switch to vetted python buildpack
* Build assets on travis and include in deploy
* Remove `dist` from `.cfignore`
Part of https://github.com/18F/openFEC/issues/1643.
Note--since auto-deploy won't run from a pull request, verifying this requires merging into develop. Manual deployment can be verified by running `gulp build-js` and deploying as normal.

Build assets on CI.

---

.travis.yml

It looks like Travis was unable to find gulp directly, but it should work within the `npm run` context.

Modify the build-js step to fix Travis deploy

---

tasks.py

Addresses https://github.com/18F/openFEC/issues/1738
This changeset ensures that we only authenticate with cloud.gov if the login environment variables are set (which should only be in the case of a bot, e.g., Travis CI), but that we always change our target organization and space to match what was detected and/or passed in.
h/t to @adborden on accounting for the targeting step!
/cc @LindsayYoung, @jontours, @noahmanger, @adborden, @anthonygarvan

Account for CF target in deploy task

---

tasks.py

When we're using `cf auth`, you need to specify which API to use before hand. Here's the [travis failure](https://travis-ci.org/18F/fec-cms/builds/139029719#L1504).

Target cloud.gov api for deploy

---

fec/fec/templates/base.html
fec/home/models.py

The nav section is based on the wagtail `Page` model. I think this makes sense.
Is there a way to add `content_section` as a model property without making it a database field? I thought we could do something like `full_name` property [described here](https://docs.djangoproject.com/en/1.8/topics/db/models/#model-methods) but it's not exposed in the template.

Add active nav classes based on content page

---

fec/home/templates/home/landing_page.html

Adds links from the registration and reporting landing blurbs to reporting deadlines for each registrant type.
Resolves https://github.com/18F/fec-cms/issues/298
Requires https://github.com/18F/fec-style/pull/410

Adding links to deadlines to reg & rep landing page

---

fec/home/migrations/0014_nonconnectedchecklistpage.py
fec/home/models.py
fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/nonconnected_checklist_page.html
fec/home/templates/home/party_checklist_page.html
fec/home/templates/home/ssf_checklist_page.html

This commit adds:
- Updates landing page with nonconnected committee content
- Adds checklist page for nonconnected committees
- Updates termination page link for all essentials checklist pages (we now have a unified termination page)
- Links to nonconnected content from other checklist pages

Nonconnected content

---

fec/fec/static/js/legal.js

This fixes a dead link by overriding Ethnio's cookie logic.

adding force display flag to override cookie

---

package.json

This changeset accounts for the latest `fec-style` release (2.6.1).

Bump fec-style version to 2.6.1

---

fec/home/templates/home/home_page.html

Moves release notes to right-hand column card. 
Remaining task for @noahmanger in `fec-style` : vertically align text with center of star image

Moves release notes to right hand side

---

fec/fec/static/hbs/calendar/events.hbs
fec/fec/static/js/calendar-helpers.js
fec/fec/static/js/calendar.js

Adds support for category tooltips in list view.
Requires https://github.com/18F/fec-style/pull/402
Resolves https://github.com/18F/fec-cms/issues/337

Adds tooltip content to calendar events

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/nonconnected_checklist_page.html
fec/home/templates/home/party_checklist_page.html
fec/home/templates/home/ssf_checklist_page.html

Makes hierarchical improvements to checklist content. Clarifies relationships of parent and child pages. 
Resolves: https://github.com/18F/fec-cms/issues/408#issuecomment-235633285

Checklist nesting

---

fec/fec/static/js/calendar.js

Adds the loading / success states to calendar filters.
Requires https://github.com/18F/fec-style/pull/435

Adding loading state to calendar filters

---

runtime.txt

With the recent cloud.gov update, the python buildpack no longer supports python 3.4.3, so let's upgrade.
https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.5.8

Bump python for cloud foundry

---

fec/fec/static/hbs/calendar/download.hbs
fec/fec/static/hbs/calendar/subscribe.hbs
fec/fec/static/js/calendar.js
fec/fec/static/js/fec.js
fec/home/templates/home/calendar_page.html

Supports the new designs and styles from https://github.com/18F/fec-style/pull/446
Unfortunately, because a lot of the title area and controls are generated by the FullCalendar library we're using, I had to use some gunky jQuery to move elements around and get them into their proper place. (Not much new from the way this code has been working, though).
cc @jenniferthibault @xtine

Rearranging calendar page

---

fec/home/templates/home/custom_page.html

Reduces the size of headers on the custom page by using the new `header__title--main`
cc @jenniferthibault 
Depends on https://github.com/18F/fec-style/pull/465

Consolidate heading styles

---

runtime.txt

This reverts commit b7bf2ca34539a8be11827c2c6dc247c5e46ade89.
The cms is still on the multi-buildpack, which does not support python 3.4.5.

Revert "Bump python for cloud foundry"

---

fec/legal/templates/legal/home.html

I think we should be consistent in our naming of statutes. 
By that I mean either we refer to them as `Title 26 and Title 52` or `26 USC and 52 USC`. That'll be less for readers to keep in mind when trying to understand statutes. 
I'm going with `Title 26 and Title 52`. 
Content only. Should be a fast merge!
cc @adborden @porta-antiporta

Clarifies language

---

fec/home/templates/home/calendar_page.html

I'm the worst and forgot to add the `data-filter` attributes to the filters on the calendar page. This will fix the calendar in production.

[MERGE WITH GITFLOW] Adds missing data-filter tags

---

fec/fec/templates/base.html

Adds the print logo from https://github.com/18F/fec-style/pull/496
Because certain browsers don't render background images it has to be included as an `img`.

Adding printer-only logo

---

fec/fec/settings/base.py
fec/fec/templates/partials/breadcrumbs.html
fec/home/templates/home/collection_page.html
fec/home/templates/home/latest_updates.html
fec/home/templates/home/press_landing_page.html
fec/home/views.py

This makes  a few fixes to the latest updates page in preparation for the release:
1. It only renders the latest updates view if either the user is authenticated or a feature flag is set. This will allow it to exist on production and be visible to authenticated users, and also on staging / dev / local and be visible to everyone. This page is just created in the code, not the DB, so I had to hide with some mechanism until they're ready.
Two questions (maybe fore @adborden or @ccostino ):
- Am I doing this right? cc @adborden 
- Where do the flags get set for the different environments? 
2. Adds the "updates preview" title to the press page above the feed
3. Removes the "FEC Record" from the filter options
4. Programmatically generates breadcrumb links on the `CollectionPage` template, …

Release fixes

---

package.json

Makes use of the new version of the glossary panel that sets focus on the element that opened the glossary.
cc @xtine

Pinning to new minor update of glossary

---

fec/home/templates/home/landing_page.html

This changes the content per FEC feedback:
> Also, wondering about "can" as in "who can register and report?" It is a legal requirement so I'm tempted to suggest "must" even though that's not the friendliest of greetings. Does suggesting an optional choice stir resentment? If the IRS said "Who can pay taxes?" I'd growl.
Resolves: https://github.com/18F/FEC/issues/489#issuecomment-252088579

Updates content

---

fec/fec/templates/partials/breadcrumbs.html
fec/home/templates/home/digest_page.html
fec/home/templates/home/press_landing_page.html
fec/home/templates/home/press_release_page.html
fec/home/templates/home/record_page.html

Updates the related resources cards on the press page:
Unrelated, it also adds the `.breadcrumbs__link` class to the breadcrumbs on the press release, digest and record pages so the links are white, and removes the "Latest updates:" prefix from the breadcrumb item, per the mockups:
Requires https://github.com/18F/fec-style/pull/535

Adding new icons and copy for related resources cards

---

fec/fec/static/scss/fec.scss

The recent header refactoring introduced a bug where the author list div on press release and weekly digest pages was incorrectly floating to the right of the content body, rather than being stacked below it:
This fixes that bug. 
Note: this CSS is in the CMS repo because the micropurchase vendor put it there. Eventually we should move it to fec-style, but this fixes the bug in the meantime.

[MERGE WITH GITFLOW] Hotfix/fix author list

---

fec/fec/templates/base.html

"View" generally isn't an ideal word for interface copy, because it can feel exclusionary to folks who use screenreaders and aren't "viewing" the text.

Eliminate "view"

---

fec/home/templates/home/contact.html

Changes from betafeedback@fec.gov to webmanager@fec.gov
per @PaulClark2 's request in slack. Access to the original account was lost, so we're replacing it with the existing webmaster email. 
Review: anyone. Maybe @emileighoutlaw

Updating beta feedback email

---

fec/home/views.py

This only shows published updates rather than all updates.
Fixes https://github.com/18F/fec-cms/issues/589#issuecomment-259191571

Only show published updates

---

README.md

We recently configured Gemnasium to watch this repository in addition to the other openFEC-related repositories.  This changeset adds the badge to our `README.md` file.
/cc @LindsayYoung

Adds Gemnasium badge

---

fec/fec/settings/base.py

This adds some checks for to user password strength. 
Note that superusers do not get the additional password validation.

This adds validation for users passwords

---

fec/fec/static/js/calendar.js

Another small inconsistency. Per our style guide we either display dates as:
`MM/DD/YYYY` or `Full month, day, YYYY`

Spells out month in date display

---

fec/fec/templates/long_page.html
fec/fec/templates/partials/breadcrumbs.html
fec/fec/urls.py
fec/home/templates/home/contact.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/press_landing_page.html
fec/legal/templates/legal/ao_process.html
fec/legal/views.py

This implements the AO process page as part of https://github.com/18F/fec-eregs/issues/290
This first pass simply implements it as a hard-coded template in the CMS, rather than making a new page model that would allow this to be edited via the admin interface. I'm open to doing that, but want to hear more about if the content here would change enough to warrant it...or if we just want to adopt the approach that everything should be editable via the Wagtail interface.
[Screenshot](https://cloud.githubusercontent.com/assets/1696495/21068080/4c7f19aa-be24-11e6-9a9f-1f140950f4b1.png)
This is ready for visual review.

Adding AO process page

---

fec/fec/static/js/fec.js
fec/home/templates/home/home_page.html

This fixes an issue where the typeahead was incorrectly being
initialized for the legal search because it also had `.js-search-input`.

Specify typeahead selector

---

fec/home/templates/home/home_page.html

Based on Commissioner seat rotations, the Chairman and Vice Chair titles have been updated on the homepage. This was also recently updated on the current FEC website (http://www.fec.gov/members/members.shtml).

Updated Chairman and Vice Chair titles for Commissioners

---

README.md

Went through the installation again and noticed that some users might prefer to run createdb via their default user rather than as the postgres user. Since when you do a fresh install of postgres, the postgres user is the default and the only user able to run any postgres commands. So I added instructions for altering the role for the default user to be able to create database. 
Also noticed that migrate needs to run first in order to have the auth model to run the createsuperuser command.

Update README.md for easier install

---

requirements.txt
tasks.py

Part of #607
Part of #609
This changeset updates invoke to the latest stable release and updates our corresponding tasks to work correctly with it.  It will also provide new tasks for retrieving and pushing database dumps to an S3 bucket for the CMS app used by the FEC project.  These tasks will make use of the `cg-migrate-db` plugin for Cloud Foundry written by @jcscottiii.
Huge h/t and thank you to @jcscottiii for all of the hard work and help with the plugin!
**UPDATE (01/11/2017)**
I'm opting to take this PR out of WIP status as it is still in good shape, and work has been postponed on the other pieces for the time being.  Furthermore, `invoke` has been updated again with some other changes and I'd rather see these things go in now as opposed to having to redo them again, this way …

Update invoke and related tasks

---

fec/home/templatetags/updates.py

This fixes a bug where draft press releases and weekly digests show up on https://beta.fec.gov/press/
cc @AmyKort

Only show published digests and releases on press page

---

fec/home/templates/home/commissioner_page.html
fec/home/templates/home/commissioners.html
fec/home/templates/partials/commissioner.html
fec/home/views.py

- Set min-width for Commissioner listings and tighten up space between title and party
- Some text updates on Ex-officio
- Unify type styles between All Commissioner and Commissioner pages
Requires: https://github.com/18F/fec-style/pull/610

Commissioner Page design updates

---

fec/home/templatetags/updates.py

Only show published posts on the "Whats Happening" section on the homepage. This updated PR is made off of master this time. 😅

Hide draft posts on Homepage

---

fec/fec/static/js/fec.js
fec/fec/static/scss/fec.scss
fec/fec/templates/partials/author-list.html
fec/fec/templates/partials/update.html
fec/home/templates/home/latest_updates.html
fec/home/templates/home/updates/digest_page.html
fec/home/templates/home/updates/press_release_page.html

This makes a few of the clean up changes from https://github.com/18F/fec-style/issues/614
- Adds a "Read more" link (needed to use javascript to get it inline)
- Capitalizes the first letter of the categories
- When clicking on a tag, it now takes you to the `#feed` div so that the filters are at the top of the screen. 
- Removes the `p--lead` sizing on the first paragraphs.
- If title and email are 'N/A' then they're not displayed on posts
Last, it adds space between the "next item" and the link back to the latest updates page, resolving https://github.com/18F/fec-cms/issues/712:

Cleaning up aspects of the fec record articles

---

fec/home/templates/home/legal/enforcement.html

Our content strategy has shifted so that all complaints content is included in the "Complaints" section. We're no longer planning to develop a "Report a violation" page, so I'm removing the option and its "Coming soon."
Content only.

Removes "Report a violation"

---

fec/fec/templates/partials/update.html

The current behavior is outputting multiple paragraphs if they’re stored as separate blocks in the body streamfield. 
Instead of looping through all body blocks and looking for paragraph block types, this just checks the first two blocks for a paragraph. This way, if the first block is an image, it will be ignored. If the first block is a paragraph, it will just show the one paragraph.

Only show the first paragraph block in the latest update preview

---

fec/fec/static/hbs/calendar/details.hbs
fec/fec/static/hbs/calendar/events.hbs
fec/fec/static/js/upcoming-events.js
fec/home/templates/home/home_page.html
fec/home/templates/partials/home-page-updates.html

These changes are designed to make the layout more flexible for fewer items. When items have fewer columns to fill, there are fewer gaps left by different item/line lengths.
**Changes:**
- Moves layout to two-column grid and splits "Upcoming events" into it's own item, instead of being part of "What's happening"
I wasn't able to get data or events to populate these fields when I was running it locally, so it MUST be reviewed by someone who can prove that I didn't accidentally break the functionality.
Through inspector, I was able to simulate what I think the changes will do, but it really needs to be run to prove it!
This is a partial improvement toward https://github.com/18F/fec-style/issues/602

Restyling "What's happening" section of the home page

---

fec/home/templates/home/home_page.html

Since we've released the Mission and history page, this link no longer needs to go to the old FEC site. 
cc @emileighoutlaw

Home page: Directs Mission link to beta site instead of old site

---

fec/fec/forms.py
fec/home/templates/home/contact-form.html

Removes all of the `max_length` attributes from the RAD contact form.

Removing the max-length on the committee name field

---

fec/fec/static/js/vendor/beautify-html.js
fec/fec/wagtail_hooks.py
package.json

As @johnnyporkchops noted in https://github.com/18F/fec-cms/issues/830, in production, the Wagtail editor isn't able to find the `beautify-html.js` script, which is preventing the "edit HTML" button from working. It _should_ be able to locate this inside `node_modules/js-beautify/js/lib/`, as it does when developing locally, but for some reason it's not. 
I'm stumped, so here's a workaround. This just moves that single script to the `/static/js/vendor/` directory. It works locally for me, and seems like a safer bet that it should work in production. 
Definitely open to other ideas though.

Adding beautify-html.js to vendor scripts

---

fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
fec/home/templates/home/legal/legal_resources_landing.html
fec/home/templates/home/registration-and-reporting/landing_page.html

This puts the links to the contact form behind feature flags so that they won't show up unless the flag is enabled.

Putting card links to form behind feature flag

---

fec/home/templates/home/legal/legal_resources_landing.html

Removes the call to action buttons from Legislation, Court cases, and Policy statements because 
1. These buttons should only be used when a call to action is needed
2. If everything gets a call to action, then they compete with one another
3. These sections are the least fleshed out, and less-used at the moment.
cc @emileighoutlaw or  @noahmanger for review

Removing unneeded buttons from legal home

---

fec/home/templates/home/legal/legal_resources_landing.html

Per discussion with @AmyKort in Slack, this separates the court cases and policy statements sections, as they're not actually related. 
I'm suggesting leaving off the button-style call-to-action links for these sections though in order to keep emphasis on the above sections.

Separating court cases and policy statement sections

---

fec/home/templates/home/agenda_page.html

The agenda page template is missing a Wagtail tag within one of the template instructions, the `include_block`: http://docs.wagtail.io/en/v1.9/topics/streamfield.html#template-rendering
This fix enables the template to render properly in both the preview and live view modes.

Fixes agenda page template

---

fec/home/templates/home/candidate-and-committee-services/services_landing_page.html

Fixes a small misspelling in the disclaimer. Anyone can review, but this definitely needs to be deployed before the `Help for candidates and committees` section can launch.

Eliminates typo in "actively"

---

package.json

**NOTE:  MERGE WITH GIT FLOW**
This changeset updates jQuery to the latest 2.x release after we received notice of a secuirty vulnerability this morning.  This includes an update to fec-style as well, which also received the update.

[MERGE WITH GIT FLOW] Critical: Updates jQuery to address security vulnerability

---

requirements.txt

Turns out that including these two dependencies is something pip warns against - removing them to ensure things work as expected (or break as expected for that matter).

Removing setuptools and wheel due to pip warning output

---

package.json

This changeset addresses the jQuery vulnerability we encountered a bit further by ensuring that a dataType parameter is set on our ajax requests.  We cannot do an upgrade to the 3.x series of jQuery just yet, so to help mitigate any potential threat we are ensuring our requests do not accept scripts to be executed.  We will update jQuery to the latest release in the near future after we have had a bit more time to test the changes and address any compatability issues.

[MERGE WITH GIT FLOW] Add dataType to ajax request

---

fec/data_loader/management/commands/import_meeting_agendas.py
fec/data_loader/management/commands/scrape_meeting_agendas.py

This changeset resolves a small issue with import statements in the meeting agenda scraper and importer.  This fix is being made in anticipation of having to run these once more in production once the release is done.

Fix import statements for meeting agendas

---

fec/home/templates/home/candidate-and-committee-services/services_landing_page.html

This fixes a few empty links I accidentally left earlier and replaces them with transition urls.

Adding links to transition pages

---

fec/home/templates/home/about_landing_page.html

This just adds a check on the About landing page so that if there's no `button_text` value set, the button won't display:
Resolves https://github.com/18F/fec-cms/issues/893

Conditional check on section button for about page

---

fec/fec/templates/partials/site-orientation.html
fec/home/templates/partials/candidate_committee_services.html

Corrects the training link on the home page

Correcting youtube link

---

fec/home/templates/partials/candidate_committee_services.html

Eliminates "free," from video links, so that we don't accidentally imply that some videos are paid.
Also updates which words we wrap in our `<a href>` to make the links more clear for screenreaders.
🔍  🎩  h/t @fechoosier for the copyedit find. 
Content only; anyone can review.

Deletes "free" from video 

---

fec/fec/templates/long_page.html
fec/home/templates/home/custom_page.html

Fixes a small issue where legal citations didn't print. That's because both `<asides>` and `.sidebar` are hidden when printing. So I just removed those from the citations boxes.
Resolves https://github.com/18F/fec-cms/issues/999

Changing markup so legal citations print

---

fec/fec/settings/base.py
fec/fec/templates/404.html
fec/fec/templates/500.html

New 404 and 500 pages based on https://github.com/18F/fec-cms/issues/966
It was suggested in the conversation to change "previous FEC.gov" to "old FEC.gov design." If this needs to be changed back, let me know.

new error pages

---

fec/fec/settings/base.py
requirements.txt

This changeset addresses an issue we have been having with the cloud.gov session/token timeout being reduced to 10 - 15 minutes.  The underlying UAA client we are using, cg-django-uaa, required an update to support refreshing tokens so that sessions remain valid while a user logs in.
A huge thank you to @toolness for providing the fix in cg-django-uaa and helping us address this issue!

Fix session timeout issue with cloud.gov

---

fec/fec/templates/base.html

Adding link to transition IG page

---

fec/home/templates/home/home_page.html

Small thing I noticed: since we're not launching the public info pages, we need to remove the links on the home page.

Removing links to citizens info

---

fec/fec/settings/base.py

Using `env.get_credential` instead of `os.getenv` in the hopes that it fixes the broken API calls.

Use env.get_credential

---

fec/fec/settings/base.py
fec/fec/wsgi.py
fec/search/management/commands/index_pages.py

This changeset fixes a few more env var references and makes use of the `env.get_credential()` method to ensure that an env var is found.  To recap, that method checks the credential service in Cloud Foundry first for an env var, and if it cannot find it then it falls back to checking the host environment the app is running in.  This method works in both the deployed apps and locally for that reason.

Update remaining env var references

---

fec/fec/constants.py
fec/home/templates/partials/candidate_committee_services.html

It turns out the calendar data was correctly coded all along, we just weren't exposing the filters on the front-end. 
This adds them here:
And also adds them in the URLs from the home page.
cc @llienfec @AmyKort @anthonygarvan

Adding mid-year and year-end filters

---

fec/home/templates/home/home_page.html

Dependent on image in https://github.com/18F/fec-style/pull/702
Replaces the outdated brochure with the brand new video.
@noahmanger, could you please run this locally to check and post a screenshot?
I ran into errors getting my local env up and running but didn't want to block the progress of a quick item.

Replacing citizens' brochure with video

---

fec/data_loader/management/commands/import_meeting_agendas.py

This is a hotfix to change the model references in the meeting agenda import script to reflect the recent model changes.  The model name had changed to `MeetingPage` from `AgendaPage`, but the import script was not updated to account for this.

[MERGE WITH GIT FLOW] Fix meeting agenda import script

---

fec/fec/static/js/calendar-helpers.js
fec/fec/static/js/home.js
fec/fec/static/js/upcoming-events.js
fec/gulpfile.js
fec/home/templates/home/latest_updates.html
fec/home/templates/partials/home-page-updates.html
fec/home/templatetags/home_page.py
fec/home/views.py
package.json

This makes a few final fixes for the meetings to be released tomorrow.
1. It adds the open meeting agendas to the "What's happening" section:
2. It removes the check on user authentication for showing meetings on latest updates, thus adding it as an option (I also arranged these alphabetically like we discussed @jameshupp ):
3. It re-arranges the content in the "About latest updates" box to more closely match the order in the select:
4. It fixes a bug that @AmyKort noticed where certain events weren't showing up in the "upcoming events" feed. I figured out that this is because in a case like `category=Open+meeting`, the `+` was being url encoded. I changed the calendar URL builder to decode the URL, but maybe there's a better way?

Meeting feed fix

---

README.md

replaces with `FEC.gov`, `the FEC`, or `the new FEC.gov` as appropriate.

swap out beta references from README

---

fec/fec/templates/partials/site-orientation.html

Update the "Start the tour" button for post-flip.
Relies on https://github.com/18F/fec-style/pull/720
https://github.com/18F/fec-cms/issues/1081

Update "Start the tour" button

---

fec/search/templates/search/search.html

Correcting a misspelling pointed out to Judith Ingram by a user:
**Judith wrote via email:**
Hi.
We got a message flagging a misspelling of the word purchase on the page here:https://www.fec.gov/search/
It's under Other Search Tools, Disbursements
Thanks.
Judith Ingram
Press Officer
Federal Election Commission

changed "Purhcases" to "Purchases"

---

fec/fec/constants.py
fec/fec/settings/base.py
fec/home/utils/search_indexing.py
fec/home/wagtail_hooks.py
fec/search/management/commands/index_pages.py
fec/search/management/commands/scrape_cms_pages.py
fec/search/tests/test_indexing.py
fec/search/utils/search_indexing.py

This adds Wagtail hooks for automatically adding, updating and deleting pages from the DigitalGov search engine. I basically took the same methods used for manually updating the index, refactored slightly and then added to Wagtail hooks on page creation, editing and deletion.
Still to do:

Adding support for automatic search indexing

---

fec/fec/templates/partials/update.html
fec/home/templates/home/meeting_page.html

To create "Sunshine Act Notice" as an official document title in the latest updates feed and on meeting pages.

Capitalizing "Notice"

---

fec/home/templatetags/home_page.py

In order to reduce duplicate content on the home page, this removes the meeting agendas from showing up in the "What's happening" updates feed on the home page, as they're already included in the calendar feed below. 
It also fixes an issue where when adding a generic update to the home page, it would add it as a fifth item, rather than limiting the total number of items to four.

Remove home meeting agendas

---

fec/fec/wagtail_hooks.py

This adds the `data-term` attribute to the `span` attribute whitelist so that glossary terms can be added by editing the HTML of a Wagtail paragraph block. Previously the attributes were stripped out.

Adding data-term attribute to whitelist

---

fec/home/templates/blocks/disabled-page-links.html
fec/home/templates/blocks/page-links.html

This removes the `usa-width-one-half` class and right arrow quote mark from the page link blocks, as that will now all be controlled by separate CSS:

Remove arrow and width class from page link blocks

---

fec/data_loader/management/commands/import_executive_sessions.py
fec/data_loader/management/executive_sessions.json

This adds an import script and json file to import the pre-2017 executive session sunshine notices.
Major thanks to @dorothyyeager for the heavy lifting on gathering the data!
Resolves https://github.com/18F/fec-cms/issues/980

Adding script and data to import executive sessions

---

fec/fec/urls.py
fec/home/views.py

**Background**: It seems that Django's default is to serve documents as "attachments".  So clicking on links to PDFs forces download instead of using the built in PDF viewer available in most modern browsers.
Documents added to the CMS either by pasting a URL into a text type fields (URLField, TextField, etc) or documents uploaded to the documents tab of the CMS via the document option in a RichTextBlock interface are force-downloaded instead of viewed in browser.
Documents added via a DocumentChooserBlock can be configured at the template-level to view in browser, instead of download by adding "file" before the URL in the template block, like this example:
Change ```block.value.item_audio.url``` to  ```block.value.item_audio.file.url``` (https://github.com/18F/fec-cms/pull/1086)
But the …

View PDF documents in browser instead of force-download

---

fec/home/templates/home/commissioner_page.html

`Currently Serving` > `Currently serving` for commissioner terms
As seen:

Lowercase "serving"

---

fec/fec/urls.py

After pointing out that /django-admin shows the Django admin interface, @LindsayYoung and @ccostino asked me to do a PR to make it so you would only see this if in debug mode. I removed the URL pattern for this in the global urlpatterns and added it to the "if DEBUG" section.
With this change,  locally , If I set ```DEBUG= False``` in fec/settings/dev.py, the Django admin does not show, setting it to true makes it show. I am not sure how this fits in with production.py and base.py on the live site. 
If this is wrong or incomplete and it requires adding a setting/change to base.py and/or production.py, please let me know and I can make the change. At least this PR gets the change started.

Hide django-admin unless in debug mode

---

fec/fec/settings/base.py

This resolves issue #1140 
Note that this will require an additional environmental variable added to set the custom path variable `CMS_AWS_CUSTOM_DOMAIN=www.fec.gov/resources`
This PR allows us to maintain user friendly URLs when accessing content uploaded to CMS.

Implemented Custom Domain Path for CMS Uploads

---

fec/fec/templates/partials/update.html
fec/home/templates/home/meeting_page.html

Issue https://github.com/18F/fec-cms/issues/1144
Show multiple amended Sunshine Act notices with numbers. One change made to the meeting_page.html template is to show the notices in the order they are added to the field rather than reversed (newest first). If I left them reversed it was over-complicated to get the order correct, but adding the numbers solves any confusion with that on the rendered page.

Multiple numbered, amended Sunshine Act notices

---

fec/home/templates/blocks/mur_search.html

This removes the line about the archived MURs not being included on enforcement page:

Removing line about archived murs not being included

---

fec/home/templates/home/candidate-and-committee-services/services_landing_page.html

This adds an ID for `#campaign-guidance` to the div that contains the sections on Help for candidates and committees so that the new nav link from https://github.com/18F/fec-style/pull/752 takes you to the right place.

Changing ID of container for campaign guidance sections

---

fec/home/models.py

Currently, trying to delete a page in Wagtail can result in a server error if there is not a `user_id` in `kwargs['instance']`. This just updates the logic a to be a little more forgiving if that's the case. 
Can @ccostino or @LindsayYoung double-check this?
Resolves https://github.com/18F/fec-cms/issues/1189

Fix logging of user info on page delete

---

fec/home/wagtail_hooks.py

This uses Wagtail's `ModelAdmin` hooks to implement custom admin panels for the latest updates. 
Now, there will be a new menu item for "News and updates", which contains links to each type of update:
Each one of those takes you to a view that is default sorted by the original date of the item:
I think this is actually a much better approach than the "Folder" concept earlier as it doesn't require any redirects or moving pages around.

Adding custom admin panels for news and updates

---

fec/fec/templates/partials/meeting.html
fec/home/models.py
fec/home/templates/home/commission_meetings.html
fec/home/templates/home/home_page.html
fec/home/templatetags/filters.py

This includes a few meeting refinements after pairing with @jenniferthibault . 
- Search inputs are now wider
- There's no search input on exec sessions
- The list now uses the `title` field to display and I added a filter for stripping away the words `open meeting` or `executive session` so that you can include the "cancelled" status in the meeting title
Requires an fec-style change

Meeting refinements

---

fec/fec/wsgi.py
requirements.txt

This changeset improves the New Relic initialization to take into account whether or not the New Relic license key is present or not.  In our current setup and workflow, the New Relic license key is always set in the cloud.gov environment, but never locally (unless we are testing this integration explicitly, in which case it is required).  The existing code assumes the license key is always present and attempts to initialize the New Relic Agent, resulting in a multitude of warnings and errors in local development environments that makes it difficult to debug and work.
The setup is copied from our current web app and API New Relic initialization configs.
Lastly, this also adds the pdbpp package for improved command line debugging.

Improve New Relic initialization

---

fec/fec/static/scss/calendar.scss

This adds the necessary style file for the accordions used in the calendar filter area.

Adding accordion.css to calendar

---

fec/home/templates/home/latest_updates.html
fec/home/views.py

This removes the meetings from the latest updates page now that they're on their own page. It doesn't do anything about moving the actual agendas within Wagtail out from under `/updates/` it just removes them from the feed.

Removing meetings from latest updates

---

.travis.yml
fec/.coveragerc

Removing django_coverage_plugin because they don't work with the Jinja templates for data and legal apps.

Remove django_coverage_plugin

---

package.json
tasks.py

This changeset fixes an issue we are having with the deploy step in the CircleCI environment.  It appears that the Django commands are not able to find where certain files are located, particularly those found in the `fec/dist` directory.
There is a larger issue here with the referencing to the path(s) of static assets, but we are fixing the immediate problem first.
Huge h/t to @tbaxter-18f and @cmc333333 for their help in debugging this issue!

Fix deploy steps to run commands in proper working directory

---

.circleci/config.yml
fec/data/templatetags/filters.py
fec/home/templatetags/filters.py

This changeset fixes an issue with static file paths being hardcoded and therefore not being found if things are being run outside of an expected directory.  It leverages the `STATIC_ROOT` setting in Django to form the first part of the file path referencing the static asset.
Furthemore, the Django tests expect all static assets to be in the `STATIC_ROOT` directory, so this changeset also adds a tweak to the CircleCI config to do that before running the tests.
The imports have also been tidied up in these two files.

Fix static asset paths for rev-manifest.json files

---

fec/home/templates/blocks/mur_search.html
fec/legal/views.py

Separates the form actions so both MUR search fields should work properly now.

MUR search fixes

---

.cfignore
.circleci/config.yml

This changeset updates the CircleCI config to use the same name for the Python virtual environment it creates for testing and deployment as we have in the `.gitignore` and `.cfignore` files.  When the name does not match, the virtual environment directory and its contents are pushed up to the cloud.gov environment, which we do not want as it is extra cruft and could potentially cause environment conflicts/issues.  This also updates the `.cfignore` file to include a couple of directories, including the virtual environment directory, that it was not ignoring before.

Match virtualenv name in CircleCI config to our ignore files

---

.circleci/config.yml

Temporarily removes circleCI cache so that there's a fresh install of requirements every time.

Temporarily removes circleCI cache

---

fec/webpack.config.js
package-lock.json
package.json

The Moment npm library we are using to parse dates in JS by default will include all the timezone locales which takes a significant amount of space in our `vendor.js` file. We were also relying on an older version which had a security vulnerability, so along with updating moment I have included a line in Webpack to ignore all locales in Moment which results in a file savings of ~1mb (4.1mb -> 3.2mb)
I've also done a profiling of the home page to reflect performance gains to show before and after.
Before:
Average load times of 1.2s
Average load times <1s
~10ms saved on script loading 
Bundle analyzer graphically showing how much moment locales were taking `vendor.js` filesize.

Update Moment library and ignore locales

---

fec/fec/static/js/legal/LegalSearch.js
fec/home/templates/blocks/mur_search.html
fec/legal/templates/legal-advisory-opinions-landing.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/legal-search-results.jinja
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja

Resolves this issue: https://github.com/18F/openFEC-web-app/issues/2303
Need a design eye to see if we need to tweak this design pattern in any way. This is what the Info messages look like in the pattern library: https://fec-pattern-library.app.cloud.gov/components/detail/inverse-alt--info-messages.html

Replacing AO and MUR banners across site

---

fec/data/templates/candidates-single.jinja
fec/data/templates/committees-single.jinja
fec/fec/static/js/modules/helpers.js
fec/fec/static/js/pages/candidate-single.js

resolves https://github.com/18F/fec-cms/issues/1329
Rearranged javascript loading order for candidate and committee pages. The candidate and committee pages has a dependency to load dataviz first before loading candidate-single.js or committee-single.js.
There were some errors due to attempting to call split or toString methods on null values, this is now handled so that the page can still be processed without error.

Candidate and committees datatables fix

---

fec/home/templates/partials/current-commissioners.html

Headshot placeholder image for "vacant seat" on about/leadership-and-structure was not showing up. Content team requested it be corrected for this release.

change png to jpg in img src path

---

fec/webpack.config.js
package.json

It seemed that setting the production node_env variable inline was not ideal as it broke AO datatables. To fix this, we are setting the value from within the webpack config itself. While it seems counterintuitive, for now it works because setting the node_env variable to production allows for webpack to compress `vendor.js` and because we don't use the variable in any of our JS files currently, it is ok for local development.
I have also used the more preferred compression flag `webpack -p`, which automatically runs UglifyJS for the build-production command.
Fixes: https://github.com/18F/fec-cms/issues/1363

Fix webpack production issue

---

fec/home/templates/blocks/mur_search.html

This seems like a visual and semantic improvement for https://fec-stage-proxy.app.cloud.gov/legal-resources/enforcement/ .

Changes h2 to h3 for visual styling

---

fec/fec/static/js/modules/keyword-modal.js
fec/home/templates/partials/legal-keyword-modal.html
fec/legal/templates/partials/legal-keyword-modal.jinja

Resolves https://github.com/18F/fec-cms/issues/1365
AND operator logic was not working and breaking during pagination because it was trying to pass an amperstand (`&`) instead of the word `AND`. This PR should fix that functionality.

Fix AND operator in boolean logic

---

fec/fec/static/js/legal/Pagination.js

Resolves https://github.com/18F/fec-cms/issues/1382
This sets the standard offset to 20 and accounts for boundaries in the from_hit value. This ensures no negative pages or pages that would go beyond the total result count.

Fixes AO pagination

---

fec/fec/static/js/modules/helpers.js
fec/fec/static/js/modules/table-panels.js
fec/fec/static/js/modules/top-entities.js
fec/fec/tests/js/top-entities-breakdown.js

Resolves https://github.com/18F/fec-cms/issues/1377
Removes `toString` as it is unnecessary. Also adds ability to get cycle from the select box rather than the URL string. This was breaking the cycle in the financial totals when table panel is expanded.
Moment was being formatted incorrectly and tests were not passing. By using the correct usage of date formats, this allows tests to pass during builds https://momentjs.com/docs/#/displaying/

Table panel fix

---

fec/fec/static/scss/datatables.scss
fec/home/templatetags/filters.py

For some reason, we weren't including the overlay stylesheet for datatables pages. This replaces it. Also, removed a print statement left over from testing merge deploy.

Replace overlay on datatable pages

---

fec/data/views.py

This changeset addresses an issue with the feedback tool introduced with the CMS/web app merge.  The cookie with the CSRF token is not being sent or passsed to the view submitting the issue, so this change should make sure that does take place.  See https://docs.djangoproject.com/en/1.10/ref/csrf/#ajax for more details.

Ensure CSRF cookie is present for feedback tool

---

fec/legal/templates/legal-advisory-opinions-landing.jinja
fec/legal/urls.py

In the merged CMS and Web app code, there is a reference to both URLs for AOs, one with a dash and one with an underscore. The underscore was incorrect. This was breaking our paths. Will also set a redirect in Wagtail for the version with underscores just in case.
**Correct:**
`data/legal/advisory-opinions/`
`data/legal/search/advisory-opinions/`
**Incorrect:**
`data/legal/advisory_opinions/`
`data/legal/search/advisory_opinions/`

AO URL Fix

---

README.md

Updating the README to describe npm commands and remove mention of django_compressor, now that we are compiling SCSS on the front-end.
@patphongs, @johnnyporkchops: feel free to add any commits of edits or any new docs you want to add.

Update front-end section on README

---

fec/fec/static/js/legal/LegalSearch.js
fec/legal/templates/legal-advisory-opinions-landing.jinja
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja

This work helps us prepare for replacing the old legal resources landing page with the new design.
- Moves text from the landing page to the AO overview page as part of https://github.com/18F/fec-cms/issues/1393
- Makes the spelling of "requesters"/"requestors" consistently "requestors" across the messages. Resolves https://github.com/18F/fec-cms/issues/1435
- Uncapitalizes "Advisory Opinions" in the "No pending AOs" message because we don't use it as a proper noun unless it's the title of an AO
⚠️  I'm still having trouble running the site locally, so these screenshots are from the inspector. The reviewer *must* run this locally before approving and merging.

Update text on advisory opinion overview page

---

LICENSE.md
README.md

When we merged the assets from `fec-style` into this repository, their licensing information didn't make the journey with them. This integrates special licenses specifically for fonts and images, as well as credits the US Web Design Standards. 
- FEC style license: https://github.com/18F/fec-style/blob/master/LICENSE.md
- Repository only

Add license for assets that aren't in the public domain

---

fec/home/templates/home/reporting_example_page.html

This corrects an applied text style that slipped through my earlier review by changing the title of the linked media to sans serif text. It's important to correct it now so that it can be used as precedent for the component to be re-used in https://github.com/18F/fec-cms/pull/1291
If I did things correctly, 
Before (left) | After (right)
cc @xtine @johnnyporkchops

Corrects link styling on related media for reporting example templates

---

fec/fec/static/js/legal/SearchResults.js
fec/fec/static/js/legal/Tags.js
fec/legal/views.py

Note: This branch needs to point to openFEC branch `feature/add-ao-status-2` to work
Along with https://github.com/18F/openFEC/pull/2738, this resolves https://github.com/18F/fec-cms/issues/1390

Display Withdrawn instead of date for withdrawn AOs - use AO status 

---

fec/home/templatetags/home_page.py

This is another attempt at solving timezone error related to timezone unaware date objects in the banner announcements code. Tested locally and it does not give error, but still need to see if other tests/monitors report errors/warnings. i.e.- Kibana

[MERGE WITH GITFLOW] localize timezone-aware date and handle DST(daylight savings time)

---

fec/fec/settings/dev.py
fec/fec/static/scss/layout/_grid.scss
fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
fec/home/templates/home/home_page.html

**This PR replaces https://github.com/18F/fec-cms/pull/1441. Past history /screenshots can be seen there.** (This also incorporates requested review-edits from closed PR https://github.com/18F/fec-cms/pull/1466)
This PR specifically solves icon stretching problems that happened in mobile sizes when placing icon images in the generic grid items
This also solves the problem of unacceptably large image/icon-heights, taking up too much screen area in mobile sizes. 
This PR uses the object-fit property, among others, to apply styles to images that are inside of  responsive grid items.
This includes three new grid styles that expand upon existing styles--following the intended convention of modularity and the use of existing building blocks, rather that creating new.
**Browser compatibility:** …

Grid-item-w-image (for H4CC and Homepage getting started sections-PR 1441)

---

fec/fec/templates/partials/meeting.html

- Fixes #1484 
- Adds a space after "Amended" so that any type of document following with automatically have a space between the two words
-  Meeting page feed: https://www.fec.gov/meetings/
**Before**
**After**
____
❗️ Please run locally before merging to ensure this works as expected.

Adds space between "Amended" and type of notice

---

fec/fec/templates/partials/footer-navigation.html

Hard-code API link in footer until we can pass FEC_API_URL into the jinja templates
- Addresses #1447 
Hard-code API link in footer jinja template until we can pass FEC_API_URL into the jinja templates properly
www.fec.gov home page API link in footer currently redirects to www.fec.gov. This PR hard-codes it to https://api.open.fec.gov/
[fec-cms/fec/fec/templates/partials/footer-navigation.html](https://github.com/18F/fec-cms/blob/94cf215d68735a1874a4350a91922aef85389e7d/fec/fec/templates/partials/footer-navigation.html#L64)

Hard-code API link in footer

---

fec/data/templates/macros/filters/ie-reports.jinja

- Addresses #1434 
- Changes the 24/48 hour report toggle to be the default option selected on page load. To support this, it also moves the selected option into the first position.
- I also caught a small typo in the tooltip content while I was looking.
[Independent expenditures data table](https://www.fec.gov/data/independent-expenditures)
If I did everything correctly, the before/after should look like this:
**Before:**
**After:** 
______________
❗️❗️  Please test this by running it locally (as you usually would)—I've had trouble with my local env so have not been able to test the functionality.

Make 24/48 hr reports default filter selection for viewing independent expenditures

---

fec/data/api_caller.py
fec/data/constants.py
fec/data/tests/test_utils.py
fec/data/utils.py
fec/data/views.py

Senate special elections can occur in years when there isn't usually an election in that state. Currently we're hard-coding states with specials in 2018, which isn't very sustainable for future cycles and states. This PR adds to `api_caller.py` so that senate specials on the data/elections pages are data-driven. 
- Addresses # [2621](https://github.com/18F/openFEC/issues/2621)
Change the logic so only the senate special cycles are added to the dropdown and not count backwards by 6 for that year. This will automatically add senate election years as new special elections are added to the `trc_election` tables. Made tests for new functionality. 
This also addressed a bug I found where extra elections were being added to AL due to senate special logic: …

Make senate special cycles in election dropdowns data-driven

---

fec/fec/settings/production.py

Should resolve cookie security issues raised in slack at https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1510695955000310. Please test before merging--I pulled this from the django docs but haven't had time to verify manually.
@LindsayYoung

Set `Secure` and `HttpOnly` flags on cookies.

---

fec/fec/static/js/data/terms.json

- Addresses # [_1394_]
Adds new terms and updates Hybrid PAC
Edit glossary

Re-creating additional glossary terms PR

---

fec/data/urls.py
fec/data/views.py

- Addresses #1461 
- Previous implementation was using a `url_for` function to construct the redirect, which is using a flask function. To fix this, we needed to convert the redirect to use a django url constructor. Django's `reverse()` was used in the PR.
-  Data section of the site. Examples of url that was previously effected: http://localhost:8000/data/committee/C90011677/. The redirect now redirects to the most recent cycle with data.

Fixed redirect to cycle with data

---

fec/fec/static/scss/elements/_forms.scss

Set default property `border-radius: 0;` on input buttons.
It seems that Chrome now sets a default `border-radius: 4px` property for inputs if they are not pre-defined, causing accordions to have a border radius:
After this fix, they should show up as they should:

Set default border radius on buttons

---

fec/fec/static/js/data/terms.json

Fix missing "t" in "personal funds..." 
Remove "- "from "Federally Chartered"
Capitalize "Senator" in "District"

Fix 3 typos in Glossary

---

fec/fec/static/js/pages/datatable-candidates.js
fec/fec/static/js/pages/datatable-committees.js

- I happened to notice this randomly, so there is no corresponding issue.
- Previously, the page titles were singular "Candidate" and "Committee" — which is awkward and incorrect since the data tables show data for all candidates and all committees, not a single one. The breadcrumbs and url on each page also uses a plural format, so I think they were singular by mistake.
- This change also makes the titles consistent with all of the other data table page titles, which are plural.
- [All candidates data table page](https://www.fec.gov/data/candidates/?has_raised_funds=true)
- [All committees data table page](https://www.fec.gov/data/committees/)
**Before**
**After**

Pluralize "Candidates" and "Committees" data table titles

---

fec/data/views.py
fec/fec/static/scss/layout/_layout.scss

- Addresses https://github.com/18F/fec-cms/issues/1634
- The `election_full` url query string used to be passed into the application in openFEC-web-app as a boolean. However after merge, we failed to account for this and passed it into `data/views.py` as a string. This caused a failure in logic because if we check `if election_full`, it would always return `True` as a string. We fix this by converting `election_full` from a string to a boolean right after the get request.
- I also fixed a UI bug caused by newer versions (62+) of Chrome that would show overflows on side bars that take up the entire window which affected Candidate pages.
- Candidate summary pages.
Correct behavior:
Fixes this Chrome overflow issue with side nav:

[MERGE WITH GITFLOW] Hotfix/fix candidate 2 yr summary cycle

---

fec/data/templates/macros/cycle-select.jinja

Relabel (replace text) the heading for the drop-down from "Election cycle" to "Two-year period"
on the following types of webpages:
- Election Summary / Candidate Financial Comparisons pages
- Election Summary / Candidate Contributions Comparisons pages
- Committee profile pages
Addresses # 1605 https://github.com/18F/fec-cms/issues/1605
Summary of changes:
Changes to the cycle-select Jiinja file for the following templates:
1) election_cycle_select template 
2) committee_cycle_select component / template
-  Election Cycle (now 'Two-Year Period') drop down menu - text on label / heading only
House election summary: Compare Candidate Financial Totals
https://www.fec.gov/data/elections/house/DC/00/2018/
Before:
After: …

Replace 'Election Cycle' filter label text with 'Two year' period

---

fec/fec/static/js/modules/home-events.js

As a result of recent calendar changes, the homepage "Events and Deadlines" section was showing the same event for all four categories:
**Before**
**After**

[MERGE WITH GITFLOW] Hotfix: Fix homepage "Events and Deadlines" section

---

fec/data/templates/macros/cycle-select.jinja
fec/fec/static/js/templates/election-cycles.hbs
fec/fec/static/js/templates/electionCycles.hbs
fec/fec/tests/js/cycle-select.js
fec/fec/tests/js/election-filter.js

- Addresses # 1444 https://app.zenhub.com/workspace/o/18f/fec-cms/issues/1444
- Changes the use of the verbiage 'cycle' on various web pages
-  Front end web pages components: 
cycle-select, candidate-cycle-select, election-cycle-select and election-filter
Before screenshots can be seen in issue#1444
- Changed the Candidate Profile pages
After design discussions this month, the final decision was to change the text from: "full cycle"
to: "All Years"
Manual Testing:
a)candidate/financial-summary==>Candidate Profile pages
Presidential
https://www.fec.gov/data/candidate/P60022654/
Senate
https://www.fec.gov/data/candidate/S6MD03177/
b)Candidate/other-spending-tab
https://www.fec.gov/data/candidate/S6MD03177/?tab=other-spendi …

Election 'cycle' text changes to web pages

---

fec/data/tests/test_legal_search.py

In data/tests/test_legal_search.py:
Updated  **test_ao_landing_page** (Test#8), test case:
- replaced the **ao_is_pending** with **ao_status variable** in Test#8
- mock calls are working as expected.

Fixed the AO's landing page test case

---

fec/home/templates/home/home_page.html

- Addresses https://github.com/18F/fec-cms/issues/1665
Updates references for new commission Chair and Vice Chair for the 2018 calendar year.
- Homepage Commissioner's section

Updated chair and vice chair references and also reordered commissioners

---

fec/data/templates/partials/candidates-office-filter.jinja

Additional work for Issue#1444
House Election period label changed from: "Election Cycle" to "Two-year period"
House Candidate Edit Filters component / Data Table filter
change to:
fec/data/templates/partials/candidates-office-filter.jinja:
Part of earlier PR https://github.com/18F/fec-cms/pull/1652
(This PR was already closed so this new one was opened to complete the work)
____

Additional update for Election Cycle text changes from branch Feature/election cycle text chgs2

---

fec/home/templates/home/contact-form.html

- Addresses # [1686](https://github.com/18F/fec-cms/issues/1686)
The toll free number listed in the message should be 1-800-424-9530 (not 425). 
I confirmed the 425 number wasn't anywhere else on the site
https://www.fec.gov/help-candidates-and-committees/question-rad/

Fix typo in RAD phone number

---

.circleci/config.yml
README.md
fec/fec/settings/base.py
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml

Fixes #904 
Addresses #1640 
This changeset makes the adjustments necessary to support the CMS in the feature space again within our cloud.gov account.  This also includes an updated CircleCI configuration to help improve that setup a bit.
**NOTE:** When this is merged into `develop` and deployed to the `dev` space and then subsequently deployed to the `stage` and `prod` spaces in the next release, this should automatically bind the S3 content bucket to the app in the respective environment as well.

Add support back in for the cloud.gov feature space

---

fec/home/templates/home/contact-form.html

Due to the government shutdown, this will remove the RAD contact form temporarily until we reopen.
RAD contact form:
https://www.fec.gov/help-candidates-and-committees/question-rad/

[HOTFIX Merge with GITFLOW] Temporarily removes rad contact form for shutdown purposes

---

fec/home/templates/home/candidate-and-committee-services/guides.html

- Addresses https://github.com/18F/fec-cms/issues/1704
This enables and updates the links for the new SSF guide content under the Corporations and labor organizations guide section of our site.
Adding Dorothy and John as reviewers.
@dorothyyeager Can you please verify the content is correct?
@johnnyporkchops Please check the code is good to go.
-  https://www.fec.gov/help-candidates-and-committees/guides/?tab=corporations-and-labor-organizations

[Hotfix merge with GITFLOW] - Added updated links for SSF guide section

---

fec/data/templates/macros/cycle-select.jinja
fec/data/views.py

- Addresses Issue# 1644 https://github.com/18F/fec-cms/issues/1644
Handles odd year special elections by changing to even year
- fec-cms/fec/data/views.py 
The candidate() function was updated to include new code for creating a new election years list of only even years from the API's returned election-years list.
- fec-cms/fec/fec/data/templates/macros/cycle-select.jinja
This macro uses the election years list for displaying the election years in the Elections pulldown menu. 
Test Case: House Candidate Karen Handel had special election in 2017
https://www.fec.gov//data/candidate/H8GA06286/
-Before screenshot
- After screenshot
List related PRs against other branches: none
Issue:2845 …

Include odd year special elections in Election dropdown as even years

---

.circleci/config.yml
fec/webpack.config.js
tasks.py

- Addresses https://github.com/18F/fec-cms/issues/1746
No cache rebuilds were failing on dev. This fixes it by removing sudo on `npm install` and also fixes a webpack issue with webpack stats option, in which it was referencing an incorrect webpack configuration object `assetSort`, it should be `assetsSort`.

Fixes cache rebuilds on dev and webpack error

---

fec/data/templates/election-lookup.jinja
fec/fec/static/js/modules/election-search.js

- Addresses #1782 
This adds the district sort to the election page search form
Example:
-  http://localhost:8000/data/elections/?cycle=2018&state=CA

Fix district sort on election results page

---

fec/fec/static/scss/components/_cards.scss
fec/fec/static/scss/components/_list-styles.scss
fec/fec/static/scss/components/_richtext.scss

Addresses:
add numbers to `list--numbered class` : https://github.com/18F/fec-cms/issues/1781
add transparent border to `.card--alternating-bg` : https://github.com/18F/fec-cms/issues/1734 
**Before:**
**After:**

fixed scss for numbered lists and alternating-bg cards

---

fec/data/constants.py
fec/data/templates/macros/tables.jinja

- Addresses # https://github.com/18F/fec-cms/issues/1720- Bad IE link on committee summary page
-Addresses part of https://github.com/fecgov/FEC/issues/5452 - Party coordinated expenses link is busted and does not filter correctly.
**Affected areas of the application:**
https://github.com/18F/fec-cms/blob/develop/fec/data/templates/macros/tables.jinja seems to be the only place in the application that the ['link'] item in a dictionary (in constants.py )is being accessed so I am fairly confident that this will not break anything somewhere else.

[MERGE WITH GIT FLOW] fix broken IE an PCE links on committee summary pages

---

fec/data/templates/landing.jinja

- This updates the styles (and underlying front end code structure) of the cards on the data landing page to use the most up-to-date approach. The notice-able visual change is that the links on the card will no longer be underlined.
- Previously, @johnnyporkchops had done some great work adjusting the hover states and implementations of these cards as a pattern, and this instance just hadn't been updated yet. It was a tiny thing that was irking me, so I had five minutes and fixed it instead of making a coffee :)
- Data landing page: https://www.fec.gov/data/
**Before:**
**After:**

Applies most recent styles to cards components on data landing page

---

fec/fec/static/js/pages/committee-single.js

- Addresses bug #1691 
Modifies the "Filings" section of Committee Pages to show Form 5 quarterly reports under "Regularly Scheduled Reports" and exclude them from the "24- and 48- Hour Notices" section. HUGE thank you to @llienfec for helping me with this logic.
Committee "Filing" pages ([Example](https://www.fec.gov/data/committee/C90013301/?cycle=2016&tab=filings))
<kbd><img src="https://user-images.githubusercontent.com/31420082/36761540-84cec166-1bed-11e8-9d4e-121638b71338.png"  width="300"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/31420082/36761655-14c800ca-1bee-11e8-8f30-e184d2b837de.png" width="300"></kbd>

Move Form 5 quarterly reports to 'Regularly filed reports'

---

fec/fec/static/js/pages/candidate-single.js
fec/fec/static/js/pages/committee-single.js

- Addresses #1760 
Ensuring that the following RFAIs show up in the correct tables.
RQ-5s - Request for Additional Information (RFAI) referencing the Statement of Candidacy. Test URL: http://localhost:8000/data/candidate/H8AR04122/?tab=about-candidate
RQ-1 - RFAI referencing the Statement of Organization. Test URL: http://localhost:8000/data/committee/C00637983/?tab=filings
RQ-2 - RFAI referencing Report of Receipts and Expenditures. Test URL: http://localhost:8000/data/committee/C00637983/?tab=filings
RQ-9 - Multicandidate status. Test URL: http://localhost:8000/data/committee/C00659672/?tab=filings
-  Committee filing page
- Candidate about page

Fixes for RFAI filings

---

fec/fec/static/js/pages/candidate-single.js
fec/fec/static/js/pages/committee-single.js

- Addresses #1760 
This update makes sure that we are inclusive of all the different RFAI request_types. There are a total of 9 different request types. This is how all the RFAIs should show up:
http://localhost:8000/data/committee/C00659672/?tab=filings
- RQ-2: RFAI referencing Report of Receipts and Expenditures
- RQ-3: RFAI referencing second notice reports
- RQ-4: RFAI referencing Independent Expenditure filer
- RQ-7: RFAI referencing failure to file
- RQ-8: RFAI referencing public disclosure
- RQ-1: RFAI referencing Statement of organization
- RQ-6: RFAI referencing 2nd notice State of organization
- RQ-9: RFAI referencing Multicandidate status
http://localhost:8000/data/candidate/H8AR04122/?tab=about-candidate
- RQ-5: RFAI referencing Statement of Candidacy
List general components …

This change makes RFAI inclusive for all request types

---

fec/home/templates/partials/commissioner.html
fec/home/templates/partials/current-commissioners.html

- Addresses #1810 
This fixes the broken image for the no photo headshot. http://localhost:8000/about/leadership-and-structure/commissioners/
-  All Commissioners page

fixes image path for no headshot image

---

fec/data/templatetags/filters.py

- Addresses https://github.com/18F/fec-cms/issues/1845
Change `strip_zero_pad` function in filters.py to only remove leading 0's - it was removing trailing 0's and turning 10 into 1.
Note: Python has `strip` and `lstrip` - [here are the docs](https://docs.python.org/2/library/string.html#string.lstrip)
-  https://www.fec.gov/data/elections/house/[state]/10/2018/ 
`data/templates/elections.jinja`
Example: https://www.fec.gov/data/elections/house/CA/10/2018/
- https://www.fec.gov/data/candidate/[ID]/?tab=about-candidate
`data/templates/partials/candidate/about-candidate.jinja`
Example: https://www.fec.gov/data/candidate/H4VA10089/?tab=about-candidate

[MERGE WITH GIT FLOW] Change `strip_zero_pad` to only remove leading 0's

---

fec/fec/static/scss/components/_pagination.scss

Discovered in the audit of the components in the pattern library https://github.com/fecgov/fec-pattern-library/issues/67
- Corrects styling of the current page nav button to distinguish it from the other possible page buttons through changing the button background color and font weight.
- Adds additional framing elements to the component's canonical example code, such as border lines and total item count
This PR _should_ only impact the code in the pattern library. This component isn't currently used, but is built and ready to be transitioned into layouts.
**Before**
**After**
branch | PR
update-pagination | [Patter library 86, Update and add pagination component](https://github.com/fecgov/fec-pattern-library/pull/86)

Corrects style on feed pagination component

---

fec/home/templates/home/home_page.html

- Addresses #1803 
Calendar filter buttons on the homepage were calling old API codes. These changes update to the correct API codes.
-  Homepage: Events and deadlines section

[WIP] Fixed events and deadlines filter buttons on homepage

---

fec/legal/templates/partials/legal-pagination.jinja

- Addresses https://github.com/fecgov/fec-cms/issues/1859
- Fix pagination when searching for MUR respondents
- Add `&mur_respondents={{mur_respondents}}` to MUR pagination links
- MUR search results
Search "Nevada NOW" as MUR Respondent...
https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=&mur_no=&mur_respondents=Nevada+NOW
then try to go to the next page. It resets your results:
Search "Nevada NOW" as MUR Respondent...
http://localhost:8000/data/legal/search/murs/?search_type=murs&search=&mur_no=&mur_respondents=Nevada+NOW
then try to go to the next page. You actually get to the next page:
**Note** I found a display problem but it's already in production. I'll enter a new bug if it's not already there.
https://www.fec.gov/data/legal/search/murs/?search=&mur_respondents= …

[MERGE WITH GIT FLOW] Add `mur_respondents` filter to "next" and "previous" buttons

---

package-lock.json
package.json

- Addresses #1542 
Upgraded a11y-dialog npm package dependency to version 4.0.0. I attempted to use the latest 4.0.1, however, this caused site dropdown mega menu issues in IE. This gives us a more up-to-date version.
-  Any dialogs and menus that use the a11y-dialog

updated a11y-dialog dependency to fix IE dialog submit issue

---

fec/data/templates/layouts/main.jinja
fec/fec/templates/base.html
fec/home/templates/home/contact.html

Change address on home and data footers and make ext changes to contact page.
Addresses: Hardcoded changes for FEC address #1848

[MERGE WITH GIT FLOW] Change addresses/text changes on contact page

---

fec/data/templates/partials/candidate/financial-summary.jinja

1)Related Issue: [https://github.com/fecgov/fec-cms/issues/1877](https://github.com/fecgov/fec-cms/issues/1877)
2)If a candidate has more than one committee listed on his/her candidate profile page. 
The second committee url is broken, due to miss the end '/')
Example: [https://www.fec.gov/data/candidate/H6NV01232/ ](https://www.fec.gov/data/candidate/H6NV01232/ )
3) How to test locally?
a)setup fec-cms repo locally, 
b)pull branch: feature/fix_committee_broken_link
c)export FEC_API_URL=dev api
d)run: [http://localhost:8000/data/candidate/H6NV01232/](http://localhost:8000/data/candidate/H6NV01232/) 
will see the correct second committee url.

Fix broken committee link in candidate profile page.

---

fec/data/templates/partials/individual-contributions-filter.jinja

- Addresses #1391 
Limits zip code input to 5 digits for the individual contributor search http://localhost:8000/data/receipts/individual-contributions/
-  Individual contributor search

[DON'T MERGE YET] Limit individual contributor zip input to 5 digits

---

fec/fec/static/js/pages/datatable-candidates-office.js

- Addresses https://github.com/fecgov/openFEC/issues/2710
_Enable candidate downloads along with https://github.com/fecgov/openFEC/pull/3021_
_Enable downloads from the prez/senate/house pages:_
- President: http://localhost:8000/data/candidates/president/?election_year=2016&cycle=2016&election_full=true&min_receipts=50000
- Senate: http://localhost:8000/data/candidates/senate/?election_year=2016&cycle=2016&election_full=false&min_receipts=50000
- House: http://localhost:8000/data/candidates/house/?election_year=2016&cycle=2016&election_full=false&min_receipts=50000
- Point local cms to the `dev` API.
- Check out this `feature/enable-downloads` branch of fec-cms repo
- Point your cms to the `dev` API `export FEC_API_URL=https://fec-dev-api.app.cloud.gov`
- Run cms locally. Don't forget to …

Enable candidate downloads

---

fec/fec/settings/base.py
fec/fec/settings/production.py
fec/fec/urls.py

The robots.txt file was not showing up for all of our non-production environments (dev, stage, and feature). This fixes the robots file so that all search engines will be disallowed from crawling them. Production is explicitly set to not have a robots.txt file to allow for search engine crawling.
- Dev
- Stage
- Feature

fixed robots.txt file in our dev, stage, and feature environments

---

fec/home/templates/home/latest_updates.html

Addresses #1778 (specifically the copy) and makes changes to #1890 
Adds copy to the email signup form on the latest updates page. 
- The interaction is slightly more complex than we'd realized on the GovDelivery end, so I'm adding a sentence to let folks know there's slightly more.
- I also made the title of the accordion refer specifically to `Latest updates`, since that's the scope of the signup page they're going to and it'll help clarify that it's different from the footer signup.
I don't think the GovDelivery privacy policy is strictly necessary, since a new subscriber will see it on the subsequent page, but I don't think it's bad to keep it anyway. It gives some visual balance to the form while also letting someone see it before doing anything else. So that stays.
One other thing …

Added copy for latest updates email signup

---

fec/home/templates/home/latest_updates.html

Addresses: 
https://github.com/fecgov/fec-cms/issues/1778
https://github.com/fecgov/fec-cms/issues/1670
Create gov delivery email signup on all-updates page that allows users to signup for all news updates or choose from a list of news/outreach related topics--NOT all gov delivery topics.
(GovDelivery token has been removed from code pushed to this repo)

GovDelivery signup on all-updates page

---

fec/data/templates/macros/tables.jinja

This PR fix the dead IE and PCE links in committee profile page.
Related Issue: 
[https://github.com/fecgov/FEC/issues/4828](https://github.com/fecgov/FEC/issues/4828)
[https://github.com/fecgov/fec-cms/issues/1744](https://github.com/fecgov/fec-cms/issues/1744)
Related PR:
[https://github.com/fecgov/fec-cms/pull/1819](https://github.com/fecgov/fec-cms/pull/1819)
[https://github.com/fecgov/fec-cms/pull/1884/files](https://github.com/fecgov/fec-cms/pull/1884/files)
Because PR1884 fixed multi committee_ids issue, by mistake remove the codes for handle IE and PCE links, so add back in this PR.
**How to test it**
1)setup fec-cms locally
2) test 3 cases and check all links in Financial summary section: 
a) has one committee in candidate profile page …

Fix dead link in committee profile page for IE link.

---

fec/fec/static/scss/layout/_layout.scss

Fixes spacing error by restoring inadvertently-deleted `.content__section--extra`  from _layout.scss.
This PR should fix this. (This  class was inadvertently deleted when adding styles for Adv Data)
**How to test:**
1) checkout `fix/header-spacing` branch
2) npm run build-sass
3) navigate to http://127.0.0.1:8000/updates/ and/or http://127.0.0.1:8000/about/reports-about-fec/foia-reports/
4) See if spacing is restored
**Screenshots of errors:**

[MERGE BEFORE RELEASE] Fixed spacing error by restoring inadvertently-deleted class

---

fec/data/templates/advanced.jinja
fec/data/templates/landing.jinja
fec/data/templates/partials/advanced/external.jinja
fec/fec/static/js/modules/tables.js
fec/fec/templates/partials/navigation/nav-data.html

- Addresses #1928 
Fixed External sources link and bulk data links across the site. Please check these areas here:
- http://localhost:8000/data/ - Check `Browse full advanced data sets` cards in this section
- information box up at the top right of the page has a bulk data link. That is pulled in through the tables.js, so modifying that file should fix all the locations below: 
- http://localhost:8000/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=04%2F19%2F2018
- http://localhost:8000/data/receipts/?two_year_transaction_period=2018&data_type=processed&min_date=01%2F01%2F2017&max_date=04%2F19%2F2018
- http://localhost:8000/data/disbursements/?data_type=processed&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=04%2 …

[MERGE WITH GITFLOW - HOTFIX] Fix Bulk data and External sources links across site

---

fec/data/templates/raising-breakdown.jinja
fec/data/templates/spending-breakdown.jinja
fec/data/views.py

- Addresses https://github.com/fecgov/fec-cms/issues/1550 and https://github.com/fecgov/fec-cms/issues/1947
_Make raising/spending page cycles data-driven. This means we won't need to manually add future cycles to these dropdowns._
Thank you @apburnes for your help!
- https://www.fec.gov/data/spending/
- https://www.fec.gov/data/raising/

Use cycle select macro to generate raising/spending cycles

---

fec/fec/static/scss/components/_icon-headings.scss
fec/fec/static/scss/components/_mega-menu.scss
fec/fec/templates/partials/navigation/nav-about.html
fec/fec/templates/partials/navigation/nav-data.html
fec/fec/templates/partials/navigation/nav-help.html
fec/fec/templates/partials/navigation/nav-legal.html

Addresses # Implement new menu designs #1905
- Updated main navigation menus for `About, CFD, H4CC, and Legal landing`
main navigation menus for `CFD, H4CC, Legal landing, About `

Implement new menu designs

---

fec/fec/static/scss/datatables.scss

Restores current-version icon to datatables
- Addresses: green check-icons not showing up for "Current version" reports #1815
Add  `@import 'common';` to `/fec/fec/static/scss/datatables.scss` to restore green-check for current-version reports
[datatables.scss](https://github.com/18F/fec-cms/blob/develop/fec/fec/static/scss/datatables.scss)

Restore current-version icon to datatables

---

fec/data/constants.py
fec/data/templates/datatable.jinja
fec/data/templates/partials/filters/committee-types.jinja

- Fixed the breadcrumbs layout to show __PAC and party committee reports__
- Fix filter names for __Super PAC (independent expenditure only)__ and __Independent expenditure filer (not a committee)_ and make sure their listed properly within the select menu
- Updates the views on the `/data/*` path

Edit grammar for Campaign Finance Data #1907

---

fec/data/templates/macros/missing.jinja
fec/fec/static/js/templates/tables/noData.hbs

- Addresses #1939
Updates the jinga and handlebars templates which display `no data` messages. The jinja template uses the new default message drafted in the issue. The handlebars template receives a `reason` parameter when querying https://api.open.fec.gov. The handlebars template displays the given reason if supplied or else it displays the updated default message.
- Templates using the `missing.jinja` macro => data templates (`committees-single.jinja` & `candidates-single.jinja`)
- Whenever the browser makes an xhr request ie `.../?tab=spending`, it is using the `noData.hbs` template
__Default message from `missing.jinja`__
__Messages with reasons from `noData.hbs`__

Update missing and no data message templates #1939

---

fec/data/templates/macros/missing.jinja
fec/fec/static/js/templates/tables/noData.hbs

Updates the jinga and handlebars templates which display no data messages. Update the link style formatting/spacing
Templates using the `missing.jinja` and `noData.hbs`

Fix link styles with updating line endings

---

fec/fec/static/scss/components/_icons.scss

Restores missing star, document and speaker(audio) icons to search result, document and meeting pages
- Addresses : Icons missing from site search results list #1838
- Also restores audio icon to meeting pages
- Document searches do not work locally or on feature, so the only way (i could think of) to test this locally is to change the CSS class in the inspector to the newly added classes to make sure the icons show up. see screenshot below.
https://github.com/fecgov/fec-cms/blob/develop/fec/fec/static/scss/components/_icons.scss

Restore i-document,i-star and i-speaker icon classes

---

fec/fec/templates/partials/navigation/nav-help.html

Addresses: https://github.com/fecgov/fec-cms/issues/2034
This his link needs to be relative to the top level, not to the page it is on--needs a leading slash
` help-candidates-and-committees/ `
--changed to--
` /help-candidates-and-committees/ `
**How to test:**
Checkout and run this branch locally:
`feature/fix-explore-h4cc-link-on-megamenu`
Spot check that  the mega menu link for `Explore all compliance resources` link works on home page and on other pages

Fix "Explore all compliance resources" link on menu

---

fec/data/views.py

Include missing "Suite" in committee addresses  on "About this committee" pages
- Addresses https://github.com/fecgov/fec-cms/issues/1888
- Added `Street_2` to template variables on data/views.py 
**[How to test &#187;](#how-to-test)** 
modified:   data/views.py
<a id="how-to-test"></a> 
Check out and run this branch locally: `feature/add-suite-to-committee-address`
Make sure suite numbers show on committee profile information on `About this committee` pages.
Example Pages:
http://127.0.0.1:8000/data/committee/C00507574/?tab=about-committee
http://127.0.0.1:8000/data/committee/C00438291/?tab=about-committee
http://127.0.0.1:8000/data/committee/C00590315/?tab=about-committee

Include missing "Suite" in committee addresses 

---

fec/data/templates/landing.jinja
fec/data/urls.py
fec/fec/static/js/pages/data-landing.js

Remove incorrect data references until we are able to correct the underlying data.
Edits to: https://www.fec.gov/data/ 
Reroute [spending](https://www.fec.gov/data/spending/) and [raising](https://www.fec.gov/data/raising/) breakdown page URLS to their respective datatables.
**Adresses:**
Resolves #2068 - Disable/hide/remove top raising candidates in 2017–2018 
Resolves #2069 - Disable/hide/remove possible uses of this data 
Resolves #2070 - Disable/hide/remove trending elections list 
Resolves #2071 - Disable/hide/remove raising line chart 
Resolves #2072 - Disable/hide/remove spending line chart 
Resolves #2073 - Disable/hide/remove raising breakdown 
Resolves #2074 - Disable/hide/remove spending breakdown 
modified:   **data/templates/landing.jinja**
modified:   **data/urls.py** …

[MERGE WITH GITFLOW] Hotfix to data-landing and reroutes of spending/raising breakdowns

---

fec/fec/static/js/templates/feedback.hbs
fec/fec/static/scss/components/_buttons.scss
fec/fec/static/scss/components/_feedback.scss
fec/fec/static/scss/mixins/_utilities.scss

- Resolves #1876 
_This adds the new feedback drawer design to the website. Includes new sign up button to have users sign up with for usability testing._
-  Feedback drawer on all pages
branch | PR
____
**IF ANY OF THE ABOVE FIELDS DO NOT APPLY, PLEASE DELETE THEM BEFORE SUBMITTING**

updated feedback drawer to new styles based on design ticket

---

fec/fec/static/js/modules/columns.js
fec/fec/static/js/modules/helpers.js
fec/fec/static/js/templates/receipts.hbs

Fix incorrect display of `contributor` for earmarked contributions on Receipts and Individual contributions datatables for main table and details panel.
Resolves #1924 - Display problem with earmarked contributions
**[How to test &#187;](#how-to-test)** 
**Summary:**
`https://www.fec.gov/data/receipts/*` was only showing correct contributor for earmarked receipt-type:`15E`, and not for `24T` and `24I`.
Example: https://www.fec.gov/data/receipts/?two_year_transaction_period=2018&data_type=processed&contributor_name=OELSNER%2C+GEOFFREY
- Changed the globals variable named `EARMARKED CODE` from a singular value(15E) to an array of values:  `EARMARKED_CODES: ['15E', '24I', '24T' ]`
- New HBS helper to check for existence of receipt-type in this array
- New inline functions in columns.js to …

Fix earmarked contributor name display on Receipts

---

requirements.txt

Fixes #3087.
The minimum version required to fix the issue is 1.5.31. Upgrading to
1.7.21, which is the latest release at this time.
Uploads

Upgrade boto3 to 1.7.21

---

fec/fec/constants.py

- Resolves #1981 
_Rename calendar category 21 to 'Mid-year and year-end' and move to the bottom of the list._
- https://www.fec.gov/calendar/
- http://127.0.0.1:8000/calendar/?calendar_category_id=21

Rename calendar category 21 to 'Mid-year and year-end', move to bottom

---

.circleci/config.yml

This fixes error messages in CircleCI builds that look like:
```
/tmp/.bash_env-..-0-build: line 1: /usr/lib/postgresql/9.6/bin/:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
No such file or directory
```

Set postgresql PATH correctly in CircleCI

---

fec/data/templates/partials/advanced/bulk-data.jinja

- Resolves #2032 
_Fixes incorrect link under bulk-data (http://localhost:8000/data/advanced/?tab=bulk-data) under the Contributions to individuals expander. Link now points to correct link for that data description: http://localhost:8000/campaign-finance-data/contributions-individuals-file-description/_
-  Bulk data page

Fixed data description link for Contributions by individuals

---

fec/data/templates/partials/filters/audit-committee-types.jinja

The last change to audit search PR# https://github.com/fecgov/fec-cms/pull/2029 did not make it in for some reason. Perhaps due to the way we manually restored the branch.
Just before merge, @JonellaCulmer  caught:  The green "filter added" message and accompanying checkbox for each dropdown filter was only working for some filters.
https://github.com/fecgov/fec-cms/pull/2029#pullrequestreview-125203578
This PR fixes that.
**How to Test**
- Checkout and run this branch locally: `fix/audit-search-filter-messages` 
- Point to some instance of OpenFEC that populates datatables locally.
- Go to: http://127.0.0.1:8000/legal-resources/enforcement/audit-search
- Check that the green "filter added"message shows up for ALL filters under `Committee type` when choosing a filter from dropdown.(See …

Audit search "Filter added" popup message for ALL filters

---

fec/data/templates/macros/missing.jinja
fec/fec/static/js/templates/feedback.hbs
fec/fec/static/js/templates/tables/noData.hbs
fec/fec/templates/partials/footer-navigation.html
fec/fec/templates/partials/navigation/nav-about.html
fec/fec/urls.py
fec/home/templates/home/collection_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/resource_page.html
fec/home/tests/test_views.py
fec/home/views.py

Resolves #2077 
**Affected areas of application:**
modified:   data/templates/macros/missing.jinja
modified:   fec/static/js/templates/feedback.hbs
modified:   fec/static/js/templates/tables/noData.hbs
modified:   fec/templates/partials/footer-navigation.html
modified:   fec/templates/partials/navigation/nav-about.html
modified:   fec/urls.py
modified:   home/templates/home/collection_page.html
modified:   home/templates/home/custom_page.html
modified:   home/templates/home/resource_page.html
modified:   home/tests/test_views.py
modified:   home/views.py

Contact page url and route maintenance

---

fec/data/templates/macros/filters/years.jinja
fec/data/templates/partials/candidates-filter.jinja

- Resolves #2103
So that users can see candidates who have registered in future elections (usually senate/presidential), add next 4 election years (currently 2019-2022) to candidate data table (https://www.fec.gov/data/candidates/). Because `constants.END_YEAR` is used in a number of other places, I added parameters to the `years.jinja` macro `years` so I could override the end date.
-  https://www.fec.gov/data/candidates/ (fec/data/templates/partials/candidates-filter.jinja)
- fec/data/templates/macros/filters/years.jinja
Local testing link: http://localhost:8000/data/candidates/

Add next 4 election years (2019-2022) to candidates data table

---

fec/fec/static/scss/components/_icon-headings.scss
fec/fec/static/scss/components/_mega-menu.scss
fec/fec/static/scss/components/_nav.scss
fec/fec/templates/partials/navigation/nav-about.html
fec/fec/templates/partials/navigation/nav-data.html
fec/fec/templates/partials/navigation/nav-help.html
fec/fec/templates/partials/navigation/nav-legal.html
fec/fec/templates/partials/navigation/navigation.html

Add searchbox to menu at mobile/tables/phablet sizes and put main mega-heading ("Explore all...") links in the menu at those sizes.
- Resolves #2083
**Related issues:**
https://github.com/fecgov/fec-cms/issues/2036 - Add main landing pages to mobile menu
https://github.com/fecgov/fec-cms/issues/1827 - Site search doesn't show up in mobile/collapsed menus
https://github.com/fecgov/fec-cms/issues/935#issuecomment-293567899 -Design site search in header #935
modified:   fec/static/scss/components/_mega-menu.scss
modified:   fec/static/scss/components/_nav.scss
modified:   fec/templates/partials/navigation/navigation.html

Searchbox and mega-headings for mobile menus

---

fec/legal/urls.py

- Resolves #2132 
_Allow characters in MUR names_
-  Canonical MUR pages
localhost:8000/data/legal/matter-under-review/2892_A/

Allow characters in MUR names

---

fec/fec/static/scss/components/_datatables.scss

Resolves: #2112 
How to test:
Run this branch locally  `feature/fix-dropdown-menus-on-filings`
npm run build
Check this example page to make sure there is padding on the document dropdown
http://127.0.0.1:8000/data/committee/C00280743/?tab=filings

padding for document dwnld links

---

fec/fec/static/scss/calendar.scss
fec/fec/static/scss/datatables.scss

The import of `global-common.scss` into `datatables.scss` (not to be confused with components/_datatables.scss) somehow got reverted from when it was added in PR https://github.com/fecgov/fec-cms/pull/1962.
**This means on production, mega-menus viewed while on a datatable and calendar show no icons and look like this:**

Restore lost icons on datatable/calendar pages

---

fec/data/constants.py

- Resolves #2152 
_Change default presidential year to 2020._
-  Presidential candidate data table http://localhost:8000/data/candidates/president/
- `DEFAULT_PRESIDENTIAL_YEAR` constant
Fixing 2020 and future election totals: https://github.com/fecgov/openFEC/pull/3219

Change default presidential year to 2020

---

fec/data/templates/partials/filters/audit-committee-types.jinja

Add `Joint fundraising committee` filter to audit search
- Resolves #2093
Related OpenFEC PR: https://github.com/fecgov/openFEC/pull/3231
<hr/>

Joint fundraising committee filter for Audit Search

---

fec/fec/constants.py
fec/home/templates/home/home_page.html

- Resolves #2160
Because the info division isn't using the generic "Reporting Deadlines" category (category 21), this PR removes that checkbox from the reporting deadlines section of the calendar.
-  https://www.fec.gov/calendar/
- "All filing deadlines" link on home page

Remove mid-year and year-end reporting deadline category

---

fec/fec/static/js/pages/committee-single.js

- Resolves #2048 
_RFAIs of request type 2 were not being included in the 24/48 hour reports table. This PR fixes that._
Check this committee page to make sure RFAI notifications show up like in the screenshot below:
http://localhost:8000/data/committee/C90017450/?tab=filings
-  Committee profile page filings tab

Add RFAIs of request_type 2 to 24/48 hour reports table

---

fec/fec/static/js/legal/Filters.js
fec/fec/static/js/legal/filters/CitationFilter.js
fec/fec/static/js/legal/filters/CitationRequireAllRadio.js
fec/legal/templates/legal-advisory-opinion.jinja

This reverts commit 8ddb86438b10e26c9aab6059bd1a29b66203fd91 (`git revert 8ddb86438b10e26c9aab6059bd1a29b66203fd91`).
- Resolves https://github.com/fecgov/openFEC/issues/3259
_Add AO citations back to the front-end._
-  AO search and canonical page
#2159

Re-add AO citations

---

fec/fec/templates/partials/navigation/nav-data.html

Add `Historical statistics` link to mega menu that links to https://www.fec.gov//data/advanced/?tab=historical
- Resolves #2054 
Change to /fec/partials/navigation/nav-data.html

Add historical stats to mega menu

---

fec/legal/templates/legal-statutes-landing.jinja

Updated file sizes and linked to FECA now uploaded on FEC CMS as well as the updated 2015 versions of title 52 and title 26 on GPO.
- Resolves # [_2169_]

Update links to statute PDFs (2015 GPO version)

---

fec/fec/static/js/pages/committee-single.js

- Resolves #2174 
Add RFAIs of request_type 4 to 24/48 hour reports table. While RAD currently only sends RFAI's with code RQ-2, the RQ-4 code was used in the past and we need to display them.
-  Committee filings page
http://localhost:8000/data/committee/C90010661/?tab=filings under "24- and 48-hour reports" and look at the "RFAI: 24 HOUR NOTIFICATION 2010" which should have "RQ-4" in the upper right-hand corner when you download it.
Added RQ-2 https://github.com/fecgov/fec-cms/pull/2170

Show RQ-4 RFAI's in the 24- and 48-hour reports section

---

fec/legal/templates/legal-archived-mur.jinja

- Resolves #2157 
_Show multi-part archived MURs._
-  Archived MUR canonical pages
- If API change isn't merged yet, connect to `dev` API and then look at http://localhost:8000/data/legal/matter-under-review/1251/
- After API change is merged, connect to `dev` API and then look at http://localhost:8000/data/legal/matter-under-review/1252/ (It's currently labeled 1252_A, which is wrong. We will address that with the reload)
branch | PR
feature/archive_murs_multi_pdf_refactor | [link](https://github.com/fecgov/openFEC/pull/3278)

Show multiple-part PDFs for archived MURs, if available

---

fec/fec/static/js/pages/committee-single.js

- Resolves #2194 
_Fix missing F6's on committee filings page._
Some 48hr reports (form type F6) have a `NULL` report type. We were filtering by `report_type = ['24', '48','-Q1', '-Q2', '-Q3', '-YE']`. When the API searches for specific "include" values (24/48), it excludes null values and only returns filings have have `24` or `48` in the `report_type` field. 
[Example API call - no results](https://api.open.fec.gov/v1/committee/C00606939/filings/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=false&sort=-receipt_date&per_page=100&page=1&form_type=F5&form_type=F24&form_type=F6&form_type=F9&form_type=F10&form_type=F11&form_type=RFAI&report_type=24&report_type=48&report_type=-Q1&report_type=-Q2&report_type=-Q3&report_type=-YE&request_type=-1&request_type=-3&request_type=-4& …

[MERGE WITH GIT FLOW] Fix missing F6's on committee filings page

---

fec/data/templatetags/filters.py
fec/legal/templates/legal-archived-mur.jinja

- Second PR to resolve #2157 
_Show document length instead of size for archived MURs. On the API side, we changed document `size` label to `length` for consistency with current MURs. @vrajmohan I'm sorry I forgot to update my branch before you merged it._
-  Archived MUR canonical pages
#2185

Show document length instead of size for archived MURs

---

requirements.txt

The bandit python requirement is unused and was removed in the latest release, however, the removal did not get merged back into develop. This removes it from develop.

Removed bandit python requirement from develop

---

fec/data/templates/partials/advanced/committees.jinja

- Resolves #2224 
_Fixes incorrect committee summary data description link. Check to make sure link is now correct._
-  http://localhost:8000/data/advanced/?tab=committees

Fix committee summary data description link

---

fec/data/constants.py
fec/data/templates/macros/filters/contributor-states.jinja
fec/data/templates/partials/individual-contributions-filter.jinja
fec/data/templates/partials/receipts-filter.jinja
fec/data/utils.py
fec/fec/static/js/modules/column-helpers.js

- Resolves #2237 
Temporarily disable link for "other" state aggregates, fix non-filtering links for (AA, AE, AP, ZZ)
-  Candidate/committee raising pages - individuals by state
- Test by running openFEC branch `feature/fix-sched_a-by-state-display` locally and look at http://127.0.0.1:8000/data/committee/C00370007/?tab=raising
- Click through to "Armed Forces Pacific" or "Armed Forces America" - should filter properly
-   'Armed Forces Americas', 'Armed Forces Europe', 'Armed Forces Pacific', 'Foreign Countries' all appear in dropdown
https://github.com/fecgov/openFEC/pull/3321/files

Temporarily disable link for "other" state aggregates, add AA, AE, AP, ZZ filters and links

---

fec/fec/static/js/modules/helpers.js
fec/fec/tests/js/helpers.js
package-lock.json
package.json

- Resolves #1953
_This replaces the vulnerable bleach package with sanitize-html._
-  Type ahead filters
- checkout and run this branch locally: `feature/1953-add-sanitizehtml`
- npm install
- npm run test-single
- Go to this page: http://localhost:8000/data/candidates/
- Try to type in a script tag like this `X0YZ12345><sCrIPt>test</ScRiPt>` into the candidate name type ahead and submit. The checkbox that is generated should be scrubbed and look like this "X0YZ12345>"

Replace bleach vulnerable package with sanitize-html

---

fec/data/templates/partials/candidate/raising.jinja
fec/data/templates/partials/candidate/spending.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja

- Resolves https://github.com/fecgov/openFEC/issues/3217
_Display transaction_coverage_date in the "Coverage dates" section of candidate and committee raising/spending pages_
- Totals-level data should continue to use `coverage_end_date`
- Transaction-level data is only available as it's processed - use new `transaction_coverage_date` field in API if it's available.
- If no data is available for `transaction_coverage_date` (for example, only one report has been received and it's un-processed, fall back to `coverage_end_date`
- Candidate raising/spending pages  "Coverage dates"
- Committee raising/spending pages "Coverage dates"
https://github.com/fecgov/openFEC/pull/3310

Use new transaction_coverage_date for candidate and committee raising/spending pages

---

fec/fec/static/js/modules/tables.js

- The `Use bulk data to export more than 500,000 records` link has been changed  go to https://www.fec.gov/data/advanced/?tab=bulk-data
- searched for other occurances-found none.
Resolves #2203
Export  message on any datatable when showing more than 500,000 records
Changed link on `tables.js`

Correct bulk-data link

---

fec/home/templates/blocks/section.html
fec/home/templates/partials/section-nav.html

- One piece of #2264 
_Resource and collection template: the left nav is not scrolling to anchors.  Looks like the templates and the section nav partial were using the `filter remove_digit` function. Not sure why that was used in the creation of the anchors.  If numbers are **not** allowed in section title anchors, this should not be merged._
- `fec/home/templates/blocks/section.html`
- `fec/home/templates/partials/section-nav.html`

Remove filter remove_digits from section titles and anchors

---

.circleci/config.yml
fec/home/migrations/0001_initial.py

- Gets `develop` set up with Python tests until we can hotfix with #2221 
Re-enable Python tests
- Comment out the `dependencies = [('wagtailcore', '0040_page_draft_title')]` line in `0001_initial.py` (Once we get a new dump file from `prod` after the release we won't have to do this)
- Restore local db with latest dump (7/27/18) if you haven't already.
```
dropdb cfdm_cms_test
createdb cfdm_cms_test
pg_restore --dbname cfdm_cms_test --no-acl --no-owner fec_cms_gov_cloud_prod_07-27-2018.dump
````
https://github.com/fecgov/fec-cms/wiki/Locally-restore-wagtail-postgres-database
- Run migrations
```
cd fec
./manage.py migrate wagtailadmin
./manage.py migrate wagtailcore
./manage.py migrate wagtaildocs
./manage.py migrate wagtailembeds
./manage.py migrate wagtailforms
./manage.py migrate …
```

Re-enable Python tests

---

fec/fec/draftail/anchor.py
fec/fec/static/js/draftail/Anchor.js
fec/fec/static/js/init.js

_Needed to update the draftail anchor component to remove the <a> tag from the anchor so that this component is not a link by default. Also updated the styles for the anchor when published and within the editor._

Removed <a> from anchor

---

fec/data/templates/election-lookup.jinja

- Discovered while testing #2087 
Remove sort by district - API sorts by 'sort_order(P,S,H), district'
-  Election search - http://localhost:8000/data/elections
Add 2020/2022 to election profile pages: https://github.com/fecgov/fec-cms/pull/2254

Remove sort by district - API sorts by 'sort_order(P,S,H), district'

---

README.md
fec/fec/templates/code.json
fec/fec/urls.py

Innovation sprint issue: add code.json file for code.gov open source inventory for repos:
1. FEC
2. fec-cms
3. openFEC
4. fec-eregs
5. fec-proxy
6. fec-infrastructure
7. fec-pattern-library
- code.json generated using https://github.com/LLNL/scraper
- Format: https://code.gov/#/policy-guide/docs/compliance/inventory-code
- Validator: https://code.gov/#/policy-guide/docs/compliance/inventory-code/tools/validate-schema
-  Should appear here: http://localhost:8000/code.json and later https://www.fec.gov/code.json

Add code.json file to root directory for code.gov open source inventory

---

fec/data/api_caller.py
fec/fec/settings/base.py

**Innovation sprint**
- Add logging for server-side API calls so we can track when the CMS makes server-side (AKA python) API calls. Right now you can see the client-side (AKA JavaScript) calls in the developer tools, but the only way to see the server-side calls that we’ve figured out is to run the API locally and check the API logs. 
- Clean up some formatting and make indentation consistent (thanks @apburnes!)
- fix an unused variable in `call_senate_specials`
This adds info-level logging to `_api_caller` along with which function is calling the API caller.
-  Server-side AKA Python API calls using `_api_caller()`

Add API caller logs

---

fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja

- Partial resolution for #2294
Fix committee pages for types 'C', 'E', and 'I'.  Assign transaction_end at top of jinja template.  `transaction_end` wasn't getting assigned for committee types 'C', 'E', and 'I', resulting in an error
Test with http://localhost:8000/data/committee/C90011875/?tab=spending
https://github.com/fecgov/fec-cms/pull/2223 
https://github.com/fecgov/fec-cms/issues/2247

[MERGE WITH GIT FLOW] Fix committee pages for types 'C', 'E', and 'I'

---

fec/data/templates/partials/advanced/candidates.jinja

The "Data description for this file" link under `All Candidates` on [/data/advanced/?tab=candidates](https://www.fec.gov/data/advanced/?tab=candidates) was linking to the `all-candidates` description page instead of the correct `candidate summary` description page.
- Resolves #2284 
modified:   data/templates/partials/advanced/candidates.jinja
**How to test:**
1) checkout feature/fix-candidate-summary-link
2) go to http://127.0.0.1:8000/data/advanced/?tab=candidates
3) make sure "Data description for this file" link under `All candidates` goes to  http://127.0.0.1:8000/campaign-finance-data/candidate-summary-file-description/

Fix link to candidate summary file description

---

fec/home/models.py

- Resolves #2314
Adding `'blank' and 'null'` KWARGs to meetings-agenda streamfield to make it an optional field so that the page can be published without agenda items entered. For meeting pages that are built ahead of time and for adding content to existing pages like Sunshine notices or meeting minutes, without having to add agenda items.
home/models.py (No migration required for this change)
`meeting-page` Wagtail editor templates
1) Checkout: feature/fix-required-wagtail-fields-meeting-page
2) Open existing executive session in Wagtail -and try to add a Sunshine Act Notice and preview or publish without  `required-field error` for the agenda field
3 OR: Create new meeting page (any type) in Wagtail and do not add any agenda items. Try to preview or publish without `required-field …

Make agenda streamfield an optional field

---

fec/data/templates/macros/cycle-select.jinja
fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/templates/partials/candidate/financial-summary.jinja
fec/data/templates/partials/candidate/other-spending-tab.jinja
fec/data/templates/partials/candidate/raising.jinja
fec/data/templates/partials/candidate/spending.jinja
fec/data/templates/partials/committee/about-committee.jinja
fec/data/templates/partials/committee/filings.jinja
fec/data/templates/partials/committee/financial-summary.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja
fec/data/tests/test_candidate.py
fec/data/views.py

- Replaces PR https://github.com/fecgov/fec-cms/pull/2316 - bad branch name
- Resolves #2294 
Refactor candidate view, fix 404's for future cycle candidates without committees, simplify 2-year select macro and use it for the candidate raising/spending pages
- Candidate profile pages
- Candidate raising/spending pages now show two-year period label (that's what we display) instead of election (election label was incorrect). Committee two-year period dropdowns should be unchanged - renamed to `two_year_select`
- Test previously 404-ing candidate pages: 
http://localhost:8000/data/candidate/H0TX09168/
http://localhost:8000/data/candidate/P40003832/
- Test future/past House/Senate/Presidential pages
#2302 *Add tests for …

Refactor candidate view, fix 404's for future candidates

---

fec/fec/static/scss/base.scss
fec/fec/static/scss/components/_responsive-object.scss
requirements.txt

- Resolves #2336 
- Upgrades the wagtail version
- Adds the `responsive-object` styling to fix embedded videos in wagtail
- Add copy and paste functionality to wagtail draftail editor
- Upgrade wagtail python package
- additional database migrations
- `wagtaildocs.0008_document_file_size`
- `wagtailimages.0020_add-verbose-name`
- `wagtailimages.0021_image_file_hash`
- `wagtailredirects.0006_redirect_increase_max_length`
- `wagtailusers.0007_userprofile_current_time_zone`
- `wagtailusers.0008_userprofile_avatar`
- add `scss` component for class `.responsive-object`

Update wagtail to v2.2.1 and responsive video styling

---

fec/fec/templates/partials/navigation/nav-help.html
fec/home/templates/home/candidate-and-committee-services/services_landing_page.html

- Resolves #2319 
- Updated  training link on Help for candidates and committees main navigation menu and link with picture labeled "Education and learning" on help for candidates and committees landing page
-  Help for candidates and committees navigation menu
- Services landing page education and outreach link

Updated links to point to new cms training page

---

fec/data/templates/landing.jinja
fec/data/templates/partials/advanced/raising.jinja
fec/data/templates/partials/advanced/spending.jinja
fec/fec/settings/base.py
fec/fec/static/js/pages/data-landing.js

_For easier feature control, this PR adds a feature flag for the line chart feature._
- To leave the linecharts turned on, set the flag in the environment: `export FEC_FEATURE_LINECHARTS=true`
- To turn off the linechart feature, remove the FEC_FEATURE_LINECHARTS from the environment variables
- Data landing: http://localhost:8000/data/
- Raising advanced data page: http://localhost:8000/data/advanced/?tab=raising
- Spending advanced data page: http://localhost:8000/data/advanced/?tab=spending

Adds feature flag for line charts

---

fec/home/models.py
fec/home/templates/home/press_landing_page.html

- Resolves #2374 
_This PR removes the hardcoded contact page information from the press landing page and leaves only the intro section. Needed to do this so that we can insert an HTML block into the contact intro for easier changes without needing a code change._
Follow-up issue to insert the HTML block is here: https://github.com/fecgov/fec-cms/issues/2375
-  Press landing page

Removes hardcoded contact page information

---

fec/fec/static/js/pages/candidate-single.js

Filings tab was not responding properly to different screen sizes causing table to be cut off and not match experience of other tables in the profile pages.
- Resolves #2381
Add proper class names to hide image number and pages at med breakpoint
modified:   fec/static/js/pages/candidate-single.js

Fix filings tab responsive issues

---

fec/fec/static/js/modules/line-chart-committees.js
fec/fec/static/js/modules/line-chart.js

_Adds an updated date format for plotting the chart line and points to work on Iphone_
- `line-chart.js`
- `line-chart-committees.js`
- https://stackoverflow.com/questions/21883699/safari-javascript-date-nan-issue-yyyy-mm-dd-hhmmss/21884244#21884244

Update date parsing for plot points to work on iphone too

---

fec/home/models.py

Make related media optional in reporting_example template so that new `reporting_example` pages can be published without r`elated media` 
- Resolves #2398
Related to issue #2389
modified:   home/models.py (no migration)

Make related media optional in reporting_example template

---

fec/data/templates/layouts/main.jinja
fec/legal/templates/legal-search-results-advisory_opinions.jinja

- Closes https://github.com/fecgov/openFEC/issues/3407
- Move the current polyfills used to support IE in the legal app to be used for all `/data` routes.
- Now it will support all maps, graphs, react, and any unsupported js methods in IE

Move polyfills scripts to be loaded for all /data routes

---

fec/fec/static/js/modules/helpers.js

- Resolves #2403 
**Hide amendment version, only show "Original" when it's confirmed for F1 and F2**
- Only show 'original' if amendment chain is 1 
- Don't show amendment number for F1 and F2 due to unreliable data **Note** This is still wonky for F1N's that were filed when we first moved to file ID's around 2006:
http://localhost:8000/data/committee/C00491951/?tab=filings&cycle=2014
http://localhost:8000/data/candidate/H8WI01024/?tab=filings
http://localhost:8000/data/candidate/H8CA05035/?tab=filings
branch | PR
`feature/fix-most-recent-logic` | https://github.com/fecgov/openFEC/pull/3392

Fix Form 1 and Form 2 original/amendment labels

---

fec/data/templates/macros/cycle-select.jinja

- Resolves #2341 
_Inserts additional div container with cycle classes to fix election dropdown width._
http://localhost:8000/data/candidate/S2MA00170/?tab=raising
http://localhost:8000/data/candidate/S2MA00170/?tab=spending
-  Candidate profile pages: Raising & Spending tab

Fixed election dropdown on candidate profile page

---

fec/data/templates/candidates-single.jinja
fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/tests/test_candidate.py
fec/data/views.py

- Resolves #2321 
Fixes candidate compare button by using election year. If there's an odd election year passed, it will make it an even year.
**Candidate: Jon Ossoff**
- http://localhost:8000/data/candidate/H8GA06195/
**Candidate: Elizabeth Warren**
- http://localhost:8000/data/candidate/S2MA00170/

Fix candidate compare button

---

fec/data/views.py

- Resolves #2417
**Show raw electronic filings for senate filers**
-  Committee profile pages, filings tab for Senate filers
http://localhost:8000/data/committee/C00471557/?tab=filings

[MERGE WITH GIT FLOW] Show senate raw filings

---

fec/fec/static/js/templates/feedback.hbs
fec/fec/static/scss/components/_feedback.scss

- Placement of recaptcha badge under the submit button and links at bottom of feedback drawer instead of docked above the button as it renders by default
- Fix relative spacing issues with button/links so that if feedback badge does not render due to cacheing, it just leaves a blank space at bottom of drawer.
- Resolves #2205
- Related PR https://github.com/fecgov/fec-cms/issues/2353
modified:   fec/static/js/templates/feedback.hbs
modified:   fec/static/scss/components/_feedback.scss
<hr>

Recaptcha badge placement

---

fec/fec/static/scss/components/_feedback.scss

Recaptcha badge placement was breakimg in  Internet Explorer
- Resolves #2205
- Related PR #2353, #2421
modified:   fec/static/scss/components/_feedback.scss
This appears on all pages of site inside feedback tool

Fix recaptcha for Internet Explorer

---

fec/home/templates/home/updates/record_page.html

- Resolves #2390 
_Record article page breadcrumbs now link back to the correct publication type and category._
-  Record article page breadcrumbs

Fix record article page breadcrumbs

---

fec/fec/static/js/modules/filters/filter-tags.js
fec/fec/static/js/modules/tables.js

- Resolves https://github.com/fecgov/openFEC/issues/3104 along with https://github.com/fecgov/openFEC/pull/3421
Re-add datatable counts now that we've fixed them with https://github.com/fecgov/openFEC/pull/3421
-  All campaign finance data tables
Receipts
-  http://localhost:8000/data/receipts/
- http://localhost:8000/data/receipts/individual-contributions/
Disbursements
- http://localhost:8000/data/disbursements/
- http://localhost:8000/data/independent-expenditures/
- http://localhost:8000/data/party-coordinated-expenditures/
- http://localhost:8000/data/electioneering-communications/
- http://localhost:8000/data/communication-costs/
Loans
- …

Re-add datatable counts

---

requirements.txt

- Resolves #2263: **[Med] Snyk: Open Redirect (due 10/8/18)**
Upgrade Django and django-dependent packages
- `django`: Python web framework: https://docs.djangoproject.com/en/2.1/releases/1.11.15/
- `django-jinja`: jinja/HTML templates https://github.com/niwinz/django-jinja
- `cg-django-uaa`: cloud.gov UAA authentication backend https://github.com/18F/cg-django-uaa
Tested with a manual deploy to `dev` and logged in to Wagtail. As of 10/11 at 9:20 ET, changes are still live at https://fec-dev-proxy.app.cloud.gov/. Follow `develop` builds: https://circleci.com/gh/fecgov/fec-cms/tree/develop

Upgrade Django and django-dependent packages

---

.gitignore

Adds .pytest_cache to git ignore for newly implemented pytest

adding pytest_cache to git ignore

---

fec/fec/static/js/modules/tables.js
fec/fec/tests/js/tables.js

Resolves #2450: **Use exact counts for datatable results**
- Because the API now returns accurate counts above 500,000, provide the exact counts where results are 500,000 or less.
-  Remove the "about" when the results are 500,000 or less.
- Remove the audit check because we have  around 1K audits total,  I didn't think we'd ever get over 500,000, and it might slightly improve performance not to do the extra check.
-  Data table counts

Show exact counts under 500K

---

fec/fec/static/js/modules/home-events.js
fec/home/templates/home/home_page.html

- Resolves #2416 
_This removes the exec closed meetings from the homepage display._
-  Homepage meetings section

Remove closed meeting from homepage events

---

fec/data/tests/test_committee.py
fec/data/views.py

First step for resolving #2446
- Add tests for committee page
- Refactor `get_candidate` to start again with API call/formatting instead of using `redirect` and  `reverse` - this keeps formatting separate from routing, for testing purposes.
Testing links from @jwchumley https://docs.google.com/spreadsheets/d/1xmDu2Ypr2tJnUjWZJcMIf_SOD7BOipCR4fGD3FmZLJ0/edit#gid=0

Add test coverage for committee profile page

---

fec/data/templates/partials/disbursements-filter.jinja
fec/data/templates/partials/filters/spender-committee-types.jinja

This PR depends on api PR 3449 [https://github.com/fecgov/openFEC/pull/3449](https://github.com/fecgov/openFEC/pull/3449) which has been merged to develop branch on openFEC already and works well.
The api PR should release first, then this cms PR.
- Resolves # [_2128_] [https://github.com/fecgov/fec-cms/issues/2128](https://github.com/fecgov/fec-cms/issues/2128)
1)Change Disbursements filter label from `Spender details` to `Recipient details`
2)Add new `Spender committee type filter`
_How to test it_
1)checkout branch: feature/add_disbursement_spender_cmte_tp_filter
2)setup api point to dev
export DATABASE_URL=postgresql://:@/cfdm_cms_test
export FEC_API_URL=https://fec-dev-api.app.cloud.gov
export FEC_WEB_API_KEY=
export FEC_WEB_API_KEY_PUBLIC= …

Add spender committee type filter into disbursements page.

---

fec/data/api_caller.py
fec/fec/settings/base.py
fec/legal/templates/legal-search-results-adrs.jinja
fec/legal/templates/partials/legal-search-results-adrs.jinja
fec/legal/urls.py
fec/legal/views.py

- Resolves #2436 
_This adds ADR datatable page to the enforcement legal features._
1. `vi ~/.bash_profile` and insert this feature flag for ADRs `export FEC_FEATURE_ADRS=true`
2. Open a new terminal window and run the branch
3. Go to http://localhost:8000/data/legal/search/adrs/ to test the page. At this point, none of the canonical ADR links will work since that is phase 2 of the development for this feature.
-  Enforcement ADR datatable page

Add ADR datatable page

---

fec/data/constants.py
fec/data/templates/partials/committee/financial-summary.jinja
fec/data/tests/test_committee.py
fec/data/utils.py
fec/data/views.py

- Resolves #2446 
Modify financial summary display for Inaugural committees. 
-  Inaugural committee financial summaries
Test with http://127.0.0.1:8000/data/committee/C00540005/?tab=summary and point to `dev` API
More test data: https://docs.google.com/spreadsheets/d/1xmDu2Ypr2tJnUjWZJcMIf_SOD7BOipCR4fGD3FmZLJ0/edit#gid=1956073211
branch | PR
`https://github.com/fecgov/openFEC/pull/3432` | https://github.com/fecgov/openFEC/pull/3432

Modify financial summary display for Inaugural committees

---

.eslintrc
fec/data/urls.py
fec/data/views.py
fec/fec/static/js/modules/reaction-box.js

- Resolves #2470 
Requires name, location, reaction, recaptcha response, and user agent to be defined. If it is not, return error.
- Check out the branch and `npm run build`
- Submit reaction boxes below line charts for:
-  Reaction feedback box

[HOTFIX - Merge with gitflow] Adds additional reaction box validation

---

fec/legal/templates/legal-adr.jinja

_On the ADR canonical page, the "Closing date" label was incorrectly labeled as "Opening date". This corrects the label_
-  ADR canonical page

Corrected ADR closing date label

---

fec/data/constants.py
fec/data/tests/test_committee.py
fec/data/utils.py
fec/data/views.py

- Resolves #2446 (Part 2)
Change labels for F4 filer financial summary
-  Committee profile pages for host committees that file on Form 4
Point to `dev` API if this PR has been merged: https://github.com/fecgov/openFEC/pull/3458 or follow the steps in the PR to point to your local API. Take a look at http://localhost:8000/data/committee/C00493254/ if pointing to local API/DB, or use the test data here https://docs.google.com/spreadsheets/d/1xmDu2Ypr2tJnUjWZJcMIf_SOD7BOipCR4fGD3FmZLJ0/edit#gid=1956073211 if it's been merged.
branch | PR
fec-cms `feature/add-f13-f4-summaries-2` | https://github.com/fecgov/fec-cms/pull/2465
openFEC `feature/add-form-4-fields` | …

Fix Form 4 (Host Committee) financial summary labels

---

fec/fec/static/js/modules/dropdowns.js
fec/fec/tests/js/dropdowns.js

Currently, once you choose all the checklist items in a filter dropdown, the dropdown disappears. Although there is a legitimate UX argument for this behavior, the fact that it does not reappear in the  unlikely (but possible edge-case ) event that the user removes all chosen filters means the user ultimately no longer has access to those filters. This PR makes the dropdowns persist, regardless of filters chosen.
Resolves: #2117
fec/static/js/modules/dropdowns.js
- Checkout and un this branch
- Make sure a checklist-dropdown does not disappear after choosing all the items and  adding them to the selected filters list above.
- http://127.0.0.1:8000/data/disbursements/ is a good one to test because it has a two-item dropdown.

Fix disappearing dropdown

---

fec/fec/static/js/modules/tables.js
fec/fec/tests/js/tables.js

- Resolves #2481 
_Shows nulls in datatables by default. Null values will no longer be hidden, which means that these rows will now be filterable and searchable_
**Future improvement**
A corresponding API fix will need to be made to make the display better by always sorting nulls last. Issue logged here: https://github.com/fecgov/openFEC/issues/3470
- Check datatables (below is not a list of all the datatables, but a list of tables that now shows nulls on first load):

show null data in datatables by default

---

fec/data/templates/partials/advanced/filings-reports.jinja
fec/data/templates/partials/advanced/loans-debts.jinja
fec/data/templates/partials/advanced/raising.jinja
fec/data/templates/partials/advanced/spending.jinja

Add datatable descriptions and glossary links(where applicable) to adv data page templates
- Resolves #2426
modified:   data/templates/partials/advanced/filings-reports.jinja
modified:   data/templates/partials/advanced/loans-debts.jinja
modified:   data/templates/partials/advanced/raising.jinja
modified:   data/templates/partials/advanced/spending.jinja
- checkout  `feature/implement-datatable-descriptions-adv-data`
- Go to http://127.0.0.1:8000/data/advanced/?tab=raising, (and other appllciable tabs) to verify changes in issue  #2426 have been made

Implement data table descriptions

---

fec/fec/static/js/modules/tables.js
fec/fec/tests/js/tables.js

- Follow-up front-end task for https://github.com/fecgov/openFEC/issues/3470 and Resolves #2481 
Because we can't know where null values belong, we should always sort nulls last (at the bottom, on the last pages) in data tables.
- Point to `dev` API 
- Check datatables (below is not a list of all the datatables, but a list of tables that were showing nulls on first load). They should all show nulls at the end.

Sort nulls last in data tables

---

fec/data/templates/candidates-single.jinja
fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/templatetags/filters.py
fec/data/views.py

Found while testing #2463
- Resolves #2499: Fix candidate page 404 errors due to missing district
- Fix candidate page 404 errors due to missing district. 
- Only show compare button if link can be generated
- Hide grey box if compare link can't be generated
- (code cleanup) Remove variable self-assignment
-  Candidate profile pages
- Point to `dev` API
- These pages should load:
http://localhost:8000/data/candidate/H0CA00116/?tab=summary
http://localhost:8000/data/candidate/H0CA00116/?tab=about-candidate

Fix candidate page 404 errors due to missing district

---

fec/fec/static/js/modules/election-map.js

Selecting states on /data/elections was inconsistent, sometimes zooming in, sometimes out
- Resolves #2447
modified:   fec/static/js/modules/election-map.js
This solution uses the leaflet.js flyTo() function, using `this.overlay.getBounds(),this.opts` as arguments,  instead of fitBounds().
- Checkout and run this branch locally: `feature/fix-districts-map-zoom`
- go to http://127.0.0.1:8000/data/elections/ and test selecting states and districts to ensure that the map zooms into each chosen state and/or districts without zooming way out like it is on production.

Fix districts map zoom-to-state

---

fec/fec/static/js/modules/helpers.js

- Resolves #2504
Fix candidate filing pages for missing amendment chain. In rare occasions like [this filing](http://docquery.fec.gov/pdf/569/201701209041436569/201701209041436569.pdf), a F99 will get coded as a F2 and won't have an amendment chain. This PR checks for an amendment chain before trying to check its length. 
-  Candidate filings page
https://github.com/fecgov/fec-cms/pull/2410
Filings should load:
http://localhost:8000/data/candidate/P80001571/?tab=filings
http://localhost:8000/data/filings/?data_type=processed&candidate_id=P80001571

[MERGE WITH GIT FLOW] Fix candidate filing pages for missing amendment chain

---

fec/fec/static/js/modules/election-map.js

Remove setTimeout function so zipcode zoom/color works properly
The setTimout error was added to remove console error, but then causes problems with the zipcode search function.( There exists a console error on production, so this still represents a step forward and the current console error will be researched.)
- Related issue #2447
- Related PR #2502
modified:   fec/static/js/modules/election-map.js
- Checkout and run this branch locally: `feature/fix-districts-map-zoom`
- go to http://127.0.0.1:8000/data/elections/ and select states and districts,  then enter a zipcode and see that it zooms to that zipcode with district colored.

Remove setTimout function-elections map

---

fec/data/templates/landing.jinja
fec/data/templates/partials/advanced/raising.jinja
fec/data/templates/partials/advanced/spending.jinja

_This removes the reaction box feedback feature from the data landing page, raising page, and spending page. The reaction box needed to be removed after 1 months time, which has been reached._
Make sure the reaction box feature no longer appears on the following pages
-  http://localhost:8000/data/
- http://localhost:8000/data/advanced/?tab=raising
- http://localhost:8000/data/advanced/?tab=spending

Remove reaction box feedback from site

---

fec/home/templates/home/commission_meetings.html

Resolves #2514: Add language to hearings page to refer people to SERS for archived hearings
- Add this sentence to the end of the description at the top of https://www.fec.gov/meetings/?tab=hearings:
>This page lists upcoming public hearings as well as those held from 2005 through the present. Use SERS to search for all archived rulemaking hearings.
- Add the link to SERS in that sentence so that it points to http://sers.fec.gov/fosers/
(note that https doesn't currently work with SERS - @patphongs is looking into it)
-  http://localhost:8000/meetings/?tab=hearings

Refer to SERS for archived hearing pages and files

---

fec/fec/settings/base.py
fec/fec/settings/dev.py
fec/fec/settings/production.py
fec/fec/tests/test_robots.py
fec/fec/urls.py

Resolves #2517: Show robots.txt in all environments except production
- Add tests
- Simplify logic
- Clarify Django settings files
-  https://fec-dev-proxy.app.cloud.gov/robots.txt
- https://stage.fec.gov/robots.txt
- https://fec-feature-cms.app.cloud.gov/robots.txt (edited)
branch | PR
feature/fix-robots | https://github.com/fecgov/fec-cms/pull/1893
I tested this with a manual deploy to the `dev` space

Show robots.txt in all environments except production

---

fec/fec/settings/base.py
requirements.txt

Resolves #2457 
- Upgrade django-storages to 1.7.1
- Default to using the bucket's ACL per django-storages warning:
From Django-storages:
> "The default behavior of S3Boto3Storage is insecure and will change
in django-storages 2.0. By default files and new buckets are saved
with an ACL of 'public-read' (globally publicly readable). Version 2.0 will
default to using the bucket's ACL. To opt into the new behavior set
`AWS_DEFAULT_ACL = None`
See https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L280-L287
-  S3 storage
- Wagtail image and document upload
branch | PR
feature/714-s3-files-uploads | …

Upgrade django-storages to 1.7.1

---

fec/fec/templates/data.json
fec/fec/tests/test_static_files.py
fec/fec/urls.py

Partial resolution for #2362: Add FEC API to data.gov
- Add data.json file to root directory (www.fec.gov/data.json) for data.gov harvesting process.
- Add tests for code.json and data.json files
branch | PR
`feature/add-codegov-json`| https://github.com/fecgov/fec-cms/pull/2260: Add code.json file to root directory for code.gov open source inventory
- http://localhost:8000/data.json should display data.json metadata file. 
- Validate with https://labs.data.gov/dashboard/validate. Schema is here: https://project-open-data.cio.gov/v1.1/schema/#modified

Add data.json file for data.gov

---

fec/fec/static/js/pages/committee-single.js

- Resolves https://github.com/fecgov/fec-cms/issues/2242
Made the`Total contributed` column  sortable on both Employer and Occupations tabs.
On committee profile pages, under Raising, on the Individual contributions table, the sort function now works on both Employer and Occupation tab.
Production (without sort):
https://www.fec.gov/data/committee/C00431445/?tab=raising#individual-contribution-transactions
Local (with sort): 
http://localhost:8000/data/committee/C00431445/?tab=raising#individual-contribution-transactions
`Total contributed` column is now sortable on both `Employer` and `Occupation` tabs

Enable sort on employer and occupation columns

---

fec/fec/static/js/modules/maps.js
fec/fec/static/js/modules/tables.js

- Resolves #2544: Fix "Individual contributions" section for future candidates
- Pass `election_full=true` for comparison table & map
-  Election profile pages of future presidential and senate candidates
https://github.com/fecgov/fec-cms/pull/2254: Add future elections to election search & profile pages (This related PR missed the "Individual contributions" section)
- http://localhost:8000/data/elections/senate/CA/2022/#individual-contributions
- http://localhost:8000/data/elections/president/2020/#individual-contributions

Election profile page: Fix "Individual contributions" section for future candidates

---

fec/data/constants.py
fec/fec/static/js/modules/columns.js

- Resolves https://github.com/fecgov/fec-cms/issues/2361
Added `Committee ID` column to Committees datapage.
-  Committees datapage
In Production(Before fix)
In Local env(After fix)
- checkout the branch `feature/add-cmteid-to-committees-datatable`
- Committee ID column should appear here :http://localhost:8000/data/committees/

Add CommitteeID column to committees datapage.

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/committees-filter.jinja
fec/data/templates/partials/individual-contributions-filter.jinja
fec/data/templates/partials/receipts-filter.jinja

- Resolves #2129 : Add `recipient_committee_type` filters to receipts and individual contribution data tables. Add a macro for committee type filters so we can pass the API the `recipient_committee_type` filter 
**Turn filter into macro**
- http://localhost:8000/data/committees/
**Add filter macro to receipts and individual contributions data tables**
-  http://localhost:8000/data/receipts/?two_year_transaction_period=2018&data_type=processed&min_date=01%2F01%2F2017&max_date=06%2F25%2F2018&committee_type=P
- http://localhost:8000/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F25%2F2018

Add recipient committee type filters to receipts and individual contribution data tables

---

fec/data/templates/partials/advanced/bulk-data.jinja

- Resolves #2522 
Rename  'Contributions to committees' section to 'Contributions from committees to candidates & independent expenditures'
-  https://www.fec.gov/data/advanced/?tab=bulk-data
http://localhost:8000/data/advanced/?tab=bulk-data

Rename section to 'Contributions from committees to candidates & independent expenditures'

---

fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/partials/legal-pagination.jinja
fec/legal/views.py

- Resolves #2351 
**Refactor MUR search to use generic `case_` filters**
I left the template variables alone and changed only the API call, but I'm open to approaching it differently.
-  MUR search
https://github.com/fecgov/openFEC/pull/3365: Add ADRs and AFs to API

Update MUR filters to use generic `case_` filters

---

fec/fec/static/scss/components/_mega-menu.scss

"Dates and deadlines" was breaking up across two columns in the H4CC mega-menu **in Safari desktop and mobile browsers**. Adding `break-inside:avoid` to the `mega__item` class fixes this.
- Resolves #2564
modified:   fec/static/scss/components/_mega-menu.scss
Checkout and this branch: fix/breaking-text-mega-menu
Run `npm run build` or just `npm run build-sass` 
View site in Safari browser to see that "Dates and deadlines" appears as expected 
____

Fix breaking text on H4CC mega-menu (Safari)

---

fec/legal/templates/macros/legal.jinja

_Fixed link to the "File an issue" button on the legal no results macro._
-  Legal global search results page
1. Go to legal global search results page: http://localhost:8000/data/legal/search/?search_type=all&search=
2. Click on "File an issue" button, it should now go to our FEC issues repo.

Fixed file an issue link on legal no results macro

---

fec/data/templates/macros/cycle-select.jinja

https://github.com/fecgov/fec-cms/issues/2588
I changed the label for the election cycle <select> from "Election" to "Two-Year Period" (both are capped with css).
- Resolves #2588 
It's a tiny change to the text in the label.
-  
The label can be reviewed at
/data/raising-bythenumbers/
/data/spending-bythenumbers/
____

Changing the label for the cycle <select>

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/about-committee.jinja
fec/data/templates/partials/committee/filings.jinja
fec/data/templates/partials/committee/spending.jinja
fec/fec/static/js/pages/committee-single.js

- Resolves https://github.com/fecgov/fec-cms/issues/2301
-  C3 filer profile pages
- Spending, Filing sections of this filer
About the filer section:
Spending section:
Filing section:
1. checkout the branch `feature/update-ec-filer-committee-profile-template`
2. point the local cms server to dev api
3. start the server
4. For EC filers :click below links to see changes made on the Section and subsections on the left hand side menu( About the filer, Spending, Filings etc..) 
-  http://127.0.0.1:8000/data/committee/C30002885/?tab=about-committee&cycle=2018
-  http://127.0.0.1:8000/data/committee/C30002885/?tab=spending&cycle=2018
-  http://127.0.0.1:8000/data/committee/C30002885/?tab=filings&cycle=2018
5. Test any non EC committee to make sure the Sections and subsections on the left hand …

[Merge After openFEC #PR3535]Update the committee profile pages for EC filers

---

fec/data/templates/macros/cycle-select.jinja
fec/data/templates/raising-bythenumbers.jinja
fec/data/templates/spending-bythenumbers.jinja

Part 2 to resolve #2588
Resolves an issue found while testing. We should keep the "election" label for `cycle_select` on election search, election profile, candidate, and committee profile pages. This PR adds an optional `label` argument to `cycle_select` macro so we can relabel the dropdown when needed.
Anywhere that uses `cycle_select`:
- Election profile pages
- Candidate/committee profile pages
- Raising/Spending charts
branch | PR
2588-relabel-election-to-twoyear-period | #2590
- Election search page cycle dropdown should be labeled "Election": http://localhost:8000/data/elections/
- Raising/Spending date range dropdown should be labeled "Two-year period": …

Add optional label for cycle_select

---

fec/data/templates/election-lookup.jinja
fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja

- Resolves #2595 
Fix spelling of Pennsylvania on PA special election banner
- Banner on all 2018 PA house election profile pages 
(ie https://www.fec.gov/data/elections/house/PA/17/2018/)
- Info accordion on https://www.fec.gov/data/elections/?cycle=2018&state=PA
- http://localhost:8000/data/elections/house/PA/01/2018/
- http://localhost:8000/data/elections/?cycle=2018&state=PA

Fix spelling of Pennsylvania

---

fec/data/constants.py
fec/data/templates/macros/filters/election-filter.jinja
fec/data/views.py

Resolves #2587 
- Set next election cycle to 2020 for election search and senate data tables, keep financial time period at 2018 (we won't have 2-year time period data for 2020 until we receive the 2018 YE on 1/31/19)
- Use constants to determine current and future elections for senate and presidential candidate data tables
- Remove unused API call for top candidates on data landing page for performance improvement
- "Election" dropdown on https://www.fec.gov/data/elections/
- "Election year" dropdown on https://www.fec.gov/data/candidates/senate/
- Removed unused API call for https://www.fec.gov/data/
- http://localhost:8000/data/elections/?state=&cycle=2020&election_full=true
- …

Update upcoming election to 2020, remove unused API call

---

fec/data/api_caller.py
fec/fec/settings/base.py
fec/legal/templates/legal-search-results-afs.jinja
fec/legal/templates/partials/legal-search-results-afs.jinja
fec/legal/urls.py
fec/legal/views.py

- Resolves #2438 
_This adds Admin fines datatable page to the enforcement legal features._
1. `vi ~/.bash_profile` and insert this feature flag for ADRs `export FEC_FEATURE_AFS=true`
2. Open a new terminal window and run the branch
3. Go to http://localhost:8000/data/legal/search/admin_fines/ to test the page. At this point, none of the canonical Admin fine links will work since that is phase 2 of the development for this feature.
-  Enforcement Admin fines datatable page

Admin fines datatable page v2

---

fec/home/templates/home/candidate-and-committee-services/guides.html

Adding Other filers to /help-candidates-and-committees/guides
- Resolves # [2222](https://github.com/fecgov/fec-cms/issues/2222)
Added an Other filers option at the bottom of the left column (in fec/home/templates/home/candidate-and-committee-services/guides.html)
And added another tabpanel at the bottom for the Other filers content
This section will link to the [new Other filers page](https://www.fec.gov/help-candidates-and-committees/other-filers) and to various places on it
- Go to http://localhost:8000/help-candidates-and-committees/guides/
- Verify that "Other filers" (capped) is at the bottom of the left column
- Click "Other filers"
- Verify that the main content has changed to the [content for Other filers](https://docs.google.com/document/d/1_76eBAtftxN4pNEq6RE1JtpAZYlJLSb1O2K1zY3 …

2222 Add "other filers" option to hard coded page

---

fec/data/constants.py
fec/data/utils.py
fec/data/views.py

Resolves #2631 along with API PR (Part 1): https://github.com/fecgov/openFEC/pull/3561
- Pass election year to API for full election totals
- Add 2020 to available transaction date ranges
- Delay new two-year period for candidate committees until Q1 (4/15/19)
-  Candidate profile pages, all-years total. Transaction data tables date range options.
branch | PR
`feature/fix-2020-totals` (openFEC) | https://github.com/fecgov/openFEC/pull/3561
- If https://github.com/fecgov/openFEC/pull/3561 hasn't been merged to `dev`, run local API on `feature/fix-2020-totals` branch
Compare 2-year/all-year totals to production:
- 2020 senate: …

Fix logic for full cycle candidate committee totals (Part 2)

---

fec/home/templates/home/candidate-and-committee-services/services_landing_page.html

As part of the other filers ticket here: https://github.com/fecgov/fec-cms/issues/2222#issuecomment-435034634, we needed to add the other filers button to the Help for candidates and committees landing page.
Test on this page: http://localhost:8000/help-candidates-and-committees/
-  Help for candidates and committees landing page

Add other filers button to h4cc landing page

---

fec/fec/static/js/modules/maps.js
fec/fec/static/js/templates/calendar/events.hbs
fec/fec/static/scss/components/_tooltips.scss

Being absolutely positioned, the tooltip was ignoring the size of its content.
- Resolves # [2644](https://github.com/fecgov/fec-cms/issues/2644)
The changes should only affect the map tooltips, and only with tooltips that appear above the pointer but we should make sure we check maps and tooltips elsewhere on the site.
`fec/fec/static/js/modules/maps.js`:
- Expanded js to set tooltip height to accommodate that of its content + padding.
- Adjusted the vertical distance between the tooltip point and the pointer so the tooltip no longer appears under the pointer.
`fec/fec/static/scss/components/_tooltips.scss`:
- Adjusted tooltip `width` settings to be `min-width` so wider content (like "Pennsylvania") don't overflow the right edge of the tooltip
- Horizontally centered the downward arrow …

Restyle tooltip so content is visibly contained within

---

fec/home/templates/home/candidate-and-committee-services/guides.html

- Resolves #2672 
_Fixed typo from `independent expenditure` to `independent expenditures`._
-  Other filers section of guides

Fixed other filers typo

---

fec/home/templates/blocks/mur_search.html

- Resolves #2637 
_Updated query to use `case_no` in order for MUR number search to work._
-  MUR search CMS widget
- Go to http://localhost:8000/data/legal/search/enforcement/
- Type a MUR number like `4321`
- Check that MUR number is filtered correctly on MUR search results

Fixed MUR number search on enforcement

---

fec/fec/static/js/modules/table-columns.js

- Resolves #2455 
_Adds `cycle` and `election_full=true` to candidate name link query parameters. This is the link that is built in the election profile page "Candidate financial information section" and "Candidate information" section_
-  Election profile pages
- Go to any election profile page, for example: http://localhost:8000/data/elections/president/2000/
- Go to Candidate financial totals datatable and make sure that the Name column links the candidate name with the cycle and election_full query parameters added.
- Go to Candidate information datatable and make sure that the Name column links the candidate name with the cycle and election_full query parameters added.

Add cycle and election_full query parameters to candidate name link

---

fec/legal/templates/legal-statutes-landing.jinja

Updates file sizes for the FEC PDF file (new version uploaded) and the 2017 versions available on GPO's website that we link on the legal resource statutes page at https://www.fec.gov/data/legal/statutes/
Specifically:
The 2019 edition of the gray book has been uploaded to https://www.fec.gov/resources/cms-content/documents/feca.pdf
Latest files from govinfo.gov for:
Title 52: 
Link to: https://www.govinfo.gov/content/pkg/USCODE-2017-title52/pdf/USCODE-2017-title52-subtitleIII-chap301.pdf
Title 26: 
https://www.govinfo.gov/content/pkg/USCODE-2017-title26/pdf/USCODE-2017-title26-subtitleH.pdf
- Resolves # [2459]
File sizes:

Update GPO links to statute PDFs

---

fec/fec/static/js/modules/other-spending-totals.js

- Resolves issue found in testing: **Remove double slashes from spending urls**
- `helpers.buildUrl` is expecting the format `['elections', 'search']`
- URL was being formatted as localhost:5000/v1//schedules...
"Spending by others to support or oppose" tab: http://localhost:8000/data/candidate/P80001571/?tab=other-spending&cycle=2016&election_full=false

Remove double slashes from spending urls

---

fec/data/templates/macros/bythenumbers.jinja
fec/data/templates/raising-bythenumbers.jinja
fec/data/templates/spending-bythenumbers.jinja
fec/fec/static/js/modules/top-entities.js
fec/fec/tests/js/top-entities-breakdown.js

- Fix the fact that candidates with `"party": null` in their data break rendering from their number to the end of that page because the JS that truncates it to one-character/uppercase cannot act on a non-string like `null`.
- Show the full, uppercase abbreviation for  candidates that have a party declaration in their data, instead of showing the one-letter that  we are now (from page 2 on)
- Show nothing for  each candidate with  `"party":null` 
(Aside: All the party abbreviations in the data are already uppercase.  I am not  sure why the code needs to ensure uppercase, unless their is some legacy code that is inconsistent. So I am leaving it in for now.)
- Resolves #2694
-Related PR: https://github.com/fecgov/fec-cms/pull/2695
modified:   data/templates/macros/bythenumbers.jinja …

[MERGE WITH GITFLOW] Hotfix-Handle party-null values in barcharts

---

fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja

- Resolves # [2671](https://github.com/fecgov/fec-cms/issues/2671)
Updated the button links on https://www.fec.gov/data/elections/president/2020
Only the Jinja template was updated but it may affect https://www.fec.gov/data/elections/president/*. Luckily, the links were made more generic so as not to require updates every year. Also, the buttons no longer link to transition.
Skipping the screenshots as there was no visible change, only URL changes
Some shots showing the URLs in the address bar and the button HREF in the status bar at the bottom of the window:
No related PRs, though there will be additional work to add the redirects specified in the To-do list in the ticket.
For these pages, verify the dark blue buttons' href values go to the new address—both the subdomain and the paths.
- …

Change button hrefs from transition to dates-and-deadlines

---

manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml
requirements.txt
tasks.py

- Resolves #2654 
_This upgrades CMS to `cflinuxfs3` stack and psycopg2 to v2.7.3.2._
We tested together by deploying manually to the CMS dev environment to make sure the deploy was successful. It succeeded without incident.
-  Database connections and ubuntu stack

Upgrade CMS to cflinuxfs3

---

fec/fec/static/js/modules/aggregate-totals.js

- Resolves (no ticket number)
Though this file is a work in progress, I removed the large chunks of comments.
Uglify was objecting to the uses of `let` and the template string so those have been changed, too.
This should only affect the aggregate totals block, which is still a work in progress and switched off by a feature flag.
-  
Nothing to see—just fixing a build error.
(none)
Running `npm run build-production` should no long err (because of aggregate-totals*)
____

Address Uglify's objections to aggregate-totals

---

.circleci/config.yml

I believe the build on `stage` was weird because Circle was caching dependencies. This change forces Circle to get fresh dependencies for the production deploy.
Use cache key prefix for finer control of cache. See the tip under https://circleci.com/docs/2.0/configuration-reference/#save_cache: "Given the immutability of caches, it might be helpful to start all your cache keys with a version prefix v1-.... That way you will be able to regenerate all your caches just by incrementing the version in this prefix."

Use cache key prefix for finer control of cache

---

fec/home/views.py

Updated the filter test for "non-filer publications". The dash in the category isn't triggering the former `if` so we'll test for the words, assuming the punctuation is escaped or otherwise encoded.
- Resolves #2745 
At least /fec/home/views.py as seen in http://localhost:8000/updates/?update_type=press-release&category=non-filer-publications
https://github.com/fecgov/fec-cms/pull/2528
- Go to http://localhost:8000/updates/?update_type=press-release&category=non-filer-publications
- Check that there are results
- Change the Press Release Subjects to something else, confirm results
- Change back to Non-filer publications, confirm results
- Check any other place this component may be used (if any)
____

Change test for non-filer filter

---

fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja
fec/data/templates/raising-bythenumbers.jinja
fec/data/templates/spending-bythenumbers.jinja

_Fixed link for "Raising overview" and "Spending overview" navigation buttons to link to the raising browse data and spending browse data section._
- raising-bythenumbers
- spending-bythenumbers
1. Go to http://localhost:8000/data/raising-bythenumbers/ and make sure raising overview link goes to the raising line chart
2. Go to http://localhost:8000/data/spending-bythenumbers/ and make sure spending overview link goes to the spending line chart

Fix raising / spending overview link

---

fec/data/templates/landing.jinja
fec/fec/static/scss/components/_search-controls.scss

_Election search page layout was falling out of alignment, so this PR creates a separate `.search--election-mini` class for elections the data landing page layout_
-  Data landing page
- Go to [data landing page](http://localhost:8000/data/) to make sure election search proportions are correct.
- Check the [homepage election search](http://localhost:8000) feature and [elections lookup main](http://localhost:8000/data/elections/) page to make sure styles did not change.

Fixed election search page layout

---

fec/data/templates/browse-data.jinja

Tiny update for the text and href of the data-use link at the bottom of /data/landing.
- Resolves #2718 
Only touched data/templates/browse-data.jinja
The text on the page and the link at the bottom of the window (status bar):
none
- Pull the branch.
- Go to http://localhost:8000/data/browse-data/
- Check the "Read more about the sale…" link just above the site footer.
____

Update the sale-or-use of FEC data link

---

fec/data/templates/partials/meta-tags.jinja
fec/fec/templates/partials/meta-tags.html

- Resolves #2778 
_Default to IE 11 browsers to resolve datatable issues._
-  Datatable related pages
- Go to the dev site, this branch is currently deployed there, data pages should function

[HOTFIX - Merge with gitflow] Specifies IE11 in meta tags

---

fec/data/templates/partials/browse-data/bulk-data.jinja
fec/data/templates/partials/browse-data/candidates.jinja

Fixed a link that was page-relative (and breaking) as well as a couple others I found while checking the rest of the site for the same issue.
- Resolves #2742 
/data/browse-data/?tab=candidates, the "Find which candidates" link.
Additionally, two orphaned links in /data/templates/partials/browse-data/build-data.jinja.
The updated href in the status bar:
none
- Go to http://localhost:8000/data/browse-data/?tab=candidates
- Check the "Find which candidates" link's href
For the other two links, verify that `/files/bulk-downloads/data_dictionaries/cm_header_file.csv` and `/files/bulk-downloads/data_dictionaries/cn_header_file.csv` exist
____

Change page-relative links to site-relative

---

README.md

- Resolves #https://github.com/fecgov/openfec/issues/3547
In README.md file, added two new sync vulnerability links. These links will display the count of vulnerabilites found in `package.json` and `requirements.txt file` off the `develop` branch
Verify  vulnerabilities count in the Snyk app link( https://snyk.io/org/fecgov/projects) vs new links added on `fec-cms` README.md file. Make sure the count matches and the links are not broken.

FEC-CMS : Add snyk vulnerability links 

---

fec/fec/static/scss/components/_table-styles.scss
fec/home/blocks.py

- Template for `custom_table block` was misplaced in `blockys.py`, causing improper rendering of custom table, specifically on statistical press releases (and anywhere else this block is used). 
- Also noticed that an empty scrollbar was appearing at bottom of custom table even when there was no overflow of content, so fixed this by changing `overflow-x:scroll` on custom-table in `_table-styles.scss` to `overflow-x:auto`
Resolves #2746
Move custom table block template into the proper location on blocks.py. 
modified:   fec/static/scss/components/_table-styles.scss
modified:   home/blocks.py
- checkout `feature/2746-fix-custom-table-template-rendering`
- run npm run build-sass
- Check statistical press release pages, like …

Fix custom table block rendering

---

fec/data/templates/partials/browse-data/filings-reports.jinja
fec/fec/static/scss/components/_accordions.scss

Add fec-notify accordion to filings-reports tab
**Do not merge until E-Filing team releases FEC Notify-- slated for release Friday, April 12, 2019**
Although there will be a new master branch (deploy date 04/09)  by the time this is merged (@04/12), it is unlikely that the simple changes here would conflict with any commits to that new master.
- Resolves #2777 
modified:   data/templates/partials/browse-data/filings-reports.jinja
static/scss/components/_accordions.scss
-  Checkout  hotfix/fec-notify-subscription-accordion
-  Test first accordion and links therein on http://127.0.0.1:8000/data/browse-data/?tab=filings
To merge with git flow, see `Step 2: For the hotfix reviewer` on t[his google doc](https://docs.google.com/document/d/1PUfmRMCkD4PaTt8D94pKdth-YlxAZJEWOZ1Id3ebq9s/edit#heading …

[DO NOT MERGE UNTIL 04/12 WITH GITFLOW] Add fec-notify accordion to filings-reports tab

---

fec/data/templates/layouts/main.jinja
fec/fec/templates/base.html
fec/fec/templates/home_base.html

- Resolves #2819 
_Feedback form was not able to load reliably since the init scripts were not given enough time to load. This PR adds a defer for the recaptcha api scripts to accommodate for time needed for init scripts to load_
Initial PR with implementation of feedback form https://github.com/fecgov/fec-cms/pull/2367

[HOTFIX - Merge with gitflow] added defer to recaptcha scripts

---

fec/fec/templates/partials/breadcrumbs.html
fec/home/models.py
fec/home/templates/home/resource_page.html
tasks.py

Resolves #2762
Added conditional statement to breadcrumbs.html that forces breadcrumb style based on parent-page type.
- All page-types published with a parent of  `legal-resources` , `campaign-finance-data` , and `introduction-campaign-finance`  will have blue breadcrumb style.
- All other page-types published NOT in the three sections above have red breadcrumb style
- Removed the  `breadcrumb-style checkbox` on the ResuorcePage "promote tab"  and the template tag ( `...style=self.breadcrumb_style %}` ) referring to this in the ResourcePage template
modified:   fec/templates/partials/breadcrumbs.html
modified:   home/templates/home/resource_page.html
modified:   /home/models.py
- Checkout `feature/2762-red-blue-breadcrumbs-custom-template`
- Login to Wagtail admin and navigate from the …

Make breadcrumbs render proper color based on parent section

---

fec/home/blocks.py
fec/home/models.py

Adds the  ability to add html (specifically, links) to core (Wagtail default) and custom table_blocks. 
- Resolves: There is no issue for this but resolves first wishlist item on the below doc:
"Tables: no github issue. Need the ability to add links within table cells (without manually html coding)- SORELY NEEDED"
https://docs.google.com/document/d/1HM1-SaxAL-pVhzwQY8ZP-1uA8bVlbAxwFhqW4f-3lAo/edit
Added html renderer option for core and custom tables in models.py and blocks.py
modified:   home/blocks.py
modified:   home/models.py
- Checkout `feature/add-html-link-capability-to-tableblocks`
- Login to Wagtail admin and create a child page of `CustomPage` type
- In the `body` section choose `Table`
- Create an html link in …

Add html/link capability to core and custom table_blocks

---

fec/data/templates/layouts/main.jinja
fec/fec/settings/base.py
fec/fec/static/js/modules/helpers.js
fec/fec/static/js/modules/tables.js

- Resolves #2833 
- Add FEC_DOWNLOAD_API_KEY as environment variable for data templates
- Add DOWNLOAD_API_KEY as a parameter to the download query
- Remove default api_key if a separate api_key is defined in the query
-  Export button when querying /download/ API calls
branch | PR
feature/limit-downloads-access | https://github.com/fecgov/openFEC/pull/3695
1. Set FEC_DOWNLOAD_API_KEY as environment variables
2. Test exporting a dataset like the candidates data: http://localhost:8000/data/candidates/. The `/download/` api call should only contain the `api_key` defined inside FEC_DOWNLOAD_API_KEY
3. Make sure all other client side API calls still uses the default …

Add download only API key to CMS 

---

fec/data/views.py
fec/fec/templates/partials/breadcrumbs.html
fec/fec/templates/partials/navigation/navigation.html
fec/home/models.py
fec/home/views.py

Make menu bar indicators consistent site-wide
- Resolves #2760
modified: home/models.py
modified: partials/navigation.html
modified: home/views.py
modified: data/views.py
- checkout `feature/2760-fix-menu-bar-indicator` or see `https://fec-feature-cms.app.cloud.gov`
- Test that menu bar indicator shows the proper parent section for all pages
- A few pages at the root level that have no parent section and will not get indicator: Example: `test-- new-features-our-design-team/` and `/freedom-information-act/`

Consistent  menu bar indicator

---

fec/fec/static/js/modules/top-entities.js
fec/fec/static/scss/components/_breakdowns.scss
fec/fec/static/scss/components/_table-styles.scss
fec/fec/static/scss/components/_toggles.scss
fec/home/templates/partials/raising-spending.html

This is a hotfix to fix responsive issues and rendering bugs with the homepage bar charts. 
Home page raising/spending bar charts
**Currently on production**
**This hotfix**
#2835
#2748
Checkout and run hot fix branch and test that above bugs are fixed at small/med screen sizes
____

[MERGE WITH GITFLOW] Hotfix for rendering bugs and responsive issues with home bar charts

---

fec/fec/static/js/modules/top-entities.js

- Fixes Raising/Spending barcharts bug on IPhone and Safari desktop which was showing non-presidential years as select option for presidential  searches. If a non-pres years was chosen, it would present the user with  a meaningless, zero-sum bar chart.
-  Adds `disabled(true/false)` property to accommodate Safari Desktop/Mobile's lack of support for hide/show --- or any JS or CSS display property manipulation on `select options`
```
if (optValue % 4 !== 0) {
$(this).hide().prop('disabled', true);
...
else {
$('#election-year option').show().prop('disabled', false);
}
```
So I think the best solution is to `hide/show` and `disable/enable` them. This way Chrome and FF do not show the options, while Safari/IPhone show them as disabled and unclickable.
**BTW:** If we REALLY needed to remove …

[MERGE BEFORE RELEASE] Raising-Spending barcharts - disable non-pres election years for Safari-and-IPhone

---

fec/data/templates/partials/loans-filter.jinja

This one PR will resolve 'incurred date filter' issue for loans page in sched_c.py:
- Resolves  [https://github.com/fecgov/openFEC/issues/3712](https://github.com/fecgov/openFEC/issues/3712)
- After openFEC PR [https://github.com/fecgov/openFEC/pull/3714](https://github.com/fecgov/openFEC/pull/3714) merge.
1)after openFEC PR  [https://github.com/fecgov/openFEC/pull/3714](https://github.com/fecgov/openFEC/pull/3714) merge to develop
2)checkout branch locally, point to develop api
3)test all filters and sortings for loan datatable page
loans page

[depends on openFEC PR3714]Change field name to 'loan_source_name' for loans filter

---

fec/fec/static/js/object-assign-polyfill.js
fec/home/templates/home/home_page.html

Dropdowns on Home barcharts do not work  in Internet Explorer 11 on FEC-issued MS Surface, some other Windows 7/10 machines  and some Android browsers. This is because  some versions of IE 11 and some Android browsers  lack  support for `ES6  object-assign`. "Versions" of IE11 refers to the WIndows Build Pack and possibly other configurations on the machine on which it is running. 
The standalone barcharts, however, do work here because they reside in /data and get the a polyfill through that build process. Including the polyfill in the same way to /home throws an error:
``` 
Uncaught SyntaxError: Unexpected string...
import 'babel-polyfill';
```
I was unable to resolve the error by editing `webpack.config` , so I just include a separate polyfill for the homepage only. 
@rfultz likely …

Polyfill ES6-object-assign for homepage apps

---

fec/legal/templates/legal-statutes-landing.jinja

- Resolves #[_2859_]
Updates the image of the FECA compilation  "Federal Election Campaign Laws" to look like the current 2019 edition's cover.
See on https://www.fec.gov/data/legal/statutes/
Before: 
After: image should look like 
Verify that image used matches the second picture.

Update image of FECA compilation

---

requirements.txt

Updated the required version of `requests` to address the [HIGH] CRLF Injection SNYK alert.
(I'm not sure who should review it so please add or remove as makes sense.)
- Resolves #2862 
It's an all-back-end change so there should be no noticeable difference, apart from no longer getting the SNYK alert. Changed two characters in `requirements.txt`, moving `requests` from `2.20.1` to `2.21.0`.
None
None
1. Pull the branch.
2. Activate the fec-cms virtual environment.
3. In the directory with requirements.txt, run `pip install -r requirements.txt`.
4. Run `pip show urllib3` to ensure urllib3 is at 1.24.2. (If not, run `pip install urllib3==1.24.2` and go to the previous step in this list.)
5. Launch the server like normal.
Should be zero errors and the site should function as it normally …

2862 [HIGH] CRLF Injection

---

.github/ISSUE_TEMPLATE/task-issue.md

- Resolves #2887
_This PR adds a "Task issue" to our list of github issue templates._
-  fec-cms repo
branch | PR
feature/2820-new-issue-template | [link](https://github.com/fecgov/fec-cms/pull/2874)
There's no way to visually test this, so please refer to the screenshot above to see what this template would look like.
____

Add task issue template

---

fec/fec/static/js/modules/download.js
tasks.py

- Resolves #2842 
_Add specific 429 over rate limit error message when a post request is received. This will only work on first 429 error with a POST xhr call. Otherwise, print a generic error message that also warns of over rate limits when there is an error._
Also see this detailed explanation about error message handling for downloads: https://github.com/fecgov/fec-cms/issues/2842#issuecomment-497367683
-  Datatable page downloads
Below you will see that the initial error may give you the 429 error message. The subsequent request gives you the generic error message.
- Check out this branch and `npm run build`
- Query stage space for FEC_DOWNLOAD_API_KEY and set it in your environment
- Change FEC_API_URL to point to …

Handle over-limit downloads

---

fec/data/templates/macros/filters/election-filter.jinja
fec/data/templates/partials/candidates-office-filter.jinja

Part one of https://github.com/fecgov/openFEC/issues/3673 
- Update the front end house candidates total to pass `election_full=True` and `election_year=2020` because results are correct
- Relabel time frame from two-year-period to election year to match other data tables
-  House candidate datables
- house datatable for MI 3 http://localhost:8000/data/candidates/house/?election_year=2020&election_full=True&state=MI&district=03 should show six results, which matches candidate datatable in production: 
https://www.fec.gov/data/candidates/?election_year=2020&state=MI&district=03

Update house candidate datatable to show full election results

---

requirements.txt

Upgrading Jinja from 2.9.6 to 2.10.1 
- Resolves #2822 
Only requirements.txt was changed and the site shouldn't see any other impact, but here are the [release notes for 2.10.1](http://jinja.pocoo.org/docs/2.10/changelog/).
None
- If `manage.py` is running, close it
- Go to the root directory beside `requirements.txt`
- Run `pip install -r requirements.txt`
- Let it do its thing
- Go back into `./fec` to run `manage.py` (`./manage.py runserver`)
- Check the site for any hiccups
____

#2822 - Update requirements.txt to Jinja2==2.10.1 from 2.9.6

---

fec/fec/static/scss/components/_table-styles.scss

- Resolves #2918 
_This adds `data-party="DFL"` to the styles for blue bars on raising and spending._
- http://localhost:8000/data/raising-bythenumbers/
-  http://localhost:8000/data/spending-bythenumbers/
Right now the change is only apparent in the 2020 house numbers.
- Check out the PR and `npm run build` to compile the new style.
- Go to https://www.fec.gov/data/raising-bythenumbers/?office=H
- Make sure the DFL party is blue instead of gray
____

Added DFL party to blue bar styles for Democrats

---

fec/data/tests/test_datatables.py

- Resolves issue found in testing where we accidentally broke some data tables with a refactor and tests passed
-  Test coverage for data tables
- `git checkout 4230b12b79d593312f5f427f20eec0ebbf764336` (From https://github.com/fecgov/fec-cms/pull/2914)
- Run `pytest` from `fec-cms` home directory
- Tests should fail

Add tests for datatable rendering

---

fec/data/templates/partials/disbursements-filter.jinja
fec/data/views_datatables.py

- Resolves #2928 
_Fix disbursement date range parameter name and add min and max date to disbursement redirects._
-  Disbursements datatable: http://localhost:8000/data/disbursements/
- Go to disbursements datatable: http://localhost:8000/data/disbursements/
- Make sure redirect is tacking on this to the URL string: `two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020`
____

Fix disbursement date range and add default date range to redirect

---

fec/data/views_datatables.py
fec/fec/static/js/pages/datatable-candidates-office.js

- Resolves #2932 
-  House/Senate/Presidential candidate datatables
http://localhost:8000/data/candidates/house/
http://localhost:8000/data/candidates/senate/?election_year=2020&cycle=2020&election_full=true
http://localhost:8000/data/candidates/president/?election_year=2020&cycle=2020&election_full=true

Fix H/S/P candidate datatable breadcrumb capitalization

---

fec/fec/static/js/modules/helpers.js
fec/fec/static/js/object-assign-polyfill.js
fec/fec/static/js/pages/committee-single.js
fec/fec/static/js/templates/tables/noData.hbs

Resolves #2895 
- Add default 'no data' messages to specific datatype 'no data' messages. 
1) Either show data-specific messages or "No one filed this type of activity during the time period." 
2) Still processing the data
3) Filing deadline hasn't passed
- Relabel disbursements from `disbursements to committees` to `disbursements` - not all disbursements are to committees
-  Candidate/Committee profile pages: Raising/Spending tabs "no data" messages
https://github.com/fecgov/fec-cms/pull/1989
- http://localhost:8000/data/committee/C00508184/?tab=raising
- http://localhost:8000/data/committee/C00508184/?tab=spending
- http://localhost:8000/data/committee/C00583567/?tab=raising

Update missing processed data message

---

fec/data/templates/partials/candidates-office-filter.jinja

- Resolves issue found in testing 
Remove extra line in candidate datatables
-  House/Senate/Presidential datatables
- http://localhost:8000/data/candidates/house/?election_year=2020&election_full=True
- http://localhost:8000/data/candidates/senate/?election_year=2020&cycle=2020&election_full=true
- http://localhost:8000/data/candidates/president/?election_year=2020&cycle=2020&election_full=true

Remove extra line in candiate datatables

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/individual-contributions-filter.jinja
fec/data/templates/partials/receipts-filter.jinja

- Resolves #2913 
_Temporarily adding `include_ssfs` parameter into committee-types template in order to exclude SSFs from individual contributions and receipts datatable filters._
-  Receipts datatable: http://localhost:8000/data/receipts/
- Individual contributions datatable: http://localhost:8000/data/receipts/individual-contributions/
- Go to Receipts and Individual contributions datatables and make sure that the SSF committee types are removed from the PACS list
- http://localhost:8000/data/receipts/
- http://localhost:8000/data/receipts/individual-contributions/
- Ensure that other datatables with this `committee-types.jinja` filter is uneffected and still includes the SSFs in the PACS list.
- …

Remove SSFs from receipts and individual contributions datatable

---

fec/fec/static/js/modules/columns.js
fec/fec/static/scss/components/_type-styles.scss

Removing the monospace currency font from column heads, and from page number columns
- Resolves #2951 
Ideally we'd skip adding the `t-mono` class to the <th> and other column-heading elements. As a quick fix, I changed the css rules to only apply to elements that aren't <th> and that don't have a role of `columneader`
None
- Go to a datatables page like http://127.0.0.1:8000/data/receipts/ and make sure the "Amount" total text _and_ that the numbers in the column are monospace
____

2951 Remove monospace font from column heads (2)

---

fec/data/templates/partials/candidate/other-spending-tab.jinja
fec/data/templates/partials/committee/spending.jinja
fec/fec/static/js/modules/filters/filter-set.js
fec/fec/static/js/modules/filters/filter-typeahead.js

Candidate and Committee profile pages Independent Expenditure datatable "filter this data" button fixed to link to regularly scheduled reports.
- Resolves #2948
modified:   data/templates/partials/candidate/other-spending-tab.jinja
modified:   data/templates/partials/committee/spending.jinja
- Checkout and run  `feature/2948-filter-this-data-btn-correct-link`
- Test Candidate and Committee profile pages  on the  `other spending tab` and `independent-expenditures` tabs respectively. The "filter this data button" above the   Independent Expenditure datatable should go to regularly scheduled reports.
http://127.0.0.1:8000/data/candidate/P80001571/?tab=other-spending
http://127.0.0.1:8000/data/committee/C00571703/?tab=spending#independent-expenditures
____

"Filter this data" button link to regularly scheduled reports

---

fec/fec/static/scss/components/_type-styles.scss

Refined the sass style rule where the t-mono rule is concerned, removed the !important and 
- Resolves #2959 
Only the sass file was updated, though it will affect anywhere (site-wide) that the t-mono class is used.
- Check any pages with stacks of currency (stacks of currency should be monospace…)
- Check that all table header text is displayed (…and their headers should _not_ be)
____

[MERGE WITH GIT FLOW] 2959 column headers font

---

fec/fec/static/js/templates/electionCycles.hbs

Fix mismatched case/vertical spacing between `Election dropdown` and `Time Period toggle` on Candidate profile pages.
Example:
https://www.fec.gov/data/candidate/P00009423/?cycle=2020&election_full=true&tab=about-candidate
Also on `Spending by others to support or appose` tab
- Resolves #2967
modified:   fec/static/js/templates/electionCycles.hbs
- Checkout  branch
- Check that Election dropdown and Time Period toggles are vertically aligned and uppercase
Example page:
http://127.0.0.1:8000/data/candidate/P00009423/?cycle=2020&election_full=true&tab=about-candidate
- Also check `Spending by others to support or appose` tab

Fix mismatched case/vertical spacing on Cand. profile pages

---

fec/data/templates/partials/browse-data/candidates.jinja
fec/data/templates/partials/candidates-filter.jinja
fec/data/templates/partials/candidates-office-filter.jinja
fec/data/templates/partials/filters/active-candidates.jinja

- Resolves #2927
Add checkbox to exclude incumbents that are not seeking re-election
- Default views when clicking to the following datatables from http://localhost:8000/data/browse-data/?tab=candidates
- http://localhost:8000/data/candidates/
- http://localhost:8000/data/candidates/senate/
- http://localhost:8000/data/candidates/house/

Add checkbox to exclude incumbents that are not seeking re-election

---

fec/fec/static/scss/components/_datatables.scss

Assigning a (new) z-index to parent objects of download options lists.
Pull-downs inside tables were visible but couldn't receive click/tap actions when the row was such that its pull-down could appear behind the table's footer—the footer's transparent background was receiving the click/tap action.
Because elements load and stack in front of preceding elements by default, we're giving a z-index to tables so the pull-down elements inside them will appear in front of the tables' footer elements.
- Resolves #2952 
The only change was to apply a z-index to .data-table at line 68, which will only affect those tables. As a side effect, though, there could be a situation where something that was (and should have been) in front of the table will now be behind the a data-table element.
Adjusted …

Adjust z-index of .data-table

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/macros/filters/spender-committee-types.jinja
fec/data/templates/partials/disbursements-filter.jinja
fec/data/templates/partials/individual-contributions-filter.jinja
fec/data/templates/partials/receipts-filter.jinja

Remove `Separate segregated funds (SSF)` and `Leadership PAC` options from Disbursements datatable  > Filters > Spender Committee Type > PACS dropdown
- Resolves #2966 
Related PR: https://github.com/fecgov/fec-cms/pull/2941
Changed spender-committee-types.jinja partial to macro, added ssf conditional option. 
It may have been possible  to reuse the commitee-types.jinja macro here since currently the options are the same for both rasing and spending datatables--  But, this macro should remain separate in case we ever need to have different filter options for Disbursements VS. raising datatables( Receipts , Individual Contributions) .
**renamed:**    data/templates/partials/filters/spender-committee-types.jinja -> data/templates/macros/filters/spender-committee-types.jinja
**modified:** …

Temporarily Remove SSF/Leadership PACS  options from Disbursements datatable

---

fec/data/templates/candidates-single.jinja
fec/data/templates/macros/entity-pages.jinja
fec/data/templates/partials/candidate/filings-tab.jinja
fec/data/utils.py
fec/data/views.py
fec/fec/static/js/modules/filters/filter-set.js
fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/pages/candidate-single.js

Resolves #2866 
- Add raw filings section to candidate profile page
- Change text to say "directly from a ~committee's~ filer's raw, electronic reports" because candidates and non-committee filers can have raw filings
- Fix bug with "filter this data" button going to processed 
- Only filter committee raw efilings by cycle - show all for candidates
- Fix bug with date filter
-  Candidate profile page, filings tab
- You can point to any space's API for this work
- As of 6/18, test with http://localhost:8000/data/candidate/P00011486/?tab=filings and http://localhost:8000/data/committee/C00000885/?tab=filings and see raw electronic filings
- If it's been more than a few days, look at candidates with recently filed F2's …

Add raw filings section to candidate profile page

---

fec/data/views.py

ex: https://www.fec.gov/data/elections/house/GA/06/2018/
on GA/06/2018 page, Click candidate name links in the table. Some of the candidates linked will 404, such as OSSOFF, T. JONATHAN and MOODY, DAN.
- Resolves [#[_2937_]](https://github.com/fecgov/fec-cms/issues/2937)
set election_full=False except State=PR in get_candidate function of views.py
candidate profile page for House
1)checkout this cms branch 
2)point to dev api: export FEC_API_URL=https://fec-dev-api.app.cloud.gov
3)test url:
http://127.0.0.1:8000/data/elections/house/GA/06/2018/
click "OSSOFF, T. JONATHAN and MOODY, DAN."
or you can go through chose state = PR to test any candidate profile page.
(Notes: This is short term solution, we will work on long term solution to use …

Fix 404 bug for House candidate profile page

---

fec/fec/static/js/widgets/aggregate-totals-box.js

Adding analytics for the aggregate totals widget
- Resolves #2802 
The new code is solely inside aggregate-totals-box.js. It's hidden behind an `if (window.ga)` so it shouldn't do anything if the `ga` element hasn't been created.
None
None
- `npm run buiild-js`
- Make sure the build and tests succeed
Because it's analytics, we may not be able to test it until it's on production
____

Add analytics

---

fec/fec/static/js/modules/columns.js

Currently, The URL in links to candidate profile pages on `Raw filings`  has  `committee` instead of `candidate` in the path. This happens because the API data  that builds the `Raw filings table` has candidate IDs in the committee ID parameter. This PR changes the path to `candidate` if the ID begins with `H, S or P`. 
- Resolves #2865
**Issue 2865: Candidate links on raw filings datatable 404**
Note: Many of the candidate (and committee) links on the first one or two pages of Raw filings datatable will still return a 404 because this is Raw, unprocessed data and often a profile page has not yet been created for these recent filings. For example, while testing this over several days, on one day, only one of the six candidate links on the first two pages worked.
Delving into this issue …

Fix  URL path in links for candidate raw filings links

---

fec/fec/static/scss/elements/_forms.scss

Adjusted the right padding of the `<select>` to base it on its own font size rather than the root document font size
- Resolves #2965 
The only style change was for the select element, but it will affect _every_ `<select>` (actual pulldown) on the site. (Anywhere we're using `<div>`s as pulldowns will be unaffected)
None
- Check the right-side padding (internal spacing) of any <select> elements e.g., [Raising](http://localhost:8000/data/raising-bythenumbers/) & [Spending](http://localhost:8000/data/spending-bythenumbers/) By the Numbers pages
- Check any other instances of <select> elements
____

2965 Adjust right padding for select elements

---

fec/fec/static/scss/elements/_forms.scss

Add box shadow to fix radio selected-state
- Resolves #2950
Added ` box-shadow: 0 0 0 1.2px $inverse inset;` to `[type="radio"]:checked + label::before`
modified:   fec/static/scss/elements/_forms.scss
**Before**
<hr>
**After**
- checkout `feature/radio-button-selected-state`
- npm run build-sass
- Go to `http://127.0.0.1:8000/data/legal/search/advisory-opinions`
- See new radio button selected-state under `Citations` filter section
____

Fix radio button selected-state

---

fec/data/templates/macros/tables.jinja
fec/data/templates/partials/candidate/financial-summary.jinja
fec/data/views.py

Fix click-through from totals links on candidate profile pages  to receipts/disbursements, ensuring that chosen time period is reflected in datatable.
- Resolves #2815
Return `aggregate_cycles` , from `get_candidate view` and use it to build the totals  links to receipts and disbursements from  candidate profile pages -- ensuring that the resulting datatable page is filtered by either the chosen two year period or all years in chosen election cycle.
modified:   data/templates/macros/tables.jinja
modified:   data/templates/partials/candidate/financial-summary.jinja
modified:   data/views.py
- Go to a candidate profile page for Senate and President and confirm that when all years are chosen in the `time period toggle`, …

Fix click-through links from candidate profiles to receipts/disbursements

---

fec/data/constants.py
fec/data/templates/partials/browse-data/spending.jinja

- Remove line 24 from Add filter on Disbursements filters > Disbursement Details > Disbursement Type > Made by PACs or party committees
- Make changes to language on  data/browse-data/?tab=spending
- Resolves #3019 
modified:   data/constants.py
modified:   data/templates/partials/browse-data/spending.jinja
- checkout and run feature/3019-remove-line-24-disbursements
- Confirm that Filters > Disbursement Details > Disbursement Type > Made by PACs or party - committees now does not include `Independent expenditures (Line 24)`
- Confirm text on `http://127.0.0.1:8000/data/browse-data/?tab=spending` reflects [Option 2 of the issue](https://github.com/fecgov/fec-cms/issues/3019#issuecomment-510618274)

Remove Line 24, disbursements, edit spending tab language

---

fec/data/templates/partials/committee/spending.jinja
fec/fec/static/js/pages/candidate-single.js
fec/fec/static/js/pages/committee-single.js

Front-end followup for https://github.com/fecgov/openFEC/issues/3686
- Specify 2-year totals for aggregates - election_full now defaults to True
- Fix link for communication costs "filter this data" button
-  Candidate profile page Raising aggregates
branch | PR
feature/change-default-election-full | https://github.com/fecgov/openFEC/pull/3846
- Point to `dev` API
- Check that http://localhost:8000/data/candidate/S4NJ00185/ should match https://www.fec.gov/data/candidate/S4NJ00185/ for State and Size aggregates
- "Filter this data" button should now work for http://localhost:8000/data/committee/C70000716/?tab=spending&cycle=2018

Specify 2-year totals explicitly

---

fec/fec/static/js/modules/filters/filter-set.js
fec/fec/static/js/modules/filters/filter-tags.js
fec/fec/static/js/modules/tables.js

- Resolves #2987 
_This adds reset filters button and functionality to schedule_a tables: receipts and individual contributions._
- http://localhost:8000/data/receipts/
- http://localhost:8000/data/receipts/individual-contributions/
branch | PR
feature/2987-fix-clear-all-filters-links | [link](https://github.com/fecgov/fec-cms/pull/2990)
1. Check out this branch
2. Go to [receipts](http://localhost:8000/data/receipts/) and click on "Reset filters" button in the top right. 
Make sure that the page resets correctly to: 
two_year_transaction_period=2020
min_date=01/01/2019
max_date=12/31/2020
3. Go to [individual …

Apply reset filter to receipts and individual contributions datatable

---

fec/data/templates/elections.jinja
fec/data/views.py
fec/fec/static/js/modules/column-helpers.js
fec/fec/static/js/modules/helpers.js
fec/fec/tests/js/column-helpers.js

- Resolves #2790: Update aggregate totals links with full election cycles
-  Election profile pages "Individual contributions to candidates" State/Size chart and Other spending (IE, EC, CC) sections: https://www.fec.gov/data/elections/president/2020/#individual-contributions
- Candidate/committee profile pages Raising and Spending tabs, https://www.fec.gov/data/candidate/P60007168/?cycle=2020&election_full=true&tab=raising and 
https://www.fec.gov/data/committee/C00696948/?cycle=2020&tab=raising
- Point to `dev` or `stage` API (stage will be faster)
- Election profile pages should have expanded date ranges or multiple `two_year_transaction_period`s to correspond with full election cycle. 
- Senate: 6 years …

Update aggregate totals links with full election cycles

---

fec/data/templates/layouts/main.jinja
fec/data/templates/layouts/widgets.jinja
fec/fec/static/js/modules/analytics.js
fec/fec/templates/base.html
fec/fec/templates/home_base.html

- Resolves #3087 
Change every instance of `UA-48605964-22` to `UA-16134356-1` so we're sending Google Analytics tracking data to our (FEC) account instead of to FEC's account. The GSA account should be unaffected.
We're only changing the account numbers. Users should see zero difference in site performance.
None
None
Testing analytics can be tricky. As-is, we shouldn't be able to test anything until the code is on production and we start seeing numbers come through to GA.
One possible complication for this update is that our Classic tracking is an older version of GA than our current Production version. I'm pretty sure simply updating the account should work but want to double-check.
Because our analytics code is inside conditional checks (`{% if not settings.DEBUG %}`, `{% if …

3087 Change Google Analytics Account Numbers from 18F's

---

fec/fec/settings/base.py
fec/legal/templates/layouts/legal-doc-search-results.jinja
fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/macros/legal.jinja

- Resolves https://github.com/fecgov/fec-cms/issues/3080
Update below templates to use `webmanager_email` variable. Remove the unused variable `contact_emai`l from base.py
1.  fec/settings/base.py
2.  legal/templates/layouts/legal-doc-search-results.jinja
3.  legal/templates/legal-search-results-advisory_opinions.jinja
4.  legal/templates/macros/legal.jinja
-  AO search
- Statues search
- All Legal search
** Before:**
**After :**
http://127.0.0.1:8000/data/legal/search/advisory-opinions/?type=advisory_opinions&search …

Fix mailto link in ao, legal and legal search templates

---

fec/data/api_caller.py
fec/data/templates/candidates-single.jinja
fec/data/templates/partials/candidate/filings-tab.jinja
fec/data/templates/partials/candidate/financial-summary.jinja
fec/data/tests/test_candidate.py
fec/data/views.py

- Resolves #[3076](https://github.com/fecgov/fec-cms/issues/3076)]
Reference openFEC PR: [https://github.com/fecgov/openFEC/pull/3919](https://github.com/fecgov/openFEC/pull/3919)
We modified three endpoint files:
CandidateTotalsView
CandidateHistoryView
CommitteeHistoryView
This PR will modified get_candidate function to use above updated endpoints.
-  Candidate profile financial summary page.
1) setup both openFEC and fec-cms on local.
2) openFEC: checkout branch: feature/refactor_ofec_totals_candidate_committees_mv
set SQLA_CONN  = dev
3) setup fec-cms point to your local api:
export DATABASE_URL=postgresql://:@/cfdm_cms_test
export FEC_API_URL=http://localhost:5000 …

[Merge with openFEC 3919]Fix Candidate profile financial summary page inconsistent data.

---

fec/fec/middleware.py
fec/fec/settings/base.py
package-lock.json
package.json

Resolves #3069 
- Adds content security policy response headers to every page. See original issue for background information.
- Add `report-uri` that sends violation reports to API for now (ran into csrf issues with a Django route)
- Add `CSRF_TRUSTED_ORIGINS` setting to address csrf errors
-  This will impact everything on our website. Need to make sure that there are no loading errors for anything we pull into our site like api calls, scripts, images, fonts, etc. 
None, this is pure code
branch | PR
openFEC/feature/3876-add-response-headers | [link](https://github.com/fecgov/openFEC/pull/3891)
Check each section of the site to make sure that the content security …

Add security response headers

---

fec/home/templates/home/home_page.html
fec/home/templates/partials/current-commissioners.html
fec/home/templatetags/commissioners.py

- Resolves #3129 
_Removes departing commissioner from homepage as reflected in the ticket._
-  Homepage
- Checkout branch
- Ensure that the HTML on the homepage reflects the commissioner change accurately. http://localhost:8000/
- Go to the leadership and structure page here: http://localhost:8000/about/leadership-and-structure/
- Ensure that if a Chair and Vice Chair are populated that it will put those first. Otherwise show commissioners in alpha by last name
____

[HOTFIX - USE GITFLOW] Update commissioner listing on homepage and leadership landing page

---

fec/fec/static/js/widgets/aggregate-totals-box.js

- Resolves #3141 
To make sure the Other parties meter displayed at least one pixel, we were using an adjusted value for the meter, but we were also putting that adjusted value into the page. This fix will write the actual value into the page rather than the adjusted value.
Just the two variables inside aggregate totals.
N/A
None
Pull and build like normal. For raising and spending by the numbers, add the party numbers on the right; they should be within $1 of the larger number
____

3141 Fix Aggregate Totals numbers

---

fec/fec/middleware.py

- Resolves #3156 
_This adds youtube videos to the allowed frame-src in the csp._
-  All pages
Embedded youtube videos should now play and show correctly
- Test a page with embedded video such as this: http://localhost:8000/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/
- Video should show with thumbnail and play
____

[Hotfix - Merge with gitflow] Add youtube to csp

---

fec/fec/middleware.py

- Resolves #3158 
_Allows google tag manager scripts in our content security policy._
-  All pages should have google tag manager
branch | PR
feature/2840-tag-manager-slim | [link](https://github.com/fecgov/fec-cms/pull/3154)
- add google tag manager feature flag
- make sure GTM loads

adds google tag manager as source for CSP

---

fec/home/templates/home/latest_updates.html

- Resolves #3122 
Updating the message on the Updates page to link the Record archive.
- Refer to #3122 for screenshot
- Refer to #3122 for message
- Verify that link goes to https://www.fec.gov/updates/record-archive-1975-2004/.
- Go to /updates/ and click + "About latest updates" to verify that message and link are there.

Update the Updates message

---

fec/data/views.py

- Resolves #3168
_Fix missing/duplicate authorizing candidates ._
- Committee profile pages with authorizing candidates  
- https://dev.fec.gov/data/committee/C00580100/?cycle=2020 
- https://dev.fec.gov/data/committee/C00580100/?cycle=2018 
- https://dev.fec.gov/data/committee/C00575795/?cycle=2016
- https://dev.fec.gov/data/committee/C00696948/?cycle=2020
- https://dev.fec.gov/data/committee/C00659938/?cycle=2020
- http://localhost:8000/data/committee/C00580100/?cycle=2020 
- http://localhost:8000/data/committee/C00580100/?cycle=2018 
- http://localhost:8000/data/committee/C00575795/?cycle=2016
- http://localhost:8000/data/committee/C00696948/?cycle=2020
- http://localhost:8000/data/committee/C00659938/?cycle=2020 …

[MERGE WITH GIT FLOW] Fix missing/duplicate authorizing candidates

---

fec/fec/static/scss/base.scss
fec/fec/static/scss/components/_fec-org-chart.scss

- Resolves #3071 
Outlines the structure for a responsive org chart and styles it according to comps
Right now, the only change is a new scss file that will apply to an upcoming org chart.
That file is included in fec/fec/static/scss/base.scss for now (see the TODOs at the bottom).
None
- `npm run build` just in case (if you get an error, you may need to run `npm rebuild node-sass` then build again)
- Copy the sample html from the bottom of fec/fec/static/scss/components/_fec-org-chart.scss
- I'm still new to Wagtail; I think this is what I did:
- In local Wagtail, find a page to edit (I chose Home > About > Leadership and structure)
- Add a new html section
- Paste the copied html into the new section
- Save draft
- Preview
- Scale your browser window from its smallest …

3071 Org chart styles

---

fec/home/templates/home/latest_updates.html

Making sure the Record search "no results" message points to the latest version of the Record archive page.
- Resolves #3122 by linking to the current Record archive page at https://www.fec.gov/updates/record-archive-1975-2004/
See #3122 for image

Update link in the Record search "no results" message

---

fec/data/templates/layouts/main.jinja
fec/data/templates/layouts/widgets.jinja
fec/fec/templates/base.html
fec/fec/templates/home_base.html

- Resolves #2840 
Updated the html templates so the GTM implementation is looking at `settings.FEC_CMS_ENVIRONMENT` rather than `settings.DEBUG`. I don't know why the previous GTM/DAP tag conditional but DEBUG is used to show us error messages or only log them.
Updated the two html templates—will affect the homepage and other Wagtail pages; won't affect pages based on Jinja templates.
None
None
- Pull and build like normal
- Make sure the `FEC_FEATURE_USE_TAG_MANAGER` environment var is `true`
- Run the server locally
- Verify that the homepage and another Wagtail page is using the non-Production Tag Manager container
- Push to Dev or Feature
- Make sure `FEC_FEATURE_USE_TAG_MANAGER` is `true` there, too
- Check …

Change to check settings.FEC_CMS_ENVIRONMENT

---

fec/data/templates/macros/entity-pages.jinja
fec/data/templates/partials/candidate/filings-tab.jinja
fec/data/templates/partials/committee/filings.jinja
fec/data/views.py
fec/fec/static/js/pages/candidate-single.js
fec/fec/static/js/pages/committee-single.js

Resolves #3119
- Fix "Filter this data" buttons for filings
- Refactor filings macros to inherit template variables
- Candidate profile pages, filings tab
- Committee profile pages, filings tab
- Connect to any FEC API
- Candidate profile page, filings tab -  "other documents" "filter this data" button should go to just the displayed filings and all RFAIs (unable to exclude by request type) http://localhost:8000/data/committee/C00560847/?cycle=2018&tab=filings#other
- Committee profile page, filings tab -  all data section "filter this data" buttons should go the the form types listed and all RFAIs http://localhost:8000/data/committee/C00035691/?cycle=2020&tab=filings
- Look for raw candidate/commitee filings and make …

Fix "Filter this data" buttons for filings

---

manifest_prod.yml

- Resolves #3197 
Increase application memory on prod from default `512MB` ([see cloud.gov docs](https://cloud.gov/docs/apps/limits/#application-limit-options-sizing)) to `1GB`
We tested this in `dev` with branch `feature/test-application-memory`. Circle output: https://circleci.com/gh/fecgov/fec-cms/2661

[MERGE WITH GIT FLOW] Hotfix: Increase application memory on prod

---

fec/fec/static/js/polyfills.js
fec/fec/static/js/widgets/contributions-by-state-box.js
package.json

Where contributions come from updates:
- Update candidate link with the correct selected election year
- Handle odd year special elections by converting list to even years 
Odd numbered election years converted to even. Example, candidate ID H8GA06195
____

WCCF: Update candidate cycle in link and make election years even

---

fec/fec/static/js/widgets/contributions-by-state-box.js

- Resolves #3204
Fixes the Individual Contributions link at the bottom of the widget to apply committee filters. Updates the table of dollar values so they link to their filtered datatable pages, too.
Generally cleaned up comments, documentation, linting.
Changes are all inside the WCCF widget, though there is a new API call to get the candidates committee IDs, and we've added links to the individual contributions page (with filters applied)
None
- Pull and build the branch like normal
- Make sure env var FEC_FEATURE_CONTRIBUTIONS_BY_STATE is true
- Visit /data/raising-bythenumbers/
- For several candidates, check that the Individual Contributions button and dollar-figure links (circled in red on the attached screenshot) go to the correct datatable pages.
____

feature/3204 WCCF Individual Contributions links

---

fec/fec/static/scss/components/_overviews.scss

Looking at the top raisers bars, apply the styles from the homepage to the raising & spending by the numbers pages
- Resolves #3133 
Added style rules that apply to `#top-raisers .chart-table .simple-table__row` so unexpected impact should be low. Would like to confirm we haven't missed anywhere else, or changed anything unexpected.
-  
Starting point:
Home, small:
Raising, small:
Home, wider:
Raising, wider:
None
- Pull, build as always
- Verify that the new styles are applied to [Raising](http://127.0.0.1:8000/data/raising-bythenumbers/) & [Spending](http://127.0.0.1:8000/data/spending-bythenumbers/) by the numbers
- Verify that other earning/spending charts are unaffected (anywhere else?)
- Verify that nothing else is affected (where?)
____

Apply styles from home

---

fec/fec/static/js/modules/helpers.js
fec/fec/static/js/templates/candidates.hbs

- Resolves #3086
Disable pre-1980 election profile page links, add operator handlebars helpers
-  Candidate flyout tabs
- Connect to any FEC API
- Rebuild JS with `npm run build` or `npm run watch`
- Go to http://localhost:8000/data/candidates/?q=mcgovern&q=trump&office=P&is_active_candidate=true&has_raised_funds=true
- Click on flyout for McGovern. The election years before 1980 should be disabled and 1980 and later should be enabled. Test that the links work properly when enabled.

Disable pre-1980 election profile page links

---

fec/fec/static/js/modules/filters/filter-base.js
fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/modules/filters/text-filter.js
fec/fec/static/js/modules/filters/typeahead-filter.js

See ticket for instructions on how to test: https://github.com/fecgov/fec-accounts/issues/213#issuecomment-536076501

Escape special chars

---

fec/data/tests/test_candidate.py
fec/data/views.py

- Resolves [#[_3127_]](https://github.com/fecgov/fec-cms/issues/3127)
We replace value of cycles with new column:  **fec_cycles_in_election**
Candidate Profile page
1. checkout cms feature branch
2. point to dev api
3. run tests
pytest
./manage.py test data.tests
npm run test-single
4. ./manage.py runserver
5. compare candidate on Raising / Spending page with prod.
P00003392
http://127.0.0.1:8000/data/candidate/P00003392/?tab=raising
P80001571
http://127.0.0.1:8000/data/candidate/P80001571/?tab=raising&cycle=2018&election_full=False

Fix candidate profile no financial activity issue

---

fec/fec/templates/500.html

Linking to FEC status page for API
- Resolves #3113 by updating the API status error message to link to https://www.fec.gov/status.
- Affects 500 error message
- Generate a 500 error (paging @patphongs for help with this)
- Ensure that link to https://www.fec.gov/status is working and points to http://status.open.fec.gov/.

Update 500 error message
