fec/fec/static/js/modules/helpers.js

- Resolves #3060 
- add condition to `helpers.js` to ensure `amendment_chain.length` is not called before checking to see that `amendment_chain` is not null.
- `helpers.js`
- `pytest`
- run local cms and check [example case](http://localhost:8000/data/reports/house-senate/?data_type=processed&committee_id=C00498683) where `amendment_chain` is null behaves as expected

add condition for amendment_chain != null

---

fec/data/api_caller.py
fec/data/tests/test_candidate.py
fec/data/views.py

- Resolves #3262 
- Resolves #3253 
_Fix committee info and raising/spending tabs for future candidates._
-  Candidate profile pages
- Committee profile pages (uses `api_caller.load_with_nested` but shouldn't be impacted)
- Look at future senate candidate profile pages, future and past cycles
- http://localhost:8000/data/candidates/senate/?election_year=2022&cycle=2022&election_full=true&is_active_candidate=true
- http://localhost:8000/data/candidates/senate/?election_year=2024&cycle=2024&election_full=true&is_active_candidate=true
- Look at other candidate profile pages
- Compare results to production (you can get to a rasising/spending tab 2-year period in production by choosing an older election first)

Fix committee info and raising/spending tabs for future candidates

---

fec/fec/static/js/draftail/components/Modal.js
fec/fec/static/js/legal/filters/CitationFilter.js
fec/fec/static/scss/_variables.scss
fec/fec/static/scss/components/_dropdowns.scss
fec/fec/static/scss/components/_search-bar.scss
fec/fec/static/scss/widgets/contributions-by-state.scss

- Resolves #3166 
- Resolves #3245 
- Resolves #1254 
- Created new variables to use for z-index values
- Applied `$z-dropdowns` to `.dropdown_panel`
- Mimicked z-dropdowns in local JavaScript files and commented to why I chose that value
- Moved dropdowns to 1100 so they're above everything except modals
The changes only affected the depth of a handful of elements, but they could now conflict with other existing components—unlikely, but still a possibility.
A fixed #3166 
A fixed #3245 
None
- `npm i`, `npm run build`, `./manage.py runserver`
- Check /data/elections/president/2020/
- Under "Individual contributions to candidates"
- Open the "More" pull-down,
- Make sure it's in front of the other content
- Check /data/
- In the "Look up candidate and committee profiles" block
- Enter …

Raise the dropdown z-index

---

fec/fec/static/scss/components/_dropdowns.scss

- Resolves #2943 
- Read the code and experimented with the perfect-scrollbars package
- Changed css for the various components involved with the drop-down-type divs
- Increased the left padding for all elements (inside the drop-downs) so subheads aren't under the scrollers
- Assigned `left` values to the scroll components rather than rely on a calculated `right`
- Gave the subheads the same border styles as its sibling elements
All changes were inside the css file for the "drop-downs" but that would affect every "drop-down" on the site. (The quotes are because these aren't native `<select>`, `<option>`, and scrollbar elements that just work with every browser, but custom divs being used for custom functionality. Any native elements across the site should be unaffected by these changes.) …

feature/2943 Update styles for dropdowns' perfect-scrollbar components

---

fec/fec/middleware.py

- Resolves #3191 
_This allows images from the *.fec.gov domain to be on the app.cloud.gov domains._
-  Image sources from fec.gov domain
`<img alt="San Diego Regional Conference" height="208" src="https://www.fec.gov/resources/cms-content/images/San_Diego_Web_Header_wag.original.png" width="620">`

Add fec.gov domain to allowed image sources in CSP

---

fec/fec/constants.py
fec/search/management/commands/index_pages.py
fec/search/management/data/transition_pages.json
fec/search/management/data/web_app_pages.json
fec/search/management/instructions.md

- Resolves #2991 
Reindexing has already been completed on the website using search.gov and our custom indexing scripts. Followed documentation based on what was written here: https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md
The transition drawer did not exist in our search.gov interface, therefore, I removed it from the site index commands. 
-  Global search on site's header
____

Updates for global site search

---

fec/fec/middleware.py

Resolves fecgov/fec-cms#3296 
Remove CSP reporting from production - too many reports cluttering the logs
-  CSP headers/reporting in production
- Check out this branch 
- ` export FEC_CMS_ENVIRONMENT="prod"`
- run your local CMS
- in another tab, `curl -I "localhost:8000"` shouldn't have a `report-uri` in the `Content-Security-Policy` header

Remove CSP reporting from production

---

fec/fec/static/js/modules/typeahead.js
package-lock.json
package.json

- Resolves #3267 
Using the typeaheads across the site, when there are five results returned (which is the limit for how many results to display), the typeahead displays _no_ results.
We changed the typeahead package to one that's had at least one commit during the last four years. ([Twitter typeahead](https://github.com/twitter/typeahead.js) hasn't been updated since 27 April 2015; [corejavascript typeahead](https://github.com/corejavascript/typeahead.js) was updated 25 Sept 2017 ("corejavascript" is the just a developer, not actually _core_ JavaScript.))
We changed the code that powers every typeahead across the site–main site search, WCCF typeahead, all text filters that offer suggestions as users type.
None
- Pull, `npm i`, `npm run build`, `./manage.py runserver` like usual
- Use the …

Switch to better-supported typeahead package

---

fec/home/templates/home/candidate-and-committee-services/guides.html

- Resolves #3230 by adding new sections for host/convention committees and inaugural committees to "other filers"
CMS
Note:  I decided to use the section titles rather than the titles in the screenshot for the links. Made more sense to do it that way.
Intro sentence: 
Host committees, convention committees and inaugural committees must register and file specific disclosure forms with the FEC regarding their activities.
Link for host committees: /help-candidates-and-committees/other-filers/#host-and-convention-committees. 
Link title now: Host and convention committees
Link for inaugural committees: /help-candidates-and-committees/other-filers/#inaugural-committees 
Link title now: Inaugural committees

Updates guides.html to add new Other Filers sections

---

fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/modules/filters/typeahead-filter.js
fec/fec/static/js/pages/reporting-dates-tables.js
fec/fec/static/scss/components/_table-styles.scss

Stripe table rows by state instead of zebra striping (Issue 3017)
Show state footnotes (first-column) under row (Issue 3263)
Resolves #3017
Also Resolves #3263
Pre-election reporting dates tables
modified:   fec/static/js/pages/reporting-dates-tables.js
modified:   fec/static/scss/components/_table-styles.scss
**Note:** This PR also includes two files from PR #3206 that where formatted when running `npm format-lint` and the PR author (@patphongs) directed me to push them up with this PR. They may have bypassed linting because apparently, `npm lint` is less strict than `npm format-lint`.
modified:   fec/static/js/modules/filters/filter-typeahead.js
modified:   fec/static/js/modules/filters/typeahead-filter.js
#3227
#3248
1) Checkout `feature/pre-election-tables-stripe-by-state 
2) `npm run …

Feature/pre-election tables, stripe rows by state

---

fec/fec/static/js/widgets/contributions-by-state-box.js
package-lock.json

- Resolves #3304 
Changing which date we're using to populate the coverage date stamp.
Only changed which date var we're using for the date stamp.
Also updated package-lock because it's been an ongoing issue, trying to remove that diff.
A quick way to check it right now:
(Prod shows 30 Sept 2019)
None
- Pull, `npm i`, `npm run build`, `./manage.py runserver`
- Check [Raising by the Numbers](http://127.0.0.1:8000/data/raising-bythenumbers/)
- A quick way to check is the screenshot above (@PaulClark2 may have other examples to check)
- If you're the last approval, remove "Please review", merge, delete
____

Feature/3304 WCCF coverage dates fix

---

fec/data/api_caller.py
fec/legal/templates/legal-search-results-regulations.jinja
fec/legal/templates/legal-search-results-statutes.jinja
fec/legal/views.py

Resolves https://github.com/fecgov/openFEC/issues/4028
- Default statutes  and regulations search to all - don't require a query to return results (matches AOs and MURs)
- Capitalize titles for statutes and regulations searches
-  Statutes and Regulation search
branch | PR
openFEC: feature/4028-default-statutes-regs-to-all | https://github.com/fecgov/openFEC/pull/4032
- Run this branch, point to `dev` API after https://github.com/fecgov/openFEC/pull/4032 is merged or run the API locally following the directions in that PR
- Go to http://localhost:8000/legal-resources/ and click on "Statutes" or "Regulations"
- For Statutes, all results load (and "statutes" is …

[Review with openFEC #4032] Default statutes search to all, capitalize titles

---

fec/home/templates/blocks/commissioners.html
fec/home/templates/home/home_page.html
fec/home/templates/partials/current-commissioners.html
fec/home/templatetags/commissioners.py

This hotfix replaces previously approved PR #3310
- This adds an argument to the `commissioners.py` templatetag  so it can be used in multiple locations including the home page commissioners' listing. 
- With this PR, the homepage commissioner listing will be  updated automatically when their Wagtail commissioner page is edited (as on [leadership-and-structure](leadership-and-structure) and [leadership-and-structure/commissioners](https://www.fec.gov/about/leadership-and-structure/commissioners/) ). We were currently  hardcoding html for home page commissioners' display. 
- Added comments to explain how to use the argument to control the grid layout of the rendered templatetag ( i.e : 2 grid or 3 grid layout )
- Resolves #3308
This impacts the commissioners block that appears in …

[MERGE WITH GITFLOW] Update Vice chair title on homepage, make it so this is auto-updates in the future

---

fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja
fec/data/templates/raising-bythenumbers.jinja
fec/fec/settings/base.py
fec/fec/static/js/pages/data-browse-data.js
fec/fec/static/js/pages/reaction-box.js
tasks.py

- Resolves #3237 
- Implement the reaction box  under WCCF widget on data/raising-by-the-numbers
- Simplify the process for adding/ removing reaction boxes which now only requires including the macro and a reference to `reaction-box.js` in a template.
- Add comments with instructions in `reaction-box.js`
- Remove residual code leftover from since-removed reaction boxes
- Put WCCF-reaction-box under feature flag (the flag is nested in the WCCF flag, so they do not have to be turned on/off separately. 
Contributions by State widget (WCCF) on `data/raising-bythenumbers/`
modified:   data/templates/browse-data.jinja
modified:   data/templates/landing.jinja
modified:   data/templates/partials/browse-data/raising.jinja
modified:   data/templates/partials/browse-data/spending.jinja
deleted: …

Reaction box for WCCF, simplify reaction box implementation

---

fec/data/tests/test_candidate.py
fec/data/views.py

This ticket will fix two issues:
1) one or more of candidate election_years is not exist in fec_cycles_in_election 
ex:Trump P80001571 / 1988, receive a server error page
https://www.fec.gov/data/candidate/P80001571/?cycle=1988&election_full=true
https://fec-dev-api.app.cloud.gov/v1/candidate/P80001571/history/
2) candidate only file F2. never in election yet, so fec_cycles_in_election=null.
receive a server error page. ex:P00012799 (2020)
https://www.fec.gov/data/candidate/P00012799/
https://fec-dev-api.app.cloud.gov/v1/candidate/P00012799/history/
- Resolves [https://github.com/fecgov/fec-cms/issues/3318]( https://github.com/fecgov/fec-cms/issues/3318)
and [https://github.com/fecgov/fec-cms/issues/3326](https://github.com/fecgov/fec-cms/issues/3326)
List general components of the …

Fix candidate profile server error in 1988 for Trump

---

fec/home/models.py
tasks.py

The `RecordPage` model   inherits from `ContentPage` model with uses `stream_factory` as its body section. So I added internal and external link buttons here.
- Resolves #2935
This will effect all page models inheriting from ContentPage model, but only to the extent that they will now also have the new internal and external link buttons.
- modified:   home/models.py
https://github.com/fecgov/fec-cms/issues/3149:
- Checkout and run branch
- Create page of type, RecordPage and confirm and test the external and internal link buttons
- Publish or Preview to confirm it works 
____

Add internal/external links to RecordPage template

---

fec/home/models.py
tasks.py

`../tasks.py` got inadvertently pushed  up with uncommented feature deploy task (My fault.)
Although, this would not have any effect if the branch name had been deleted after merge, I want to revert it to the expected state, just to be safe.
This file keeps getting pushed up with the task uncommented (with a non-existent placeholder branch name)--maybe there is a better way to control deploys to feature that don't open us up to possible unintended overwrites of feature space. But for now,  an just reverting.
This PR also removes extra, redundant `reporting_example_cards` block from ExamplePage model. This did NOT make it show up twice in steramfield, but it should obviously be removed anyway.
modified:   ../tasks.py
modified:   home/models.py

Revert tasks.py, remove redundant block from ExamplePage model

---

fec/legal/templates/legal-statutes-landing.jinja

Adding new thumbnail and PDF file size to page.
- Resolves #3317 by updating the file size of the revised feca pdf that was uploaded, and updating the thumbnail used for the gray book.
Legal resources statutes page
Image should look like: 
File size of PDF should be listed as 2.97 MB.
When you click on the PDF, it should say it's the February 2019 edition.

Update statutes page

---

fec/fec/static/js/widgets/contributions-by-state-box.js

- Resolves #3290 
- Adjusted the links to Puerto Rico House elections to include both two-year periods rather than only one like the other House elections.
Only WCCF, and only the method that builds the URLs for the state totals' links.
None
None
- Pull, `npm i`, `npm run build`, `./manage.py runserver`
- Check [WCCF](http://127.0.0.1:8000/data/raising-bythenumbers/) for House candidates with contributions that come from Puerto Rico (Gonzalez Colon, Jenniffer is a 2020 candidate with data)
- Find the Puerto Rico line item
- Hover over the linked dollar amount to check that two appropriate `two_year_transaction_period` params are present
- Hover over another state or two to make sure there's only one value for `two_year_transaction_period`
- Check a presidential election that every state …

Update WCCF PR H elections to four years

---

package-lock.json
package.json

- Resolves #3228 
- removes `eslint-plugin-no-unsanitized` from `package.json`
-  developers who used this package to warn about sanitizing inputs will no longer receive warnings.
- `pytest`

removed eslint-plugin-no-unsanitized from package.json

---

fec/fec/static/js/pages/committee-single.js

Replace SA, SB and SE api calls with the latest api endpoints. A total of  7 endpoints are updated
- Resolves https://github.com/fecgov/fec-cms/issues/3285
Committee Raising (SA), Spending (SB) and Independent Expenditure (SE) api calls (endpoints).
**Committee raising tab screen:**
#########################################################################
** Raising tab api calls:** ::: #4 endpoints are updated
#########################################################################
Before:
https://fec-dev-api.app.cloud.gov/v1/committee/C00448696/schedules/schedule_a/by_state/?api_key=pjE98TJBLgSA1XyqNHVMgt1TK88S7qtpIklwztqW&sort_hide_null=false&sort_nulls_last=true&sort=-total&per_page=99&page=1&cycle=2020&election_full=false
After: …

Replace SA, SB and SE cms calls with the latest  api endpoints

---

fec/data/templates/partials/independent-expenditures-filter.jinja

- Resolves #3247 
_Fixes candidate mentioned search field by correcting query param._
While doing this PR, I found a bug that the `candidate_search` query param is not returning all possible results. Although this PR fixes the query on the front end, we should investigate why we don't see all possible results. Issue logged: https://github.com/fecgov/openFEC/issues/4086. 
-  Independent expenditures raw filings search

Corrected candidate mentioned query param

---

fec/fec/settings/production.py

- Resolves 216 (fec-accounts)
_Adds .fec.gov and .app.cloud.gov host names to CMS app._
-  CMS application and website
____

Update hosts in CMS

---

fec/fec/static/js/pages/committee-single.js

Fix filter by committee_id for EC on committee profile page. currently return all committee EC.
https://www.fec.gov/data/committee/C30000533/?cycle=2018&tab=spending
- Resolves [#4098]( https://github.com/fecgov/openFEC/pull/4098)
Change 
/committee/{committee_id}/electioneering/by_candidate/
to use:
/electioneering/aggregates/?committee_id={committee_id}
checkout branch
point to dev api
npm run build
npm run test-single
./manage.py runserver
Test 1:
prod: return all committee electioneering communication:
https://www.fec.gov/data/committee/C30002562/?cycle=2018&tab=spending
local: return no data …

Change to use EC endpoint /electioneering/aggregates/ filter by committee_id

---

fec/data/templates/macros/bythenumbers.jinja
fec/data/templates/raising-bythenumbers.jinja
fec/data/templates/spending-bythenumbers.jinja
fec/fec/static/scss/data-landing.scss

- Resolves #3328 
_Adds a horizontal rule between each feature on the raising-bythenumbers and spending-bythenumbers pages._
- Raising by the numbers
- Spending by the numbers
- Go to Raising by the numbers page: http://localhost:8000/data/raising-bythenumbers/
- Go to Spending by the numbers page: http://localhost:8000/data/spending-bythenumbers/
____

Adds separating line between features on by the numbers pages

---

fec/data/templates/partials/candidate/other-spending-tab.jinja

- Resolves #3374 
_Fixed typo in candidate profile page communication costs section. Updated Oppose section to have detail language also read "Spent by others to **oppose**..."_
-  Candidate profile page communication costs section: http://localhost:8000/data/candidate/H0PA12181/?tab=other-spending#communication-costs
____

Fixed typo on communication costs section

---

fec/fec/templates/partials/footer-navigation.html

- Resolves #3412 
_Update open government link in footer from `https://www.data.gov/open-gov/` to `/open/`._
-  Footer
This might include:
- Add redirect in wagtail for `/open/` to go to the open govt page in wagtail, select the wagtail page instead of using the URL path
- Go to the footer and click on the "open government" URL. It should redirect to the correct wagtail page locally.
____

[MERGE WITH GITFLOW - HOTFIX] Update open gov link

---

fec/fec/static/js/modules/tables.js
fec/fec/tests/js/tables.js

- Resolves #3367 
_Added error message for more than 10 committee_ids that are added to the committee id typeahead._
- Receipts datatable
- Individual contributions datatable
- Disbursements datatable
- Independent expenditures datatable
- Go to Receipts, Individual contributions, Disbursements, and Independent expenditure datatables to add more than 10 committees to `RECIPIENT NAME OR ID` and `SPENDER NAME OR ID` fields. This is the first typeahead filter on these datatables. For convenience, I have added links to these datatables with greater than 10 committee ids already inserted. 
- http://localhost:8000/data/receipts/?data_type=processed&committee_id=C00034728&committee_id=C00 …

Datatables handle >10 committee_ids

---

fec/fec/static/js/modules/download.js
fec/fec/static/scss/components/_downloads.scss

- Resolves #3339 
Added a close button for download window error messages.
Added it to the error message in the template for the download error message text and styled it
None
- `npm i` `npm run build`
- Change your API key to one with limits that you can hit, or otherwise ensure you get an error message
- Check an [Individual Contributions page](http://127.0.0.1:8000/data/receipts/individual-contributions/?committee_id=C00577130&committee_id=C00696948&contributor_employer=Amazon&two_year_transaction_period=2020), limit the results so the Export button is active
- Click the Export button at the top right
- The error message should appear at the bottom
- Clicking the X to the right of the message should close the window _and_ re-enable the export …

Add error message close button for downloads

---

fec/legal/templates/legal-archived-mur.jinja

- Resolves #2798 
Modify format of archived MURs with one document
-  Archived MUR "documents" section
- `export FEC_API_URL="https://fec-dev-api.app.cloud.gov"`
Archived MUR with 1 doc
- http://localhost:8000/data/legal/matter-under-review/1/
- https://dev.fec.gov/data/legal/matter-under-review/1/
Archived MUR with multiple docs
- http://localhost:8000/data/legal/matter-under-review/3485/
- https://dev.fec.gov/data/legal/matter-under-review/3485/
Current MUR
- http://localhost:8000/data/legal/matter-under-review/7000/
- https://dev.fec.gov/data/legal/matter-under-review/7000/

Modify format of archived MURs with one document

---

fec/data/templates/partials/committee/about-committee.jinja

- Resolves #3435 
_This fixes the connected organization field inside SSF about this committee page._
-  SSF about this committee profile page: http://localhost:8000/data/committee/C00062224/?tab=about-committee
branch | PR
feature/fix_committee_profile_not_show | [link](https://github.com/fecgov/fec-cms/pull/3299)
____

[HOTFIX - Merge with gitflow] Fix connected organization on committee profile page

---

fec/data/api_caller.py
fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/templates/partials/committee/about-committee.jinja
fec/data/tests/test_candidate.py
fec/data/tests/test_committee.py
fec/data/views.py

- Resolves #2964
Add most recent Form 1 to committee profile page "About this Committee" tab, add test coverage, move "most recent" logic out of template
Note: Candidate profile page shows most recent regardless of cycle, so for now that's what we're doing with committee profile pages. 
-  Committee profile page "About this Committee" tab, Candidate profile "About this candidate" tab
-  run this branch, check out http://localhost:8000/data/committee/C00693234/?tab=about-committee&cycle=2020
- this **won't show up** for non-committee filers, example: http://localhost:8000/data/committee/C90010661/?tab=about-committee
- Candidate page: http://localhost:8000/data/candidate/H8CA05035/?tab=about-candidate&cycle=2018

Add most recent Form 1 to committee profile pages

---

fec/data/templates/partials/receipts-filter.jinja

- Resolves #3371 
-  Changes "CONTRIBUTOR NAME OR ID" text to be "RECIPIENT NAME OR ID" for raw efile receipts on https://www.fec.gov/data/receipts/?data_type=efiling&committee_id=C00010603&contributor_name=miller
Fixed version: 
1. check out this branch
2. run local api
3. run local cms
4. view fix at http://localhost:8000/data/receipts/?data_type=efiling&committee_id=C00010603&contributor_name=miller

fix name text for raw efile

---

fec/home/templates/home/candidate-and-committee-services/guides.html

-Takes out "understanding" from the public funding bucket to shorten link title
List general components of the application that this PR will affect: Guides landing page
Link title should now be: Public funding of presidential elections

Update Guides.html to shorten link title

---

fec/legal/templates/legal-statutes-landing.jinja

- Resolves #3428 
- Updates the link for Title 52 to the permalink and the link for Title 26, Subtitle H to the latest version available.
- Fixes the filenames used for the images next to Title 52 and Title 26, Subtitle H (the filenames for the images were missing "original" so that may be why they aren't showing up currently).
Before:
After: 
Thumbnails should look like this:
Images are located at:
Title 52: https://www.fec.gov/resources/cms-content/images/thumbnail--title52.original.jpg
Title 26: https://www.fec.gov/resources/cms-content/images/thumbnail--title26.original.jpg
Make sure images show up when tested on …

Update statute landings page

---

fec/fec/static/js/modules/toggle.js

If it dynamic content (e.g. datatables) wasn't visible when it was created, its width will be 0px, so we'll trigger a resize when we toggle it on (or off) to trigger its layout to refresh.
- Resolves #3344 
- Added a resize event that will fire after any content has been toggled using the `js-panel-toggle-control` class name  
None
- Pull branch, `npm i`, `npm run build`, `./manage.py runserver` like normal.
- Go to a [candidate's raising page](http://127.0.0.1:8000/data/candidate/P60007168/?cycle=2020&election_full=true&tab=raising)
- Under Individual Contributions, switch to the State tab
- Make sure the header for the newly-visible table is the same width as the table content below it (rather than only as wide as the text content requires it to be—see the screenshots from [the original …

Trigger resize when toggling content

---

requirements.txt

- Resolves #3423 
Upgrading Django from 1.11.23 to 1.11.27
Being an upgrade to Django it's a universal change, but it's only patch-level so any changes should be fixes rather than new or tweaked features.
None
None
- activate the pyenv instance
- in `/`, run `pip install -r requirements.txt`
- run `npm i` and `npm run build`
- in `/fec/`,  `./manage.py runserver`
- get no errors
- [site](http://127.0.0.1:8000) should load and behave like normal
____

Upgrade Django from 1.11.23 to 1.11.27

---

fec/data/templates/raising-bythenumbers.jinja
fec/fec/settings/base.py

Resolves #3460
- Remove reaction box macro from raisingbythenumbers.jinja
- Remove reaction box script tag from raisingbythenumbers.jinja
- Remove feature flag env var from settings/base.py
modified:   data/templates/raising-bythenumbers.jinja
modified:   fec/settings/base.py
https://github.com/fecgov/fec-cms/pull/3302
- checkout `feature/3460-remove-wccf-reaction-box`
- runserver
- confirm that reaction box is NOT under WCCF map on http://127.0.0.1:8000/data/raising-bythenumbers/
____

Remove reaction box from WCCF feature

---

fec/data/api_caller.py
fec/data/templates/partials/browse-data/candidates.jinja
fec/data/views.py

- Resolves #3486 
_Adds accordions for 2020 presidential map data files._
**This hotfix needs to be deployed on Wednesday 1/29. Please provide feedback ASAP.**
-  Browse data candidates tab: https://www.fec.gov/data/browse-data/?tab=candidates

[Merging to release branch] Display presidential map data for 2020 (Deploy on 1/29)

---

fec/data/templates/macros/filters/version-status.jinja
fec/data/views_datatables.py

- Resolves #3538 
_The current version checkbox needs to be checked on load instead of always checked. This applies a redirect to the independent expenditures datatable, consistent with other implementations to load a filter on default._
-  Independent expenditures datatable
- go to IE datatable: http://localhost:8000/data/independent-expenditures/
- check to make sure on load, the current version checkbox is checked
- uncheck the current version checkbox to make sure it will apply correctly
____

redirect to default most_recent to true on load

---

package-lock.json
package.json

- Resolves #3525 
Upgraded the version of handlebars as outlined at https://www.npmjs.com/advisories/1325
Could impact any page / template that used handlebars (Anything with `{{` and `}}`; any template with an `.hbs` extension)
There were no visual changes
None
- Pull the branch as usual
- `npm i`
- Confirm there are no build errors
- Check that different types of pages display as usual:
- Homepage
- Data pages (a couple)
- Legal pages (a couple)
- Blog pages (a couple)
____

Upgrade handlebars

---

fec/data/templates/macros/filters/ie-reports.jinja
fec/fec/static/js/modules/tables.js
fec/fec/tests/js/tables.js

- Resolves #3463 
_Update the regularly scheduled report form from F3X to F24 when 24- and 48-Hour Reports are selected._
-  Independent expenditures datatable: https://www.fec.gov/data/independent-expenditures/
-No screenshots, just modified fetch call._
____

Update F3X to F24 when 24- and 48-Hour Reports selected

---

fec/data/templates/macros/filters/version-status.jinja
fec/data/templates/partials/independent-expenditures-filter.jinja
fec/fec/static/js/modules/tables.js

- Resolves #3545 
- Resolves #3549  
_This PR disables the version filter when regularly scheduled reports toggle is selected within processed. It also adds the report type toggle to the raw IE data filters. The helper_text option was added to the version filter as an option when the methodology is complete._
-  Independent expenditures datatable: http://localhost:8000/data/independent-expenditures/
Processed only: Disables the version filter when regularly scheduled reports toggle is selected
- go to the IE datatable: http://localhost:8000/data/independent-expenditures/
- Ensure that Version is disabled when regularly scheduled report is selected
- Ensure that Report type toggle is …

Conditionally disable current version and add report type toggle to raw

---

fec/data/templates/widgets/pres-finance-map.jinja
fec/data/urls.py
fec/data/views.py
fec/fec/settings/base.py
fec/fec/static/js/modules/data-map.js
fec/fec/static/js/widgets/pres-finance-map-box.js

- Add feature flag for presidential map
- Fix formatting, silence tests for map
- Clean up python logic, fix default year per https://github.com/fecgov/fec-cms/pull/3547#discussion_r380817871
- Use `constants.states_excl_territories` for state list per https://github.com/fecgov/fec-cms/pull/3547#discussion_r380777664
**Feature flag info**
To turn on the feature, `export FEC_FEATURE_PRESIDENTIAL_MAP=True`
To turn it off, `unset FEC_FEATURE_PRESIDENTIAL_MAP`
You may want to add it to your bash profile so that you don't have to keep setting it.

Add feature flag, silence JS tests, address some feedback for presidential map

---

fec/data/templates/widgets/pres-finance-map.jinja

- Resolves https://github.com/fecgov/openFEC/issues/4219
Fix number for transfers in
-  Presidential map, transfers in
https://github.com/fecgov/openFEC/issues/4219 
- Connect to `dev` API (after https://github.com/fecgov/openFEC/issues/4219 is merged)
- make sure `FEC_FEATURE_PRESIDENTIAL_MAP` is set to `True`
- Go to http://localhost:8000/data/candidates/president/presidential-map/
- Check that "Transfers in" number for 2020 nationwide matches screenshot

[MERGE AFTER openFEC 4220] Fix number for transfers in

---

requirements.txt
tasks.py

- Resolves #3466 
Update gunicorn to 19.10.0 See https://snyk.io/vuln/SNYK-PYTHON-GUNICORN-541164
- Gunicorn is only used in production, so you need to deploy to `dev` to test
-  More info about gunicorn: https://gunicorn.org/
- See https://github.com/fecgov/fec-cms/blob/develop/bin/run.sh#L17

Update gunicorn to 19.10.0

---

tasks.py

@fec-jli @pkfec: This PR removes the manual deploy branch accidentally merged under #3557. As part of the manual deploy/review I added the feature branch to tasks.py and merged before dropping that commit. This PR restores tasks.py.
cc @lbeaufort

Revert "Update gunicorn to 19.10.0"

---

fec/fec/static/js/pages/committee-single.js

Fix filter by committee_id for CC on committee profile page. currently return all committee's EC.
(passing committee_id=C70000112  cycle=2014, return 1265 records)
[https://www.fec.gov/data/committee/C70000112/?cycle=2014&tab=spending](https://www.fec.gov/data/committee/C70000112/?cycle=2014&tab=spending)
Resolves [#3615]( https://github.com/fecgov/fec-cms/issues/3615)
Change 
/committee/{committee_id}/communication_costs/by_candidate/
to use:
/communication_costs/aggregates/?committee_id={committee_id}
checkout branch
point to dev api
npm run build
npm run test-single
./manage.py runserver
Test :
one prod: return all committee's …

[before cut release]Change to call /communication_cost/aggregates

---

requirements.txt

- Resolves #3606 
Update Django one minor version (`2.2.10` > `2.2.11`)
https://docs.djangoproject.com/en/3.0/releases/2.2.11/
-  Minor bug and security fixes
-  Run locally
- Run pytest

Update Django to 2.2.11

---

fec/data/tests/test_utils.py
fec/data/utils.py

- Resolves issue found in testing
- Remove timestamps from date comparisons, fix coverage dates for presidential bulk files
- Improve test coverage
-  http://localhost:8000/data/browse-data/?tab=candidates
-  http://localhost:8000/data/browse-data/?tab=candidates should show 1/31/20 as ending monthly coverage date until tomorrow (1/21/)
Original PR: https://github.com/fecgov/fec-cms/pull/3629

[MERGE WITH GIT FLOW] Hotfix/fix coverage dates

---

fec/fec/static/scss/widgets/pres-finance-map.scss
tasks.py

Fixes IE alignment of candidate column on pres-finance-map
If we just want to add this to second round of edits, I can cancel this PR --OR--  if we think this is important, we can hotfix it.
- Resolves # (No current GH issue) This issue is referenced on page 7 of the MSCW document:
https://docs.google.com/document/d/1CH5-W6QzVF7Zve2P3ttVPK9gdfVNm_x5NBY4gXoV9vQ/edit#
- Add MS prefixed rule `display:-ms-flexbox` to last-child TDs of candidate column
- Change width from `100px` to `auto` (@robert - I hope this one  is OK?--did not seem to break anything in desktop or responsive views)
modified:   fec/static/scss/widgets/pres-finance-map.scss
Presidential map branch 5
https://github.com/fecgov/fec-cms/pull/3632
**One can test on feature space:** …

fix aligment in IE of candidate column on pres map

---

fec/search/templates/search/policy_guidance_search_page.html
fec/search/views.py

- Resolves #3662
_Adds best bets count to total count for guidance search._
-  Guidance search
branch | PR
feature/3601-policy-guidance-search | [https://github.com/fecgov/fec-cms/pull/3607]()
- Pull down this PR
- `export SEARCH_GOV_POLICY_GUIDANCE_KEY` in your environment vars. You can grab this API access key by logging into search.gov and accessing the fec_content_s3 site.
- `export FEC_FEATURE_GUIDANCE_SEARCH = true`
- Go to http://localhost:8000/legal-resources/policy-and-other-guidance/guidance-documents/
- Try a search that includes best bets search like `citizens united`. The total count should add best bets and results count to give an accurate count 
____

Add best bets count to total count

---

fec/fec/static/js/widgets/pres-finance-map-box.js

During some code cleanup, a variable name-change  was overlooked,  making the initial button-state (open/close ) incorrect on first-load of the `raising exports download area`. The button should be a minus(-), when the accordion is open.
**Commit of original changes:**
7d8cde1 Cleanup (comments, typos, unused, tests)
**Proposed changes, this PR:**
https://github.com/fecgov/fec-cms/blob/fad2446d4a227f3e4da0a676c89b415b7034fddd/fec/fec/static/js/widgets/pres-finance-map-box.js#L1252
- change the above line to:
`$(this.raisingExportsToggle).toggleClass('button--close', true);`
- Also remove unnecessary `instance=this` declaration on line [#1238 ](https://github.com/fecgov/fec-cms/blob/fad2446d4a227f3e4da0a676c89b415b7034fddd/fec/fec/static/js/widgets/pres-finance-map-box.js#L1238)
modified: …

Correct var name missed in code-cleanup on pres map

---

fec/search/views.py

_I noticed that the guidance page was not loading on load. It had this error below. This is because I did not make sure results appear before doing a count, so none was returned. This patch ensures that total_count always has a value._
total_count = results['meta']['count'] + results['best_bets']['count']
TypeError: 'NoneType' object is not subscriptable
-  Guidance search
branch | PR
feature/3662-add-best-bets-to-count | [https://github.com/fecgov/fec-cms/pull/3663]()
- Pull down this PR
- `export SEARCH_GOV_POLICY_GUIDANCE_KEY` in your environment vars. You can grab this API access key by logging into search.gov and accessing the fec_content_s3 site.
- `export …

fix guidance search on load

---

fec/search/management/data/sitemap_html.xml

Updates the sitemap of HTML pages to catch changes made this month to those pages
- Verify that the dates are in correct format YYYY-MM-DD and are April 2020 (except for the last one).

Update sitemap for html guidance pages

---

fec/fec/settings/base.py
fec/fec/templates/partials/navigation/nav-legal.html
fec/fec/urls.py
fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
fec/search/templates/search/policy_guidance_search_page.html
fec/search/views.py

- Resolves #3671 
- Resolves #3670
- Updated intro and footer text according to OGC requests
- Added links for guidance search on H4CC and Legal resources nav
- Added helper tool tip next to guidance search label
- Removed feature flag as it's unneeded now.
-  Guidance search page
- Pull down this PR
- `export SEARCH_GOV_POLICY_GUIDANCE_KEY` in your environment vars. You can grab this API access key by logging into search.gov and accessing the fec_content_s3 site.
- Go to http://localhost:8000/legal-resources/policy-and-other-guidance/guidance-documents/ and make sure it loads
- Try a search that includes best bets search like `citizens united`. The total count should add best bets and results count to give an accurate …

Changes to Guidance search

---

fec/fec/templates/partials/usa-banner.html

- Resolves issue in testing - more consistent with USDS example https://designsystem.digital.gov/components/banner/
branch | PR
`feature/3579-3678-usa-and-env-banners` | https://github.com/fecgov/fec-cms/pull/3700
See https://github.com/fecgov/fec-cms/pull/3700

Bold "https://" in banner

---

fec/home/templates/blocks/section.html
fec/home/templates/partials/section-nav.html
fec/home/templatetags/filters.py

Resolves JS errors that were breaking `sticky menu` and `feedback box` on pages using numeric section titles like `2017-2018`. 
Prepends non-digit-containing string to these titles in order to create strings that can be used as HTML IDs. Note that these strings would remain invalid after simply using the existing `remove_digits` filter. (Example: '2017-2018' would become the invalid '#-'). 
- Resolves #3661
modified:   home/templates/blocks/section.html
modified:   home/templates/partials/section-nav.html
modified:   home/templatetags/filters.py
- checkout `fix/restore-feedback-box-on-pages`
- runserver
- Go to: http://127.0.0.1:8000/help-candidates-and-committees/candidate-taking-receipts/archived-contribution-limits/  
--AND/OR--
- Any of the pagea linked in the bulleted list on: …

Filter to create valid anchors out of numeric titles

---

fec/fec/static/js/widgets/pres-finance-map-box.js

- Resolves #3709
Fix download export link on presidential map
From original issue? 
>When I click on the export spending data button, I receive a contributions file instead of a disbursements file. Here's the URL of the downloadable file https://www.fec.gov/files/bulk-downloads/Presidential_Map/2020/P00000001/P00000001-ALL.zip. It should end with "D-ALL..zip."
> I should have recieved a disbursments file. The naming convention for all disbursement files is D-ALL.zip.
>For example, https://www.fec.gov/files/bulk-downloads/Presidential_Map/2020/P00000001/P00000001D-ALL.zip
-  https://www.fec.gov/data/candidates/president/presidential-map/
- Go to http://localhost:8000/data/candidates/president/presidential-map/
- Click on …

[HOTFIX] [MERGE WITH GIT FLOW] Fix download export link

---

requirements.txt

- Resolves #3699
Update wagtail to 2.7.2, remove old `TODO` comment
Wagtail 2.7.1 and 2.7.2 changelogs:
- https://docs.wagtail.io/en/v2.8.1/releases/2.7.1.html
- https://docs.wagtail.io/en/v2.8.1/releases/2.7.2.html
-  Wagtail
- `snyk test --file=requirements.txt`
- Run locally, check H4CC pages, try http://localhost:8000/admin/
- Tesedt with manual deploy, log in to Wagtail ✅ content team said it looked ok

Update wagtail to 2.7.2 (security update)

---

fec/data/api_caller.py

- Resolves https://github.com/fecgov/fec-accounts/issues/248
_Sets python get requests timeout to 90 seconds. This will ensure that requests are closed at a regular interval so that CMS PG connections do not build. If timeout is reached a 500 error page will come up and, this will appear in the logs:
```
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host=‘localhost’, port=5000): Read timed out. (read timeout=90)
```
-  FEC python requests in api_caller.py
- Follow instructions here to create local API load https://github.com/fecgov/fec-accounts/issues/248#issuecomment-618541364
- Connect local CMS to local API
- Run the CMS and try a page that uses a GET request from the …

Set python get request timeout

---

fec/data/templates/layouts/main.jinja
fec/fec/static/scss/components/_site-header.scss
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/fec/templates/partials/usa-banner.html

- Resolves #3733
modified:   data/templates/layouts/main.jinja
modified:   fec/static/scss/components/_site-header.scss
modified:   fec/templates/base.html
modified:   fec/templates/home_base.html
modified:   fec/templates/partials/usa-banner.html
- Checkout and run `fix/minor-edits-usa-env-banners`
- npm run build-sass
- Confirm that font size on "The site is secure." is same as the rest of the text `(1.6rem )` 
- Go to https://www.fec.gov/data/legal/statutes/ and open usa banner, confirm that the accordion close button (minus button) does not show. 
____

Minor edits to usa and env-specific banners

---

fec/fec/static/js/legal/SearchResults.js
fec/fec/static/js/legal/filters/TooltipHelp.js
fec/legal/templates/layouts/legal-doc-search-results.jinja
fec/legal/templates/macros/legal.jinja

Point `Try FEC.gov` link on legal search no-results page to fec.gov search, passing the  search query
- Resolves #3618
modified:   legal/templates/macros/legal.jinja
modified:   fec/static/js/legal/SearchResults.js
modified:   legal/templates/layouts/legal-doc-search-results.jinja
checkout `feature/fix-try-fec-link-legal-srch`
Runserver:
- Go to: http://127.0.0.1:8000/data/legal/search/?search_type=all
- Type in a nonsense search string
- Click on `Try FEC.gov` button
- Confirm that it goes to the main fec.gov search page, passing your query along
- Also test :
- http://localhost:8000/data/legal/search/enforcement/ , - - - -- 
- http://localhost:8000/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F
- http://localhost:8000/data/legal/search/statutes/
- …

Fix try fec.gov  btn on legal no-results page

---

fec/fec/urls.py
fec/home/views.py

Resolves #3760
_500 page environment specific banners will now only display on local, dev, and stage. Prod 500 error page will not display this banner._
-  500 error page
branch | PR
feature/3742-static-status-page | [link](https://github.com/fecgov/fec-cms/pull/3750)
- Pull down the branch
- Turn off DEBUG mode inside of the dev.py file. Change to `DEBUG = False`. Also add `ALLOWED_HOSTS = ['*']`. These will be temporary changes to test out the 500 error messaging.
- Build assets using collectstatic so that scripts and styles will work on site: `./manage.py collectstatic --noinput -v 0`
- Set your local CMS environment to prod: `export FEC_CMS_ENVIRONMENT=prod`
- …

[HOTFIX - MERGE WITH GITFLOW] Fix env banner for 500 error page

---

package.json

- Resolves #3698 
_Upgrades jquery to 3.5.1 and remediates XSS vulnerabilities._
See jquery docs on what was released for 3.5.1: https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/
Upgraded jQuery from 3.4.1 to 3.5.1
modified: ../package-lock.json
modified: ../package.json
- `npm i`
- Spot check pages that use jquery
____

Upgrade jquery to 3.5.1

---

fec/data/templates/committees-single.jinja
fec/fec/static/scss/components/_datatables.scss

To make it more clear to our users what the status of a committee is, we want to add an indicator at the top of the committee profile page.
- Resolves #[3642](https://github.com/fecgov/fec-cms/issues/3642)
committees-single.jinja
_datatables.scss
2) point to dev api
3) npm run build-sass
4) ./manage.py test
5) npm run test-single
6) ./manage.py runserver
7) test urls
a) active committee:
http://127.0.0.1:8000/data/committee/C00580100/?cycle=2020
b) terminated committee:
http://127.0.0.1:8000/data/committee/C00619411/
c)
http://127.0.0.1:8000/data/committee/C90018904/

Add committee active/terminated indicator on profile page

---

package-lock.json

- Add on for #3698 
_Adds package-lock.json for the jquery to 3.5.1 upgrade._
This needs to be added as we are checking hashes for upgrades to packages.

add package lock file for jquery upgrade

---

fec/data/templates/committees-single.jinja
fec/fec/static/scss/components/_datatables.scss

Current style sheet class name is is_active and is_terminated, we should change name to
is_active_status and is_terminated_status
Related Issue: [https://github.com/fecgov/fec-cms/issues/3796](https://github.com/fecgov/fec-cms/issues/3796)
2) point to dev api
3) npm run build-sass
4) ./manage.py test
5) npm run test-single
6) ./manage.py runserver
7) test urls
a) check green dot not show on next to Summery
http://127.0.0.1:8000/data/legal/matter-under-review/4321/
b) active committee:
http://127.0.0.1:8000/data/committee/C00580100/?cycle=2020
c) terminated committee:
http://127.0.0.1:8000/data/committee/C00619411/
d)
http://127.0.0.1:8000/data/committee/C90018904/

Change stylesheet class name to is-active-status and is_terminated_status

---

fec/fec/static/js/modules/typeahead.js
fec/fec/static/scss/base.scss
fec/fec/static/scss/calendar.scss
fec/fec/static/scss/data-landing.scss

To make it more clear to our users what the status of a committee is, we want to add an indicator on global committee search dropdown list. Should be keyed off the current year.
- Resolves https://github.com/fecgov/fec-cms/issues/3752
add logic to typeahead.js  function: committeeDataset()
2) npm run build
3) run:
pytest
npm run test-single
4) test green/grey dot on globe search committee dropdown list.
globe search dropdown list

Add active/terminated indictor on dropdown list.

---

fec/data/api_caller.py
fec/legal/templates/legal-archived-mur.jinja
fec/legal/templates/legal-current-mur.jinja

- Resolves #3772 
_Uses a `try` and `except` to gracefully fail when there are no current MUR docs. Incorporates an input into the logs when there is an exception thrown. Also creates an error message for archived MURs._
- Current MUR canonial page
- Archived MUR canonical page
- In `api_caller.py` line 157, change the param name `"documents"` to something that does not exist like `"test"`. Then take a look at a current MUR page like this to check if the error appears: http://localhost:8000/data/legal/matter-under-review/7620/. 
- In `legal-archive-mur.jinja` lines 93, 100, and 109, change the param name `'documents'` to something that doesn't exist like `'test'`. Then take a look to see if the error appears for an …

Gracefully fail when there are no MUR docs

---

fec/data/api_caller.py

_Resolves failed flake8 in pytest by removing extra lines._
-  api_caller.py
branch | PR
feature/3772-handle-missing-mur-docs | [link](https://github.com/fecgov/fec-cms/pull/3813)
feature/3651-flake8-linting | [link](https://github.com/fecgov/fec-cms/pull/3824)
- Run `pytest` and check if there are any failures
____

removed extra lines causing flake8 error

---

fec/data/api_caller.py

_Fixed misspelling in query._
- MUR canonical page
branch | PR
feature/3772-handle-missing-mur-docs | [link](https://github.com/fecgov/fec-cms/pull/3813)

[HOTFIX - MERGE WITH GITFLOW] Fix MUR document param

---

fec/data/templates/pres-finance-map.jinja

Remove reaction box from presidential map
- Resolves #3649 
modified:   data/templates/pres-finance-map.jinja
Checkout and run branch: `feature/3649-remove-reaction-box`
Confirm pres map reaction box is removed
____

Remove reaction box code from  pres map

---

fec/fec/static/js/modules/download.js

- Resolves #3819 
_Updates the downloads error message for when there is a server error. Normally these server errors are 500 error message._
-  Downloads on the website
To test that messages display when needed, I updated the stage API download key to something very low and kept trying to execute a download until the 429 error displayed. Then I stopped the celery worker app in stage to simulate a server error for downloads. To save testing time, I've already done the testing and put screenshots above. One for when a server error happens and one for when a 429 error happens.
____

Update downloads error message

---

package-lock.json
package.json

Update lodash v4.17.19
- Resolves #3740
- update lodash to the latest v4.17.19 in `package.json` and `package-lock.json`
on Develop branch lodash v4.17.14
on Feature with lodash v4.17.19:
**Following instructions work if `SNYK CLI` is already installed on your workstation:**
- pull the latest code from fec-cms/develop branch.
- `git checkout develop`
- run `snyk test --file=package.json` on `fec-cms` repo(This should flag the LODASH pkg is vulnerable, in the terminal)
- checkout feature branch  
- run `git checkout feature/3740-upgrade-lodash`
- create a new python virtual env 
- run - `pyenv virtualenv 3.7.7 cms377`
- activate virtual env
- run - pyenv activate cms377
- run `rm -rf node_modules/`
- run `npm …

update lodash v4.17.19 to fix the synk vulnerability

---

pytest.ini
requirements.txt

- Resolves #3777
Update wagtail to 2.7.3, exclude static directories from linting
_This might include:_
- links to sample pages to test
- Any local environmental setup that is unusual (env vars, API version to point to, etc)
____

Update wagtail to 2.7.3, exclude static directories from linting

---

fec/fec/static/js/modules/table-columns.js
fec/fec/static/js/pages/committee-single.js

- Resolves #3900 
- Related #https://github.com/fecgov/openFEC/issues/4360
- in `fec/static/js/modules/table-columns.js`, update independentExpenditureColumns,  communicationCostColumns and electioneeringColumns to include the candidate_name and committee_name. 
- IE, CC and EC sections in Election pages
- IE section in Spending pages
**In Production:**
**After fixing sort in local env:**
- checkout the branch
- run  `git checkout feature/3900-fix-sort`
- compile JS 
- run `npm run build`
- connect your cms to API branch that has the fix (see API pr for details # https://github.com/fecgov/openFEC/pull/4482) 
- start API and CMS servers
- run  `./manage.py runserver`
Compare and test the following URL:
1.  **_sort by candidate column  on independent …

Fix the sort by candidate and spent by columns on the elections and spending pages.

---

package-lock.json
package.json

- Resolves #3919 
- adds `"ajv": "^6.12.3",` to `package.json` as vulnerability is introduced through upstream `request` package which is deprecated.
- `ajv` is https://ajv.js.org/

add ajv to package.json

---

README.md

- Resolves #3757
-  README.md
- local postgreSQL

update README.md with correct postgreSQL version documentation

---

fec/fec/forms.py
fec/fec/settings/base.py
fec/fec/tests/test_form.py
fec/home/templates/home/contact-form.html
fec/home/views.py

Resolves #3718
- Handle ServiceNow API outage/URL change by only showing analyst lookup 
- Add test coverage 
- Remove feature flag for RAD form
- Add error message when ServiceNow is unavailable
Contact RAD page
- Checkout `develop`
- ~Set `FEC_FEATURE_RADFORM=True`~ removed this env var
- Set these, but with bad URL or creds:
- `FEC_SERVICE_NOW_API`: "https://api.open.fec.gov/" or "https://api.open.fec.gov/v1/committees/?api_key=DEMO_KEY&committee_id=C00431445&page=0" until the server error is fixed, or anything that doesn't have a "results" object
- Go to http://localhost:8000/help-candidates-and-committees/question-rad/
➡️ get error `KeyError: 'result'`
- ~Set `FEC_FEATURE_RADFORM=True`~ removed …

Handle ServiceNow API outage or URL change

---

fec/fec/static/scss/components/_articles.scss
fec/fec/static/scss/components/_examples.scss
fec/fec/static/scss/components/_richtext.scss
tasks.py

This PR addresses three Wagtail wishlist items:
1)  #3445, Images in RTE (Rich Text Editor)  not resizing proportionally in mobile sizes by observing the height html attribute ([Example &#187;](https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/nonconnected-coordinated-communication-example/))
2)  #3968,  `ExampleImage captions` do not respond properly in mobile sizes. They should move under the image in mobile.
See screenshot below. ([Example &#187;](https://www.fec.gov/help-candidates-and-committees/making-disbursements/advertising/candidate-committee-yard-sign-example/))
3)  #3541,  There is too much space under headlines above tables using `TableBlock` ([Example &#187;](https://www.fec.gov/updates/march-25-webinar-candidate-committees-2020/))
- Resolves: #3445 …

Fix RTE mobile image resize , example-img, and table-spacing bugs.

---

fec/fec/static/js/pages/candidate-single.js
fec/fec/static/js/pages/committee-single.js

- Resolves #3921 
- Resolves #3945 
_Updates candidate and committee sort parameters to use `committee_name` and `candidate_name`._
Merge after the API work is merged: https://github.com/fecgov/openFEC/pull/4529
- Candidate profile page communication costs
- Committee profile page: independent expenditures, communication costs, and electioneering communications datatables
branch | PR
feature/fix-communication-cost-sort | [link](https://github.com/fecgov/openFEC/pull/4529)
- Run your API off this PR: https://github.com/fecgov/openFEC/pull/4529
- Connect your CMS to your local API
- Run your CMS
- Go to the candidate profile page: …

[Merge after openFEC#4529] Fix candidate name and committee name sort for IE, EC, and CC tables

---

package-lock.json
package.json

- Resolves #3983 
Updating lodash by a patch level to address a [Snyk vulnerability](https://app.snyk.io/vuln/SNYK-JS-LODASH-590103)
If there were any effect, it would appear in the older interactive parts of the site. i.e. datatables, and interactive elements built before 2019.
The upgrade is only a patch-level step, though, so should be easy.
No noticeable changes
None
- `npm i`
- check that the pre-2019 interactive elements on the site work as expected (datatables, graphs, etc)
____

SNYK - 3983 Update lodash

---

fec/data/views.py

- Resolves #4001
Add one converted committee (PCC to PAC). OK not to hotfix per PM's.
-  Add more candidates to manual conversion list
- Committee and candidate profile pages should have explanatory text:
https://www.fec.gov/data/committee/C00727156
https://www.fec.gov/data/candidate/P00014407
https://github.com/fecgov/fec-cms/pull/3953
- Would like two approvals, at least one developer please
- If you can run locally: Committee and candidate profile pages should have explanatory text:
http://localhost:8000/data/committee/C00727156
http://localhost:8000/data/candidate/P00014407
- Anyone: Make sure the values match the [tracking …

Add one PCC->PAC converted committee

---

fec/home/models.py
fec/home/templates/home/resource_page.html
tasks.py

- Add a `RichTextBlock` to the `related_pages` ("Read next") section on `ResourcePage` templates, allowing editors to add an external link in addition to the existing internal PageChooserBlock. 
- Adjust temp[late logic to accommodate
- We chose a `RichTextBlock` to give editors the versatility to add an external link as well as pretty much any other content  they might need to add here. 
- The seemingly extraneous  looping in the template is necessary because the `PageChooserBlock` is  inside a `ListBlock`, requiring looping to separate them into `<li>s` on the front end.. Attempts to simplify template logic by  switching from a `ListBlock` to a singular block in the model would group existing database entries for `PageChooser` `ListBlocks` into one `<li>`  on the front end. 
- Resolves …

Add external page link to "Read next" sidebar on ResourcePage

---

fec/data/templates/browse-data.jinja
fec/data/templates/partials/browse-data/historical.jinja
fec/fec/templates/partials/navigation/nav-data.html

- Resolves #4017
Hard-coded changes of campaign finance data menu item and page changes from "Historical statistics" to "Campaign finance statistics"
-  CMS
- _Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface or front-end change, include both Before and After screenshots._
- Required: One front-end developer
- Campaign finance data menu on any page
- /data/browse-data/?tab=historical
____

Update campaign finance statistics pages

---

fec/data/api_caller.py
fec/data/tests/test_legal_search.py

- Resolves #4033 
MURS
- https://www.fec.gov/data/legal/matter-under-review/(mur case number)
(for example https://www.fec.gov/data/legal/matter-under-review/7594)
- (@patphongs OR @lbeaufort )
- I added a test as well based on Pat's suggestion to add to logger when we come across a mur with no action. One way to run the test is with: `pytest -o log_cli=true data/tests/test_legal_search.py -s` (thanks Pat for having that in slack history)
- verify server error screen: https://dev.fec.gov/data/legal/matter-under-review/7594/
- check out branch
- run local cms and point to dev api (thanks Laura for explaining this vs local api)
- go to localhost:8000/data/legal/matter-under-review/7594/ and see that page loads (with …

Add empty string when null action

---

fec/fec/static/js/modules/cycle-select.js
fec/fec/tests/js/cycle-select.js

- Resolves #3805 
_This change will disable all two year periods on the candidate profile page if fec_cycles_in_election is null._
-  Candidate profile pages with no two year transaction periods in election
- Go to a candidate profile page with null fec cyles in election, such as this candidate: http://localhost:8000/data/candidate/P00010298/. There are additional test cases that you can click around in this [spreadsheet](https://docs.google.com/spreadsheets/d/1KJXrGS45HoC7B2vzAHg3tOEb15PeIdqkfyiGepIr60s/edit#gid=0) too. 
- Make sure that all individual two year election periods are all disabled and the All years button is selected.
- `npm run test-single` make sure tests …

disable two year period on candidate page when cycles is null

---

fec/data/views.py

- Partial resolution for #4038
Add one converted PCC -> PAC committee manually
-  Add more candidates to manual conversion list
- Committee and candidate profile pages should have explanatory text:
https://www.fec.gov/data/committee/C00693713
https://www.fec.gov/data/candidate/P00009183
- One approval needed
- Committee and candidate profile pages should have explanatory text:
http://localhost:8000/data/committee/C00693713
**EXAMPLE**
http://localhost:8000/data/candidate/P00009183
**EXAMPLE**

[Before release] Add one converted committee manually

---

fec/search/management/data/sitemap_pdf.xml

Adds RAD PAC FAQs PDF to guidance search sitemap (lines 225-228)
- Resolves #4053 
Adds the RAD PAC FAQ PDF - https://www.fec.gov/resources/cms-content/documents/RAD_FAQs-PACs_EO13892.pdf to the xml sitemap for the PDFs in guidance search database.

Adds RAD PAC FAQs to guidance search

---

fec/fec/static/js/pages/datatable-communication-costs.js

- Resolves #3963 
_Looks like I only needed to change the communication costs datatable page itself. All the others were already referencing the correct `/communication_costs/` endpoint._
-  Communication costs datatable: http://localhost:8000/data/communication-costs/
branch | PR
feature/4591-update-deprecation-notice | [link](https://github.com/fecgov/openFEC/pull/4594)
- go to communication-costs datatable page and check the xhr to see that the endpoint path is now using `/communication_costs/`
____

update xhr of communication-costs to communication_costs

---

requirements.txt

- Resolves #4027 
Upgrades Django from 2.2.13 to 2.2.16 to address Snyk vulnerabilities [609368](https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-609368) and [609369](https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-609369)
The entire site, but also only the requirements file and running the site generally.
No related PRs
- `cd fec`, `./manage.py runserver`
Site should run normally, Snyk should not find vulnerabilities [609368](https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-609368) or [609369](https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-609369)
____

4027 Upgrade Django from 2.2.13 to 2.2.16

---

fec/fec/middleware.py

- Resolves #4084 
@jason-upchurch found an issue with our csp on localhost. This adds our domains to our CSP. Good catch!
Targeting the next release.
Every data call should fail without this.
None
None
- Pull and build like normal
- 127.0.0.1:8000 datatable pages should work again
____

Include self in connect-src

---

fec/data/templates/layouts/main.jinja
fec/data/templates/layouts/widgets.jinja
fec/data/templates/partials/google-tag-manager-noscript.jinja
fec/data/templates/partials/google-tag-manager-script.jinja
fec/fec/templates/500-status.html
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/fec/templates/partials/google-tag-manager-noscript.html
fec/fec/templates/partials/google-tag-manager-script.html

- Resolves #4083 
- Consolidated the GTM code to a few external files rather than update code site-wide.
- Updated GTM code to use the various environments of our main GTM container rather than rely on separate containers.
Source code of every page
None
- Having other eyes is always good, but feel free to add or remove yourself
- pull and build branch like normal
- Check each page's source, being sure to include a the homepage, a Wagtail page, a data page, a legal page, and a widget
- Check with GTM turned on
- and with GTM turned off
- If `echo $FEC_FEATURE_USE_TAG_MANAGER` tells you `true`, you should see entries for GTM in every page's source code; if not, no page on the site should have 'gtm' in the source code.
- To turn on GTM, use …

Consolidate GTM code, update to use environments

---

fec/fec/static/js/modules/home-events.js

- Resolves #4139 
_This ensures that general FEC deadlines show up on the homepage first. Otherwise, just show the dates like normal._
-  Homepage calendar events
- Check the homepage to make sure that the 10/22 event of "12G Pre-Election Report Due" shows up first
**Test a different date after 10/22**
- Try changing the `min_start_date` to a future date past the 10/22 report due date, such as '2020-10-23'. 
- `npm run build-js` again
- Check the homepage and the next report due on the homepage should display "GA 05 Special Post-General Report due"
____

[HOTFIX - MERGE WITH GITFLOW] Fix homepage event priority

---

.circleci/config.yml
README.md
tasks.py

Resolves #4135
**Deploy task changes:**
- With cf cli version 7, `cf api <endpoint>` logs you out - this is a known issue: https://github.com/cloudfoundry/cli/issues/2075. Only set the endpoint if `deploy` task `--login True` (used for CircleCI)
- Cf cli doesn't exit with code 0 anymore, so I had to add it. (not sure where this is documented but you can read between the lines here: https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute)
**Other minor changes**
- Specify version in README because it's specified for other repose - the `--command` change to `cf run-task` is backwards incompatible
-  Deploys
- Example build: https://app.circleci.com/pipelines/github/fecgov/fec-cms/674/workflows/303ee8ad-6ec …

Update cf cli to version 7

---

fec/data/templates/partials/browse-data/historical.jinja

We need to update the button "Find statistics" on the Campaign finance statistics browse data page to the newly created landing page with the 10/26/20 release.
- Resolves #4131
modified:   data/templates/partials/browse-data/historical.jinja
#4132
#4088

[Before release] Change link to new summary tables landing

---

fec/fec/templates/partials/navigation/nav-legal.html

Changes the link for the policy page to point to the new page at https://www.fec.gov/legal-resources/policy-other-guidance/
Related to work at #4115 
Navigation menu for legal resources
branch | PR
Update links on guidance search page | [link](https://github.com/fecgov/fec-cms/pull/4145)
Link to Policy and other guidance should point to https://www.fec.gov/legal-resources/policy-other-guidance/

Updates link to the policy page

---

fec/home/templates/home/legal/legal_resources_landing.html
fec/search/templates/search/policy_guidance_search_page.html

Part of #4115  - Updates the links in the introductory text to point to the newly migrated policy page.
branch | PR
Updates legal resources drop down menu | [link](https://github.com/fecgov/fec-cms/pull/4147)
Guidance Search intro text:
Make sure the link to the policy statements points to https://www.fec.gov/legal-resources/policy-other-guidance/#policy-statements and the link to the interpretive rules points to https://www.fec.gov/legal-resources/policy-other-guidance/#interpretive-rules
Legal resources landing page:
Make sure box for policy points to https://www.fec.gov/legal-resources/policy-other-guidance/
Make sure contribution limits link under "You might also like" points to …

Updates links to policy and other guidance page

---

requirements.txt

- Resolves #4106 
-  requests library
1. checkout develop branch
1. from fec-cms project root, ensure `develop` branch requirements.txt are installed
1. `snyk test --file=requirements.txt` (you should see the vulnerability listed, if not, let's discuss)
1. checkout this PR
1. from fec-cms project root, ensure PR branch requirements.txt are installed
1. `snyk test --file=requirements.txt` (the vulnerability should not longer be listed)
1. pytest
1. I did a manual deploy of this branch to dev space and it build successfully. I verified a few datatable returns. Please feel free to deploy and test further.
1. While testing, I saw the build give some warnings that also exist in `develop` (note the 404s):
```
HeadlessChrome …
```

Update requests library to resolve security vulnerability in urllib3

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
tasks.py

- Partial resolution for https://github.com/fecgov/fec-accounts/issues/316
- Add internal routes to CMS
- Add network policy to build script - should fail if the proxy isn't created
-  Routes - will allow proxy to connect to these internally
- At least two reviewers, please
Test the "happy path":
- Do a deploy to `dev` (please don't commit to this branch) and make sure CMS still works
- Check out routes with `cf app cms` and see the two routes, internal and external
- Make sure the proxy can connect by manually deploying https://github.com/fecgov/fec-proxy/pull/187 (https://github.com/fecgov/fec-proxy#deployment) and going to dev.fec.gov
- Make sure you can't access fec-dev-cms.apps.internal
Test a failed build:
- Delete …

Add internal route to CMS, add network policy to deploy script

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

Partial resolution for https://github.com/fecgov/fec-accounts/issues/318
- Merge after https://github.com/fecgov/fec-proxy-redirect/pull/1
- Remove public app URLs - after https://github.com/fecgov/fec-proxy/pull/194 the proxy connects through internal `apps.internal` route
- Note that we'll need to manually remove the routes after deployment due to the [additive-only](https://github.com/cloudfoundry/cloud_controller_ng/issues/1866) nature of deploying with manifests. Example: `cf unmap-route cms app.cloud.gov --hostname fec-dev-cms`
-  Routes
See https://github.com/fecgov/fec-epics/issues/191 for all related work
- Manually deploy this branch
- (Assuming https://github.com/fecgov/fec-proxy-redirect/pull/1 has been …

Remove public app URLs

---

package-lock.json
package.json

- Resolves #4105 
_Upgrade datatables.net to v1.10.22 to fix vulnerability._
-  Any page that loads datatables
- `npm install`
- Test out a couple of pages that loads datatables and make sure it still works.
____

Upgrade datatables.net to v1.10.22

---

fec/fec/templates/partials/footer-navigation.html

- Resolves #4154 
New link in the site footer: our site status page
Every page, but a simple addition to the footer menu
- Design/UX
- Front-end
- Content (via screenshots, then dev later)
Feel free to add/remove individuals
Wider views
Narrow views
None
- Pull the branch like normal
- Check any page on [localhost](http:127.0.0.1:8000/) to make sure the link is in the footer 
- Click the status link to make sure it directs accordingly.
- Since it's technically taking users to a different site, should we open in a new tab?
- I added "site" to the link but can easily change it. If it's on fec.gov, why not simply "Site status"? "FEC status" seemed to imply status of the agency instead of only the site(s)/tools (e.g. could "FEC status" be "evacuation order/maximum …

4154 Add site status link to footer menu

---

fec/data/views.py

- Resolves #4234 
_Candidate profile pages that have no committees are broken. This fix will check if there are committees, if not, then it will return the normal no results message for the candidate profile page_
Related API call from candidate profile page: https://api.open.fec.gov/v1/candidate/H2OR01240/committees/history/2022?per_page=100&election_full=True&api_key=DEMO_KEY
-  Candidate profile pages with no committees
branch | PR
feature/3896-pcc-to-pac-from-api | [link](https://github.com/fecgov/fec-cms/pull/4193)
- Check any candidate that has no committees linked yet. Examples: http://localhost:8000/data/candidate/H2OR01240/ and http://localhost:8000/data/candidate/S6CA00808/. Make sure the page loads.
- …

Fix candidate profile pages that have no committees

---

fec/data/views.py

Resolves #4221 
- Use `load_first_row_data` instead of `get_candidate` for sponsor candidate information so we can fall back to the most recent cycle and not user-provided cycle (or 2020 when not specified). Also, `get_candidate` does a lot of things that aren't needed here. https://github.com/fecgov/fec-cms/commit/5ff4f77c5ec95cd06f873454e59b36d0b5276d32
- Since `get_candidate` and `get_committee` use the same `load_first_row_data ` functionality to get the most recent candidate information, move it to its own function with a friendlier name https://github.com/fecgov/fec-cms/commit/1858730c3561cc9b61ba7c79673c2db3abeb3db0
- Minor reformatting, don't reuse `filters` for different endpoints/purposes in `get_candidate` https://github.com/fecgov/fec-cms/commit/efdad06124177e4aadd7e78443327d7f …

Fix committee profile page 404

---

fec/data/views.py

Resolves #4221: Fix committee profile page 404 when sponsor candidate didn't run in the election year that's selected for the committee 
- Use `load_first_row_data` instead of `get_candidate` for sponsor candidate information so we can fall back to the most recent cycle and not user-provided cycle (or 2020 when not specified). Also, `get_candidate` does a lot of things that aren't needed here. https://github.com/fecgov/fec-cms/commit/5ff4f77c5ec95cd06f873454e59b36d0b5276d32
- Since `get_candidate` and `get_committee` use the same `load_first_row_data ` functionality to get the most recent candidate information, move it to its own function with a friendlier name https://github.com/fecgov/fec-cms/commit/1858730c3561cc9b61ba7c79673c2db3abeb3db0
- Minor reformatting, don't reuse `filters` for …

[MERGE WITH GIT FLOW][HOTFIX] Fix committee 404

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/committees-filter.jinja

- Resolves #4061 
_Add Leadership PAC sponsor filter only to committees datatable._
- Committees datatable - http://www.fec.gov/data/committees/
- Go to the committees datatable: http://localhost:8000/data/committees/
- Make sure that the Leadership PAC sponsor filter is present in the filter sets
- Try searching a sponsor name. Ex: Peters, Gary. You should see an autosuggest pop up, select the name from the autosuggest and the datatable should filter. You can grab a list of additional sponsor names to test from [this CSV from our website](http://www.fec.gov/files/bulk-downloads/2020/leadership2020.csv).
- Add additional sponsor names to filter additional sponsor …

Add leadership PAC sponsor filter to committees datatable

---

requirements.txt

- Resolves #4231 
_Upgraded lxml to v4.6.2. Also moved to dev dependencies since we don't need this other than for local scraping._
- fec-cms/fec/search/management/commands/scrape_cms_pages.py
- fec-cms/fec/search/management/commands/scrape_transition_pages.py
- fec-cms/fec/search/management/commands/scrape_web_app_pages.py
- fec-cms/fec/search/utils/search_indexing.py
- Try performing scraping on your local by running the following commands one by one:
- `fec/manage.py scrape_cms_pages` (when done, check the  fec-cms/fec/search/management/data/output.json to see if it wrote ok)
- `fec/manage.py scrape_web_app_pages` (when done, check the  fec-cms/fec/search/management/data/output.json to see if it wrote ok)
- `fec/manage.py …

upgrade lxml and move to dev dependencies

---

requirements.txt

- Resolves #4282
[PyJWT](https://pypi.org/project/PyJWT/2.0.0/#history) package had a major breaking change for our Wagtail authentication `cg-django-uaa`. We need to pin at PyJWT v1.7.1 for now.
-  Wagtail authentication
- `pip freeze`
- Check the version of PyJWT is now v1.7.1
- Temporarily deploy a new branch to dev and check login
- Try logging into Wagtail on dev, it should now work
____

[MERGE WITH GITFLOW] Pin PyJWT to v1.7.1

---

fec/fec/middleware.py

- Resolves #4281 
_Adds headers in the CMS admin console so that it is not cached._
-  Wagtail admin
____

[MERGE WITH GITFLOW - HOTFIX] Do not cache CMS admin

---

package-lock.json
package.json

- Resolves #4105 
_Upgrade datatables.net to v 1.10.23._
-  Datatables pages
branch | PR
feature/4105-upgrade-datatables | [link](https://github.com/fecgov/fec-cms/pull/4209)
- `npm install`
- Test out a couple of pages that loads datatables and make sure it still works.
____

upgrade datatables.net to v1.10.23

---

fec/fec/static/js/pages/statistical-summary.js

Make latest available tables based on most recent existing year instead of  "this year" (`today.getFullYear();`)
modified:   fec/static/js/pages/statistical-summary.js
https://github.com/fecgov/fec-cms/pull/4088
I verified this works based onm screenshot above, but if you want to test:
- checkout branch
- make a page in Wagtail based on this page, or edit it locally if you have it on your local already.
https://www.fec.gov/campaign-finance-data/congressional-candidate-data-summary-tables/?year=2020&segment=21
- In Wagtail, change selected attribute of the year-select to 21 or 24 month
- Make sure everything after the period you chose is disabled (just for the 2020)
- Add 2021-2022 Select to year-selects on Wagtail and do the same as above to make sure those would be …

latest available based on selected, not on this year

---

package.json

- Resolves #4266 
Removing ua-parser-js from our package.json file because of its redundancy—package pins it to the same version required by fbjs. (This won't alleviate the Snyk alert)
Should be no change, to the build, behavior, or appearance.
None
None
- Pull the branch like normal
- `npm i`
- The build, tests, and site functionality should be unchanged, particularly
- anything interactive (because it's a JavaScript change)
- typeaheads (because fields are concerned)
- Wagtail admin fields (because ua-parser-js is used by draft-js, our Wagtail editor(s))
____

4266 Removing ua-parser-js from package

---

fec/fec/settings/base.py
fec/fec/static/js/modules/calendar-helpers.js
fec/fec/templates/base.html
fec/fec/tests/js/calendar.js
fec/fec/tests/js/setup.js

Resolves https://github.com/fecgov/fec-accounts/issues/350. Related issue: https://github.com/fecgov/openFEC/issues/1532. 
- Add optional `API_KEY_PUBLIC_CALENDAR` setting, which allows us to separate restrictions for the calendar and the rest of the site.
- If unset, the application will use the `API_KEY_PUBLIC` environment variable, which is the current behavior (so we don't have to create new keys for dev/stage/feature)
-  Calendar subscriptions: http://127.0.0.1:8000/calendar/
One reviewer requested, others appreciated
- Make sure you have `FEC_WEB_API_KEY_PUBLIC` set locally
- Go to http://127.0.0.1:8000/calendar/
- Subscribe to any of the three calendar options
- Hover over the links, see the API key used is …

Add optional `API_KEY_PUBLIC_CALENDAR` setting

---

fec/data/jinja2.py
fec/home/templates/home/meeting_page.html
fec/home/templates/partials/jobs.html

Resolves https://github.com/fecgov/fec-accounts/issues/340
Setting Jinja's autoescape to True and changing two instances to use the `safe` filter instead of bypassing autoescape
autoescape was already True but we want to explicitly set it. The meeting page and jobs templates each had one place where we were turning off autoescape; we've changed those to use the `safe` filter instead
Could affect any part of the site where we're processing content with Jinja—every Jinja template or component, including *.jinja and *.html
None
None
- pull the branch like normal
-`npm i`, `npm run build` just in case? Should have zero effect
- `pip install -r requirements.txt` just in case? Likely have zero effect
- Make sure the blog/Wagtail parts of the site behave correctly, …

Jinja autoescape

---

fec/data/templates/candidates-single.jinja
fec/data/templates/partials/candidate/about-candidate.jinja

In candidate profile page, under About this candidate section, display committees information only when cmte_dsgn is of type P, A or J. 
- Resolves #4303
Display  candidate affiliated committee only when the committee designation is of type P, A or J. 
1. candidates-single.jinja 
2. about-candidate.jinja
Candidate profile page/ About this candidate section
- checkout `feature/4303-cand-profile-without-cmte`
- point local cms to `dev` api : `export  FEC_API_URL=https://fec-dev-api.app.cloud.gov` 
- start server  : `./manage.py runserver`
- copy & paste url in a browser :  `http://localhost:8000/data/candidate/P00010298/?tab=about-candidate`
- verify that under About the candidate section, committee heading shouldnt appear 
- test another …

Display committee section only when cmte_dsgn is of type P, A or J.

---

fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/tests/test_candidate.py
fec/data/views.py
fec/fec/static/scss/components/_glossary.scss

Add leadership PACs to the committees section in 'about this candidate' page
- Resolves #4270
about this candidat section in Candidate Profile page
1)Add leadership PAC to committees section
2)Add Glossary links to each of the committee subheaders
1)checkout branch
npm run build
2)run tests:
pytest
./manage.py test data.tests
3)compare some examples with prod
(1)P00009092 / 2020  (only have one dsgn=P committee)
http://127.0.0.1:8000/data/candidate/P00009092/?tab=about-candidate
https://www.fec.gov/data/candidate/P00009092/?tab=about-candidate
(2)S4AR00103 /2020 (has P, A, 2J and two leadership pac committees)
http://127.0.0.1:8000/data/candidate/S4AR00103/?tab=about-candidate&cycle=2020&election_full=tru …

Add leadership PACs to about this candidate section of candidate profile pages

---

fec/fec/settings/base.py
fec/fec/static/js/modules/calendar-helpers.js
fec/fec/static/js/modules/calendar.js
fec/fec/static/js/pages/calendar-page.js
fec/fec/static/js/templates/calendar/subscribe.hbs
fec/fec/tests/js/calendar.js

Use `FEC_API_KEY_PUBLIC_CALENDAR` for Calendar subscriptions and use `FEC_API_KEY_PUBLIC` for homepage Event and deadlines links and Calendar filters. 
- Resolves https://github.com/fecgov/fec-accounts/issues/354
modified:  fec/fec/static/js/modules/calendar-helpers.js
modified:  fec/fec/static/js/modules/calendar.js
modified:  fec/fec/static/js/pages/calendar-page.js
modified:  fec/fec/static/js/templates/calendar/subscribe.hbs
modified:  fec/fec/tests/js/calendar.js
checkout feature/345-use-calendar-key-for-subscriptions-only
`npm run build`
`export FEC_WEB_API_KEY_PUBLIC=12345`
`export FEC_WEB_API_KEY_PUBLIC_CALENDAR=67890`
runserver
Check that the links in subscribe dropdown have  `api_key=67890`
Check in network tab that changes to filters register an api call using `api_key=12345` …

Use public calendar key for subscriptions only

---

fec/data/templates/partials/committee/about-committee.jinja
fec/data/views.py

Currently, we only show Leadership PAC sponsor name string on about-committee section in committee profile page and don't have the link to candidate profile page.
ex: https://www.fec.gov/data/committee/C00326439/?cycle=2022&tab=about-committee
after this PR, we change sponsor name to name card and link to candidate profile page.
- Resolves #4361
1) get sponsor_candidates list from get_committees function in view.py, send to front-end. 
2) modify about-committee.jinja, the sponsor_candidate info will be displayed by the way of name card.
data/view.py
about-committee.jinja
2) point any api
3) pytest
4) ./manage.py runserver …

Add sponsor link in committee profile

---

fec/data/constants.py

- Resolves #4378: Add 2022 to datatables
-  Datatables (http://localhost:8000/data/browse-data/) such as receipts, filings, reports, candidates
- Datatables (http://localhost:8000/data/browse-data/) such as receipts, filings, reports, candidates
- Make sure 2022 is an option

[MERGE WITH GIT FLOW] [HOTFIX] Add 2021 and 2022 option to datatables

---

fec/fec/templates/partials/navigation/nav-about.html
fec/fec/templates/partials/navigation/nav-data.html
fec/fec/templates/partials/navigation/nav-help.html
fec/fec/templates/partials/navigation/nav-legal.html
fec/fec/templates/partials/navigation/navigation.html

- Resolves #3887 
Adding trailing slashes to header nav menu links
Site-wide header nav
None
- `npm i`
- Check [localhost](http://127.0.0.1:8000) header navs to make sure all links still work. Specifically:
- Campaign finance data **†**
- All data
- Raising
- Spending
- Loans and debts
- Filings and reports
- Candidates
- Committees
- Bulk data
- Find elections. Search by state or ZIP code
- Look up contributions from specific individuals
- Help for Candidates and Committees (this link itself wasn't changed)
- Guides
- Forms
- Dates and deadlines
- Legal resources **†**
- All legal resources
- Advisory opinions
- Enforcement
- Statutes
- Legislation
- Regulations
- Court cases
- About **†**
- News and …

3887 Add trailing slashes to header nav

---

fec/data/views.py
fec/home/templates/home/home_page.html
fec/home/templates/partials/oig-most-recent.html
fec/home/templatetags/top_entities.py

- Resolves #4418 
Updated the default office for the homepage fundraising chart (top entities) and Raising and Spending by the numbers
Squeezed in a fix for the Most Recent Reports links on the OIG landing page
None
- `npm i` (just in case)
- `npm run build` (just in case)
- Check the [homepage Who's raising the most](http://127.0.0.1:8000). Default office should be Senate
- Click 'Browse top raising candidates' 
- [Raising by the numbers](http://127.0.0.1:8000/data/raising-bythenumbers/) Aggregate totals and Who's raising the most should default to Senate races
- Same with [Spending by the numbers](http://127.0.0.1:8000/data/spending-bythenumbers/)
**DO NOT MERGE — HOTFIX**
____

[HOT FIX - DON'T MERGE!] Updating chart offices to default to S

---

package-lock.json
package.json

- Resolves #4390 
Bumped the version of lodash from 4.17.20 to 4.17.21, just a patch-level change
None
None
- pull branch
- `npm i`
- while Lodash could be used anywhere, `npm ls lodash` is telling me that only devDependencies are using it
- `npm run build` should work fine
- `npm run build-js` and `npm run build-sass` are both included with `npm run build` but they should work independently, too
- `npm run test-single` should run without errors
____

4390 bump lodash from 4.17.20 to 4.17.21

---

fec/fec/static/js/pages/datatable-audit.js

- Resolves #4302 
- Update Audit Reports to title casing 
- Title of the Audits data table
- Audits data table before:
- Audits data table after:
_This might include:_
https://github.community/t/checkout-a-branch-from-a-fork/276/2
- links to sample pages to test
- https://127.0.0.1:8000/legal-resources/enforcement/audit-search/
- Any local environmental setup that is unusual (env vars, API version to point to, etc)
____

Change Audit Reports to title case in data table only

---

fec/home/templatetags/filters.py

- Resolves https://github.com/fecgov/fec-accounts/issues/342
Replace `mark_safe` with `format_html`
Replace `mark_safe` with `format_html` which has string escaping
https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.html.format_html
`format_html` is similar to `str.format()`, except that it is appropriate for building up HTML fragments. All args and kwargs are passed through `conditional_escape()` before being passed to `str.format()`.
>So, instead of writing:
```python
mark_safe("%s <b>%s</b> %s" % (
some_html,
escape(some_text),
escape(some_other_text),
))
```
>You should instead use:
```python
format_html("{} <b>{}</b> {}",
mark_safe(some_html),
some_text,
some_other_text,
)
```
**Test functionality**
- Set env vars needed for searches:
`export FEC_DIGITALGOV_KEY="<get from …

Replace 'mark_safe' with 'format_html'

---

fec/fec/templates/home_base.html

- Resolves #4462 
Closing an include
Homepage
No real visual changes, apart from the homepage isn't an error message if this works
None
- If the [homepage](http://127.0.0.1:8000) isn't an error message, 🎉
____

Add apostrophe

---

fec/data/templates/layouts/main.jinja
fec/fec/static/js/modules/dropdowns.js
fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/modules/site-nav.js
fec/fec/static/js/modules/typeahead.js
fec/fec/static/scss/components/_nav.scss
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/fec/templates/partials/navigation/navigation.html

The work for this PR was originally to address issue [4183](https://github.com/fecgov/fec-cms/issues/4183) `aria-hidden="true"] elements contain focusable descendants` on the homepage. 
Since the mobile menu and its child global search filed appear on every page of the site, I decided to combine the fixes for these into one PR. This also extended to datable search fields that use typeahead.
- Resolves #4183 - [aria-hidden="true"] elements contain focusable descendants
- Resolves #4186 -  ARIA IDs are not unique`
Also partially addressed:
#4185 [aria-*] attributes do not have valid values
[aria-*] attributes do not match their roles
[role]s do not have all required [aria-*] attributes
<hr>
1) The mobile menu failed `aria-hidden="true"] elements contain focusable descendants` …

ARIA/accessibility fixes for mobile menu and search/typeahead

---

fec/home/templatetags/filters.py
fec/home/tests/test_filters.py

Resolves #4491: Fix sitewide search when results have characters `{` and/or `}` 
- Because `format_html` uses `str.format`, remove `{` and `}` because they are special characters.
- Add test coverage
- Sitewide search
- Policy search
#4452: Replace `mark_safe `with `format_html`
- `export FEC_DIGITALGOV_KEY="<get from dev with cf env cms>"`
- `export SEARCH_GOV_POLICY_GUIDANCE_KEY="<get from dev with cf env cms>"`
**Broken on production** 
https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=Micellaneous+text+submission
https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=field+name+%2318
https://www.fec.gov/search/?query=new+form+2&type=candidates&type=committees&type=site …

[Adding to hotfix branch] Fix filter when results have `{` or `}`

---

fec/fec/templates/partials/navigation/navigation.html
fec/home/templatetags/filters.py
fec/home/tests/test_filters.py

- Resolves #4494]
- Restore `tabindex=0` to desktop menu links to make Mega Menu work in Safari. Those `tabindex` attributed  were removed as part of https://github.com/fecgov/fec-cms/pull/4456 to resolve the Lighthouse flag for `[aria-hidden="true"] elements contain focusable descendants` on `div#site-menu.site-nav__container`. This was fine in other browsers but made the menu inoperable in Safari.
- Also removed residual commented code from same file
According to the documentation for Accessible-Mega Menu [Keyboard Accessibility docs](https://github.com/noahmanger/Accessible-Mega-Menu#keyboard-accessibility), these tabindexes are necessary, however they are not in the source code on the GH repo. 
Followup work: 
modified:   fec/templates/partials/navigation/navigation.html
- checkout …

[MERGE WITH GITFLOW] Fix Safari bug with desktop-size menu

---

fec/fec/templates/home_base.html
fec/home/views.py

- Resolves #4349
- Resolves #4473
Change open meeting query to include only open meetings and also to exclude those Hearings pages made using meeting type 'O' (open meeting) by excluding by existence of 'hearing' (case insensitive) in title. 
Limit open meetings free text search to only open meetings
modified:   home/views.py
- checkout and run `feature/4349/exclude-hearings-from-open-mtg-tab`
- Make sure no hearings show up in Open meetings tab
- Make sure Hearings pages made with with incorrect meeting  type of 'O', like September 14, 2017 audit hearing,  don't show up in Open meeings tab
- Search for Oklahoma democratic party in open meetings tab and confirm results contain those keywords
- **Note:** in rare instances, Imported html for meetings before May 2017 may have commented-out …

Exclude hearings from open mtg tab/fix open mtg search

---

fec/data/views.py
fec/legal/templates/legal-archived-mur.jinja
fec/legal/templates/legal-current-mur.jinja

TERMINATED/ACTIVE indicator shows wrong when no cycle passed on committee profile page.
ex:  C00409011
https://www.fec.gov/data/committee/C00409011/
shows `TERMINATED`.
It should be `ACTIVE` in 2005-2006 (the last financial cycle)
- Resolves [#4448](https://github.com/fecgov/fec-cms/issues/4448rl)
data/views.py
2) point to any api
3) ./manage.py test
pytest
4) test committee profile page (compare with prod)
(1)C00409011
(local) http://127.0.0.1:8000/data/committee/C00409011/
(prod) https://www.fec.gov/data/committee/C00409011/
(2) C00580100 (active committee)should no change
(local) http://127.0.0.1:8000/data/committee/C00580100/
(prod) …

Fix committee terminated bug on committee profile page

---

fec/data/tests/test_committee.py

- Resolves #4488 
This adds a little bit more test coverage for the changes in #4366. It will fail if run on `develop` but passes since I rebased off that branch.
@fec-jli 
-  Test coverage
https://github.com/fecgov/fec-cms/pull/3299: Fix committee summary page with wrong form or cmte_type
Run pytest

Add more fallback cycle test coverage

---

fec/fec/static/js/data/terms.json

Added "administrative termination" to the glossary
Please make sure the end result looks like this:
**Administrative termination** - Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S.C. 30103(d)(2) and 11 CFR 102.4. Administrative termination does not relieve a committee of any legal responsibility for the payment of any outstanding debt or obligations. 
And the links for the statute and regs works too. Thank you.

Added Administrative termination to the glossary

---

package-lock.json
package.json

Resolves #4392
Upgrading ua-parser-js to satisfy the vulnerability warning
front-end
Potentially draft-js and backend editing but likely none. It was a patch-level increase of a dependency of a dependency (draftjs > fbjs > ua). Rather than edit package-lock, we're adding ua-parser-js to package, which gets inherited/deduped for fbjs' `^0.7.18` requirement. (I looked at upgrading `fbjs`, too. 2.0.0 is the only 2.x release)
None
None
- pull branch
- `npm i`
- scan package.json
- check that the warning about ua-parser-js has gone away
- check that site admin/management works as expected

Upgrade ua-parser-js

---

fec/data/tests/test_committee.py
fec/data/views.py
fec/fec/static/js/pages/committee-single.js

Customers should be able to view all reports and statements before 4/15.
When passed cycle is out of cycles_has_activity array, set cycle = last_cycle_has_activity
- Resolves #4366 
- Ref ticket: add test coverage [https://github.com/fecgov/fec-cms/issues/4488](https://github.com/fecgov/fec-cms/issues/4488)
one cms front-end developer
one cms back-end developer
* checkout branch
* point to any api
* run `npm run build`
* run `./manage.py test` and `npm run test-single`
* compare local test urls with production, make sure you can display the `Filings` data locally.
example urls:
1)https://www.fec.gov/data/committee/C00728238/?cycle=2022&tab=filings
http://127.0.0.1:8000/data/committee/C00728238/?cycle=2022&tab=filings …

Fix unable view 2020 filings

---

fec/data/templates/committees-single.jinja
fec/data/views.py

- Resolves #4465 
Adds administratively terminated to the committee profile page if they were administratively terminated.
One designer and one developer
- Committee profile pages
branch | PR
feature/add_active_cmte_indicator | [link](https://github.com/fecgov/fec-cms/pull/3781)
- Go to any committee that is active and make sure that the committee status in the header reads "Active". Ex: [http://localhost:8000/data/committee/C00409011/?cycle=2006](http://localhost:8000/data/committee/C00409011/?cycle=2006) 
- Go to any committee that is terminated and make sure that the committee status in the header reads "Terminated". Ex: …

add administratively terminated committee status

---

fec/fec/settings/base.py
fec/fec/static/scss/components/_responsive-object.scss

Legacy support for Wagtails built-in responsive embeds in Draftail Rich Text Editor
- Resolves comment on Wagtail upgrade issue https://github.com/fecgov/fec-cms/pull/4518/files#r605231989
--AND -- 
- Resolves #2212
**Note/Possible followup work:** This issue originally stemmed from content teams desire not to have tiny videos on the page and not to have the "black-boxing" on either side of the video when using the embed option. They are now 100% width of the content area. If content team decides this is too big, we can make an adjustment to the CSS and set a max-width on the videos. 
modified:   fec/settings/base.py
modified:   fec/static/scss/components/_responsive-object.scss
**General components of the application that this PR will affect:**
Use of th media embed button in the …

Legacy support for responsive embeds in Wagtail Draftail RTE

---

package-lock.json
package.json

- Resolves #4523 
Addressing a vulnerability in underscore
- front-end
Nearly all of the interactive parts of the site built after '18, though, being a minor and patch upgrade, likely none.
None
- `npm i` (no errors)
- `npm run build` (no errors)
- `npm run test-single` (no failures)
- Check the interactive parts of the site to make sure race/district search, site search, and filters/chiclets all still work. A couple places where underscore is used:
- LegalSearch
- Tags (legal)
- analytics
- calendar
- column-helpers
- columns
- cycle-select
- download
- election-form
- election-map
- election-search
- election-utils
- feedback
- filters-events
- fips (maps data)
- helpers
- line-chart-committees
- maps
- other-spending-totals …

Up-grade under-score

---

fec/fec/static/scss/_fonts.scss
fec/home/templates/blocks/section.html
package-lock.json
package.json

- Resolves # (none?) Not sure if I should create a ticket for such a small fix when its branch has already been merged
Fixing the section.html template to close one div and close another a little earlier.
There was also a patch released for draftail so bumping that by its patch number.
1-2
The only changes are inside the section.html template/component that's only used by the ResourceBlock
broken:
correct:
The previous PR for this upgrade work: https://github.com/fecgov/fec-cms/pull/4518
- pull the branch, run the server
- go to [dates and deadlines](http://127.0.0.1:8000/help-candidates-and-committees/dates-and-deadlines/) or other Resource types of pages
- make sure the columns align like they do in Production

Close resourceblock section divs, patch draftail

---

fec/fec/static/scss/_fonts.scss

- Resolves #4173 
Optimizing out site, let's let our content swap from default fonts to our requested fonts
1-2 people, likely either front-end or ux
Ideally, only the fonts on the initial load of any page on the site on a slow connection should be affected. If there's no change, great. This PR will let the content display before fonts have finished loading and will then swap over to use our fonts when they're available.
None
**Warning**: This branch is based on the latest version of develop, which has the newest Wagtail and Django. Switching to this branch should be fine (but takes a couple extra steps), but switching back to older branches that aren't using the newest Wagtail/Django/etc could be challenging. You may want to make a backup of your current database so you …

4173 - Set font faces to swap

---

fec/fec/static/js/templates/top-entity-row.hbs
fec/home/templates/partials/raising-spending.html

**ARIA error:**
**Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children**
-  **Fix:** Add `aria-role="gridcell"`  to raising/spending table elements. [Reference](https://www.w3.org/TR/wai-aria-1.1/#gridcell)
**ARIA error:**
**[aria-*] attributes do not have valid values**
- **Fix:** Change to `aria-controls="top-table` for the tableSwitcher widget on the home page raising/spending chart
**Additional changes:** Remove unnecessary code from raising/spending partial used on home page. 
- Resolves #4184
- Resolves #4185 
Requires one front end reviewer
modified:   fec/static/js/templates/top-entity-row.hbs
modified:   home/templates/partials/raising-spending.html
General components of the application that this PR …

ARIA roles for children and controls

---

fec/data/constants.py

- Resolves #4280 
Updating default (non-presidential) election year to 2022.
**NOTE**: also:
- updated `END_YEAR` from 2022 to 2024
- updated the note for `DEFAULT_TIME_PERIOD`
- should we add a note / ticket for when we should change `DEFAULT_PRESIDENTIAL_YEAR`?
Two of UX, front-end, back-end
Any table/component that looks at the default election years for its data
Defaults that can be non-presidential
Defaults that have to be presidential:
None
- pull the branch like normal
- `pip install -r requirements.txt` if needed (likely not)
- `npm i` if needed
- Check a handful of pages where we have default dates that should default to 2022. Some I know:
- [homepage](http://127.0.0.1:8000) (map, raising/spending chart(s))
- [Raising by the …

4280 - Update default year

---

package-lock.json
package.json

- Resolves #4572 
underscore 1.12.1 is breaking [some datatables](http://127.0.0.1:8000/data/committee/C00703975/?tab=filings&cycle=2020)
A couple
Downgrading underscore—should take all underscore-related functionality back to previously-working version
Broken on left, working on the right
None
- pull branch
- `npm i`
- Test!

[MERGE WITH GITFLOW - HOTFIX] Downgrade underscore to 1.9.2

---

fec/fec/static/js/modules/column-helpers.js
fec/fec/static/js/modules/filters/filter-tags.js
fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/modules/filters/text-filter.js
fec/fec/static/js/modules/maps.js
fec/fec/static/js/pages/committee-single.js
package-lock.json
package.json

- Resolves # 
With the recent complications with underscore and templates, let's upgrade our template functionality from underscore and to standard ES6
Front-end, 
Tags, typeaheads, and their tests, site-wide
No changes
None
- `npm i`
- `npm run build-js` (or `npm run build`)
- check various filters and typeaheads across the site

Convert _.template to ES6

---

fec/data/templates/partials/meta-tags.jinja
fec/fec/templates/partials/meta-tags.html

- Resolves #4188 
Lighthouse gave us accessibility guidance that our maximum-scale was 1 and should be 5+. So I changed it to 5. This should let mobile users zoom into our pages (up to 5x)
A couple who can review front-end usage (not code, but usage).
Will affect every page of the site, though likely only for mobile.
No visible changes, but look at this:
None
- Make sure pages load normally and don't look too zoomed (in or out)
**Will need to check on a mobile device from feature, dev, and/or stage**
Make sure pages:
- load at the right size
- can scale/zoom/unpinch,
- pinch back down to 100% device width (if they go smaller, they should relax back to 100%)

4188 Change maximum-scale to 5

---

requirements.txt

- Resolves #4562 
Upgrading Wagtail from 2.11.6 to 2.11.7 to address a [security concern](https://snyk.io/vuln/SNYK-PYTHON-WAGTAIL-1252240). [Release notes](https://docs.wagtail.io/en/stable/releases/2.11.7.html) say the .6 > .7 is only to fix this vulnerability.
The updated code is in the admin section and now forces that URLs use a valid protocol (e.g., `http://`, `https://`, `ftp://`)
Two (feel free to adjust the list)
Maybe all of Wagtail, but likely nothing
None
- `npm i` and `npm run build` just in case
- Make sure [localhost](http://127.0.0.1:8000) works as expected
- Make sure the admin tools work as expected, particularly saving rich text fields with URLs and URL fields

4562 SNYK - Upgrade Wagtail

---

fec/fec/static/js/init.js

- Resolves #4610
- Remove any content that comes after the read more link
one content reviewer
modified:   fec/static/js/init.js
**Content team:**
This is deployed to feature https://fec-feature-proxy.app.cloud.gov/updates/
-  Confirm that there is no content after the Read more links on https://fec-feature-proxy.app.cloud.gov/updates/ 
(To see broken behavior, see screenshots in issue or view on production, Pages 1 and 2 of /updates have example of the issue on prod)
**Developers:**
- checkout `feature/4610-fix-read-more-links`
-  Confirm that there is no content after the Read more links on http://127.0.0.1:8000/updates/ 
(To see broken behavior, see screenshots in issue or view on production)

Feature/4610 fix read-more links

---

fec/fec/static/js/modules/column-helpers.js
fec/fec/tests/js/column-helpers.js

- Resolves #4625 
The `results` in the stateColumns function is an object type. When `_.map()` was replaced with jquery `.map()`, jquery could not handle it because it was expecting an array for it's function and not just an object. So we needed to transform the results object to an array so that it could be handled in the jquery map.
1 front end
-  Election profile page contributor state datatable
branch | PR
feature/remove-underscore-templating | [link](https://github.com/fecgov/fec-cms/pull/4574)
- Go to any election profile page individual contributions datatable section, ex: http://localhost:8000/data/elections/president/2024/#individual-contributions.
- Click on …

[HOTFIX - MERGE WITH GITFLOW] Fix election profile page contributor state datatable

---

fec/data/templates/widgets/pres-finance-map.jinja
fec/fec/static/js/data/terms.json

Takes out hyphens in cash on hand in two different entries (cash on hand and ending cash on hand).
And also in Net outstanding campaign obligations
And also in the presidential map.

Removes hyphens in cash on hand

---

fec/legal/templates/legal-search-results.jinja

- Resolves #4568 
Fixes the bug using global legal resources search on the legal resources landing page (seen below) by distinguishing the results link based on type by adding the category variable to the results link and adding the underscore replace filter. 
Following the results link below, for any resource type, will take you to MURs. 
-  The global legal resources search datatable on the legal resources landing page
Before:
After:
- links to sample pages to test:
http://127.0.0.1:8000/data/legal/search/?search_type=all&search=money
select "877 results"
www.fec.gov/data/legal/search/?search_type=all&search=money
select "877 results" 
Also, thanks to Laura I'm no longer using my forked copy so you don't have to checkout my …

4568 fix legal resources datatable link

---

fec/search/management/data/transition_pages.json
fec/search/management/instructions.md

- Resolves #4646 
Removed all the remaining transition links from the global search index. Updated docs for drawer name.
1 front end and 1 content
-  Global search
- Take a look at the changes and make sure there's no more links left in the `transition_pages.json`
- Look at instructions to make sure the drawer name has been updated correctly

Remove redirected transition pages from the global search index

---

requirements.txt

- Resolves #4622 
Upgrading Django to address vulnerability
A couple
The entire site, but only a couple security patch levels.
- [3.1.10](https://www.djangoproject.com/weblog/2021/may/06/security-releases/) addressed an issue with `URLValidator`.
- [3.1.11](https://docs.djangoproject.com/en/3.2/releases/3.1.11/) was for an issue with `FileField`.
None
None
- `npm run build` just in case
- check that the site's working as expected (a thorough test would include trying to break url fields with invalid/suspect characters)

4622 - Upgrade Django

---

fec/data/templates/partials/elections/election-profile-cards.jinja
fec/fec/static/scss/components/_cards.scss

- Resolves #4654 
Activate state election cards and links them on the election profile pages
1 front end and 1 UX
-  Senate and house election profile pages
- Go to each type of office (President, Senate, and House) election profile page. Ex: http://localhost:8000/data/elections/president/2020/, http://localhost:8000/data/elections/senate/CA/2022/, http://localhost:8000/data/elections/house/CA/01/2022/, 
- Check that the:

Activate state election cards on election profile pages

---

fec/data/templates/macros/disclaimer.jinja
fec/data/urls.py

- Resolves #4657 
Fix the incomplete disclaimer text at the bottom of the committee profile page disbursements datatable.
1 front end and 1 UX
- Go to any committee profile page disbursements section and click on the "Recipient name" tab. Look at the disclaimer text below the table to make sure it's complete and links correctly.

Fix disclaimer text

---

fec/data/constants.py
fec/data/templates/partials/browse-data/committees.jinja
fec/data/templates/partials/pac-party-filter.jinja
fec/data/urls.py
fec/data/views_datatables.py
fec/fec/settings/base.py
fec/fec/static/js/modules/columns.js
fec/fec/static/js/pages/datatable-pac-party.js
fec/fec/static/js/templates/pac-party.hbs

- Resolves #4651 
Create new PAC and party datatable with committee name/ID and time period filters.
**Note:** This datatable is under a feature flag. There are also filters and fields that were added prior to the API work being done. I've noted the items as `TODO` in the code, so we know where to revisit when that data is in the API.
1 UX and 1 front-end
-  PAC and party datatable
- Go to datatable: http://localhost:8000/data/committees/pac-party/. Click on the details panel to see more info.
- Go to committees browse data page to see the link to the datatable: http://localhost:8000/data/browse-data/?tab=committees

Create PAC and party datatable

---

fec/data/templates/partials/warnings.jinja
fec/fec/static/scss/components/_site-header.scss
fec/fec/templates/500-status.html
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/home/templates/sample-homepage-for-purgecss.html
package.json

- Resolves #4693 
Add IE warning banner to `home/templates/sample-homepage-for-purgecss.html` purge template and build processes so that we can ensure that these are built and tested correctly.
One front end
-  Homepage
branch | PR
feature/4648-no-longer-support-IE | [link](https://github.com/fecgov/fec-cms/pull/4649)
feature/4170-remove-unused-css | [link](https://github.com/fecgov/fec-cms/pull/4606)
- `npm i`
- `npm run build` and look at homepage to make sure IE banner does not appear unless you are in Internet Explorer.
- `npm run build-production` and look at homepage to make sure IE banner does not appear unless you are in Internet Explorer.
- After this is merged in, let's check on dev in an Internet …

Fix internet explorer homepage banner

---

fec/data/templates/partials/google-tag-manager-noscript.jinja
fec/data/templates/partials/google-tag-manager-script.jinja
fec/fec/templates/partials/google-tag-manager-noscript.html
fec/fec/templates/partials/google-tag-manager-script.html

- Resolves 
Not sure if these got out of sync or never were in sync, but GTM is using the Prod (default) settings because the string values for Dev and Stage weren't the same as are being set in base.py
1-2
Only which version of GTM is being used for Dev and for Stage.
None
- Will have to test on Dev and Stage.
- Load any page and look at its source.
- Dev should mention `_vM9qqeervv47SONwk4KRg`
- Stage should mention `ZYJODko0wNc0p1iWNPgvFw`
- Neither Dev nor Stage should mention `EDR0yhH3jo_lEfiev6nbSQ`

Sync string values of environment names for GTM

---

fec/search/management/data/sitemap_pdf.xml

Adding https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2009-11.pdf to the guidance search as of 6/10/2021.
- Resolves #4691

Adds 2009 FR notice to Guidance search

---

fec/data/templates/partials/browse-data/candidates.jinja
fec/data/templates/partials/browse-data/committees.jinja
fec/data/templates/partials/browse-data/external.jinja
fec/data/templates/partials/browse-data/filings-reports.jinja
fec/data/templates/partials/browse-data/loans-debts.jinja
fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja

- Resolves #4704 
Add responsive classes to browse data content sections. This fixes the overflow of those sections in mobile view.
1 front end and 1 UX
-  Browse data pages
- Use the browser inspector tool
- Click on the device toolbar button (second button from the left in the inspector tools
- Go to the [browse data pages](http://localhost:8000/data/browse-data/?tab=raising) and click on each tab to make sure the responsive layout looks right

Fix mobile view of browse data sections

---

fec/fec/static/js/templates/pac-party.hbs

- Resolves #4688 
Refines filter display to match design mock ups.
**Note:** Leadership PAC sponsor code was added but commented out for now until that can be added to the API. Related issue: https://github.com/fecgov/fec-cms/issues/4690
1 UX, 1 front-end, 1 back-end
-  PAC and party datatable
branch | PR
feature/4651-minimal-pac-party-datatable | [link](https://github.com/fecgov/fec-cms/pull/4653)
feature/4686-single-select-time-period | [link](https://github.com/fecgov/fec-cms/pull/4692)
- Go to [PAC and party datatable](http://localhost:8000/data/committees/pac-party/)
- Click on a committee details panel button
- Ensure that all fields in the details panel appears as expected per the comp

Refine display of details panel in PAC and party datatable

---

fec/data/templates/macros/filters/years.jinja
fec/data/templates/partials/pac-party-filter.jinja
fec/data/views_datatables.py
fec/fec/static/js/modules/filters/select-filter.js

- Resolves #4686 
When PAC & party datatable is loaded, apply the DEFAULT_ELECTION_YEAR, which is 2022. Also made the time period select box single select and non-removable.
1 UX, 1 front-end
-  Single select filter on PAC & party datatable
branch | PR
feature/4651-minimal-pac-party-datatable | [link](https://github.com/fecgov/fec-cms/pull/4653)
- Go to [PAC & party datatable page](http://localhost:8000/data/committees/pac-party/)
- Ensure that 2022 is what is defaulted on load of that page
- Ensure that you cannot remove the time period filter
- Ensure that changing the filter updates the datatable with the selected year

PAC & party datatable: default election year applied on load and make time period a single select

---

fec/data/constants.py

Offsets misspelled in Receipts datatable  filter panel  `Receipt details` >`Received by PACs or party committees` > `Offsets to operating expenditures (Line 15)`
- Resolves issue_number  #4614
one frontend
modified:   data/constants.py
- Checkout and run  `feature/4614-typo-receipts-datatable`
- Confirm that  /data/receipts  > filter panel  >  `Receipt details` >`Received by PACs or party committees` > `Offsets to operating expenditures (Line 15)` is spelled correctly

Fix type in data constants

---

fec/data/templates/partials/browse-data/external.jinja

- Resolves #4711 
Updating the bad link to the Office of Government Ethics (OGE) presidential candidate financial disclosure reports
1-2 reviewers
-  Page at https://www.fec.gov/data/browse-data/?tab=external (hard coded page) is updated with the new link. The new link is https://www.oge.gov/web/oge.nsf/Officials%20Individual%20Disclosures%20Search%20Collection?OpenForm
- http://127.0.0.1:8000/data/browse-data/?tab=external 
- http://www.fec.gov/data/browse-data/?tab=external

4711-Update bad link to OGE reports

---

fec/fec/static/scss/components/_glossary.scss

- Resolves #4727
- Glossary and adjacent `italic, bold, or .t-sans` tags had no space between them 
- The glossary icon was slightly cut off in some paragraphs
one content, one frontend
modified:   fec/static/scss/components/_glossary.scss
<hr>
<hr>
<hr>
<hr>
<hr>
- checkout `fix/4727-glossary-spacing-bug`
- Test adding glossary terms and adding italic, bold or sans-serif from the RTE menu to words before the glossary term
One offending page was http://localhost:8000/help-candidates-and-committees/registering-political-party/qualifying-political-party/

Correct glossary terms spacing bug

---

requirements.txt

- Resolves https://github.com/fecgov/fec-cms/issues/4752
Upgrade django python package to a minor version
Atleast one front-end developer approval is required
- checkout `feature/4752-upgrade-django`
- run `snyk test --file=requirements.txt --package-manager=pip`
-  run `npm i` 
- run `npm run build`
- start server run `./manage.py runserver`
- check that the cms app works as expected on local env.

Update django to minor v3.1.13

---

fec/home/templates/partials/document.html

- Resolves #4630 
Since the template crashes if fec_url isn't specified and there's no file at that url, let's not link to the non-file url
Just a couple—feel free to edit the list
Only the document.html template
The testing document has no url so isn't a link and doesn't have an icon or file size
None
- go to the [list of reports](http://127.0.0.1:8000/about/reports-about-fec/agency-operations/)
- Make a mental note of a report with a link
- Find that report in Wagtail
- Remove its url
- Publish it
- Go back to the list of reports
- The report should still be listed but shouldn't be a link and shouldn't have an icon or a file size listed
- All other reports in the list should be unchanged
Alternatively, make a new report with no url, publish it, and make sure it doesn't …

4630 Only link to document.file_url if it exists

---

fec/fec/static/scss/components/_calendar.scss
fec/fec/static/scss/components/_tooltips.scss

- Resolves #3979 
Polishing the appearance of the calendar tooltip
Two
Changed the style rules for the calendar tooltip
(The ticket has a 'before' shot)
Top (with a long title)
Right
Bottom
Left
None
- Go to the [calendar](http://127.0.0.1:8000/calendar/)
- Switch to the calendar grid view
- Start clicking events!
- Higher ones
- Lower ones
- Left & right ones
- Find one with a really long title (or use Inspector to edit one to be really long)
- Chrome should be fine
- Double-check Firefox
- If you can get Safari to load calendar entries, check that (or wait until dev/stg)

3979 Calendar tooltip widths

---

fec/data/templates/partials/committee/about-committee.jinja
fec/fec/static/js/templates/committees.hbs

- Resolves #4660 
Updated label on about this committee profile page to "Leadership PAC sponsor". Also added the leadership PAC sponsor information to the datatables details panel. 
1 UX
1 frontend or 1 backend developer
- Committees datatable
- Go to the committees datatable and try a leadership PAC search. Example: http://localhost:8000/data/committees/?sponsor_candidate_id=S6CA00584
- Go to the committee profile about this committee section to check the new label for Leadership PAC sponsor. Ex: http://localhost:8000/data/committee/C00629071/?tab=about-committee

Add leadership PAC sponsor info to datatable details panel

---

fec/data/templates/elections.jinja
fec/data/templates/partials/elections/about-this-election-tab.jinja
fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja
fec/fec/static/js/modules/table-columns.js
fec/fec/static/scss/components/_data-container.scss

- Adds priority to show  `Total receipts` , `Total disbursements`,  and `Cash on hand` columns in mobile for the first table `Candidate financial totals` in mobile view, issue:  #4668
- Allows obscured rows to be scrolled/swiped to
- Fixes responsive stacking issue on Election and Candidate profile pages, issue:  #4656
- Committee profile pages stack the tab nav and above the tables at 940px whereas the Election and Candidate proffile pages were not until the size reached @640p cutting off content.
- Quote from issue 4656 that applies to both issues:
```
The display should stack according to screen size and 
you should also be able to scroll horizontally for the datatables when there's smaller screens.
```
<hr>
-  Resolves #4668 
- Also resolves issue #4656
<hr>
**Note:** At some …

Elections page - fix responsive behavior  and show currency columns in mobile

---

fec/data/constants.py

- Resolves #4615 
Making minor updates to formatting for text in disbursements data table filter
1-2 reviewers
-  Disbursements Datatable located: https://www.fec.gov/data/disbursements/?data_type=processed&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022
- Select Disbursement Details, Made by PACs or party committees
Before:
After:
- https://www.fec.gov/data/disbursements/?data_type=processed&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_dat …

4615-Fix text in disbursements datatable filter

---

fec/fec/static/scss/components/_data-container.scss

In the last PR merged for this, a style rule somehow got reverted and left out of the code. This PR corrects that.
The change makes the tab nav full width when the tab nav stacks above the content
Resolves issue #4656 
Original PR #4754 
one front-end --OR-- one UX
modified:   fec/static/scss/components/_data-container.scss
Original PR #4754 
- checkout and `npm run build`
- See that the tab nav spans the whole screen when the screen is resized and the tab nav stacks above the tabbed content

[BEFORE RELEASE]Add style rule for full width tab nav

---

fec/data/constants.py
fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/macros/filters/filing-frequency.jinja
fec/data/templates/partials/pac-party-filter.jinja
fec/fec/static/js/templates/pac-party.hbs

- Resolves #4690 
- Resolves #4769  
What's included:
- Removes tooltips for PAC & party datatable as well as committees datatable for IE, Party, PACs, and filing frequency in filters and details panel
- Removes tooltips for IE and PACs from the committees datatable
- Retains tooltip for Ending cash on hand in details panel
- Adds leadership PAC sponsor field to the details panel
1 front end & 1 UX
- PAC & party datatable http://localhost:8000/data/committees/pac-party/
- Committees datatable http://localhost:8000/data/committees/
- Go to PAC & party datatable: http://localhost:8000/data/committees/pac-party/
- Ensure tooltips are removed from …

Modify PAC/Party datatable

---

fec/data/templates/macros/filters/range.jinja
fec/data/templates/partials/pac-party-filter.jinja

- Resolves #4781 
Adds "Ending cash on hand" tooltip to the pac and party filter
1 UX & 1 frontend
-  PAC and party datatable range filter
- Go to pac and party datatable page: http://localhost:8000/data/committees/pac-party/?cycle=2022
- Check that the tooltip is present on the ending cash on hand filter with the correct definition from the glossary term

adds tooltip to COH range filter

---

fec/fec/static/js/modules/calendar.js
fec/fec/static/js/templates/calendar/details.hbs
fec/fec/static/js/templates/calendar/events.hbs
fec/fec/static/scss/components/_calendar.scss

- Resolves #4111 
Adds the calendar event summary and updates styles [per the comp](https://github.com/fecgov/fec-cms/issues/4111#issuecomment-880920525)
1 UX & 1 frontend
- Calendar view 
- Go to the calendar page: http://localhost:8000/calendar/
- See that the correct components are there in the calendar events list view [per the comp](https://github.com/fecgov/fec-cms/issues/4111#issuecomment-880920525)
- Toggle to calendar view ![Screen Shot 2021-07-21 at 3 09 42 PM](https://user-images.githubusercontent.com/12799132/126545909-a72fe0e9-02b5-4a44-b86b-bf5aefbf70e7.png)
- See that the correct components are there in the calendar events calendar view [per the …

Add calendar event summary and update styles

---

fec/data/templates/election-lookup.jinja
fec/fec/static/js/modules/election-search.js
fec/fec/static/scss/components/_search-controls.scss

- Add a **persistent** accordion for 2021 redistricting information to Election search page. 
- Fix an existing bug : If you click on the map itself, before choosing any form filters, the "Results" headline does not show up until you choose a form filter.
- Fixes existing bug of the "Results" headline flashing briefly on the page before being hidden when you load page (we may not have noticed this in 2020  because it loaded showing the presidential listing for 2020 by default.)
- Resolves #4570
one UX, one frontend
modified:   data/templates/election-lookup.jinja
modified:   fec/static/js/modules/election-search.js
modified:   fec/static/scss/components/_search-controls.scss
Related PR:
https://github.com/fecgov/fec-cms/pull/2409
- checkout branch `feature/4570-district-update-msg`
- `npm …

2021 district message for Election search

---

fec/home/models.py

- Shows new title (in Wagtail admin) of a page created using the Wagtail `Copy` option while the page is still in draft. 
- This  issue only effected pages that have  the `menu_title` option in the Settings tab (CustomPage, ResourcePage and CollectionPage). All other pages correctly show the title of copied pages in draft.
- Resolves #4416
One frontend
modified:   home/models.py
This model change does not have a migration associated with it
**Content team:**
This is deployed to feature env: https://fec-feature-cms.app.cloud.gov/
**Developers:**
Checkout and run `feature/4416-wagtail-draft-title-display`
- Create a copy of a `Custom, Resource or Collection page` with a new title and uncheck  "Publish copied page" 
- Confirm that the new title shows up in the Wagtail admin
- Can also verify …

Show title for copied pages in draft

---

fec/data/templates/macros/filters/committee-types.jinja

- Resolves #4766 
Update the "Other committees" filter label to "Other committees and filers" on the following datatables:
http://localhost:8000/data/committees/
http://localhost:8000/data/disbursements/
http://localhost:8000/data/receipts/
http://localhost:8000/data/receipts/individual-contributions/
1 UX
- Committees datatable: http://localhost:8000/data/committees/
- Disbursements datatable: http://localhost:8000/data/disbursements/
- Receipts datatable: http://localhost:8000/data/receipts/
- Individual contributions datatable: http://localhost:8000/data/receipts/individual-contributions/
- Make sure that the "Other committees and filers" label exists on the following …

Update Other committees filter label

---

fec/fec/static/js/modules/calc-admin-fines.js
fec/fec/static/scss/components/_fec-org-chart.scss

- Resolves [no related ticket]
Fixing a repeated typo inside the admin fines calculator.
One person (feel free to remove yourself)
Only changing "adminstrative" to "administrative" in three places inside the admin fines calculator
None
None
- Check the [admin fines calculator](http://127.0.0.1:8000/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine)
- intro text
- the "When was the committee's administrative fine assessed?" frame
- the help text for "Number of previous violations"

Fix admin fines calculator typo

---

fec/data/constants.py
fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/receipts-filter.jinja
fec/fec/static/js/pages/datatable-receipts.js
fec/fec/static/js/templates/receipts.hbs

- Resolves #4513
- Change "contributor" to "source" on `data/receipts` :
- labels, help-text, and warning messages on filter panels(processed and raw)
- datatable header and flyout panel
- change `Contributor information` to `Receipts information` on flyout panel
- Change "contributor" to "source"  on Browse data Receipts section
one front-end, on UX
modified:   data/constants.py
modified:   data/templates/partials/browse-data/raising.jinja
modified:   data/templates/partials/receipts-filter.jinja
modified:   fec/static/js/pages/datatable-receipts.js
modified:   fec/static/js/templates/receipts.hbs
- checkout `feature/4513-change-contributor-to-source`
- Please see PR Summary or [issue](https://github.com/fecgov/fec-cms/issues/4513) for places where changes should be …

Change 'contributor' to 'source' for Receipts

---

requirements.txt

- Resolves #4723 
Security update to address XSS possibility
1 front-end (localhost or test env)
1 content (test env) (need to choose and tag)
Wagtail StreamFields, which are all over the place. But, according to the [release notes](https://docs.wagtail.io/en/stable/releases/2.11.8.html), it's only exploitable by those with admin/author privileges, so 🤞🏼 no noticeable changes for us.
None
- Being that it's a fix, I don't know if there's a way to test a failure.
- The release notes say the changes would affect `include_block` which we're only doing in `section.html` and `meeting_page.html` so we should check those:
- meeting pages (make sure content displays correctly)
- resource pages (ditto) …

Upgrade Wagtail from 2.11.7 -> 2.11.8

---

fec/fec/settings/base.py
fec/fec/templates/base.html
fec/fec/templates/home_base.html
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml

- Resolves #4682 
Removes all references to the FEC_TRANSITION_URL
1 frontend
-  Anywhere the FEC_TRANSITION_URL might have been used
- `npm run build` just in case
- Ensure that we are no longer using the `FEC_TRANSITION_URL` in the CMS code.
- View page source and ensure that the `FEC_TRANSITION_URL` is no longer in the page HTML source code.

remove all references to the FEC_TRANSITION_URL

---

fec/data/templates/committees-single.jinja
fec/data/utils.py

- Resolves #4827 
Updates committee profile pages to display committee registration date and filing frequency. 
1-2 reviewers
Before:
After:
After screenshots of the committee selected specifically for character length in #4827.
Different committee types and lengths of characters for testing: 
- http://127.0.0.1:8000/data/committee/C00489658/
- https://www.fec.gov/data/committee/C00489658/
- http://127.0.0.1:8000/data/committee/C00631481/
- https://www.fec.gov/data/committee/C00631481/
- http://127.0.0.1:8000/data/committee/C00139139/
- https://www.fec.gov/data/committee/C00139139/
- http://127.0.0.1:8000/data/committee/C00153262/
- https://www.fec.gov/data/committee/C00153262/
I kept the leading …

4827-Add filing frequency and registration date to committee pages

---

fec/data/views.py

Fix Electioneering communication committee pages server errors:
https://www.fec.gov/data/committee/C30001101/
- Add a an else statement to the com_type conditionals on data/views.py to stop server errors for committee pages of `committee type 'E'` (and any others that might have their com/org types listed) 
(reported in Slack by @prstoetzer / @djgarr)
one frontend
modified: data/views.py
https://github.com/fecgov/fec-cms/pull/4767
- see that http://127.0.0.1:8000/data/committee/C30001101/ loads without 500 error
- see that others on committee pages linked from the EC datatable page load without server error: http://127.0.0.1:8000/data/electioneering-communications/

[BEFORE RELEASE 09-07-21] Fix EC committee page server errors

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/pac-party-filter.jinja
fec/fec/static/js/templates/pac-party.hbs

- Resolves #4868 
- Resolves #4873 
Removes 2 IE filter options from committee type accordion. Also inserts political party label within the details panel.
1 UX and 1 front-end
-  PAC & Party datatable: http://localhost:8000/data/committees/pac-party/
- Go to the pac and party datatable: http://localhost:8000/data/committees/pac-party/
- Under the "committee type" accordion, choose one of the filters under "Parties". Check to see if the political party is listed under the details panel, as seen in the screenshot above
- Under the "committee type" accordion, make sure that there is now only one option available under the "INDEPENDENT EXPENDITURE COMMITTEES" filter: "Super PAC …

add political party to filter panel, remove 2 options from IE filters

---

package-lock.json
package.json

Upgrade NPM to latest  version 7.24.0
- Resolves #4591
- update NPM version in package.json
- generate package-local.json with latest npm changes
At least two developers required
**Before NPM package upgrade**:
```
(cms3710) macadmins-mbp-5:fec-cms pkasireddy$ node -v
v10.16.0
(cms3710) macadmins-mbp-5:fec-cms pkasireddy$ npm -v
6.14.3
```
**After NPM package upgrade**:
```
(cms3710) macadmins-mbp-5:fec pkasireddy$ node -v
v14.13.0
(cms3710) macadmins-mbp-5:fec pkasireddy$ npm -v
7.24.0
```
- checkout branch
- create new python virtual env: run `pyenv virtualenv 3.7.10 cms3710` 
- install requirements: run `pip install -r requirements.txt`
- check the local  npm version before upgrade:
- run `npm -v` : terminal  display …

Upgrade npm to latest

---

fec/data/templates/partials/filings-filter.jinja
fec/data/templates/partials/reports-filter.jinja

- Resolves #4845 
Changes the checkbox filter on the Filings and Reports data-tables to say "Current version"
1-2 reviewers
-  Filings and Reports data-tables
Before:
After:
http://www.fec.gov/data/filings/?data_type=processed
http://127.0.0.1:8000/data/filings/?data_type=processed
https://www.fec.gov/data/reports/presidential/?is_amended=false&data_type=processed
http://127.0.0.1:8000/data/reports/presidential/?is_amended=false&data_type=processed

4845-Fix filter label on filings and reports data-tables

---

fec/data/constants.py
fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/filters/audit-committee-types.jinja

- Resolves #4878 
Updating the labels for "PAC with non-contribution account" to "Hybrid PAC" (both qualified and non-qualified)
1 UX, 1 front-end
Datatables for Political action and party committees, Committees, Receipts, Individual contributions, Disbursements, and PAC and party committee reports.
The value in the table columns is coming from the API, as `committee_type_full`
None
- Check
- [Political action and party committees](http://127.0.0.1:8000/data/committees/pac-party/)
- [Committees](http://127.0.0.1:8000/data/committees/)
- [Receipts](http://127.0.0.1:8000/data/receipts/)
- [Individual contributions](http://127.0.0.1:8000/data/receipts/individual-contributions/)
- [Disbursements](http://127.0.0.1:8000/data/disbursements/)
- [PAC and …

Change the label for the qualified and non-contribution PACs

---

fec/data/constants.py
fec/data/templates/committees-single.jinja
fec/data/templates/partials/committees-filter.jinja
fec/fec/static/js/modules/columns.js
fec/fec/static/js/templates/committees.hbs
fec/fec/static/js/templates/pac-party.hbs

Resolves #4843
Resolves #4879 
Many places in the application are displaying/searching the first file date for the first form 1 date (labeled "registration date" on the committee profile page). The first file date is _almost_ always but not always the same date as the first Form 1 date. This PR updates the front-end to always use first Form 1 date for committees and label it "registration date".
**Committees datatable**
- Update filters to search first Form 1 instead of first file date for first form 1 filter
- Rename filter "Registration date"
- Rename column "Registration date" and show first F1 date
**Committee profile page**
- Display first form 1 date under registration date
**PAC/Party datatable**
- Modify flyout panel to show first form 1 date
@JonellaCulmer and one front-end …

Fix references to first file date/registration date

---

fec/fec/static/js/modules/columns.js

- Resolves #4951
Fix candidates datatable by sorting by `first_file_date` instead of `first_f1_date` (First F1 only applies to committees, not candidates)
One developer
-  Candidates datatable
https://github.com/fecgov/fec-cms/pull/4856
- Rebuild static assets with `npm run watch` or `npm run build`
- Make sure http://localhost:8000/data/candidates/?has_raised_funds=true&is_active_candidate=true loads candidates

[MERGE WITH GIT FLOW] Hotfix/fix candidates datatable

---

fec/fec/static/js/pages/datatable-committees.js

- Resolves #4923 
Updates default sort to registration date, descending
1 reviewer
-  Committees datatable
Before:
After:
- https://www.fec.gov/data/committees/
- http://127.0.0.1:8000/data/committees/

4923-Committees datatable default sort set to registration date

---

fec/data/templates/landing.jinja

- Resolves #4932
Improves our list of examples for the individual contribution search feature (and removes "celebrity.")
1 reviewer
-  Individual contribution search feature
Before:
After:
http://127.0.0.1:8000/data/
https://www.fec.gov/data/

4932-Remove "celebrity" from examples for individual contribution search 

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/views.py

- Resolves #3390 
For Inaugural organization types, don't show the individual contributions on the committee profile pages.
1 front end or 1 back end developer
-  Inaugural committee profile pages
- Go to any inaugural committee page and make sure that the individual contribution section does not show up under the raising tab. Ex: http://localhost:8000/data/committee/C00540005/?tab=raising&cycle=2014, …

Don't show individual contributions for inaugural organization type committees

---

fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja
fec/data/templates/partials/widgets/contributions-by-state.jinja
fec/fec/static/scss/components/_headings.scss

- Resolves #4937
-  Change  from accordion to modal popup for methodology overviews on browse data raising and spending tabs
-  Switch font to Ghandi on Raising by the numbers methodology overview
-  Fix some ga-events tags that were conflicting or incorrect
-  Fix some mismatched h6 tags on browse data raising and spending tabs
modified:   data/templates/partials/browse-data/raising.jinja
modified:   data/templates/partials/browse-data/spending.jinja
modified:   data/templates/partials/widgets/contributions-by-state.jinja
modified:   fec/static/scss/components/_headings.scss
- checkout branch and `npm run build-sass`
-  Test methodology buttons on:
- http://127.0.0.1:8000/data/browse-data/?tab=raising
- http://127.0.0.1:8000/data/browse-data/?tab=spending
- See that font is `Ghandi` on …

Change to modal window for methodology overview

---

package-lock.json
package.json

- Resolves #4967 
High-severity vulnerability due to the json-schema JavaScript package.
But, looking at its dependency tree
```
fec-cms@1.0.0 /…/fec-cms
└─┬ request@2.88.0
└─┬ http-signature@1.2.0
└─┬ jsprim@1.4.1
└── json-schema@0.2.3
```
`json-schema` was used only by `jsprim`, which was used only by `http-signature`, which was used only by `request`.
We'd included `request` as a dependency in our package file, but I couldn't find anywhere in the code that was still importing or requiring it. Running the site locally and running tests, I couldn't find anything that was broken when it was missing.
So let's rip it out?
Its [repo](https://www.npmjs.com/package/request) even lists it as [deprecated](https://github.com/request/request/issues/3142) 2.5 years ago
- 1-2 front-end (code review …

4967 SNYK - json-schema (request)

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/committees-filter.jinja

- Resolves #4963 
Added the tooltips to "authorized committees", "independent expenditure committees", and "PACs" filter labels.
1 front end, 1 UX, and 1 content
Please see screenshots to check definitions
- check that the tooltips are present with the correct definitions for "authorized committees", "independent expenditure committees", and "PACs" filter labels on the following datatables:
- [Committees datatable](http://localhost:8000/data/committees/)
- [Political action and party committees datatable](http://localhost:8000/data/committees/pac-party/)
- [Receipts datatable](http://localhost:8000/data/receipts/)
- [Individual contributions datatable](http://localhost:8000/data/receipts/individual-contributions/)

Add pac, IE, and auth committees filter tooltips

---

fec/data/templates/partials/committee/spending.jinja
fec/fec/static/js/pages/committee-single.js

- Resolves #4962 
This adds percent of total disbursements column to the committee profile page.
1 UX, 1 front end, 1 back end
-  Committee profile pages disbursement recipient name tab
branch | PR
feature/4988-add-disbursement-percents | [link](https://github.com/fecgov/openFEC/pull/4992)
- Go to any committee profile page disbursements tab. Ex: http://localhost:8000/data/committee/C00727834/?tab=spending&cycle=2020. Click on the group by "Recipient name" tab within disbursements. Check that the "Percent of total disbursements" column is present. 
- Go to a committee profile page with nulls for the …

Add percent disbursement column per recipient name for committee profile page

---

fec/fec/static/scss/components/_buttons.scss
fec/legal/templates/legal-search-results-regulations.jinja
fec/legal/templates/legal-search-results-statutes.jinja

- Wrap filters in `filters__inner` on  Statute and Regulations search  to add missing padding, 
- Fix placement of `.button--keywords` button  here and elsewhere in `/legal` and `/data`
- Resolves #4975
Only one reviewer required:
Any one of frontend, content or UX
modified:   fec/static/scss/components/_buttons.scss
modified:   legal/templates/legal-search-results-statutes.jinja
modified:   legal/templates/legal-search-results-regulations.jinja
<hr>
<hr>
- Checkout branch and `npm run build-sass`
- See inner padding on `filters` on  http://127.0.0.1:8000/data/legal/search/statutes/
- See `button--keywords` CSS change is  also OK where it is used elsewhere like http://127.0.0.1:8000/data/independent-expenditures/?data_type=efiling&is_notice=true
- Test responsive

Filter padding on statute and regulations search

---

fec/fec/static/js/modules/calc-admin-fines-logic.js
fec/fec/tests/js/calc-admin-fines.js
tasks.py

- Resolves #5000 
Updated the calculator for the new 2022 totals (and removed 2019)
Internal team has already verified functionality, so just one code reviewer
The admin fines calculator and its tests.
The date(s) is the only visible change
None
Internal team tested it on Feature at /legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine

[MERGE WITH GIT FLOW] hotfix/5000 admin fines 2022

---

requirements.txt

- Resolves #4994 
_Upgrade lxml to v4.7.1.  for security vulnerability_
- fec-cms/fec/search/management/commands/scrape_cms_pages.py
- fec-cms/fec/search/management/commands/scrape_transition_pages.py
- fec-cms/fec/search/management/commands/scrape_web_app_pages.py
- fec-cms/fec/search/utils/search_indexing.py
- Try performing scraping on your local by running the following command:
- `./manage.py scrape_cms_pages` 
One approval sufficient

Update lxml for security vulnerability

---

fec/fec/static/js/modules/maps.js

- Resolves #4575
- Change the initial tooltip style from `display: none/block`  to `visibility hidden/visible` to maintain tooltip innerHeight value when a user switches to a new candidate's map via the dropdown on all Election profile page's contributions-by-state maps. (or when choosing "Show two candidates" button)
Related issue: https://github.com/fecgov/fec-cms/issues/2644
Related PR: https://github.com/fecgov/fec-cms/pull/2657
One frontend
Tooltips on election profile page's contributions-by-state maps.
modified:   fec/static/js/modules/maps.js
<hr>
**After** 
<hr>
- Checkout branch and run `npm run build-js`
- View an election profile page and go to Individual contributions section, choose  `Contributor state` button, choose `Map` button
- Select a new candidate from the dropdown …

Bugfix for state maps tooltip display

---

fec/home/templates/home/meeting_page.html

#(https://github.com/fecgov/fec-cms/issues/4950)
Replaced audit hearing language with this:
The Commission considers new regulations and other public matters at public hearings. Members of the public can attend public hearings in person. Public hearings are also streamed live online. To attend in person, please bring a photo ID and be prepared to go through a security check. After security, attendees are escorted to the Commission's hearing room.
Meeting pages for audit hearings
Example of audit hearing page and what it should say after this change is at https://www.fec.gov/updates/november-10-2021-audit-hearing/
Ensure it says the updated language above.

Update language for audit hearings

---

fec/data/constants.py

- Partially fixes #5035 
This will update the dropdown for the PAC & Party datatable to have IE types listed as "Independent expenditure filer (not a committee)".
The API committees endpoint still lists `committee_type_full` as "Independent expenditor (person or group)". Need to do a separate PR for the API to fix that. Related issue: https://github.com/fecgov/openFEC/issues/5041
One content or one UX
-  PAC & Party datatable
branch | PR
Content team, please see screenshots above.
For others:
- Go to the [PAC & party …

Update IE type name

---

requirements.txt

Noticed this morning that CMS deploy’s are failing due to  Jinja2 dependency package MarkupSafe.
Jinja2 is now pulling MarkupSafe 2.1.0 as of Feb 17, 2022 which will break all CMS deploys to DEV, STAGE, FEATURE and PRODUCTON spaces.
Here is the DEV build that broke:
https://app.circleci.com/pipelines/github/fecgov/fec-cms/1732/workflows/cb5f52e6-7e18-433c-be3b-277e92cb38c8/jobs/5024
We need to upgrade Jinja2 to v3.0.0 which then pulls MarkupSafe-2.1.0 and push this change to our [cms-release-pr](https://github.com/fecgov/fec-cms/pull/5068)
With Jinja2 2.11.1 we get this error for pytest:
packages/jinja2/filters.py", line 13, in <module>
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/jcarroll/.pyenv/versions/3.8.12/envs/CMS-3812/lib/python3.8/site-packages/mark …
```

[BEFORE  02/22/22 RELEASE ] Upgrade Jinja to 3.0.0

---

.circleci/config.yml
README.md
runtime.txt

- Resolves #4894
circle python 3.8.12 docker image is pulled from here: 
https://hub.docker.com/layers/circleci/python/3.8.12-buster-node-browsers/images/sha256-5afc92a6d6144e8115f8c9872526daa7e224d05e51d40cf7be6d5fa59f4b8008?context=explore
Update python version 3.8 in
- circleci/config.yml
- README.md
- runtime.txt
One backend, one other front or backend
Last update to 3.7: https://github.com/fecgov/fec-cms/pull/3639
- Create and activate a Python 3.8.12 virtual environment ( You may have to install 3.8.12 with  Pyenv first)
- Checkout `feature/4894-upgrade-python-to-3.8`
- run `pytest`
- run `npm run test-single`
- runserver and test datatables, presidential map and few endpoints to make sure data loads OK
-  These changes were tested with a deploy to dev with  no issues on a …

Upgrade cms python-runtime to 3.8.12

---

requirements.txt

- Resolves #4993 
Upgrade Django to 3.1.14. That version specifically remediates [access bypass restriction vulnerability](https://github.com/django/django/commit/22bd17488159601bf0741b70ae7932bffea8eced).
1 front end
-  URL bypass

Upgrade django to 3.1.14

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/filters/audit-committee-types.jinja
fec/fec/static/js/modules/tables.js
tasks.py

- Resolves #4010
- Research issue: https://github.com/fecgov/fec-cms/issues/4316
- **Related user-submitted issues:**
https://github.com/fecgov/FEC/issues/10195
https://github.com/fecgov/FEC/issues/10194
This PR  addresses **two existing issues** with some data tables that are causing inconsistencies between the URL querystring parameters  and the state of the filters panel  and taglist buttons.(active filters). Below is each issue and its fix.
1. **Issue:** Certain checkbox filters  (in a checkbox dropdown widget) are not added to the URL querystring parameters when  chosen, or do not remove from the querystring when manually removed via the filter panel or taglist buttons. 
**Fix**: Use the correct macro variable in `committee_types.jinja` for `data-name` attributes of fieldsets to …

Shareable accurate datatable links

---

fec/data/templates/landing.jinja

- Resolves #5087
Moving Compare Candidates to the top of /data/
One front-end or UX
Only the data landing page
None
- check the [data landing page (http://127.0.0.1:8000/data/)](http://127.0.0.1:8000/data/)
- make sure "Compare candidates" is first and "Look up candidate and committee profiles" is second
- if it isn't:
- open Inspector (right-click anywhere on the page, choose Inspect)
- switch to the Application tab
- in the left column, choose Storage > Local Storage > http://127.0.0.1:8000
- under Key, look for `gtmExp:2021_data_landing` and change its value to `0`
- reload the page (close inspector if you like)

Swap top /data/ sections

---

requirements.txt

- Resolves #5071 
Upgrading Pillow to address a vulnerability, which required a Wagtail upgrade. Luckily, the [Wagtail upgrade](https://github.com/wagtail/wagtail/releases/tag/v2.11.9) addressed only the Pillow vulnerability and only changed the required version
- one front-end or UX
- should probably check on dev or feature so we can play with image uploads (Pillow being an image handler)
Pillow and Wagtail
None
None
Testing vulnerabilities is always tricky, like proving an absence. The vulnerability reads,
> Affected versions of this package are vulnerable to Improper Input Validation. When the path to the temporary directory on Linux or macOS contained a space, this would break removal of the temporary image file after im.show() (and related actions), and potentially remove an …

5071 SNYK - Upgrade Pillow (and Wagtail)

---

fec/fec/static/js/pages/reporting-dates-tables.js
fec/home/templates/home/full_width_page.html
tasks.py

- Resolves #5124
Fixes issue  with Feedback box failing to  submit   on pages using `full_width_page.html`. It was submitting to `/issue` instead of `data/issue` 
- Set BASE_PATH  to  `'/data'` in extra JS section of `full_width_page` template to override the BASE_PATH setting of `'/'` that gets set by the  parent template,   `base.html`.  
- Also put in a conditional statement in `reporting-dates-tables.js` so if an editor uses the full_width_page for something that does not have  a `.election_dates_table ` , it will not throw JS error which will potentially block feedback JS or other JS on the page . (followup ticket to be created to only include the JS in pages when its needed)
Issue created: https://github.com/fecgov/fec-cms/issues/5153
one frontend
Any page using full_width_page.html …

Fix feedback box errors on full width template

---

fec/home/models.py
requirements.txt
tasks.py

Upgrade wagtail to 2.15.4
- Resolves #4807
Also resolves https://github.com/fecgov/fec-cms/issues/5043
**Please check these  upgrade-considerations notes and see if anything needs attention and add to "Items to check" list below.**
- [2.12 Release upgrade-considerations](https://docs.wagtail.org/en/stable/releases/2.12.html#upgrade-considerations)
- [2.13 Release upgrade-considerations](https://docs.wagtail.org/en/stable/releases/2.13.html#upgrade-considerations)
- [2.13.5 Release upgrade-considerations](https://docs.wagtail.org/en/stable/releases/2.13.5.html#upgrade-considerations)
- [2.14 Release upgrade-considerations](https://docs.wagtail.org/en/stable/releases/2.14.html#upgrade-considerations)
- [2.14.2 Release upgrade-considerations](https://docs.wagtail.org/en/stable/releases/2.14.2 …

Upgrade wagtail to 2.15.4

---

fec/fec/settings/base.py
requirements.txt

- Resolves #5161 
- Resolves #5126 
Updates Django to 3.2.13 to remediate 2 different SQL injection vulnerabilities
1-2
QuerySet.annotate(), aggregate(), and extra() methods, in column aliases, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to these methods.
Affected versions of this package are vulnerable to SQL Injection via QuerySet.explain(**options) in option names, using a suitably crafted dictionary, with dictionary expansion, as the **options argument on PostgreSQL.
- `pip …

5161-Update django 3.2.13

---

fec/home/templates/home/meeting_page.html

- Resolves #5197 
Move additional info and informational message to below template intro text for open meeting and hearing pages.
1 developer
-  Commission public meeting pages such as open and hearing pages
- Go to a meeting page and add a snippet and additional information
- Make sure that the text shows up like the screenshots above

[HOTFIX - MERGE WITH GITFLOW] Update additional info and informational message placement in CMS

---

fec/data/templates/partials/house-senate-overview/election-data.jinja
fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
fec/fec/static/js/pages/elections-overview.js

- Resolves #5131 
All elections totals datatable using the new `/candidates/totals/aggregates/` endpoint.
1 front-end,  1 UX
-  House and Senate elections overview pages
branch | PR
feature/5034-contributions-across-time | [link](https://github.com/fecgov/fec-cms/pull/5166)
- `npm run build
- Go to the elections overview pages:
- [Senate all elections totals table](http://localhost:8000/data/elections/senate/#totals-for-all-elections)
- [House all elections totals table](http://localhost:8000/data/elections/house/#totals-for-all-elections)

All elections totals table

---

fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/partials/filters/audit-committee-types.jinja

Update Hybrid pac descriptions where hardcoded in CMS
Descriptions in `datatables` and `commitee profile pages`  should  be fixed by https://github.com/fecgov/openFEC/issues/5133
- Resolves #5121
- Related OpenFEC issue : https://github.com/fecgov/openFEC/issues/5133
Old hybrid PAC description
- PAC with Non-Contribution Account - Nonqualified
- PAC with Non-Contribution Account - Qualified
Updated hybrid PAC description
- Hybrid PAC (with Non-Contribution Account) - Nonqualified 
- Hybrid PAC (with Non-Contribution Account) - Qualified
one frontend
modified:   data/templates/macros/filters/committee-types.jinja
modified:   data/templates/partials/filters/audit-committee-types.jinja
- Checkout and  run branch
- Below are the pages using  `committee type filter`  to confirm it shows the …

Update hybrid pac descriptions on committee filters

---

fec/data/templates/election-lookup.jinja
fec/fec/static/scss/layout/_layout.scss

- Add  links to H/S overview pages  on election search page
- Feature flag the links with  "house_senate_overview"
- Resolves #5182
One  UX required.  Optionally,   one frontend
modified:   data/templates/election-lookup.jinja
- test links on  http://127.0.0.1:8000/data/elections/
- Test feature flag by mimicking prod env on your local:  `export FEC_CMS_ENVIRONMENT=prod`  (new links should not show)
- @JonellaCulmer Don't forget to reset your local env:  `export FEC_CMS_ENVIRONMENT=local`

Add links to H/S overviews on Election search page

---

fec/data/templates/partials/house-senate-overview/election-data.jinja
fec/fec/settings/base.py

#5232 
Add methodology feature flag for house and senate overview pages.
1 front end
- House overview page methodology: http://localhost:8000/data/elections/house/
- Senate overview page methodology: http://localhost:8000/data/elections/senate/
- Comment out line 85 of base.py so that the feature won't turn on for your local:    
- Check the house and senate overview pages and make sure methodology does not appear
- House overview page methodology: http://localhost:8000/data/elections/house/
- Senate overview page methodology: http://localhost:8000/data/elections/senate/
- Uncomment line 85 of base.py so that the methodology re-appears again to see if it's working as …

Add methodology feature flag for house & senate overview pages

---

fec/data/templates/macros/filters/states.jinja
fec/data/templates/partials/filings-filter.jinja

We need to add "Candidate" to "state or territory" label under `Filer` filters on filings data table
Add `type=''` arg to states  macro, set it to  `type='candidate'` for filings data table filters
- Resolves #5180
one frontend
Affects filings data table, `filer` filters 
modified:   data/templates/macros/filters/states.jinja
modified:   data/templates/partials/filings-filter.jinja
- check filing data-table for `CANDIDATE STATE OR TERRITORY` label: http://127.0.0.1:8000/data/filings
- check another page using state macro for filters to make sure it displays as usual:  http://127.0.0.1:8000/data/disbursements/

'Candidate state or territory'  label for filings data table

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/about-committee.jinja

- Resolves #5238
- Fix syntax to enable human-readable committee designation( `designation_full`)  on the header/about-tab of committee profile pages
- History: Conditionals for designation were added here https://github.com/fecgov/fec-cms/commit/49d8ada9b764fa41972b1a90a77dd0467bf9d472  . (Maybe something in view logic has since changed that broke the logic (?), but I could not find  anything in the history.).
one frontend and  @PaulClark2 
modified:   data/templates/committees-single.jinja
https://github.com/fecgov/fec-cms/pull/3162
- verify that committee designations show in header on committee profile pages (see  [the issue](https://github.com/fecgov/fec-cms/issues/5238) for example pages)

Committee designation on committee profile page

---

fec/data/templates/partials/house-senate-overview/election-data.jinja

- Resolves #5232 
Updates disclaimer text for all totals elections datatable
1 UX and 1 data expert
-  All elections totals datatable
- Go to the datatable: http://localhost:8000/data/elections/house/#totals-for-all-elections

Update disclaimer text for all totals elections datatable

---

fec/data/templates/browse-data.jinja
fec/data/templates/partials/browse-data/loans-debts.jinja
fec/fec/templates/partials/navigation/nav-data.html

- Resolves #5168 
Removes debts language from the loans and debts page, the main navigation and the browse data left navigation
One front-end
-  Browse data
-  Main navigation
- The word "debt" does not appear on the browse data section, main navigation

Remove debts from Loans and debts page

---

fec/data/templates/raising-bythenumbers.jinja

- Resolves #5230 
Removing "See a " from the raising methodology
Someone from front-end, UX, or content
- The raising methodology
- Just a quick code review?

5230 Remove "See a"

---

fec/fec/static/js/pages/committee-single.js

- Resolves #5178 
Handle null strings for SA by employer, by occupation, and SB by recipient. I do not see anywhere in the CMS code we are using `/schedules/schedule_a/by_zip/` aggregates. So I did not need to accommodate for that, but we will have to later if we decide to make a feature for this.
1 front-end, 1 UX, 1 content specialist
- Committee profile page individual contributions employer tab (http://localhost:8000/data/committee/C00213512/?tab=raising) 
- Committee profile page individual contributions occupation tab (http://localhost:8000/data/committee/C00000539/?tab=raising)
- Committee profile page disbursements recipient name tab (http://localhost:8000/data/committee/C00103861/?tab=spending) …

Handle null strings for SA/SB aggregates

---

fec/fec/static/js/pages/elections-overview.js

Preserve  `recipient_committee_type`  parameter (H or S)  in totals links from H/S overview across time chart by explicitly adding `data_type=processed` to URL querystring. Otherwise it strips it.
Although `data_type=processed` gets automatically added to a link to receipts datatable ( https://fec.gov/data/receipts ) ,  the `recipient_committee_type`  will be removed unless `data_type=processed` is already in link at time of clicking (or pasting into browser url bar). Not sure why (?)
one frontend
modified:   fec/static/js/pages/elections-overview.js:
https://github.com/fecgov/fec-cms/pull/5166
-  `npm run builld-js`
-  Make sure links from totals on chart include the office parameter (`recipient_committee_type=H/S`) in the resulting datatable

[MERGE WITH GITFLOW] H/S across time chart  -  preserve  office param (H/S)  in totals links 

---

fec/legal/templates/legal-admin_fine.jinja

- Resolves #4763  
Adds closing `<th>` tag that was missed.
1 front end
-  Admin fines canonical page
branch | PR
feature/4763-accessible-vertical-tables| [link](https://github.com/fecgov/fec-cms/pull/5236)
- Look at an admin fine page such as this one: http://localhost:8000/data/legal/administrative-fine/4262/. Check the Summary section table and see that the `<th scope="row">...</th>` was inserted correctly. 
- You can turn on voiceover on your machine and highlight the header row, it should say that the selected item is a heading.

Fix closing th tag

---

fec/home/templates/home/commission_meetings.html
fec/home/templates/home/meeting_page.html

- Resolves #5275 
10:00am. as shown in screenshot from an open meeting page should be 10:00 a.m. with a space between 10:00 and a.m., with a.m. having a period after each letter.
1 front-end dev
General components of the application that this PR will affect: Meeting page template, in the description for open meetings
(https://user-images.githubusercontent.com/24437369/171252874-7c66f15a-f92c-412e-bca5-70aa6e26c82a.png)

Minor style guide fix

---

fec/home/templates/home/resource_page.html
tasks.py

- Resolves #4797
Remove {% block_title %} from resource page so it uses the block from `base.py`-- its "grandparent" template (long_page.html` is its parent)
@djgarr 
modified:   home/templates/home/resource_page.html
A copy of this branch is deployed to feature space for testing:  https://fec-feature-cms.app.cloud.gov/
- confirm that the value in the promote tab > `Title tag` field shows in browser tab with existing or newly published `Resource Pages`
- Please double check that any places where a title is rendered  (like the title in Wagtail page explorer or other places you can think of) are not affected.
**Note:** This branch is combined with https://github.com/fecgov/fec-cms/pull/5304 for testing on feature space, so no deploy task to remove before merge

Resource page title for browser tag

---

fec/fec/static/js/legal/FilterPanel.js
fec/fec/static/js/legal/Filters.js
fec/fec/static/js/legal/filters/TextFilter.js

- Resolves #5211 
Update and clean up DOM HTML elements to add dividing lines to AO filters
1 front end and 1 UX
-  AO filter panel: http://localhost:8000/data/legal/search/advisory-opinions/
- Go to the [AO search page](http://localhost:8000/data/legal/search/advisory-opinions/) and check the dividing lines are present in the first set of filters. The accordion content should also retain the dividing lines.

Add dividing lines for AO filters

---

requirements.txt

- Resolves #5327 
Updates Django to 3.2.14 to remove critical SQL injection vulnerability 
1-2 devs
-  [Django](https://pypi.org/project/Django/) is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Affected versions of this package are vulnerable to SQL Injection via the Trunc(kind) and Extract(lookup_name) arguments, if untrusted data is used as a kind/lookup_name value.
- `rm -rf node_modules`
- `npm i &&  run build`
-  run `snyk test --file=requirements.txt --package-manager=pip`  (confirm vulnerability is removed)
- `pytest`

5327-Upgrade django in release

---

fec/fec/static/scss/components/_accordions.scss
fec/fec/static/scss/components/_legal-search.scss
fec/fec/static/scss/components/_table-styles.scss
fec/fec/static/scss/components/_tags.scss
fec/fec/static/scss/layout/_layout.scss
fec/legal/templates/partials/legal-search-results-adrs.jinja
fec/legal/templates/partials/legal-search-results-afs.jinja
fec/legal/templates/partials/legal-search-results-mur.jinja

- Resolves #5255
Update MUR search results display with:
- election cycle
- disposition
- subject
- document name
- document links
- document type
- removed ellipses
- force all-caps for committee name
1 front-end and 1 UX
-  MUR search results (http://127.0.0.1:8000/data/legal/search/murs/)
- Go to the MUR search page: http://127.0.0.1:8000/data/legal/search/murs/
- Perform a keyword search. Ex: http://127.0.0.1:8000/data/legal/search/murs/?search_type=murs&search=spending 
- Check to see if the results match what's in the design within this [epic](https://github.com/fecgov/fec-epics/issues/221).

Update MUR search results display

---

requirements.txt

- Resolves #5362 
1-2 who can verify SNYK alerts have been satisfied (feel free to remove yourself)
It's Django, so potentially the entire site. But it's [only a patch release](https://docs.djangoproject.com/en/4.0/releases/3.2.15/) and only affects something we weren't using
None
- `snyk test --file=requirements.txt`
- make sure this vulnerability isn't listed
- check [localhost](http://127.0.0.1:8000) to make sure it's working
- check admin to make sure it's working
- let the rest of us know of a better way to test it?

5362 - SNYK Django Reflected File Download

---

.circleci/config.yml
README.md
requirements.txt

- Resolves #5387
This updates the docker images and pins flake8 until we can fix our tests failing in the most recent major version. That ticket is [here. ](https://github.com/fecgov/openFEC/issues/5217)
1-2 devs
-  circleci config
https://github.com/fecgov/openFEC/issues/5217
I tried to test run circleci config locally via their CLI tools and wasn't able to run them successfully. I got some errors that they seems to know about and aren't moving forward with right now. I did deploy to dev and everything ran successfully. 
-checkout this branch
-deploy to dev
NOTE for future changes- changing the docker images requires a new branch each time as there's issues with caching!

5387-Upgrade circleci docker images (python 3.8 and PG 12.8), pin flake8 

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/spending.jinja

- Resolves #5352 
For inaugural committees, remove IE table and change disbursements to refunds
1 UX and 1 front-end
-  Inaugural committee pages
- Go to an inaugural committee page - Ex: http://127.0.0.1:8000/data/committee/C00540005/?tab=spending
- Check that the independent expenditure table is not there
- Check that the "Disbursements" table is now labeled "Refunds"
- Go to any committee that is not an inaugural committee and check to make sure that there are no changes - Ex: http://127.0.0.1:8000/data/candidate/S2KY00012/?tab=spending, http://127.0.0.1:8000/data/committee/C00822940/?tab=spending

Update spending page for inaugural committees v2

---

.circleci/config.yml
README.md
requirements.txt
runtime.txt

- Resolves #5247 
There's a vulnerability with pyJWT which was pinned in cg-django-uaa. cloud.gov released a new version of cg-django-uaa with [my PR's changes ](https://github.com/cloud-gov/cg-django-uaa/pull/66) 
They release other system updates with the new version that needs python 3.9, so we should upgrade in CMS and API. 
1-2 devs
-  wagtail cloud.gov login
API PR- https://github.com/fecgov/openFEC/pull/5233
EREGS PR-https://github.com/fecgov/fec-eregs/pull/710
(pattern, proxy ok)
(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never …

5247-Upgrade python and cg-django-uaa

---

fec/data/templates/partials/filings-filter.jinja
fec/data/templates/partials/independent-expenditures-filter.jinja
fec/data/templates/partials/reports-filter.jinja

- Resolves #5248
- Allow text and typeahead search for `committee name or id` fields on filings and reports datatables.
- This is for processed and raw tabs on :
- [All filings](http://127.0.0.1:8000/data/filings)
- [Presidential committee reports](http://127.0.0.1:8000/data/reports/presidential/?is_amended=false)
- [House and Senate committee reports](http://127.0.0.1:8000/data/reports/house-senate)
-  [PAC and party committee reports](http://127.0.0.1:8000/data/reports/pac-party)
- For processed only on 
- [Independent expenditures](http://127.0.0.1:8000/data/independent-expenditures)
- There is an outstanding issue to resolve raw filings text-search issue, [see spreadsheet](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=0)
one frontend …

[MERGE BEFORE RELEASE 09/20/22 ]Combo text/typeahead search for committee field  on filings and reports

---

fec/fec/static/js/pages/committee-single.js

Change sort from `report_type_full` to `report_type_full_original` due to recent [API changes](https://github.com/fecgov/openFEC/pull/5239/files)
1 developer
-  Committee profile page regularly filed reports table. Ex: http://localhost:8000/data/committee/C00213512/?tab=filings 
branch | PR
feature/5222-change-notification-to-report | [link](https://github.com/fecgov/openFEC/pull/5239)
- Go to any committee profile and make sure that the regularly filed reports are returning correctly. Ex: http://localhost:8000/data/committee/C00213512/?tab=filings

[HOTFIX - MERGE WITH GITFLOW] Change sort from `report_type_full` to `report_type_full_original`

---

fec/data/templates/partials/committee/spending.jinja

- Resolves #5422 
Fixes the "Filter this button" link for Independent Expenditures on committee profile pages
1 developer
-  Independent Expenditures on committee profile pages
- Go to a committee profile page spending section. Ex: http://localhost:8000/data/committee/C00687103/?tab=spending. Click on the "Filter this data" button under the Independent expenditures section. It should filter the IE datatable correctly.

update committee profile page IE filter button query

---

fec/data/templates/macros/tables.jinja

- Resolves #5422 
Fixes link for independent expenditures on financial summary committee profile pages
1 developer
-  Committee profile page financial summary
branch | PR
- Open any committee profile page with independent expenditures. Ex: http://localhost:8000/data/committee/C00687103/?tab=summary
- Make sure independent expenditures line item has `q_spender` in the link. Party coordinated expenditures should remain the same with `committee_id` in the link.

[HOTFIX - MERGE WITH GITFLOW] Update committee profile page financial summary query string for IEs to be q_spender

---

fec/data/templates/macros/tables.jinja

- Resolves #5422 
Make the independent expenditures link on the financial summary page of a committee profile page go to the processed regularly filed reports
1 developer
-  Financial summary IE link
branch | PR
[fix/other_pr](https://github.com/fecgov/fec-cms/pull/5438) | [link](hotfix/fix-IE-link-financial-summary)
- Open any committee profile page with independent expenditures. Ex: http://localhost:8000/data/committee/C00687103/?tab=summary
- Make sure independent expenditures line item has `is_notice=false&data_type=processed` in the link. Click on the link.
- Make sure that the IE datatable loads the correct processed datatype with the committee and regularly filed …

[HOTFIX - MERGE WITH GITFLOW] On financial summary, make IE link go to regularly filed processed reports

---

fec/legal/templates/partials/legal-search-results-mur.jinja

- Resolves #5423 
In MUR results for archive MURs:
- Update language for dispositions to say "Not available for archived cases"
- Change document link text to be "Case documents, part [document_id]"
- Remove document category as it does not exist
- fix up styles to add padding as needed
1 UX and 1 front end
- MUR search results display
- Go to MUR search page and look at archive MUR results with keywords and only one document. Ex: http://localhost:8000/data/legal/search/murs/?search=committee&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=4000#results-murs
- Go to MUR search page and look at archive MUR results with …

Update results display for archive MURs

---

fec/data/api_caller.py

Remove references to participant citations object for both MUR and ADR. Update dictionary name for ADR dispositions
1 developer
- MUR cannonical page
- ADR cannonical page
branch | PR
feature/4793-adr-parameters | [link](https://github.com/fecgov/openFEC/pull/5250/files)
- Go to any MUR cannonical page, make sure citations are there and page loads. Ex: http://localhost:8000/data/legal/matter-under-review/8013/
- Go to any ADR cannonical page, make sure page loads: http://localhost:8000/data/legal/alternative-dispute-resolution/954/

Fix ADR and MUR cannonical pages

---

fec/fec/static/js/templates/pac-party.hbs

add a tooltip to the PAC and party datatable side panel that clarifies which types of contributions are included in the "individual contributions" dollar figure
- Resolves #4876 
- Tooltip added to the `individual contributions` field on the PAC and party datatable side panel 
- Removed redundant `Designation` field from the PAC and party datatable side panel 
1-2 developers 
PAC and party datatable side panel 
Before (In production):
After:
- checkout feature branch: `git checkout feature/4876-add-ic-tooltip`
- complie JS files: run `npm run build` 
- run python tests: `pytest`
- run java script tests: `npm run test-single`
- start local server `./manage.py runserver` 
- view changes in browser: http://localhost:8000/data/committees/pac-party/?cycle=2022

Add a tooltip to the individual contributions field on PAC and party datatable side panel

---

fec/fec/static/scss/components/_posts.scss
fec/legal/templates/legal-advisory-opinions-landing.jinja
fec/legal/views.py

- Resolves #5400
- Adds view logic and template changes to display AO comment deadlines extracted from document descriptions
- Update `How to Comment` link to point to anchor
UX/Frontend
AO Landing page
modified:   legal/templates/legal-advisory-opinions-landing.jinja
modified:   legal/views.py
- Checkout and run branch
- Since there are currently no AOs with pending comment dates, there is sample data dict in the view called `pending_aos_sample` . This is the data output from the exact same call to the api that the `pending_aos var`  makes to api_caller with the document descriptions edited allow some AOs comment dates to show on page. (See comment on line 399)
- Edit the doc description "Comments due by..."  section to test reliability of the regex and view logic 
- Edit the doc …

AO Comment deadlines display

---

fec/legal/templates/partials/legal-search-results-mur.jinja

- Resolves [#5121](https://github.com/fecgov/openFEC/issues/5121)
Removes non-unique values in election cycle for MUR. After discussing with OGC, only displaying the unique values for MURs is a better depiction of the data. 
1 dev
-  MUR search/tables
After:
Before:
https://www.fec.gov/data/legal/search/murs/?search=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=40#results-murs
(Specifically look at 7882)
Pull the branch
- `cd fec`
- `python manage.py runserver`
- http://127.0.0.1:8000/data/legal/search/murs/?search=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=40#results-murs

5121 MUR election cycle bug fix

---

fec/data/templates/partials/browse-data/committees.jinja

- Resolves #5471 
Changes /year/ to /data.fec.gov/.
Also added word "PAC" to last sentence of description.
One front end person to check links
Data page for bulk downloads

Update links to leadersthip pac csv files

---

requirements.txt

- Resolves #5433 
Upgrades django to 3.2.16 to remove medium security vulnerability
1 dev
-  Django
- `rm -rf node_modules`
- `npm i &&  run build`
-  run `snyk test --file=requirements.txt --package-manager=pip`  (confirm vulnerability is removed)
- `pytest`

5433-upgrade django 3.2.16

---

fec/fec/static/scss/components/_site-header.scss

Letters on the USA banner were being cutoff at the bottom. ("g" in `government` and "y" in` you know`). This PR adds 1px of padding to fix that.
- Resolves #5453
One UX -or- One Frontend
USA-gov banner that appears on every page of the site
modified:   fec/static/scss/components/_site-header.scss
- `npm run build-sass
- confirm that the "g" in` government` and "y" in `you know` are not cutoff at the bottom of USA banner.
- merge and celebrate!

Padding to fix bottom cutoff of letters on usa banner

---

package-lock.json
package.json

- Resolves #5447 
upgrades minimatch to remove snyk vulnerability 
1 dev
-  package, package-lock
(check to make sure you're on node v. 14.13.0 & npm 7.24.0, if not nvm install 14.13.0)
- checkout develop
- `snyk test`  see current vulnerability
-  checkout this branch
- `npm i && npm run build`
- `snyk test` no longer see vulnerability
-  `pytest`
-  `python manage.py runserver` test locally

5447- upgrade minimatch

---

fec/home/templates/home/commission_meetings.html
fec/home/templates/home/meeting_page.html

- Resolves #5510 
Update open meeting time to 10:30
1 content reviewer
- Commission meeting landing page
- All Commission open meeting pages
- See screenshot, if that looks good, feel free to merge

Update open meeting time

---

fec/fec/static/js/modules/table-columns.js

- Resolves #5480 
Election profile pages > Candidate financial totals tab > Source-reports-link (View all) does not filter the committee ID correctly.
Replace committee_id filter with q_filer 
2 frontend developers
- Election profile pages 
Before:
**For Presidential election profile pages:**
__________________________________________________________________________________________________________
**House/Senate election profile pages:**
Changes in this PR:
**For Presidential election profile pages**:
**For House/Senate election profile pages:**
-  checkout  branch `feature/5480-replace-cmteid-with-qfiler-filter`
- npm run build-js
- run pytest
- ./mange.py runserver
- Test endpoints: **Election profile pages > Candidate financial totals tab > Source-reports-link (View all) filter by …

Replace committee_id with q_filer

---

fec/data/views.py

- Resolves #5481 
The $ links were broken on `/data/elections/president/` [Communication costs](https://www.fec.gov/data/elections/president/#communication-costs) and [Electioneering communication](https://www.fec.gov/data/elections/president/#electioneering-communication).
The templates were referencing `election_duration` which didn't exist. Simply adding that variable fixed the date issue and shouldn't complicate anything else.
Someone to approve the code, maybe someone else to be another check for the functionality?
Some of the links in the tables of `/data/elections/president/`
- pull branch
- `npm run build` just in case
- Check the presidential tables on [localhost](http://127.0.0.1:8000/data/elections/president/2020 …

5481 min/max dates in URLs

---

requirements.txt

- Resolves #5509 
GitPython is in maintenance mode. I did some research and as we use Gitpython for our automated releases it will be challenging to switch over to Pygit2 or Dulwich, but we will probably need to do it in the future. Currently, GitPython is most widely used and have releases/patches faster than the other two main options, even though it's in maintenance mode. 
1 dev
-  Interaction with git libraries, release process
Before:
After:
- checkout and pull the latest `develop` branch
- 'pyenv virtualenv 3.9.14 cms'
- 'pyenv activate cms'
-  run `pip install -r requirements.txt` 
- run `snyk test --all-projects`. Shows vulnerability. 
- `gh pr checkout 5534`
- run `pip install -r requirements.txt` 
- run `snyk test …

5509-upgrade gitpython

---

requirements.txt

- Resolves #5488 
We pinned setuptools due to a previous deploy issue. It's a dependency of gevent. Upgrading gevent and un-pinning setuptools should both remove the  ReDOS vulnerability and cause less issues for us down the line. 
1 dev
Before:
After:
- pull latest develop (run requirements if you haven't recently)
- `snyk test --file=requirements.txt` shows current vulnerability
- `pip freeze` setuptools should be updated
- `snyk test  --file=requirements.txt` shows zero vulnerabilities
-  `cd fec`
-  `python manage.py runserver`

5488- Upgrade setuptools

---

fec/data/templates/layouts/main.jinja
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/home/templates/purgecss-homepage/full.html
fec/home/templates/purgecss-homepage/navs.html

- Resolves #5573 
This PR adds an explicit type to the footer button so we can upgrade babel and es packages. 
-  footer
1. Navigate to the home page - http://127.0.0.1:8000/ 
2. Scroll down to the footer
3. Click the button that states "Sign up for FECMail"
4. Ensure that the button works still
Other links to try: 
- http://127.0.0.1:8000/calendar/?calendar_category_id=25&calendar_category_id=26&calendar_category_id=27 (base.html)
- http://127.0.0.1:8000/data/raising-bythenumbers/

Add Type to footer button

---

fec/data/views.py

On the committee profile page, we will show Raw filing when cycle is greater than DEFAULT_TIME_PERIOD (now is 2022).
- Resolves #5588 
1 dev
2) test urls
http://127.0.0.1:8000/data/committee/C00099259/?tab=filings&cycle=2024
http://127.0.0.1:8000/data/committee/C00766162/?tab=filings
http://127.0.0.1:8000/data/committee/C00781443/?tab=filings

Allow cycle greater than DEFAULT_TIME_PERIOD to show efiling data

---

.flake8
.pre-commit-config.yaml
pytest.ini
requirements.txt

pre-commit hook is run first, before you even type in a commit message. 
-  inspect the snapshot that's about to be committed
-  to make sure tests run OK
-  inspect the code for linting errors
- Resolves #5578 
pre-commit scripts run automatically every time a file change event occurs in a Git repository
2 or more developers
- checkout branch: `git checkout feature/5578-setup-precommit-hook`
- create new python virtualenv: `pyenv virtualenv 3.9.14 venv-cms`
- activate python virtualenv: `pyenv activate venv-cms`
- install requirements : `pip install -r requirements.txt` 
- run: `pre-commit install`
-  in case you run into error shown below:
```
[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
hint: `git config --unset-all core.hooksPath`
```
- run: `git config …

Setup pre-commit git hook

---

.pre-commit-config.yaml

flake8  flagged snytax error when `git commit` is ran on local branch before pushing the changes. Invalid argument given in pre-commit-config.yaml. 
- Replace  `--line-length` with `--max-line-length` in pre-commit-config.yaml
one developer
**Before:** 
```
(venv-cms-dev) F611836M:fec-cms pkasireddy$ git commit
fix end of files.........................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 2
usage: flake8 [options] file file ...
flake8: error: unrecognized arguments: --line-length=120
```
**After:**
```
(venv-cms-dev) F611836M:fec-cms pkasireddy$ git commit
fix end of files.........................................................Passed …
```

fix the snytax error in pre-commit yaml file

---

package-lock.json
package.json

- Resolves #5567 
This ticket replaces nswatch with npm-watch and concurrently. 
- We watch three directories for front-end changes 
- `./fec/fec/static/js/**/*.js`
- `./fec/fec/static/js/templates/**/*.hbs`
- `./fec/fec/static/scss/**/*.scss`
- On startup it executes build-js and build-sass
- The watcher continues running in the terminal 
- Upon changes to js. or .hbs files it automatically reruns build-js
- Upon changes to .scss files it automatically reruns build-sass
Concurrently allows npm-watch to re-run the build scripts based on which type of file has changed. Using npm-watch and concurrently together has the same functionality as nswatch.
Documentation: 
[Concurrently](https://www.npmjs.com/package/concurrently)
[npm-watch](https://www.npmjs.com/package/npm-watch)
General …

replace nswatch with npm-watch and concurrently

---

fec/data/templates/house-senate-overview.jinja

- Resolves #5607 
The Methodology buttons on [/data/elections/house/](https://www.fec.gov/data/elections/house/) and [/data/elections/senate/](https://www.fec.gov/data/elections/senate/) aren't/weren't working; in addition, the console is showing a warning and 1-2 errors
HT @johnnyporkchops for the research and solution!
A front-end or UX
The House and Senate election pages
None
- Open the House or Senate election pages for localhost (linked below) or Production (linked above)
- Check the console that there's a warning (yellow) and 1-2 errors (red)
- Click any/all of the Methodology buttons—they should do nothing
- Open the [House](http://127.0.0.1:8000/data/elections/house/) or [Senate](http://127.0.0.1:8000/data/elections/senate/) …

5607 - Election pages methodology buttons

---

fec/fec/static/js/modules/toc.js
fec/fec/tests/js/toc.js

Links to TOC pages with a hash suffixed to the URL now land in the right location on page and highlight correct menu button
- Resolves issue #5532
one frontend or content
modified:   fec/static/js/modules/toc.js
modified:   fec/tests/js/toc.js
Content team can test this on dev:
Examples:
- https://dev.fec.gov/legal-resources/policy-other-guidance/#interpretive-rules
- https://dev.fec.gov/legal-resources/policy-other-guidance/#proposals
This was also tested on the new menus on house and senate overview pages where the toc.js functionality is also used.

Fix toc menu highlight bug

---

fec/data/templates/partials/browse-data/bulk-data.jinja
fec/data/templates/partials/browse-data/candidates.jinja
fec/data/templates/partials/browse-data/committees.jinja
fec/data/templates/partials/browse-data/filings-reports.jinja
fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja

- Resolves #5622 
Adds the links for the 2023-2024 bulk data sets.
1 dev
bulk download section
Before:
After:
- pyenv virtualenv 3.9.15 test-links
- pyenv activate test-links
- nvm install 18.13
- npm i &&  npm run build
- cd fec

5622-Add 2023-2024 links

---

fec/fec/templates/robots_prod.txt
fec/fec/tests/test_robots.py
fec/fec/urls.py

- Resolves https://github.com/fecgov/fec-accounts/issues/466 
Add robots.txt for prod with disallow statements for dynamic search result queries and fix flake8 syntax issues
Google developer documentation on [useful robots.txt rules](https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt#useful-robots.txt-rules). This is what was referenced to create the disallow statements.
2 developers
-  robots.txt
branch | PR
feature/5522-sitemap | [link](https://github.com/fecgov/fec-cms/pull/5579)
- Check robots.txt for local and lower environments: http://localhost:8000/robots.txt. This should disallow all …

Add robots.txt for prod 

---

fec/fec/static/scss/components/_data-container.scss
fec/fec/static/scss/components/_datatables.scss
fec/fec/static/scss/components/_dropdowns.scss
fec/fec/static/scss/components/_entity-header.scss
fec/fec/static/scss/components/_messages.scss
fec/fec/static/scss/components/_posts.scss
fec/fec/static/scss/components/_search-bar.scss
fec/fec/static/scss/components/_side-nav.scss
fec/fec/static/scss/components/_tags.scss

Fixing lots of word wraps across the site.
- code approver
- appearance approver
- Multiple additions of `word-wrap: break-word;` site-wide. In addition:
- Every datatable <td> now has a maximum width
- On committee pages, there are now width limits for the page title (committee name) 
- On committee pages, About this committee, the values column now has width limits
- Datatable lookup ("Typeahead") filters now have width limits
- Site search ("Typeahead") in the upper nav now has width limits
- Search page results now have width limits
- Seems like there are more
| Before | After |
| :----: | :----: |
| ![image](https://user-images.githubusercontent.com/26720877/227352152-df498ed1-629b-4c05-bfa6-fe46b272250f.png) | …

[HOTFIX - MERGE WITH GITFLOW] Word wrapping, mostly committee name

---

fec/fec/static/scss/components/_filters.scss

- Resolves #5675 
Add a width for `.content__section` when the filter panel is open.
1 front end
-  MUR search filter panel
- Admin fines search filter panel
| Before | After |
| :----: | :----: |
| ![image](https://user-images.githubusercontent.com/12799132/228085555-8d1afb63-3ea1-44d9-ab7d-b9ae9438ab68.png) | ![image](https://user-images.githubusercontent.com/12799132/228088658-9797cb06-0013-4bce-8757-d9fe06b5f7d1.png) |
| ![image](https://user-images.githubusercontent.com/12799132/228085568-d6a5cfa9-695a-4c79-b805-5d2319924d76.png) | <![image](https://user-images.githubusercontent.com/12799132/228088965-fb3c50f3-c23c-488c-be84-cb5816d7edff.png) |
branch | PR …

Add width setting for .filters.is-open + .content__section

---

.circleci/config.yml
requirements.txt

- Resolves https://github.com/fecgov/openFEC/issues/5400 
Our deploys are failing because codecov removed/deprecated their uploader package. To fix this, we have to move to their new [universal uploader](https://docs.codecov.com/docs/codecov-uploader).
-  circleci pipeline 
- requirements.txt
- view pipeline on circleCI: hhttps://app.circleci.com/pipelines/github/fecgov/fec-cms/2590/workflows/5ab27894-dfd2-4ed3-a258-82db62343796/jobs/5952
- view codecov report: https://app.codecov.io/github/fecgov/fec-cms/commit/556dcb6be61cd8e7cc5e2aee472fb7fdedf1c506
Other way to test: 
1. Create new branch based off of this branch : `git branch <new-branch-name> hotfix/use-new-codecov-uploader` 
2. Make any change to the code
3. Commit …

[MERGE WITH GIT FLOW] Hotfix/use new codecov uploader

---

fec/data/constants.py

In order to deploy a hotfix, I needed to revert this to 2018 so that it wouldn't get deployed premature of the actual release going out next week on 4/25. This PR changes the `DISTRICT_MAP_CUTOFF` back to 2024 so that the release cut for 4/25 will have this update.

Update district map cutoff to 2024

---

fec/data/templates/partials/browse-data/candidates.jinja
fec/data/views.py

- Resolves #5701 
- 2024 links for presidential candidate map exports is added
- Update the coverage date sentence
1 reviewer
- Check the Presidential map candidate exports box to make sure that the 2024 links and the sentence is updated according to the ticket
http://127.0.0.1:8000/data/browse-data/?tab=candidates

[HOTFIX - MERGE WITH GITFLOW] Hotfix/5701 add 2024 pres export links v2

---

fec/home/templates/home/meeting_page.html

- Resolves #5698 
Updates the first sentence of the open meeting page template to correct AM to a.m. (to follow Content Guide rule).
No second period is needed according to GPO Style Manual if sentence ends with a.m.
One front-end to make sure page isn't broken by this
Meeting pages
How to test:
First sentence of the open meeting page should end with a.m.

Corrects styling of AM to a.m. for open meeting first paragraph

---

fec/data/views.py
fec/fec/static/js/widgets/aggregate-totals-box.js

- Resolves #5657 
Updating Aggregate Totals to use the new aggregate endpoint
1-2 front-end
1 back-end
?
The Aggregate Totals box for raising and spending by the numbers.
**NOTE**: This PR also changes the default office for the by the numbers pages to P from S.
none
- [Raising: by the numbers](http://127.0.0.1:8000/data/raising-bythenumbers/)
- Should function as expected (start with correct election, update as election years are changed)
- Make sure the data are correct (i.e. that localhost matches dev)
- [Spending: by the numbers](http://127.0.0.1:8000/data/spending-bythenumbers/)
- Should function as expected (start with correct election, update as election years are changed)
- Make sure the data are correct (i.e. that …

5657 - Aggregate Totals Endpoints

---

fec/fec/static/js/modules/columns.js
fec/fec/static/js/modules/helpers.js
fec/fec/static/js/pages/candidate-single.js

Update the text under version column to display `Version unknown` instead of `Version unknown null` when `most_recent` flag is null.
- Resolves #2218 
1 content and 2 or more developers
-  Candidate filings section, Committee filings section, Filings, Presidential reports, house-senate and pac-party report data tables.
Example: PAC and party committee reports (https://www.fec.gov/data/reports/pac-party/?two_year_transaction_period=1988&data_type=processed&min_receipt_date=01%2F01%2F1987&max_receipt_date=12%2F31%2F1988)
**Before:**
**Now:**
**From Transaction Time period > 2000** , there are cases when Version is Unknown and yet have `fec_file_id` 
- `git checkout` `feature/2218-drop-null-filing-table`
- `cd fec`
- run `pytest`
- run `./manage.py runserver`
- Test …

Remove Null from display when amendment version is unknown

---

requirements.txt

- Resolves #5791
To remediate snyk vulnerability, upgrade django from v3.2.19 to v3.2.20
1 developer
**Before:**
**After:**
- run `git checkout develop`
- run `pyenv virtualenv venv-cms-5791` 
- run `pyenv activate venv-cms-5791`
- run `snyk test --file=requirements.txt --package-manager=pip` (ReDos vulnerability shows on django v3.9.19)
- run `git checkout feature/5791-upgrade-django`
- run `snyk test --file=requirements.txt --package-manager=pip` (ReDos vulnerability no longer appear)
- run `./manage.py runserver` (test cms datapages on browser )

upgrade django 

---

fec/fec/middleware.py

- Resolves #5843 
Adding `"https://tiles.stadiamaps.com/tiles/"` to our img-src CORS policy
One
Technically site-wide but only election search pages will benefit.
Current (broken) and fixed
None
- Check the homepage and the [elections search page](http://127.0.0.1:8000/data/elections/) to make sure the image tiles load

5843 - Election search map tiles

---

requirements.txt

upgrade gitpython to v3.1.32
- Resolves #5860 
1 developer
- run `git checkout develop`
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output show gitpython as vulnerable package)
- run `git checkout feature/5860-upgrade-gitpython`
- run `pyenv activate venv-cms`
- run `pip install -r requirements.txt` 
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output **no longer shows** gitpython as vulnerable package)

upgrade gitpython

---

tasks.py

- Removes the deploy to feature accidentally left in when 5806 was merged to dev

remove deploy to feature

---

.circleci/config.yml
package-lock.json
package.json

NPM 10 was released and it's not compatible with node versions below 18.17. We are currently pulling in the most recent NPM version in the circle config for API. I'm upgrading CMS to keep consistent across repos
2 devs 
Upgrade e-regs: https://github.com/fecgov/fec-eregs/issues/789
Upgrade pattern-library: https://github.com/fecgov/fec-pattern-library/issues/218
API research fix: https://github.com/fecgov/openFEC
-pull branch
-nvm install 18.17.1 (should be on npm 9.6.7)
-rm -rf node_modules
-npm i && npm run build
-flask run

upgrade node

---

fec/home/templates/home/candidate-and-committee-services/guides.html

Part of work in https://github.com/fecgov/fec-cms/issues/5828
Changes the URLS for the Guides on this page... 
Guides | Old URL | New URL
Candidate guide | (old) https://www.fec.gov/resources/cms-content/documents/candgui.pdf | (new) https://www.fec.gov/resources/cms-content/documents/policy-guidance/candgui.pdf
Party guide | (old) https://www.fec.gov/resources/cms-content/documents/partygui.pdf | (new) https://www.fec.gov/resources/cms-content/documents/policy-guidance/partygui.pdf
Corporate/Labor guide | (old) https://www.fec.gov/resources/cms-content/documents/colagui.pdf | (new) https://www.fec.gov/resources/cms-content/documents/policy-guidance/colagui.pdf
Nonconnected guide | (old) https://www.fec.gov/resources/cms-content/documents/nongui.pdf | (new) …

Update guides.html to update Guide URLs

---

fec/home/templates/home/meeting_page.html

Adds “Please check the meeting page for updates to the agenda, including cancellations.” after the hard-coded sentence “After security, attendees are escorted to the Commission hearing room.” to both the open meeting page language and the hearing page language.
One front end code review
One content team or PM team member to review language
Open meeting pages and hearing pages.

Update meeting_page.html to add sentence about cancellation to open meeting and hearing page templates

---

fec/fec/static/scss/elements/_forms.scss
tasks.py

Reduce padding to unobscure date-filter placeholder text
- Resolves #5844
one team member
Data and legal Datatable filters that have `mm/dd/yyyy` placeholder text
modified:   fec/static/scss/elements/_forms.scss
**Content/UX teams**
- This is pushed to dev space for testing:
- Check that placeholder text on data and legal datatables shows full text `mm/dd/yyyy`
- https://dev.fec.gov/data/loans/ (hover over `Incurrred date` fields)
- https://dev.fec.gov/data/legal/search/murs/
- Are there any others not covered by this CSS change?
**Devs:**
- checkout branch
-`npm run build-sass`
- Check that placeholder text on data and legal datatables shows full text `mm/dd/yyyy`
- http://127.0.0.1:8000/data/loans/ (hover over `Incurrred date` fields)
- http://127.0.0.1:8000/data/legal/search/murs/
- …

Unobscure date-filter placeholder text

---

requirements.txt

- Resolves #5896 
Upgrades django to 3.2.21
1 dev
Before: 
After:
- `git checkout develop`
- `pyenv virtualenv venv-cms-5896` 
- `pyenv activate venv-cms-5896`
-  `pip install -r requirements.txt`
-  `npm i && npm run build`   (maybe need `nvm install 18.17.1`)
- `snyk test --file=requirements.txt --package-manager=pip` 
- `gh pr checkout 5909` 
- `snyk test --file=requirements.txt --package-manager=pip` 

5896-upgrade django

---

fec/search/management/data/sitemap_pdf.xml

Incorrect metadata in document properties for two PDFs was affecting search result rendering. After correcting this, we need to update their lastmod dates on the sitemap so  the search.gov engine can pickup the change.
- Update lasmod dates for  `fecfrm3pposti.pdf` and `fecfrm4i.pdf` after correcting metada in their `document properties tab`. 
one content team member
- Test searching policy guidance docs for these forms, by the time you test this it should be re-indexed. See screenshots below of incorrect search results.
-  `fecfrm4i.pdf` Only listed the file name in the title because there was no title in the PDF document properties
- `fecfrm3pposti.pdf`  had the word "Sumamary" instead of "Summary" in the title
<hr>

New lastmod for fecfrm3pposti.pdf and  fecfrm4i.pdf

---

fec/home/templates/home/document_page.html

- Resolves #5918
`DocumentPages`, otherwise not navigable on the site, are showing in search results. This is a temporary fix so users will be able to get to the document if they access a DocumentPage through a search result link.  A final solution for handling this issue is being researchd. See this [comment/mockup in issue](https://github.com/fecgov/fec-cms/issues/5918#issuecomment-1738106863)
one frontend
Document pages in Reports about the FEC
There is a WIP/DRAFT PR that shows more options for the final solution https://github.com/fecgov/fec-cms/pull/5922
- You can login to Wagtail and navigate from the sidebar `Pages > Home > About > Reports about the FEC`, then go into one of the sections like `Agency Operations or FOiA` …

[MERGE BEFORE 09/28/23 RELEASE] Add link to document page

---

fec/data/templates/partials/browse-data/spending.jinja

- Resolves #5914 
Double check the language in the ticket "Search select disbursements from committees by the recipient, purpose, amount and date. Excludes outside spending to support or oppose candidates and allocated federal/nonfederal disbursements.” made it through to the PR

Update disbursement search language

---

fec/home/templates/home/document_page.html

The new logic that shows file extension on `DocumentPages(Reports about the fec)` was  causing some report pages to get a 500 server error with `index out of range` error. Since `self.file_extension` is a property on the model and not a field value it always returns "true" [Example 500 error](https://www.fec.gov/about/reports-about-fec/oig-reports/audit-agency-controls-governing-process-procurement-vendor-training-services-executive-summary/).
This logic was added in https://github.com/fecgov/fec-cms/pull/5931
One frontend
Reports about the FEC pages that do not have a document associated with them like :
https://www.fec.gov/about/reports-about-fec/oig-reports/audit-agency-controls-governing-process-procurement-vendor-training-services-executive-summary/
modified: …

Fix server error on some reports

---

fec/fec/static/scss/components/_icon-headings.scss
fec/fec/static/scss/components/_mega-menu.scss
fec/fec/templates/partials/navigation/nav-about.html
fec/home/templates/purgecss-homepage/full.html
fec/home/templates/purgecss-homepage/navs.html

- Resolves #5904 
Adding "Introduction to Campaign Finance and Elections" to the site's main nav
BONUS: I tweaked the layout of the right-angle quotes so they don't wrap to the next line
- Content for text and link accuracy
- UX for appearance
The site nav (every page across the site)
Current
This PR's version of the About menu with the Data menu open for comparison
Example of the wrapping I tried to fix (campaign finance statistics)
Smallest XS width
Smallest small width
Smallest medium width
- load any page on the site
- check the About menu for accurate links and layout _across all widths_
- check that line breaks aren't separating the right-angle quotes (») from their text _across all widths_

5904 About Menu: Intro to Campaign Finance and Elections

---

requirements.txt

- Resolves #5946 
Upgrades urllib3 to remove snyk vulnerability
1 or more devs
-  `urllib3` is a HTTP client for Python used by `requests`, which is used for server-side API calls (https://github.com/fecgov/fec-cms/blob/209cc8bb02d0337cb3dda485bb9c3f1264b5f3d7/fec/data/api_caller.py#L21)
- `pip install -r requirements.txt` or create a new virtual environment for this.
- Run your server `./manage.py runserver`
- Check out some pages with server-side calls like the candidate or committee profile pages
- Run `pytest`

5946- upgrade urllib3

---

fec/home/models.py
fec/home/views.py
tasks.py

- Exclude aliased press release pages under the guidance-search path from listings on https://www.fec.gov/updates/
- Resolves #5970
- Still need to resolve [this conversation](https://github.com/fecgov/fec-proxy/pull/379#issuecomment-1778531308) before doing this
one frontend, one content
Press release listings on https://www.fec.gov/updates/
modified:   home/models.py
modified:   home/views.py
**Only one listing for  FEC issues interim reporting guidance for national party committee accounts**
**Content team**
- On feature space go to https://fec-feature-cms.app.cloud.gov/updates/?page=2&update_type=press-release&year=2015
- Confirm that even though there is an alias of the National party accounts press release under …

Exclude duplicate press releases in /updates 

---

fec/fec/static/css/customize-editor.css
fec/home/blocks.py
tasks.py

- Fix hidden-rows-bug on Wagtail tableblocks using HandsonTable's setting: [renderallrows](https://handsontable.com/docs/javascript-data-grid/api/options/#renderallrows)
- Resolves #5910
one content team member and @djgarr. One developer optional.
Wagtail templates that use `TableBlock, CustomTableBlock and ReportingTableBlock`
modified:   fec/static/css/customize-editor.css
modified:   fec/home/blocks.py
Fixed only for Reporting dates tables in https://github.com/fecgov/fec-cms/pull/5786 using CSS -- now expanded to cover all tableblocks with a setting instead of CSS.
**Content team:** 
This is  pushed this to feature for testing.
- Open pages with `tableblocks` in Wagtail to see that all table rows are visible and editable:
- https://fec-feature-cms.app.cloud.gov/legal-resources/regulati …

Fix hidden-rows-bug on Wagtail tableblocks

---

fec/fec/static/scss/components/_headings.scss
tasks.py

Ensure date is completely aligned right, on pages with `<header class="heading--main heading--with-date">`
- Resolves #5959
One team member
Pages with `<header class="heading--main heading--with-date">` 
- Document pages
- Meeting pages 
- Digest, Press Release, Record and Tips for Treasurers pages
modified:   fec/static/scss/components/_headings.scss
@JonellaCulmer - If you need help getting your local working, let me know
- `git checkout feature/5959-right-align-date-heading`
- check pages with `<header class="heading--main heading--with-date">` to ensure that the date is aligned right regardless of how short the headline text is. 
Examples:
-  http://127.0.0.1:8000/about/reports-about-fec/foia-reports/chief-foia-officer-report-fy-2013/
- …

Ensure date is aligned right on heading w/ date

---

fec/data/templates/partials/debts-filter.jinja

- Resolves #5969 
switch line_number filter to new form_line_number filter that allows multiple inputs. Both form_line_number and line_number will work for a month to allow users a grace period, but then line_number will be removed. As it currently is not working satisfactorily for the front-end we should switch is as soon as possible to the the new hybrid property. 
1-2 devs, at least 1 front-end 
-  Debts data tables
https://github.com/fecgov/openFEC/pull/5627
deploy[ the api PR ](https://github.com/fecgov/openFEC/pull/5627) to dev 
- Make sure that FEC_API_URL is pointing to dev
- pull this branch
- cd fec
- Compare www to local  
-  Go to [debts data table …

switch line_number filter to form_line_number for debts

---

requirements.txt

- Resolves #5952 
Upgrade django to remove snyk vuln
NOTE: This is a blocker to upgrade to 4 https://github.com/cloud-gov/cg-django-uaa/issues/70
Extended support for 3 ends April 2024, we should keep this on our radar in early next year
1 dev
-  django
- pull this branch
- activate virtual environment
- cd fec

5953-upgrade django

---

fec/home/templates/home/commission_meetings.html
fec/home/templates/home/meeting_page.html

- Resolves #5998 
Changes time for open meetings from 10:30 a.m. to 10:00 a.m.
1 front end reviewer
- Commission meeting landing page
- All Commission open meeting pages

Update meeting page templates for 10 am time for 2024

---

requirements.txt

- Resolves #6007
This ticket removes a security vulnerability by upgrading urllib3 to v1.26.18.
-  server-side API calls
- Check out this branch 
- `snyk test --file=requirements.txt --package-manager=pip` (ensure urllib3 is not listed)
- `cd fec/`
-  `./manage.py runserver`
-  `pytest`
- Test pages with server-side calls like the candidate or committee profile pages

Upgrade Urllib3

---

fec/fec/static/js/modules/election-map.js

- Resolves #6027 
Removing the grey from the palette for district colors because it gets lost against our current map tiles
One?
The district-level colors of the election search maps
Districts
| Before | After | 
| :-- | :-- |
| <img width="465" alt="image" src="https://github.com/fecgov/fec-cms/assets/26720877/dd3beef8-203e-4ba0-b213-a1bd133d4f42"> | ![dists-after](https://github.com/fecgov/fec-cms/assets/26720877/08cea16b-07c9-4a8c-92ad-7e067e35cd90) |
| Looking especially at FL 8, 17, and 26… |  (east of Orlando, south of Tampa, and west of Miami) |
States
| Before and currently | Why we didn't change the palette for states |
| :-- | :-- |
| ![states-before](https://github.com/fecgov/fec-cms/assets/26720877/40c564e8-d639-4853-9384-9c1dd1f6c948) | …

6027 - Remove Grey from Election Search Maps

---

requirements.txt

- Resolves #6083 
This ticket upgrades Jinja2 to remove a security vulnerability. 
-  datatables/pages that use jinja 
- checkout this branch 
- ensure that snyk vulnerability is gone `snyk test --file=requirements.txt --package-manager=pip`
- pytest
- `./manage.py runserver` test datatables/ pages that use jinja

upgrade jinja2

---

fec/data/templates/election-lookup.jinja
fec/fec/static/js/modules/election-search.js
fec/fec/static/scss/components/_messages.scss
tasks.py

- Resolves #6080 
Updating some functionality on the election search page, generally targeting 
UX and front-end?
The election search page's various components
Before, with the problem areas circled
Afters
None
- `npm i`
- Check the [elections search page](http://127.0.0.1:8000/data/elections/
- map should appear for 2024+ only
- "District maps on this page" map disclaimer should appear for 2024+ only
- "Election maps are only available…" message should appear < 2024
- "Election maps are only available…" message should be top-aligned with the left column's content for >= medium widths
- FIND BY ZIP CODE field and 🔍 button should only be active >= 2024
- "Information about redistricting…" accordion item should only appear 2020+ …

6080 - Update Election Search

---

.circleci/config.yml
README.md
requirements.txt
runtime.txt

- Resolves #6058 
This pr upgrades python to version 3.10.13.
-  pytest
- circleci pipeline
1. Checkout this branch 
2. `pyenv install 3.10.13`
3. `pyenv virtualenv 3.10.13 <new test env>`
4. `pyenv activate <new test env>`
5. `pip install -r requirements.txt`
6. `npm i` 
7. `npm run build`
8. `pytest`
9. `cd fec`
10. `./manage.py runserver`
- check that the site's working as expected

upgrade python v3.10

---

fec/home/templates/home/office_page.html
tasks.py

- Resolves #6146
- Changes the office-sections anchors from `<a name=`... to `<a id=...` because `<a name` is deprecated and not what editors are looking for when creating an anchor-link(#) to a place in the page.
- Wraps the `extra info` field in rich-text class to make sure it styles rich-text elements as expected. 
1 reviewer (UX, content, developer) 
Ask to have it deployed to feature if you prefer to test it there
File(s) modified
modified:   home/templates/home/office_page.html
- office-sections anchors 
- `extra info` Wagtail  rich-text field 
- Checkout and run branch or ask to have it deployed to feature space for testing
- Create or test an existing  Office page to make sure the section anchors work.
- You can see …

Office template anchors and rich-text

---

fec/home/templates/home/meeting_page.html

- Resolves #6146
Remove language that previously referred to a separate caption file (transcript) being uploaded after meeting ends.
one
modified:   home/templates/home/meeting_page.html
- Look at the text on line 58 of  `home/templates/home/meeting_page.html`

Meeting page, remove reference to captions file

---

fec/legal/templates/layouts/legal-doc-search-results.jinja
fec/legal/templates/legal-statutes-landing.jinja
fec/legal/templates/macros/legal.jinja

Able to seach Statues using  titles (e.g., 26 or 52) and sections (e.g., 9001 or 30109) or the document name description (e.g.,short title )
1. Update statutes  language search example in [statutes page](https://www.fec.gov/data/legal/statutes/) and [statutes search feature](https://www.fec.gov/data/legal/search/statutes/)
2. Update the language in the [information box](https://www.fec.gov/data/legal/search/statutes/?)  at the top of the search 
1 UX and 1 Front end developer
- Statutes search  
**After:**
Statues Page:
Statues Search:
- Deploy this [test branch](https://app.circleci.com/pipelines/github/fecgov/fec-cms?branch=test-5747) to dev space and verify statues search example language changes and test the search functionality from the following links:
1. …

update statutes example search

---

.circleci/config.yml
README.md

- Resolves #6140 
This ticket upgrades the circleci pipeline to postgres 15 to match production. 
Note: Frontend developers can now switch over to pg15 on their local machines. 
-  circleci pipeline
1. rerun circleci build on [this](https://app.circleci.com/pipelines/github/fecgov/fec-cms/3241/workflows/dc07fe48-eccb-4f21-b2f7-2c44e2ebc698/jobs/6680) branch 
2. verify the circleci pipeline runs on postgres 15 and pytest passes.

upgrade to pg v15

---

fec/home/models.py

- Resolves #6149
`HomePageBannerAnnouncement` and `AlertForEmergencyUseOnly` pages will not show up in Wagtail sitemap and site search.
- Spot check by [searching 'option'](https://www.fec.gov/search/?query=option&type=site) or [searching 'offline](https://www.fec.gov/search/?query=offline&type=site) the global search box 
- Opening `https://www.fec.gov/sitemap-wagtail.xml/` and doing a "Ctl-f" search for "banner".  
one frontend, one content
models.py
https://www.fec.gov/sitemap-wagtail.xml
- While on develop or any other branch go to sitemap:   http://127.0.0.1:8000/sitemap-wagtail.xml/  and do a text search (Cmd-f ) on the page for "banner". You should  find  banners in the sitemap
-  checkout and run branch
- Do the same search. Should not find any banners.

Remove banners from sitemap and search index

---

fec/home/views.py
tasks.py

- Resolves #6118
- Added `search_updates()` function to convert the body (on pages with html fields) to a string and do a Python string search on them
- Preserve superior existing backend Postgres search for pages with searchable fields types (non-html)
- Exclude duplicate search results  on rare occurrences where both search options return results for the same query because  a page has both html and other database-searchable fields
one frontend AND one UX or content
The `/updates` keyword search
modified:   home/views.py
Coming soon...
This has been pushed to dev for testing, check with me to confirm its still live if you are testing there.
- do a keyword search for a term that appears in an html block of a Digest, PressRelease, Record, or TipsForTreasurers page …

Expand keyword search on /updates to include html content

---

fec/home/templates/blocks/af_search.html
fec/home/templates/blocks/mur_search.html
fec/legal/templates/legal-search-results-adrs.jinja
fec/legal/templates/legal-search-results-afs.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/legal-search-results.jinja

Removes references to eqs.fec.gov across the website.
1 developer, 1 UX
-  Global [legal search results page](http://localhost:8000/data/legal/search/?search_type=all&search=campaign)
- [MUR search page](http://localhost:8000/data/legal/search/murs/?search=campaign&search_type=murs)
- [AF search page](http://localhost:8000/data/legal/search/regulations/?search=campaign&search_type=regulations)
- [ADR search page](http://localhost:8000/data/legal/search/adrs/)(Feature to be released in the near future)
- MUR and AF wagtail search blocks on the [enforcement landing page](http://localhost:8000/legal-resources/enforcement/).
Take a look at the pages
- Pull down the PR and run it locally. Check out the pages linked in the …

Remove eqs.fec.gov references across the website

---

fec/legal/templates/legal-adr.jinja

- Resolves #6228
- Check whether the number of collated adrs is odd or even to determine the style of the appended  rows that follow (non_monetary_terms).
One dev
adr canonical page
https://github.com/fecgov/fec-cms/pull/6216
- Find an ADR with multiple rows in the disposition table and check correct alternating row styles
- An ADRs with only one non-monetary term for testing the change from `>1` to `>0` : http://127.0.0.1:8000/data/legal/alternative-dispute-resolution/1151/

ADR Canonical - Alternate row striping by disposition

---

fec/home/views.py

- Resolves #
- Related issue:  #6118 
- Related PR: https://github.com/fecgov/fec-cms/pull/6214
- The [original PR](https://github.com/fecgov/fec-cms/pull/6214) for resolving un-searchable html in `/updates` searches worked, but the search was noticeably slow when searching across all update-types. This PR speeds that search up.
- This PR also combines  a more inclusive text-search with the existing  `wagtail.search.backends.database` search for  `Open meetiings` and `Hearings` which will find more results for all years in addition to resolving the issue of previously unsearchable legacy pages with `imported_html` content.
One dev
One UX or One Content
-  `/updates` searches (PressRelease, WeeklyDigest, TipsForTreasurers and Record) 
-  Meetings page searches on `/meetings`
modified: …

Faster keyword search for updates and html search for legacy meetings

---

requirements.txt

- Resolves #6208 
Upgrades gunicorn to remove snyk vulnerability 
Breaking changes: 
V. 22
minimum version is Python 3.7
the limitations on valid characters in the HTTP method have been bounded to Internet Standards
requests specifying unsupported transfer coding (order) are refused by default (rare)
HTTP methods are no longer casefolded by default (IANA method registry contains none affected)
HTTP methods containing the number sign (#) are no longer accepted by default (rare)
HTTP versions < 1.0 or >= 2.0 are no longer accepted by default (rare, only HTTP/1.1 is supported)
HTTP versions consisting of multiple digits or containing a prefix/suffix are no longer accepted
HTTP header field names Gunicorn cannot safely map to variables are silently dropped, as in other software
HTTP headers …

6208-upgrade gunicorn

---

package-lock.json
package.json

- Resolves #6132 
Pins es5-ext temporarily until es6-weak-map increases their versioning. es5-ext is pulled in through weakmap 
ticket for removal of the pin is here https://github.com/fecgov/fec-cms/issues/6275
1 dev
-  es5 is used for polyfills for old browsers 
(make sure you're using node v. 18.17.1)
- run `snyk test --file=package.json` on develop (should see es5 snyk issue)
- rm -rf node_modules
- npm i && npm run build
- snyk test --file=package.json (should no longer see issue)
- cd fec

6132- add temporary es5 pin

---

fec/fec/static/scss/components/_hero.scss
fec/home/templates/home/oig_landing_page.html

- Resolves #6178 
- Resolves #6213 
Changing style rules for the logo/content block on the OIG page. Removed the background color and padding from the block so the content can set its own, though also moved those rules to the placeholder-oig-logo class
-UX
Only the OIG landing page, the logo/content block and the submit button
None
- check the screenshot …
- merge
- deploy
- publish my saved draft of the OIG page

OIG - move background color to oig-logo instead of its parent

---

.circleci/config.yml

Today we experienced failing builds due to CircleCI caching bad node_modules. This will increment the circleCI cache key to v2 to update the cache and fix failing builds.
1 developer
-  CircleCI builds
branch | PR
develop | [link](https://app.circleci.com/pipelines/github/fecgov/fec-cms/3448/workflows/196632af-eb98-4db0-8f8b-2c7e251c498f/jobs/6916)
feature/5259-document-type-filter-2 | [link](https://app.circleci.com/pipelines/github/fecgov/fec-cms/3446/workflows/5d171e49-2473-463d-91e4-e72f76698b7f/jobs/6911)
- Make sure that circleCI build passes for develop

Increment circleCI cache key to v2 to fix failing builds

---

manifest_prod.yml

- Resolves #6310 
Increases memory in CMS prod to 1.5G per instance as a follow-up item to the CPU entitlement meeting. 
1 dev (PM already approved)

increase memory for prod to 1.5

---

fec/data/templates/partials/browse-data/bulk-data.jinja

- Resolves #6327 
Add missing link for the 1979-1980 Contributions from committees to candidates & independent expenditures bulk data link.
1 reviewer
-  Bulk data page
- See screenshot and code. Ensure the link is correct.

Add missing 1979-1980 bulk data

---

fec/data/api_caller.py
fec/data/tests/test_legal_search.py
fec/legal/views.py

- Resolves #6282
- The `api_caller` is currently still searching our api regulations endpoint ([which will be removed](https://github.com/fecgov/openFEC/issues/5827) ) and that is where is gets its `results["regulations_returned"]` count which differs from the count returned from new eCFR regulations search.
- Remove the reference to regulations in api_caller and add `results["regulations_returned"]`  to `legal_search()`  in `legal/views.py`
- Remove tests for `api_caller` that reference regulations. There are tests for  regulations  in`ecfr_caller` 
one team member (frontend, content, UX)
Legal search boxes on these pages:
https://www.fec.gov/data/legal/search/
https://www.fec.gov/legal-resources/
Files changed:
modified:   data/api_caller.py
modified:   legal/views.py
modified: …

Fix regulations search results counts on global legal search

---

package-lock.json
package.json

- Resolves #6206 
Upgrades dompurify (still being used) to [the latest MSIE compatible version](https://www.npmjs.com/package/dompurify?activeTab=readme) 
I upgraded to the MSIE compatible version as I don't think we have guidance on whether we can fully drop IE, but that meeting is to be scheduled? @rfultz 
1 dev
-  API helpers
run snyk test --file=package.json on develop (should see es5 snyk issue)
rm -rf node_modules
npm i && npm run build
snyk test --file=package.json (should no longer see issue)
cd fec
python manage.py runserver

6206 upgrade dompurify

---

fec/fec/middleware.py
fec/fec/templates/500-status.html
fec/fec/templates/base.html

- Resolves #6347 
We're removing all references to the polyfill.io domain
- One front-end?
The base template and the 404 page reference the domain and its permissions are in middleware.
It looks like we were only using it for `Object.assign`—[which is very well supported](https://caniuse.com/?search=object.assign)—so this shouldn't be an issue, especially since our own polyfills file includes `Object.assign`
None
- `npm i` (probably not necessary)
- `npm run build` (probably not necessary)
- Things don't break?
- Open to suggestions for how to test a polyfill being requested if we don't have technology that requires that polyfill

6347 - Remove links and permissions for polyfill.io

---

fec/home/models.py

- Resolves #6204
Allow CustomPage as child of AboutLandingPage
one team member
AboutLandingPage template child page options
Modified: home/models.py
- Verify that, in Wagtail,  you can add a custom page as a child page of `about/ `(AboutLandingPage template)

Allow CustomPage as child of AboutLandingPage

---

fec/fec/static/js/modules/typeahead.js
fec/fec/static/scss/components/_search-bar.scss
fec/legal/templates/legal-search-results.jinja

- Resolves #6350 
- Adds legal search to global search autosuggest
- Also adds small fix to admin fines link in legal search results
1 front end
1 UX
- Global site autosuggest
- Legal search results page
- Try to use the global search box on any page. 
- Check the bottom of the list to see if the "search legal resources" option is there. 
- Click on the "search legal resources" option and make sure that the query is passed to the legal search results page.
- Test the admin fines link on legal search results page: http://localhost:8000/data/legal/search/?search_type=all&search=test

Add legal search to global search autosuggest

---

fec/fec/static/js/modules/typeahead.js

- Resolves #6378 
Stripping quotes from global search field
- Front-end
- Product manager(s)
The global search and everywhere it links
- Exact-match search terms will be bold and blue because they're an exact match.
- Search terms that we've altered on the way to the page aren't an exact match so they won't be bold or blue.
| | Production  | This PR |
| ------------- | ------------- | ------------- |
| `tester` | <img width="219" alt="image" src="https://github.com/user-attachments/assets/bf7bd029-0a46-4508-8e0e-00d56abc2b03">  | <img width="218" alt="image" src="https://github.com/user-attachments/assets/9f3c6504-2440-42e0-96ec-b9e6c0b40527">  |
| `"tester"` | <img width="219" alt="image" src="https://github.com/user-attachments/assets/e29751da-7f24-4ae1-86f3-577431d3a538">  | <img …

[HOTFIX - MERGE WITH GITFLOW] 6378 Quotes in Search 2

---

requirements.txt

- Resolves #6398
Pin setuptools to 71.1.0 to fix recent failing builds.
1 front end or backend
See ticket #6398 for associated branches and builds

pinned setuptools to v71.1.0 to fix failing builds

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja
fec/data/tests/test_committee.py
fec/data/views.py
fec/fec/settings/base.py
fec/fec/static/js/pages/committee-single.js
fec/fec/static/scss/elements/_elements.scss

- Resolves #6182 
- Resolves #6183 
Adding the "National party headquarters, recounts and convention accounts" sections to single committee pages
- UX
- front-end
- data SME
The single pages for committees
nah
- **SME**: Right now the National party sections will appear on every committee's page. What are the rules to show it? e.g. when `committee.designation == '[?]'`
- **UX**:
- Should the new section have _both_ kinds of coverage dates flags? (the sentence and the tag-like version)
- Should the new section have both the "See the financial…" sentence _and_ the Export button?
- Having both sections has given us too many top/bottom borders
- `npm i`
- Test the feature flag negative
- Edit base.py
- Comment out lines 115 and/or …

6182, 6183 National Party Accounts Data on Single Pages

---

fec/data/templates/macros/filters/years.jinja
fec/data/templates/partials/national-party-account-disbursements-filter.jinja
fec/data/templates/partials/national-party-account-receipts-filter.jinja

- Resolves #6316 
Adding optional date constraints for the cycles selector, like we have for the years selector
- UX
- front-end?
The cycle selector for the national party datatables but maybe every other cycle selector, too
nah
- `npm i`
- Check the [national party disbursements datatable](http://127.0.0.1:8000/data/national-party-account-disbursements/) cycle filter
- Check the [national party receipts datatable](http://127.0.0.1:8000/data/national-party-account-receipts/) cycle filter
- Check other datatables cycle filters (unlikely to have been affected)

6316 National Party Datatables Cycles Selector Limits

---

fec/legal/templates/legal-search-results.jinja
fec/legal/templates/partials/legal-search-results-adrs.jinja
fec/legal/templates/partials/legal-search-results-mur.jinja

- Fixes bug on global legal search results page that was preventing document highlights for MUR/ADR from being included. 
- Set a boolean for a specific rendering of documents when MUR/ADR partial is included in `legal-search-results.jinja`
- Maintain the existing logic to conditionally render docs on MUR/ADR datatables only when keyword or doc type filters are applied.
- Resolves #6334
One frontend, one UX
Global legal search results page
modified:   legal/templates/legal-search-results.jinja
modified:   legal/templates/partials/legal-search-results-adrs.jinja
modified:   legal/templates/partials/legal-search-results-mur.jinja 
- Search  a keyword on http://127.0.0.1:8000/data/legal/search/?search_type=murs
- Search  a keyword on …

Document highlights for MUR/ADR on global legal search results

---

requirements.txt

Bump wagtail to 5.2.6 to fix snyk-reported vulnerability
- Resolves #6394
1-2 devs
Wagtail.
modified:   requirements.txt
- activate a virtual env
- Before installing requirements.txt, run `snyk test --file=requirements.txt`
- You should see:  
```
✗ Regular Expression Denial of Service (ReDoS) (new) [High Severity][https://security.snyk.io/vuln/SNYK-PYTHON-WAGTAIL-7443632] in wagtail@5.2
```
- Run snyk test again
- You should no longer see the vulnerability
- You could also verify that wagtail is upgraded to 5.2.6 by running server and logging into Wagtail admin 
- Or drop into the python interpreter and verify :
```
python
>>> import wagtail
>>> wagtail.VERSION
```

Bump wagtail to 5.2.6 to fix vulnerability

---

fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja

- Resolves #6429 
We're removing the "See the financial summary for a breakdown of each type of account" sentences from the NPA section of the single committee pages for raising and spending
- front-end
- UX
- SME
The NPA sections of raising and spending on committee single pages
None
- Check a national party page

[HOTFIX - MERGE WITH GITFLOW] 6429 NPA Single Page Updates

---

requirements.txt

- Resolves #6343 
This ticket upgrades urllib3 to remove a security vulnerability. 
-  server-side API calls
- Check out this branch 
- activate your virtualenv 
- `snyk test --file=requirements.txt --package-manager=pip` (ensure urllib3 is not listed)
- pytest
- `cd fec/`
-  `./manage.py runserver`
- Test pages with server-side calls like the candidate or committee profile pages
You can also test by deploying [this](https://github.com/fecgov/fec-cms/tree/test-urllib3-upgrade) test branch to stage

Upgrade urllib3v2.2.2

---

requirements.txt

- Resolves #6376 
This PR upgrades django to remove security vulnerabilities. 
Note: we will not be able to upgrade django to v5 until wagtail is upgraded to version > 5.2 
-  django
- `git checkout feature/6376-upgrade-django`
- activate your virtual env
-  `pip install -r requirements.txt`
- `snyk test --file=requirements.txt --package-manager=pip` - make sure that django does not appear in list

upgrade django v4.2.15

---

fec/data/api_caller.py
fec/data/tests/test_legal_search.py
fec/fec/static/js/legal.js
fec/fec/static/js/legal/Filters.cjs
fec/fec/static/js/modules/keyword-modal.js
fec/home/templates/partials/legal-keyword-modal.html
fec/legal/templates/layouts/legal-doc-search-results.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/macros/legal.jinja
fec/legal/templates/partials/legal-keyword-modal.jinja
fec/legal/views.py

- Resolves #6360 
This updates the query string syntax that is used on the web UI as well as what is submitted in the API query string. Refer to the [ticket](https://github.com/fecgov/fec-cms/issues/6360) for the syntax.
1 Developer
1 UX
- More keyword search for all legal documents (MURs, ADRs, AFs, AOs, Statutes)
- https://fec-feature-cms.app.cloud.gov/data/legal/search/murs/
- https://fec-feature-cms.app.cloud.gov/data/legal/search/adrs/
- https://fec-feature-cms.app.cloud.gov/data/legal/search/admin_fines/
- https://fec-feature-cms.app.cloud.gov/data/legal/search/statutes/
- https://fec-feature-cms.app.cloud.gov/data/legal/search/advisory-opinions/
branch | PR …

Update bool operator syntax for Elasticsearch simple_query_string and excludes

---

package-lock.json
package.json

Remove unused node packages `es6-weak-map` and `es5-ext` from package*.json files
- Resolves [#6275](https://github.com/fecgov/fec-cms/issues/6275)
2 developers
- run `git checkout feature/6275-delete-es5-ext`
- run `pyenv virtualenv activate <new virtualenv>`
- run `pyenv activate <new virtualenv>`
- run `pip install -r requirements-dev.txt`
- run `rm -rf node_modules`
- run `npm i`
- run `npm run build`
- run `npm run test-single`
- run `cd fec`
- run server: `./manage.py runserver` (CMS app runs OK without any errors)

Remove unused node pkgs, es6-weak-map and es5-ext

---

bin/run.sh
requirements.txt
tasks.py

- Resolves #6400 
1. Remove unused notify code block and slack environment variabless
2. Delete archived slacker package from requirements.txt file
3. Bump setuptools to v73.0.0
one developer
- deploy a test branch to `dev` space. CMS app should deploy successfully, with setuptools v73.0.1

Remove unused slacker python package and notify function

---

fec/fec/static/js/modules/tables.js
fec/fec/static/js/templates/comparison.hbs
fec/fec/static/scss/components/_dropdowns.scss
fec/fec/tests/js/tables.js
tasks.py

- Limit the candidates selected on contribution by size and state to 10
- As explained in this comment:
https://github.com/fecgov/fec-cms/issues/6186#issuecomment-2047690409
- Resolves #6226
One developer, One UX
Election page, Contributions by size and state 
modified:   fec/static/js/modules/tables.js
modified:   fec/static/scss/components/_dropdowns.scss
-  `npm run build`
- Go to an election profile page, individual contribution tab: Example: http://127.0.0.1:8000/data/elections/senate/FL/2024/#individual-contributions
- You should only be able to have 10 candidates' checkboxes checked 
- Checkboxes above 10 …

Limit 10 candidates for contribution by size and state

---

fec/data/templates/partials/candidate/other-spending-tab.jinja
fec/data/templates/partials/candidate/raising.jinja
fec/data/templates/partials/candidate/spending.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja
fec/data/templatetags/filters.py

- Resolves #6414 
Trying to prevent line breaks from landing in the middle of dates so they're easier to read.
As a bonus, wrapping those long dates in `<time>` elements to make them a little more accessible.
- product manager?
- front-end?
- UX?
- content?
Candidate profile pages
Committee profile pages
Site editors could also wrap dates in `<time></time>` such as
`<time>December 31, 1999</time>` or `<time datetime="1999-12-31">December 31, 1999</time>`
(if the `datetime` attribute is included, it should be in the ISO format of `YYYY-MM-DD`)
Above: what this PR does
Below: _why_ (highlighted in blue)
None
- Candidate pages - across the various widths, line breaks should not wrap
- the dates in Total Receipts
- the dates in Total disbursements
- other …

6414 Dates & Time Elements

---

fec/legal/templates/legal-current-mur.jinja
fec/legal/templates/partials/legal-search-results-mur.jinja
fec/legal/views.py

- Resolves #6498 
Update subjects list to use list comprehension
1 developer
- MUR search page - http://localhost:8000/data/legal/search/murs/
- Current MUR individual page - http://localhost:8000/data/legal/matter-under-review/8231/
branch | PR
feature/5965-add-case-subject-filters | [link](https://github.com/fecgov/openFEC/pull/5997)
- Go to [MUR search page](http://localhost:8000/data/legal/search/murs/) and make sure that the "subjects" list is populating
- Go to any [current MUR page](http://localhost:8000/data/legal/matter-under-review/8231/) and make sure that the "subjects" list is populating

Update subjects list in template

---

fec/fec/static/js/data-init.js
fec/fec/static/js/global.js
fec/fec/static/js/init.js
fec/home/templates/home/full_width_page.html
tasks.py

- Resolves #6493
- Add `a11y-dialog.js` to `global.js` to fix inoperable modal windows on new reporting dates tables. 
- Remove `a11y-dialog.js` from `init.js` and `data-init.js`
one frontend
- New reporting dates tables that use `reporting_dates_table.html`
- Legacy reporting dates tables that use `full_width_page.html`
- methodology buttons on any page that now gets the a11y JS from global.js 
https://github.com/fecgov/fec-cms/pull/5798
- Checkout and `npm run build-js`
- Test a new reporting dates table page and verify that the header modals work as in the gif above.:
- **Local** (might need to be published from draft to test):  http://127.0.0.1:8000/help-candidates-and-committees/dates-and-deadlines/dates-2024-reporting-dates-and-deadlines/congressional-pre-elec …

Add a11y modal dialog to global.js

---

fec/data/templates/macros/filters/checkbox.jinja
fec/legal/templates/legal-search-results-murs.jinja

- Resolves #6504 
Adding a tooltip for the MURs search Final disposition filter, but also had to create that option for checkbox.checkbox_dropdown_multiple()
- 1 Front-end
- optional: UX for appearance, content
- optional: Content
-  Everywhere checkbox.checkbox_dropdown_multiple is being called, but the default shouldn't affect anything else
- [MURs search](http://127.0.0.1:8000/data/legal/search/enforcement/) Final disposition filter should now have a tooltip
After:
None?
**Note:** The Case details accordion must exist
- report-type
- Monthly Reports
- Quarterly Reports
- Semiannual Reports
- Election Sensitive Reports
- Bundling Reports
- Other Reports
- debts
- form line number for House or Senate …

6504 MURs Final Disposition Tooltip

---

requirements.txt

- Resolves #6506 and https://github.com/fecgov/fec-cms/issues/6489
This PR upgrades django to remediate a security vulnerability. 
-  django
- `git checkout feature/6506-upgrade-django`
- activate your virtual env
-  `pip install -r requirements.txt`
- `snyk test --file=requirements.txt --package-manager=pip` - make sure that django does not appear in list

Upgrade django v4.2.16

---

fec/data/api_caller.py
fec/legal/templates/legal-advisory-opinion.jinja

- Resolves #6487 
Final opinion date should now be using `issue_date` rather than `document.date`.
1 engineer
-  Advisor opinions canonical page
- Look at this [spreadsheet](https://docs.google.com/spreadsheets/d/1fKNeBEgEWppeuxDjb_cF6pMlCFzonWN6kRWdCa-x9qY/edit?gid=0#gid=0) to check that the AOs with incorrect final opinion dates. They should now all be using the issue_date.
- Check any AO individual canonical page to make sure that the final opinions are also using issue_date.

Use issue_date for final opinion date

---

fec/fec/static/js/data-init.js
fec/fec/static/js/global.js
fec/fec/static/js/init.js
fec/fec/static/scss/components/_site-header.scss

- Resolves #6536 
- Resolves #6516 
Moving the accordion initialization to global.js because it didn't exist in home.js but was duped in both init.js and data-init.js. Since we need it on every page, we're moving it to global
Digging in to the .gov banner, I unbolded the datatables version (its font-weight was being overridden by accordion styles).
- front-end
The .gov banner but also every accordion. We should check a few templates.
Not bold
It opens again
None
- Check that the homepage .gov banner opens and closes as expected.
- Check a few other styles of templates to make sure there are no errors with accordions otherwise (calendar, cms, data, legal, 404?)
- Check that the datatable pages' version of the .gov banner isn't …

.gov Banner on Homepage, Datatables

---

fec/data/api_caller.py
fec/data/constants.py
fec/legal/templates/partials/legal-search-results-mur.jinja
fec/legal/views.py

- Resolves #6508 
Archived MUR 3620 has a rare case where it was reopened without creating a different MUR number. Therefore, it will have 2 separate MUR cases attached to it, one is the current case and the other is the archived case. This PR will handle the particular URL depending on which case you are interested in seeing.
1 engineer
-  MUR 3620
- Go to http://localhost:8000/data/legal/search/murs/?search_type=murs&case_no=3620 and see the results for MUR number 3620. There should be 2, one archived case, and one current case.
- Archived case should have this URL: http://localhost:8000/data/legal/matter-under-review/3620?mur_type=archived
- Current case should have this URL: …

Handle URL for archived MUR 3620

---

fec/fec/templates/500-status.html
fec/fec/templates/base.html
fec/fec/templates/home_base.html

- Resolves #6532 
Doesn't add Tag Manager to pages if request.is_preview. 
(Only edited the .html templates because the .jinja templates aren't in Wagtail so won't appear in the content editor's preview panel.)
- One or two who can log in to the Wagtail editor on localhost
- The home base template
- The base template for other Wagtail pages
- The 500 template (for consistency)
None
- Pull, build, and run develop (or any branch but this one)
- Log in to the localhost content editor
- Start to edit any page that gives you a preview (all/any of them?) (No reason to make any edits or save anything)
- Check inspector for that preview
- cmd-f for "tagmanager"; there should be at least two occurrences
- Switch to _this_ branch (the one for this PR)
- Log in to the localhost …

6532 - Remove Tag Manager from Pages in Preview

---

fec/fec/static/scss/components/_entity-header.scss

- Resolves #6505 
There's an extra visual separator after the last item in entity headers. This removes that right border when the element is the last-child (i.e. it's the last html element in its html element parent)
- design
- code approach
Anywhere .entity__type is used but it seems like it's only here inside entity-header
None
- Open a [candidate](http://127.0.0.1:8000/data/committee/C00431445/) and check the entity_type items (e.g. active/terminated, registration date)
- Across widths, the final item should not have the following visual separator (which was a border-right)
**Are we using this anywhere else?**

6505 - Remove right border from entity_type:last-child

---

fec/data/constants.py

- Resolves https://github.com/fecgov/fec-cms/issues/6546
Update mur disposition ids
one developer
mur search disposition filter
- test mur dispositon category id filter functionality 
- The new MUR disposition category list:
[ref_case_disposition_category.csv](https://github.com/user-attachments/files/17682305/ref_case_disposition_category.csv)
- New IDs are not in API yet

Update mur disposition ids

---

requirements.txt

- Resolves #6544 
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output will show gevent as vulnerable package)
-  checkout this branch
- run `pyenv activate`  your virtual env
- run `pip install -r requirements.txt` 
- run `snyk test --file=requirements.txt --package-manager=pip` (Terminal output no longer shows gevent as vulnerable package)

upgrade gevent v24

---

fec/fec/settings/base.py

- Resolves #5923
Remove all  SEARCHGOV env vars from `all cloud environments` and `app code(base.py)`,  except these two:
SEARCHGOV_API_ACCESS_KEY
SEARCHGOV_POLICY_GUIDANCE_KEY
one frontend OR one backend
modified: fec/fec/settings/base.py
`fec-creds-*`  on all cloud environments were edited accordingly
https://github.com/fecgov/fec-cms/pull/5925
- There is not really a way to test this except to confirm that search results still work on prod
- Or you could check the `fec-creds-*`  dictionaries on cloud environments to make sure only the only remaining searchgov vars are:
- SEARCHGOV_API_ACCESS_KEY
- SEARCHGOV_POLICY_GUIDANCE_KEY

Remove legacy search.gov env vars from code and cloud environments

---

fec/fec/static/js/legal-search-ao.js
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja

- Resolves #6558 
- Resolves #6559 
Fixing the AO keyword search functionality.
- SME
- Front-end
The AO search page and its filters
None
None
- **Other filters should be unaffected**
- Keyword search should work as expected whether one uses
- the More Keyword Options pop-up
- the Enter button while typing in the field
- the magnifying button while typing in the field
- the Tab button while typing in the field
- In the right column, the AO number links should work correctly
- on first load (testing the Jinja template)
- after filters have been changed (testing the JavaScript fetching results)

[HOTFIX - merge with gitflow] hotfix/6558 6559 ao keyword search

---

fec/data/templates/macros/filters/checkbox.jinja
fec/data/templates/macros/filters/committee-types.jinja
fec/data/templates/macros/filters/contributor-states.jinja
fec/data/templates/macros/filters/districts.jinja
fec/data/templates/macros/filters/states.jinja
fec/data/templates/macros/filters/years.jinja
fec/data/templates/partials/filters/audit-committee-types.jinja
fec/fec/static/js/modules/dropdowns.js
fec/fec/static/js/templates/comparison.hbs
fec/fec/static/scss/components/_dropdowns.scss
fec/fec/tests/js/tables.js
package-lock.json
package.json

- Resolves #6510 
Bringing back the longer dropdowns' scrolling handles but doing so by moving to a native solution, away from a JavaScript package (perfect-scrollbar)
- UX/Design
- Front-end
- Every `.dropdown__panel` across the site e.g. filters, Calendar, Legal
| Production  | Pattern library | This PR | 
| ------------- | ------------- | ------------- |
| <img width="297" alt="image" src="https://github.com/user-attachments/assets/4cb7b620-1375-42e1-afcc-f62ff0f33b36">  | <img width="298" alt="image" src="https://github.com/user-attachments/assets/627f5959-3623-4846-a711-1d914dba3d31">  | <img width="296" alt="image" src="https://github.com/user-attachments/assets/5aadedcf-294d-4ffd-8166-ceb196109a9c">  |
None
**Known issue**: Firefox doesn't like …

6510 Dropdowns Scrolling

---

fec/fec/static/js/templates/feedback.hbs
fec/fec/static/scss/components/_feedback.scss
fec/home/templates/purgecss-homepage/full.html
fec/home/templates/purgecss-homepage/toggled.html

- Resolves #6497 
Adding a new section to the Feedback panel
- UX/design
- 1 front-end
The feedback panel on the homepage and site-wide
None
- `npm i`
- At different widths, open the feedback box and click the signup form on
- Homepage
- Wagtail page
- Data page

Add signup button to feedback panel

---

fec/data/templates/datatable.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja
fec/data/views_datatables.py
fec/fec/static/scss/components/_datatables.scss

- Resolves #6540 
Adding disclaimers under the datatables for the national party accounts raising & spending
- UX/design
- 1 front-end
Technically every datatable page would be affected but the only visible differences should be for national party disbursement and receipts.
Disbursements
Receipts
None
- `npm i`
- The disclaimer should appear for [disbursements](http://127.0.0.1:8000/data/national-party-account-disbursements/)
- The disclaimer should appear for [receipts](http://127.0.0.1:8000/data/national-party-account-receipts/)
- Disclaimers should not appear for any other datatable page (candidate and committee single pages still have their own disclaimers under their smaller tables)

6540 Add Disclaimers to National Party Datatables

---

fec/fec/static/scss/components/_datatables.scss
fec/fec/static/scss/components/_site-header.scss
fec/fec/static/scss/components/_table-styles.scss
fec/fec/static/scss/elements/_elements.scss

- Resolves #5225 
Adding style rules to print href values when printing pages. Any affected elements will get their border-bottom removed, will get an underline (printing borders can be tricky) and will get its `href` value appended after it in the body of the page, inside brackets: `\00a0[href]` (`\00a0` is a space)
Then the rules are to include a link's href value if it's one of
- `#main a.button` (main content, any `<a>` with the `button` class)
- `#main h2 a` (main content, any `<a>` inside of `<h2>`)
- `#main h3 a` (main content, any `<a>` inside of `<h3>`)
- `#main li > a:first-child` (main content, `<li><a>` (first child directly inside the `<li>`))
- `#main p a` (main content, any `<a>` inside any `<p>`)
- `#main .message a` (main content, any `<a>` inside any `.message`)
- …

5225 - Show HREF on Print-outs

---

fec/data/templates/layouts/main.jinja
fec/data/templates/partials/meta-tags.jinja
fec/fec/templates/base.html
fec/fec/templates/home_base.html

- Resolves #6564 
- code review
- Anywhere `CANONICAL_BASE` was being used on the front-end but I couldn't find it in the repo
- The `<link rel="canonical">` href values for every jinja template, so everything under `/data/`—everything not in Wagtail
Removing `CANONICAL_BASE` from front-end:
None
- Review the `<link rel="canonical">` `href` values for
- homepage
- some Wagtail pages
- several Jinja pages
- several Jinja pages with query params (that shouldn't be included in the canonical tag)
- Are there places where `CANONICAL_BASE` was being used by the front-end?

6564 - Fix canonical rel links

---

fec/data/api_caller.py
fec/legal/templates/legal-advisory-opinion.jinja

Revert recent changes for final opinion issue date so recent AO-2024-15 can render correctly on site
PR: https://github.com/fecgov/fec-cms/pull/6541
one developer
- Checkout and run branch
- Make sure the link to page for AO-2024-15 from AO datatable works and that is shows and links properly to final opinion document

[MERGE WITH GIT FLOW] Temporarily revert final opinion issue date changes

---

fec/fec/static/js/legal-search-ao.js

- Resolves #6600 
- Dev(s)?
The queries that run after a user changes the Search Keywords filter for AOs
None
- Experiment with the [AO search](http://127.0.0.1:8000/data/legal/search/advisory-opinions/) filters

6600 - AOs q_exclude filters

---

fec/home/templates/home/commissioner_page.html

- Resolves #6630 
Update Commissioner downloadable photo to be "Download official photo"
1 front-end
-  Commissioner pages
- Go to a commissioner page that contains a downloadable photo and check the button to make sure it has the correct text

Update downloadable photo text

---

fec/fec/static/js/legal-search-ao.js

- Resolves #6561 
Fixing the pagination buttons for AOs and resetting the `offset` when filters change.
- 1 Front-end and/or UX?
The AO search template, its pagination and its filters controls (all of them independent from the other legal search tools from datatables and those filters)
None
- `manage.py runserver`
- Pagination - first & current page buttons ([sample url](http://127.0.0.1:8000/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_citation_require_all=false&ao_min_issue_date=&ao_max_issue_date=&ao_min_request_date=&ao_max_request_date=&limit=20&search=testing&ao_doc_category_id=F&sort=-ao_no))
- Should start on page 1
- Should show the page 1 button (as opposed to being absent)
- Should not offer a page 3
- Clicking page 2 should …

6561 AO Search Pagination and Page Offset

---

fec/fec/static/js/modules/typeahead.js
fec/legal/templates/layouts/legal-doc-search-results.jinja
fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/partials/legal-pagination.jinja
fec/legal/templates/partials/legal-search-results-adrs.jinja
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja
fec/legal/templates/partials/legal-search-results-afs.jinja
fec/legal/templates/partials/legal-search-results-mur.jinja
fec/legal/views.py

- Resolves #6445 
Adding the citations filters for MURs searches
**ALSO** fixed a related oversight for AOs search
- front-end
- UX and/or SMEs
- MURs templates
- views.py
- typeahead filters can now handle citations
- tweaks to other Legal pagination button values (instead of one huge string)
- legal search results template for filter tag updates
- AOs templates
Updated filter order:
| 1 | 2 | 3 | 4 |
| --- | --- | --- | --- |
|<img width="336" alt="image" src="https://github.com/user-attachments/assets/2a84e9cc-6cb3-4006-a9c0-fe0bba459b99">|<img width="336" alt="image" src="https://github.com/user-attachments/assets/844aa797-bb69-42d3-a1ad-3db8aaa617a3">|<img width="336" alt="image" src="https://github.com/user-attachments/assets/01329642-5a06-42aa-93d4-5bc03a806c43">|<img width="336" …

6445 MUR citation filters

---

.circleci/config.yml
README.md
requirements.txt
runtime.txt

- Resolves #6419 
This PR upgrades python to v3.11
-  tasks.py
- deploy
branch | PR
api | https://github.com/fecgov/openFEC/pull/6097
- install python 3.11: `pyenv install 3.11`
- create new virtual environment: `pyenv virtualenv 3.11 <new env>`
- activate virtual environment: `pyenv activate <new env>`
- install dependencies: `pip install -r requirements.txt` and  `pip install -r requirements-dev.txt`
- Note: I had to upgrade pip, setuptools, packaging, and wheel locally
-   `pytest`
- test invoke command: 
- `invoke add-hooks`
- test cms: `cd fec`  then `./manage.py runserver `
- test deploy using dev test branch: …

Upgrade python v3.11

---

fec/fec/wagtail_hooks.py
fec/home/models.py
fec/home/wagtail_hooks.py
requirements.txt

- Resolves #6416 
Upgrades to Wagtail 6.3 (LTS)
**Relevant changes in Wagtail 6.0**
[Changes for users ](https://guide.wagtail.org/en-6.3.x/releases/new-in-wagtail-6-3/#universal-design)
- NEW Universal search is shown in the screenshots below
[Adds support for Django 5.0](https://docs.wagtail.org/en/stable/releases/upgrading.html?#compatible-django-python-versions) (still supports 4.2) 
- I put in a ticket to upgrade to Django 5.0/python 3.12 (https://github.com/fecgov/fec-cms/issues/6642), but that work is blocked by cg-django-uaa. I put in a ticket for upgrading cg-django-uaa here(https://github.com/cloud-gov/django-uaa/issues/81). 
Wagtail 6.0 has removed the ModelAdmin app
- We made this change when moving to 5.2 
- Follow-up work is happening after this PR …

6416-upgrade Wagtail to 6.3

---

fec/data/templates/partials/browse-data/bulk-data.jinja
fec/data/templates/partials/browse-data/candidates.jinja
fec/data/templates/partials/browse-data/committees.jinja
fec/data/templates/partials/browse-data/filings-reports.jinja
fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja

Add 2023-2024 links for bulk datasets
- Resolves #6645 
1 developer
-  [Download bulk data](https://www.fec.gov/data/browse-data/?tab=bulk-data)
**Before:** 
**After:**
-  run `git checkout feature/6645-add-bulk-data-links`
- run `pyenv activate <cms virtualenv>`
- run ` cd fec`
- run `./manage.py runserver`
-  Verify newly setup 2025-2026 links are available under [Download bulk data](http://localhost:8000/data/browse-data/?tab=bulk-data)

Add 2023-2024 links for bulk datasets

---

.circleci/config.yml
package-lock.json
package.json

The Cloud.gov v2 API for Cloud Foundry is reaching its end-of-life. CF CLI versions 6 and 7 still rely on Cloud Foundry API v2 and will no longer work at some point with foundations that have disabled it. However, CF CLI v8 no longer uses Cloud Foundry API v2. For more details, refer to this [link](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0032-cfapiv2-eol.md#impact-and-consequences).
1. circleci/config.yml, is upgraded to CF CLI v8.9.0. This version supports Cloud Foundry API v3. Deploying to a cloud.gov space should work smoothly with this update
2. Update node/npm combo to fix the node/npm inconsistencies in circleci.  node v22.1.0 uses nvm 10.7.0. 
3. fec-pattern-library repo is also upgraded to use node v22.1.0 and nvm 10.7.0.
- ## Resolves …

upgrade cf cli 

---

fec/fec/static/scss/components/_cards.scss

- Resolves #6666 
Fixing the cards' icon images for the alternating-bg cards
- Dev or UX or Content?
The CSS for cards with alternating backgrounds, only reverting the order with a special override to allow declarations to follow attributes/elements (e.g. `declaration: value;` after `& .child {`)
None
- Check that [reporting cards' icon images](http://127.0.0.1:8000/help-candidates-and-committees/candidate-taking-receipts/questionable-contributions/) are correct (like the screenshot above, not like on www or Pattern Library)

6666 Fix icons for cards with alternating backgrounds

---

requirements.txt

- Resolves #6661 
This PR upgrades our db driver to make it [compatible with gevent ](https://github.com/psycopg/psycopg/issues/527)
changes---https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html
NOTE I'm not upgrading to the latest versions due to open issues in the [gevent repos with performance. ](https://github.com/psycopg/psycopg/issues/888)
1-2 devs
-  connections to db waiting should be once again non-blocking
- gh pr checkout 6662
- pyenv virtualenv 3.11.9 cms
- pyenv activate cms
- pip install -r requirements.txt 
- pip install -r requirements-dev.txt
- npm i && npm run build 
- cd fec
- pytest
Load tests [here](https://docs.google.com/spreadsheets/d/119Oq_p640dtbHby9PZeBdvOrTDezxGTja …

upgrade psycopg

---

requirements.txt

Update Django to a minor patch version to resolve snyk vulnerabilities:
https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-8623541
https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-8623542
- Resolves #6643
1 Developer
**Before:** 
**After:**
- run `git checkout develop`
- run `pyenv activate <cms virtualenv>`
- run `snyk test --file=requirements.tx`t (Snyk flags django v4.1.17 as vulnerable)
- run `git checkout feature/6643-upgrade-django`
- run `pyenv activate < new cms virtualenv>`
- run `pip install -r requirements-dev.txt`
- run `snyk test --file=requirements.txt` (Snyk NO longer flags django as vulnerable)
- cd fec
- ./manage.py runserver (test cms app)

Update Django to a minor patch version to fix the snyk vulnerability

---

fec/data/templates/partials/browse-data/candidates.jinja

Add 2025-2026 bulk datasets links  under  **candidates/all candidates** section
- Related #6645 
1 developer
https://github.com/fecgov/fec-cms/pull/6647
-  [Browse data Candidates](https://www.fec.gov/data/browse-data/?tab=candidates)
**Before: In Production** 
**After: In local branch**
-  run `git checkout feature/add-all-candidates-bulk-downloads-link`
- run `pyenv activate <cms virtualenv>`
- run ` cd fec`
- run `./manage.py runserver`
-  Verify newly setup 2025-2026 links are available under [Candidates/All candidates ](http://127.0.0.1:8000/data/browse-data/?tab=candidates)

Add 2025-2026 links for bulk datasets

---

fec/fec/static/js/modules/calc-admin-fines-logic.js
fec/fec/static/scss/components/_calc-admin-fines.scss

- Resolves #6122 
Changed a bit of text for haven't-been-accessed and polished the ⓘ icon margins
- bug filer (UX)
- a dev?
- The language for that one item in the admin fines calculator
- CSS rules for those icons in the admin fines calculator
- Strengthened a CSS rule to prevent scrolling `<body>` while the calculator is open
www above, localhost below
None
- Check the [admin fines calculator](http://127.0.0.1:8000/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine)
- Open the calculator by clicking 'Calculate estimated fine'
- Click 'Start calculating'
- Choose 'I haven't been assessed a fine'
- Click 'Next'
To check

6122 - Admin Fines Calc Visual Polish

---

fec/legal/templates/legal-admin_fine.jinja

- Resolves #6684 
Updates disposition rows to use `penalty` instead of `amount` for penalty values.
1 engineer
-  AF canonical pages
https://github.com/fecgov/openFEC/pull/6023/files#diff-dfe44ead3abda2c14d09833b0191cf66c3cad807fdd2c4b97cf5919e5fb16403R230
- Try a few admin fine pages:
- http://localhost:8000/data/legal/administrative-fine/4463/
- http://localhost:8000/data/legal/administrative-fine/4245/
- http://localhost:8000/data/legal/administrative-fine/4158/

Fix Admin fines penalty amounts

---

fec/data/constants.py
fec/data/views.py
fec/home/templates/home/home_page.html
fec/home/templatetags/top_entities.py

- Resolves #6689 
Updated the default constants for `END_YEAR`, `DEFAULT_ELECTION_YEAR`, and `DISTRICT_MAP_CUTOFF` to 2026 for the new year. Also updated visualizations to default to Senate 2026 for the new election two-year-period.
1 engineer
- Homepage, Who's raising/spending the most visualization: http://localhost:8000/
- Raising by the numbers: http://localhost:8000/data/raising-bythenumbers/
- Spending by the numbers: http://localhost:8000/data/spending-bythenumbers/
- Elections district map: http://localhost:8000/data/elections/
- Transaction and reports datatables should now show 2025-2026 as a year option. Try http://localhost:8000/data/filings/?data_type=processed and http://localhost:8000/data/receipts/. May want …

Update year and office constants

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja
fec/fec/static/js/modules/tables.js
fec/fec/static/js/pages/committee-single.js

- Resolves #5353 
Adding the donations tables for inaugural committees
- dev
- UX
- SME(s)? (Tricia?)
The left column for single committee pages but, because of the if, we should check other non-inaugural committees' pages to make sure they haven't changed.  
| Before / Production  | After / this PR |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/e18bf01b-b375-4bf0-ade5-fb89391c8c23)  | ![image](https://github.com/user-attachments/assets/5ecc88c0-7955-4bf4-81c9-6867a0b3b761)  |
None
- Some inaugural committees to test (these types of committees are limited)
- [2009](http://127.0.0.1:8000/data/committee/C00458166/)
- [2013](http://127.0.0.1:8000/data/committee/C00540005/)
- Review
- …

5353 - Add Donations Tables for Inaugural Committees

---

fec/home/models.py

- Resolves #5667 
- dev for code
- Content for content accuracy
- SMEs (Content?) for proper limitations
- Anyone who can't, feel free to remove yourself
This only affects how Wagtail page templates appear and behave while being edited.
The changes:
- `HomePage` can no longer be added as a child to any other page template
- Single templates (landing pages) that can now only be added to the `HomePage` (they will no longer appear as options for other pages' "Add child" option)
- `AboutLandingPage` template
- `ContactPage` template
- `LegalResourcesLandingPage` template
- `OigLandingPage` template
- `PressLandingPage` template
- `ServicesLandingPage` template (H4CC)
- Landing-page templates that now have limited child templates (AFAIK, the only ones being used so far. Clicking "add child" …

5667 Wagtail Page Descriptions

---

fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/legal-search-results-murs.jinja

- Resolves #6692 
Changing the labels for the "Citations" filters for AOs and MURs
- one
AOs & MURs filters but only those for Citations 
AOs
MURs
None
- Test [MURs](http://127.0.0.1:8000/data/legal/search/murs/)
- Test [AOs](http://127.0.0.1:8000/data/legal/search/advisory-opinions/)
- approve, merge

Change Citations filters labels for AO & MURs

---

fec/fec/static/scss/components/_calendar.scss

- Resolves #6719 
Adjusting the layout after the Sass upgrade a little while ago, we'd added an `!important` for the `margin-right` but that wasn't being overridden when we needed it to be.
This change removes the `!important` and changes the way that bit of sass is structured (i.e. moves the `margin-right` into a `& { … }` so we don't get deprecation warnings)
- 1 Dev
The right margin of calendar event dates in the list view and only widths >= 860px
The right margin is back
None
- Pull
- Check the [Calendar page](http://127.0.0.1:8000/calendar/)
- Make sure the calendar stays in the list view and the left menu should be closed
- Check the events' time columns from 860px and up

[HOTFIX - MERGE WITH GITFLOW] Hotfix/calendar event time style fix

---

requirements.txt

- Resolves #6707
Upgrade django 2 minor versions to remove Allocation of Resources Without Limits or Throttling snyk issue
1 dev
-  django 
git checkout develop
pyenv activate <old cms virtualenv>
snyk test --file=requirements.txt (Snyk flags django v4.1.18 as vulnerable)
git checkout feature/6643-upgrade-django
pyenv virtualenv 3.11.9 <new cms virtualenv>
pyenv activate <new cms virtualenv>
pip install -r requirements.txt
pip install -r requirements-dev.txt
npm i && npm run build
snyk test --file=requirements.txt (Snyk NO longer flags django as vulnerable)
cd fec
python manage.py runserver (test cms app)

6706-upgrade django

---

fec/fec/static/scss/layout/_layout.scss

- Resolves #2808 
Visual tweak. We were removing the side padding for main content columns as soon as we got into the $lg range but that meant content was against the edge of the browser window. This change adds a media query for that column so the content in full-width .container is never closer to the edges than the padding shared among the other widths
- 1 dev for code & UX?
- 1 UX?
The smallest widths of the $lg range for the `.container` selector
Localhost/this PR above; www below
Localhost/this PR above; www below
Localhost/this PR above; www below
None
- Load the site in localhost
- Open inspector to more easily see the page widths. We're looking at widths 850px to 1000px (10px before the new media query starts and 10px …

2808 - Don't remove side padding for smallest $lg widths

---

fec/legal/templates/legal-advisory-opinion.jinja

- Resolves https://github.com/fecgov/fec-proxy/issues/414
For AO citations that are outside of the FEC's title 11 jurisdiction, we must reformat the URL to point directly to the eCFR with the title and section defined in the URL. This allows for the eCFR to correctly find the corresponding citation.
One engineer
-  Advisory opinion individual page
- Go to an individual AO page that has legal citations that are outside of title 11. For example: http://localhost:8000/data/legal/advisory-opinions/2012-02/
- Try the URLs for citations that are outside of title 11, such as title 29. The link should go to the correct corresponding title and section inside the eCFR.
- Similarly, try the URLs or citations that are part of title 11. …

Rewrite AO legal citations to point to the eCFR

---

fec/legal/views.py

- Resolves #6679 
Add q_exclude to statues API query
1 engineer
-  Statutes search
branch | PR
feature/6133-fix-q_exclude-for-statutes (API) | [link](https://github.com/fecgov/openFEC/pull/6137)
feature/bool-ops-simple-query-string-v2 (CMS) | [link](https://github.com/fecgov/fec-cms/pull/6405)
- Go to the statutes search and perform a search with exclude in the statement. The exclude should be split out into it's own `q_exclude` parameter.
- Example of one result 
CMS: http://localhost:8000/data/legal/search/statutes/?search=federal%20-activities&search_type=statutes
API call: https://api.open.fec.gov/v1/legal/search?type=statutes&hits_returned=20&from_hit=0&q=federal&q_exclu …

Add q_exclude to statutes

---

fec/fec/static/scss/components/_articles.scss

- Resolves #4258 
Letting block-table table columns autosize
- 1+ devs
- 1+ SMEs?
(I tagged way more than I needed)
Added `table-layout: auto;` to `.block-table table`.
It won't affect any table that's not in a `block-table` class element, but it will affect _every_ table inside one.
**SMEs**: Are there places we do _not_ want this to happen—anyplace where this will break things?
Production above, localhost below
None
- Check [the example page used for this ticket](http://127.0.0.1:8000/legal-resources/enforcement/audit-reports/authorized-committee-audit-reports/kelly-for-congress-2016/)
- Check other locations `.block-table table` is being used
- Are they generally okay?
- Any of them broken?
- In the browser
- right-click on …

4258 - Auto-size block-table table columns

---

fec/data/templates/election-lookup.jinja
fec/data/templates/landing.jinja
fec/fec/settings/base.py

- Resolves #
Created and applied an env var to hide the election search map, currently only hiding for the data landing page.
a dev
Currently, only `/data/`
Production:
This PR:
None
- Check the [data landing page](http://127.0.0.1:8000/data/) (Should have the map search and the Raising/Spending cards combo)
- Cancel run server
- `export FEC_HIDE_ELECTION_SEARCH_MAP=True`
- Check the data landing page again. (The map should be gone, replaced with a larger Raising card, and a larger Spending card)
- (reject, comment, approve, merge)
- Revert the env var to nothing: `unset FEC_HIDE_ELECTION_SEARCH_MAP`

Toggle Election Search Map

---

requirements.txt

- Resolves #6731
Upgrades gunicorn to remediate snyk vuln
[Breaking Changes ](https://docs.gunicorn.org/en/latest/news.html)
refuse requests where the uri field is empty 
refuse requests with invalid CR/LR/NUL in heade field values 
remove temporary --tolerate-dangerous-framing switch from 22.0
1 dev
-  gunicorn servers
https://github.com/fecgov/openFEC/pull/6187
Running gunicorn locally has issues for me for CMS
- Deploy to a space or you can rebuild [this test branch in dev](https://app.circleci.com/pipelines/github/fecgov/fec-cms/4158/workflows/f6e54270-38ea-4666-95a7-88abcd46ede3/jobs/7688)

6731-upgrade gunicorn 23.0.0

---

fec/data/api_caller.py
fec/fec/static/js/legal-search-ao.js
fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/partials/legal-pagination.jinja
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja
fec/legal/views.py

- Resolves https://github.com/fecgov/openFEC/issues/6167
- Add sort by issue_date to AO data table
- Change sort column header styles to match other datatables
one frontend, one backend
AO datatable `Case(ao_no)` and `Date(issue_date)`  columns
https://github.com/fecgov/openFEC/pull/6173
- `export FEC_API_URL=https://api-stage.open.fec.gov`
- Test AO datatable sort columns - Case(ao_no) and Date(issue_date)
- Confirm the sort-type and sort-order in the url (i.e: `sort=-ao_no` or `ao_no` and  `sort=-issue_date` or `issue_date`)
- Confirm that the sort icon is always toggles to the correct direction for the current sort order
- Test pagination. The sort-type and sort-order should persist when paginating. 
- Note: Changing the sort always takes you back to page one is …

  [PR TO RELEASE] Sort AO by issue_date,  fix toggle on ao_no sort btn icon

---

fec/fec/static/js/legal-search-ao.js
fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja

- After deploying [recent sort changes](https://github.com/fecgov/fec-cms/pull/6742) for AO datatables, we noticed that the top and bottom paginations  do not match when you change sort-order or sort-type
- Also, to match other datatables, fix the initial view on load  to  show the first column (ao-no) as being sorted descending with the icon pointing down. 
one frontend, one backend
AO datatables sort and pagination functionality
https://github.com/fecgov/fec-cms/pull/6742
- Confirm that the default, on first page load, shows the first column sorted descending 
- Confirm that switching sort-type …

AO datatable consistent pagination

---

fec/data/templates/partials/committee/raising.jinja
fec/fec/static/js/modules/tables.js

- Resolves #6770 
Fixed the data-export-for attributes for the export buttons so the export/download code finds the relevant tables
1-2?
The Export buttons for inaugural committees' single pages
It works!
None
- `npm run build` (probably unnecessary)
- **FOR THIS TEST ONLY**
1. Close Chrome
2. Launch Chrome without CORS protection: `open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials`
- Load any inaugural committee ([site search for `inaugural` offers several](http://127.0.0.1:8000/search/?query=inaugural&type=committees))
- Click to the Raising tab, Donations table
- Skip to the Spending tab, Refunds section
- Feel free to poke around more, …

6770 Inaugural Committee Export Buttons

---

fec/fec/static/js/modules/audit-category-sub-category.js
fec/fec/static/js/modules/audit_tags.js
fec/fec/static/js/modules/dropdowns.js
fec/fec/static/js/modules/election-search.js
fec/fec/static/js/modules/filters/date-filter.js
fec/fec/static/js/modules/filters/election-filter.js
fec/fec/static/js/modules/filters/filter-base.js
fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/modules/filters/select-filter.js
fec/fec/static/js/modules/filters/text-filter.js
fec/fec/static/js/modules/filters/toggle-filter.js
fec/fec/static/js/modules/filters/validate-date-filters.js
fec/fec/static/js/modules/tables.js
fec/fec/static/js/modules/top-entities.js
fec/fec/tests/js/checkbox-filter.js
fec/fec/tests/js/contact-form.js
fec/fec/tests/js/cycle-select.js
fec/fec/tests/js/date-filter.js
fec/fec/tests/js/election-search.js
fec/fec/tests/js/statistical-summary-archive.js
fec/fec/tests/js/toggle-filter.js
fec/fec/tests/js/typeahead-filter.js
fec/legal/templates/legal-search-results-murs.jinja

- Resolves # (if we set this to 6410, will this one PR close that whole ticket? It'll have other PRs, too.)
Resolving the jQuery deprecations has been a burden so let's break https://github.com/fecgov/fec-cms/pull/6411 into much smaller pieces
- front-end for code
- anyone for functionality
`change()` and `.change(𝑓)` on/in:
- Audit category sub category
- Audit tags
- Dropdowns
- Election search
- All filters, especially
- Date
- Election
- Select
- Text
- Typeahead
- Tables
- Top entities
No changes
PR | Branch | Deprecated features
------ | ------ | ------
#6750 | feature/jquery-deprecation-click | `.click`
#6751‡ | feature/jquery-deprecation-change | `.change`
#6753 | …

Move from jQuery.change

---

fec/fec/static/scss/components/_messages.scss
fec/search/templates/search/policy_guidance_search_page.html
fec/search/templates/search/search.html
fec/search/views.py

- Resolves #6525
Revised designs: https://github.com/fecgov/fec-cms/issues/6557
- Handle errors for the global site search and Policy Guidance search when the FEC API or search.gov API  do not return search-result data
- Use a catch-all  `Try/Except` block to handle:
-   `Connection Errors` when the FEC API  endpoints (Candidtes or Committees) or search.gov  API  are not responding. 
- `Key Error`, `JSON Decode Error` or any other error that arises when the data returned is not processable, search-result json.
- Render an error message to the search-result page and log errors in server logs.
One developer, One UX
- Global site search 
- Policy Guidance search
modified:   fec/static/scss/components/_messages.scss
modified: …

[PR TO 05/13/25 RELEASE] Error handling and logging for global and policy searches

---

fec/fec/static/scss/components/_buttons.scss
fec/search/templates/search/search.html
fec/search/views.py

- Resolves #6686 
Updating the site search results pagination
- 1 dev for code
- UX for UX?
Site search results footer–the message, the back button, and both buttons' icons icon position
**and every button across the site that uses `button--next` or `button--previous` classes** (though only their icons' background position may be centered if it wasn't already for some reason)
BONUS: New "Showing #-## of" message for results count. I added it for my own debugging and decided to keep it, moving us a little closer to search results across the rest of the site.
Production above, this PR below
None
- Go to site search ([link directly](http://127.0.0.1:8000/search/) or use the header nav search and choose the "Other pages" option …

6686 Site Search Pagination

---

fec/data/templates/partials/audit-filter.jinja
fec/fec/static/scss/components/_buttons.scss
fec/fec/static/scss/components/_filters.scss
fec/home/templates/home/legal/legal_resources_landing.html
fec/home/templates/partials/legal-keyword-modal.html
fec/legal/templates/legal-search-results-adrs.jinja
fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/legal-search-results-afs.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/legal-search-results-regulations.jinja
fec/legal/templates/legal-search-results-statutes.jinja
fec/legal/templates/partials/legal-keyword-modal.jinja

- Resolves #6799
Add link to legal search guide on legal landing, legal datatables' filter panel and in keyword modal 
One UX or Content, One Dev
A new link on all legal datatables' filter panel  and keyword modal (except audit search)
A new link on legal landing
-  
<hr>
Related issue:
https://github.com/fecgov/fec-cms/issues/6773
- Go to legal landing, legal datatables and keyword modal to see the link and verify it goes to the correct place
- Link in keyword modal should open in new tab

Add legal search guide to website

---

fec/fec/static/js/modules/calendar-tooltip.js
fec/fec/static/js/modules/calendar.js
fec/fec/static/js/modules/download.js
fec/fec/static/js/modules/dropdowns.js
fec/fec/static/js/modules/filters/date-filter.js
fec/fec/static/js/modules/filters/filter-panel.js
fec/fec/static/js/modules/filters/filter-typeahead.js
fec/fec/static/js/modules/filters/text-filter.js
fec/fec/static/js/modules/search.js
fec/fec/static/js/modules/skip-nav.js
fec/fec/static/js/modules/tables.js
fec/fec/static/js/pages/contact-form.js
fec/fec/static/js/pages/reporting-dates-tables.js

- Resolves # (if we set this to 6410, will this one PR close that whole ticket? It'll have other PRs, too.)
Resolving the jQuery deprecations has been a burden so let's break https://github.com/fecgov/fec-cms/pull/6411 into much smaller pieces
- front-end for code
- anyone for functionality
`focus()` and `.blur()` on/in
- Calendar
- Contact form
- Download
- Dropdowns
- Date filters
- Filter panel
- Reporting dates table
- Search
- SkipNav
- Tables
- Text filter
- Typeahead filter
No changes
PR | Branch | Deprecated features
------ | ------ | ------
#6750 | feature/jquery-deprecation-click | `.click`
#6751 | feature/jquery-deprecation-change | `.change`
#6753‡ | …

Move from jQuery .focus, .blur

---

fec/data/constants.py

- Resolves #6829 
Updating `DEFAULT_TIME_PERIOD` and `DEFAULT_PRESIDENTIAL_YEAR` from 2024 to 2026
- Dev
- Everywhere that uses the defaults
Updated defaults
None
- Check pages (mostly data tables) that use default years

6829 Update Default Election Years

---

fec/fec/settings/base.py
requirements.txt

- Resolves #6836 
Adds connection pooling, [Django 5.1 added connection pooling using psycopg3's pool](https://docs.djangoproject.com/en/5.2/releases/5.1/#postgresql-connection-pools)
I set max_size at 50 which is 600 possible db connections
I lowered max_idle from 600 to 400 s
We should lower both eventually, but these are conservative estimates. Hoping we can ask cloud.gov for a month of PI db connections like we can do with the API. 
It seems that we regularly need <50 db connections, so for right now django's in built connection pooling should suffice. If this is not enough connections we can consider external pooling with pgbouncer later. 
Max CMS Application DB connections = the lowest of these two options :
(num of workers) x (instances) x (limit of greenlets spawned) 
OR …

6836-add connection pooling via Django/psycopg

---

fec/home/views.py

- Resolves #6841 
Changes template statuses to 500, so that Pingdom will alert us with server errors. I don't think we should build an alternative template for DB connection errors, I think we should keep this information exclusive to our logging/alerts
1-2 devs
-  CMS server errors
**DO NOT TRY TO PUSH TO DEV/STAGE**
- Pull down the branch
- Set the feature flag `export FEC_FEATURE_WEBSITE_STATUS=true`. This will turn on the alternative 500 error messaging (see screenshot above for what that looks like).
- Turn off DEBUG mode inside of the dev.py file. Change to `DEBUG = False`. Also add `ALLOWED_HOSTS = ['*']`. These will be temporary changes to test out the 500 error messaging.
- Build assets using …

6841-switch template status to 500

---

fec/data/api_caller.py
fec/legal/tests.py
fec/legal/urls.py
fec/legal/views.py

- Resolves https://github.com/fecgov/fec-proxy/issues/425
Creates new redirect endpoint `/legal/search/documents/` to look up document filename redirect paths.
This PR should be merged along with the proxy PR https://github.com/fecgov/fec-proxy/pull/429, so that the legacy legal documents paths will redirect to this new endpoint to look up the filename.
1 engineer
-  Legal documents path /legal/search/documents/
branch | PR
feature/425-redirect-to-legaldocs-endpoint | [link](https://github.com/fecgov/fec-proxy/pull/429)
- Pass a filename to query the endpoint to see if it will redirect. Examples: 
- http://localhost:8000/legal/search/documents/?filename=1069112
- http://localhost:8000/legal/search/documents/?filename=8332_13
- …

Create legal document redirect endpoint

---

fec/fec/middleware.py
fec/fec/settings/base.py
fec/fec/slack.py
fec/fec/templates/500-status.html
fec/fec/templates/500.html
fec/fec/templates/503.html

- Resolves #6843 
Adds 503 template when we are getting db driver pool timeout errors 
Posts to slack that we are getting these errors once an hour
Changes website status page to match formatting (the 500 template we can switch to with an env var) 
2 devs, at least 1 front end, 
1 design 
-  Middleware and error templates 
Current 500 page:
Current 500-status page:
New 500 page:
New 500-status page:
New 503 page:
- git checkout test-pooltimeout. (This branch has the current changes, plus some changes that make it easier to test timeouts locally) 
- activate your pyenv
- In dev.py: change debug to false and allow hosts 
DEBUG = False
ALLOWED_HOSTS = ['*']
- Build assets using collectstatic so that scripts …

Add 503 middleware
