.gitignore
fec/fec/templates/base.html
requirements.txt

- It should be /scss/ not /css/
- I had to instal django-libsass
- Ignoring compiled css

Fixing a couple install things

---

.gitignore
Procfile
bin/run.sh
fec/fec/settings/base.py
fec/fec/wsgi.py
requirements.txt

* Serve with gunicorn
* Add Procfile

Deploy to Cloud Foundry.

---

bin/run.sh
fec/fec/settings/dev.py
fec/fec/settings/production.py
fec/fec/wsgi.py
manifest.yml
requirements.txt

* Use whitenoise to serve static files
* Collect and compress static files
* Set `ALLOWED_HOSTS` in production

Various fixes for production static files.

---

README.rst
fec/fec/settings/base.py
manifest.yml

Link to data app via environment variable.

---

.gitignore
README.rst
bin/run.sh
fec/fec/settings/base.py
fec/fec/static/js/fec.js
fec/fec/templates/base.html
fec/fec/templates/partials/glossary.html
fec/gulpfile.js
package.json

* Use glossary and accordion widgets from fec-cms
* Bundle assets with gulp and browserify
* Compress bundled scripts with django-compressor

Bundle scripts from fec-style.

---

fec/fec/static/js/fec.js

Depends on https://github.com/18F/fec-style/pull/30.

Handle update in glossary API.

---

README.rst
fec/fec/settings/production.py
fec/home/models.py
requirements.txt

Use RDS service in production.

---

fec/home/models.py
fec/home/templates/home/custom_page.html

Add sidebar field to custom page.

---

fec/fec/templates/base.html

Addresses https://github.com/18F/openFEC-web-app/issues/537

Spelling changes

---

fec/home/templates/home/checklist_page.html

Updates the markup on the checklist accordion.
[Resolves https://github.com/18F/openFEC-web-app/issues/540]

Fixing markup on accordions

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/home_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/options_page.html

Updates capitalization. Wherever relevant, swaps in approved FEC content. Addresses microcopy edits from minor usability issues, as identified in testing.

Content stylings

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/home_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/options_page.html

There were some conflicts so I branched off `making-style-tweaks`, updated from `master` and resolved conflicts. Now merging back into `making-style-tweaks`.

Merging from master and resolving conflicts

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/home_page.html

This styles link content on the beta home page.
Ready for review @noahmanger

Making style tweaks

---

fec/fec/templates/robots.txt
fec/fec/urls.py

Self-explanatory. Is this adequate for pre-ATO @NoahKunin?
cc @leahbannon

Disallow all robots.

---

fec/fec/templates/base.html
fec/home/templates/home/checklist_page.html
fec/home/templates/home/home_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/options_page.html

- Various content and layout tweaks. 
- Updates the menu
- Updates the various "learn more" links on the checklist
- Adds images for the campaign guides

Content updates

---

README.rst
fec/fec/settings/base.py
fec/fec/templates/base.html

1. Update the nav to be the same as the web app's
2. Update the fec-style server url to be the same as the web app's so you don't need to set two separate variables

Updating nav + env variables

---

fec/home/templates/home/landing_page.html

Fixes and issue where FEC computers can’t access FEC.gov links without the www 
Resolves https://github.com/18F/openFEC-web-app/issues/621

Adding wwws

---

fec/fec/templates/base.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/home_page.html

1. Adds the link to the contact page in the utility nav
2. Adds the ethnio scrip to resolve https://github.com/18F/openFEC-web-app/issues/601

Adding contact link

---

README.rst
fec/fec/settings/credentials.py
fec/fec/settings/production.py
manifest.yml

Add zero-downtime deploys with autopilot.

---

fec/fec/templates/base.html

Add web analytics.

---

fec/home/models.py

Proposed resolution to #26. @noahmanger, want to check this out and give it a try before merging? I'm hoping this will be enough to get by for now.

Allow raw HTML blocks in StreamField fields.

---

fec/home/templates/home/home_page.html

makes beta.fec.gov beta.FEC.gov in API section.

updates beta.FEC.gov

---

fec/home/templates/home/landing_page.html
fec/home/templates/home/options_page.html

Makes icons in cards links to the pages when relevant.
Resolves https://github.com/18F/openFEC-web-app/issues/663

Linking icons

---

.gitignore
fec/home/migrations/0008_auto_20150917_1906.py
fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/options_page.html

Adds terms and fixes broken links
Resolves https://github.com/18F/openFEC-web-app/issues/698
Resolves https://github.com/18F/openFEC-web-app/issues/694
Resolves https://github.com/18F/openFEC-web-app/issues/688

Glossary terms

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html

Resolves 18F/openFEC-web-app#716
Resolves #19

Updates link and content

---

fec/fec/templates/base.html
fec/home/templates/home/checklist_page.html
fec/home/templates/home/home_page.html

Adds things to improve accessibility / focus behavior.
Goes with https://github.com/18F/fec-style/pull/108

Accessibility improvements

---

fec/fec/settings/base.py
fec/fec/templates/base.html
fec/home/templates/home/home_page.html

Updating the email address to use betafeedback@fec.gov

Changing email address

---

fec/fec/templates/base.html

Trying out new labels to see if it helps users find the election search easier.

Changing label text for usability testing

---

fec/home/templates/home/checklist_page.html

fixes broken link

---

fec/fec/static/js/fec.js
fec/fec/templates/base.html
fec/home/templates/home/landing_page.html

- And adding proper alt tags to PDFs
- Makes use of the skip nav and accessibility helpers from https://github.com/18F/fec-style/pull/115

Implementing skip nav

---

fec/fec/templates/base.html

Changing disabled link styles to satisfy 508 requirements.
Also moves the "Registration" card on the home page to to "Coming Soon" and removes the link.
Resolves https://github.com/18F/openFEC-web-app/issues/760

Changing disabled link styles

---

fec/fec/templates/404.html
fec/fec/templates/500.html

Resolves https://github.com/18F/fec-cms/issues/37

Styling error pages

---

fec/fec/templates/base.html

Depends on https://github.com/18F/fec-style/pull/129

Switching to nav button toggle

---

fec/fec/templates/base.html
fec/fec/templates/partials/meta-tags.html

Adds the meta tags from the app to the cms.

Adds meta tags to cms

---

fec/fec/settings/base.py
fec/fec/templates/base.html

* Restore user bar template tag.
* Respect x-forwarded-proto header.
Thanks @dlapiduz!
[Resolves #49]

Restore admin user bar.

---

fec/fec/templates/base.html

This re-orders nav items to match the format proposed in https://github.com/18F/openFEC/issues/1184
review: @noahmanger

re-ordering an adding classes to style nav. matches the web-app nav styling

---

manifest_base.yml
manifest_dev.yml
manifest_prod.yml

Add dev and production environments.

---

fec/fec/wsgi.py
manifest_base.yml
manifest_dev.yml
manifest_prod.yml
newrelic.ini
requirements.txt

Add monitoring with new relic.

---

fec/fec/templates/base.html

This links to all candidates active in the last 6 years.

Removing the statutory filtering, it did not work well.

---

fec/home/templates/home/contact_page.html
fec/home/templates/home/home_page.html

This begins the work for implementing the feedback strategy in https://github.com/18F/openFEC-web-app/issues/866

Feedback strategy

---

fec/home/templates/home/home_page.html

Eliminates very serious period.

---

fec/home/templates/home/home_page.html

Minor fix that fixes a weird display issue I noticed on IE 11 which the other browsers apparently ignored.

Adds missing closing tags to fix display issue on IE11

---

CONTRIBUTING.md
LICENSE.md
README.rst

[ci skip]
@leahbannon @LindsayYoung @jenniferthibault @noahmanger @jmcarp

Content edits

---

fec/fec/templates/base.html

Include current date in links to transactions.

---

fec/fec/templates/base.html

Goes with https://github.com/18F/fec-style/pull/170

Updating markup to work with refactored nav

---

fec/fec/templates/base.html

Adds the feedback links to the footer on the CMS.

Feedback footer

---

README.rst

Adds Wagtail line to CMS README

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/contact_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/options_page.html

Markup changes to go with https://github.com/18F/fec-style/pull/190
@jenniferthibault make sure to check out this branch when reviewing the style changes.

Updating markup to clean up CMS pages

---

.buildpacks
package.json

Pin fec-style to last commit before beta release.

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html

Updates styles for the new article template.
- It includes dummy hard-coded links for "next" and "previous" buttons just for the purposes of testing.
- The new sidebar makes use of multiple StreamFields, so once we decide this is what we want, we'll need to update sidebar content areas for each page in the CMS

Updated article template page

---

fec/home/templates/home/checklist_page.html

I think anyone can look over this content update!
[ci skip]

Makes OGC required tweaks

---

fec/home/templates/home/checklist_page.html

Adds some new classes and makes a couple copy edits to implement the new essentials page designs from https://github.com/18F/fec-cms/issues/148
Resolves https://github.com/18F/fec-cms/issues/148
Requires https://github.com/18F/fec-style/pull/203

Essentials page

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html

Content edits, per OGC. Hopefully this captures all of them.
[ci skip]

Edits content

---

fec/fec/static/js/fec.js
fec/fec/static/js/toc.js
fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html
package.json

- Implements the component-sticky library to sticky the side nav
- Adds a module based on scroll monitor to highlight active elements of
a table of contents
- Implements on reg. & reporting landing page and checklist page
Resolves #146 #152

Sticky side nav

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/landing_page.html

Adding it to the checklist page, the registration and reporting landing
page, and the basic article page.
cc @emileighoutlaw
Styles included here https://github.com/18F/fec-style/pull/207

Adding content warning of OGC

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html

Content only: Fixes one link and one acronym.
Anyone can review.
[ci skip]

Content tweaks

---

fec/home/templates/home/checklist_page.html

Let’s wait until we’ve gotten the thumbs up from FEC before we merge this.
Also, not technically a hot fix as this isn’t a gitflow enabled repo, so we’ll need to manually merge to master and develop.

De-linking inactive sidebar links

---

fec/home/templates/home/contact_page.html

Adds Congressional affairs and Press Office phone.
Anyone can review!  cc @LindsayYoung? @noahmanger? 
Resolves: https://github.com/18F/openFEC-web-app/issues/825
[ci skip]

Content only: adds to Contact Us page

---

fec/fec/settings/base.py
requirements.txt

Log errors using Sentry.

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html

Adds a couple glossary terms into our content (hooray!). 
Now that we've got a beefed-up glossary, I'm going to try to add these in when I do my content QA on the site. Anyone can review. :)

Adds glossary terms

---

fec/home/templates/home/contact_page.html

Resolves: https://github.com/18F/FEC/issues/228#issuecomment-178166339
cc @jenniferthibault ?

Adds hours to Contact page

---

fec/fec/templates/base.html

Adding the link to IEs on the CMS

---

fec/fec/templates/base.html

We’ve got this on the web-app side, so adding it here

Adding max-date to IE link

---

.travis.yml
fec/fec/static/js/calendar.js

Preserve query params in export URLs.

---

fec/fec/static/js/calendar.js

Temporarily hiding the week view from the calendar while we work out the kinks.

Removing week view

---

fec/home/templates/home/checklist_page.html

Content edits only. Anyone can merge.
Resolves: https://github.com/18F/fec-cms/issues/219

Pruning checklist content

---

fec/fec/static/js/calendar-helpers.js
fec/fec/static/js/calendar.js

* Respect `all_day` flag
* Show datetimes in local time
Requires https://github.com/18F/openFEC/pull/1555

Use localized datetimes and all_day flag.

---

fec/fec/static/js/calendar.js

Relabling quarter toggle to "list"

---

fec/home/templates/home/landing_page.html

This adds the OGC approved SSF content to the Registration Options page. 
Prepping content for release this week.
cc @noahmanger @jenniferthibault

SSF content

---

fec/home/templates/home/calendar_page.html
fec/home/templates/home/checklist_page.html
fec/home/templates/home/custom_page.html
fec/home/templates/home/home_page.html
fec/home/templates/home/ssf_checklist_page.html
package.json

Resolves a conflict between develop and the release branch.

Merging release

---

fec/fec/templates/partials/glossary.html
fec/home/templates/home/calendar_page.html

Work in progress. This goes with https://github.com/18F/openFEC-web-app/pull/1141
and 
https://github.com/18F/fec-style/pull/279

Color palette changes

---

fec/home/templates/home/landing_page.html

Attempt 2 at missing button. :) @ccostino

Adds button to registration and reporting

---

fec/fec/templates/404.html

h/t to @noahmanger for reminding me to make this change in CMS :)

Winnows content

---

fec/fec/static/hbs/calendar/details.hbs
fec/fec/static/hbs/calendar/download.hbs
fec/fec/static/hbs/calendar/events.hbs
fec/fec/static/hbs/calendar/subscribe.hbs
fec/fec/static/js/calendar.js
fec/fec/templates/base.html
fec/fec/templates/partials/search-hero.html
fec/fec/tests/js/calendar.js
fec/home/templates/home/calendar_page.html
fec/home/templates/home/checklist_page.html
fec/home/templates/home/home_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/ssf_checklist_page.html

Fixing a class name to go with changes in https://github.com/18F/fec-style/pull/287

Updating class name to use new styleguide class

---

.travis.yml
README.rst
package.json
requirements.txt
tasks.py

This changeset adds support for the Cloud Foundry autopilot plugin, Slack notifications, and Travis build enhancements to make the deployment of our CMS mirror the deployment procedures for our API and web app.

Improved Autopilot Deployment

---

fec/fec/templates/partials/search-hero.html

Legal resources search on CMS should proxy to the web-app search.
No UI changes for this one.

Legal resources search

---

fec/home/templates/home/landing_page.html

Re-arranging sub-nav and linking title

---

fec/home/templates/home/landing_page.html
fec/home/templates/home/party_checklist_page.html

Deletes stray `s`s
Makes `only`s bold
Adds glossary link
cc @ccostino

Content hotfix

---

.gitignore
README.rst
manifest_base.yml
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml
tasks.py

- Adds the feature manifest for feature space.
- Enables legal search on `feature`, `dev`, and `stage`.

Adds the feature manifest

---

fec/fec/templates/404.html
fec/fec/templates/500.html

Updates the 404 and 500 error pages.

New 404 and 500 errors

---

fec/fec/static/js/fec.js
fec/fec/templates/base.html
fec/home/templates/home/home_page.html
package.json

Prepares the nav for the mega menu from https://github.com/18F/fec-style/pull/316
- Removes the old sub-lists
- Re-arranges some nav components
- Adds a global variable for the CMS url

Beginning mega menu work

---

fec/fec/templates/partials/search-hero.html

Remove options we don't have, fixes the names for ones we do.

Fix legal search selector

---

fec/fec/templates/base.html

Implements condensed header.
Depends on https://github.com/18F/fec-style/pull/366

Markup for condensed header

---

fec/legal/templates/legal/home.html

Woohoo legal landing! I was just reviewing for launch and made a couple small changes:
- Lowercasing headers (we're using sentence case)
- Re-arranging the "let us know" in the alert message to the front of the sentence (which I think makes it easier to read). 
Anyone can review and merge, but cc'ing @edmullen and @anthonygarvan on this one!

Small content tweaks

---

fec/fec/templates/partials/search-hero.html

Changed content & broke up long line.

changing placeholder content

---

bin/run.sh
fec/home/templates/home/ssf_checklist_page.html

[MERGE WITH GIT FLOW] Hotfix/turn off slack

---

bin/run.sh

turning off slack

---

fec/fec/constants.py
fec/home/templates/home/calendar_page.html

- Moves the reporting and compliance periods together with elections and filing deadlines
- Changes label language based on https://github.com/18F/openFEC/issues/1675
- Removes redundant label on legal filter
Resolves https://github.com/18F/fec-cms/issues/307
Resolves https://github.com/18F/openFEC/issues/1675

Editing calendar filters

---

package.json

This changeset updates `fec-style` to be the latest version.
/cc @noahmanger, @jontours, @LindsayYoung

Updated fec-style to latest version

---

tasks.py

to work locally and with Travis

fix local deploy

---

package.json

A small update to account for the latest version of https://github.com/18F/fec-style.
/cc @noahmanger, @adborden

Update fec-style 2.5.1

---

tasks.py

This changeset fixes the cloud.gov deploy task to match the recent fixes done in the release branch and the other repos.
/cc @LindsayYoung, @adborden, @jontours, @anthonygarvan, @noahmanger

Fix cloud.gov deploy task

---

fec/home/templates/home/landing_page.html

Removes content accidentally left behind from our addition of the new heroes:
Review: @ccostino 
cc @noahmanger

Removes content duplicated from hero

---

fec/fec/static/js/calendar.js
fec/fec/tests/js/calendar.js

Removing setHeight() calls

---

fec/home/templates/home/landing_page.html
package.json

Fixes https://github.com/18F/openFEC-web-app/issues/1305

Version bump

---

manifest_base.yml
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml

Fixes the unusual case where you navigate directly to the cms app and try to use the nav, or search. e.g.
search on https://fec-dev-cms.18f.gov/legal-resources/

Fix web-app urls

---

fec/fec/templates/partials/search-hero.html

Fix copy on legal resources page

---

package.json

In preparation of the changes in https://github.com/18F/fec-style/pull/413/

[MERGE WITH GITFLOW] Bumping fec-style version

---

fec/home/templates/home/home_page.html

- Removes coming soon for legal
- Updates links
- Updates content
cc @noahmanger @jenniferthibault

Updates homepage

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/landing_page.html
fec/home/templates/home/party_checklist_page.html
fec/home/templates/home/ssf_checklist_page.html

Removed extraneous plus signs, fixed text, and added missing learn more button.

[MERGE WITH GITFLOW] Minor content fixes

---

fec/home/templates/home/calendar_page.html

Replaces `form` with `div`, per https://github.com/18F/Accessibility_Reviews/issues/15#issuecomment-228167208
Requires https://github.com/18F/fec-style/pull/424

Replacing form with div

---

fec/home/templates/home/checklist_page.html
fec/home/templates/home/nonconnected_checklist_page.html
fec/home/templates/home/party_checklist_page.html
fec/home/templates/home/ssf_checklist_page.html

Coming in under the wire on this one, but this is the PR to:
- Add explanatory content introducing "How to file"
- Update our links to checklist pages, so they reflect our updated CMS
For reference, the updated CMS pages:
- Combine all electronic filing content to one page
- Update paper filing to apply to all committees so FEC only has a single page to maintain
cc @noahmanger

Links and content

---

fec/fec/templates/404.html
fec/fec/templates/500.html
fec/fec/templates/base.html

- Edits "beta.FEC.gov" to "FEC"
Related:https://github.com/18F/fec-cms/issues/385
cc @noahmanger 
h/t @edmullen for noting the style inconsistency

Page title content update

---

fec/home/templates/home/home_page.html

release-notes link

---

README.rst
fec/fec/settings/base.py
fec/fec/templates/base.html

updated style reference to using new method
Issue #415

Updated style reference to using new method

---

fec/home/templates/home/home_page.html

Adds a link to an evergreen release notes markdown file.

Adding release notes link

---

fec/legal/templates/legal/home.html

Can't believe I missed this one.

Use url prefix for legal urls

---

.buildpacks
.cfignore
.travis.yml
bin/run.sh
manifest_base.yml
runtime.txt

We reverted the work to move the asset building onto CI. This branch contains the revert, thus re-instating that work.

Build assets on CI and drop buildpack-multi

---

fec/legal/templates/legal/home.html

Copy from https://github.com/18F/fec-eregs/issues/199

Statutes intro copy

---

fec/home/templates/home/home_page.html

Touts eFiling data and statutes. 
Updates date for release notes.
cc @porta-antiporta and @noahmanger for content. Let me know if you see edits that are needed.

Updates content

---

README.rst

[Resolves #184]
To review: @LindsayYoung and/or @ccostino, try out the instructions in `README.rst`, and revise or ping me if you run into issues or find anything unclear.

Document data export process.

---

fec/home/templates/home/home_page.html

I put in the date I issued the PR and not the release date. This fixes it to the release date. 
Content only.

Fixes date

---

fec/legal/templates/legal/home.html

updating copy to landing page per: https://18f.slack.com/archives/fec-partners/p1472757492000081

[MERGE WITH GITFLOW] hotfix: updating copy

---

fec/fec/settings/base.py
fec/legal/templates/legal/home.html

fixes: https://github.com/18F/fec-eregs/issues/234

remove statutes feature flag

---

fec/home/templates/home/landing_page.html

This is my first pass at improving our links for people using screenreaders.

Adds context for screenreaders

---

fec/fec/templates/partials/glossary.html

Our pattern on the site so far has been to use "search" as a verb and "filter" as a noun.
This is a one-word PR, so I'm thinking maybe @jenniferthibault would be a good 👀 ?

Changes verb to "search"

---

fec/legal/templates/legal/home.html

Change paired with search combo changes from https://github.com/18F/fec-style/pull/523

Add class for search combo with select

---

README.md

Capitalizes president in our README file, per: https://github.com/18F/fec-cms/issues/563
Content only. Anyone can review.

President capitalization

---

fec/home/templates/home/landing_page.html
fec/home/templates/home/nonconnected_checklist_page.html

Partially resolves: https://github.com/18F/fec-cms/issues/587
Makes Political Action Committee (PAC) capitalization consistent.
Content only.

Hybrid / Super

---

fec/home/templates/home/home_page.html

Content only.
Partially resolves: https://github.com/18F/fec-cms/issues/585

eFiling --> electronic filing

---

requirements.txt

It wanted me to do a migration I did a migration merge locally, but I don't think it was related to this so I did not commit it.

Upgrading Django and Wagtail worked for me locally.

---

fec/fec/templates/partials/glossary.html
fec/legal/templates/legal/home.html

Removes placeholder text and adds an example. I'm not feeling 100% confident I did this HTML right, so 
cc @noahmanger and @jenniferthibault

Search consistency

---

fec/fec/static/js/fec.js
fec/fec/static/js/legal.js
fec/home/templates/home/home_page.html
fec/legal/templates/legal/home.html

This removes all instances of the ethnio script and all links to it.

Removing all instances of ethnio

---

fec/home/templates/home/home_page.html

h/t to @noahmanger for the original fix which missed the train.  D'oh!

[MERGE WITH GIT FLOW] Updated release notes date to the latest release.

---

fec/fec/templates/base.html
fec/home/templates/home/landing_page.html

Updates file names for:
-  `seal-white`>> `seal-inverse` 
-  `guide`>> `thumbnail`
Dependent on https://github.com/18F/fec-style/pull/578
cc @xtine

Image file name changes

---

fec/home/templates/home/home_page.html

Added `container` class for correct hero alignment.
Supporting styles: https://github.com/18F/fec-style/pull/584

New Homepage Hero update

---

fec/home/templates/home/home_page.html

Issue #644 
Relies on: https://github.com/18F/fec-style/pull/585

Homepage Registration and Reporting Section

---

scrapers/fec_record_article_scraper.py

This just add's @tadhg-ohiggins 's [FEC Record scrape script](https://gist.github.com/tadhg-ohiggins/6f62923b0674a5eb915e405e0c252bc8) to the repo as discussed in https://github.com/18F/fec-cms/issues/457#issuecomment-267450391

Adding fec record scraper

---

fec/home/templates/home/home_page.html

Issue #639 
Relies on https://github.com/18F/fec-style/pull/586

New Homepage Commissioners section

---

manifest_prod.yml

should take care of the small periods of downtime we have seen

Up production instances

---

.gitignore
fec/fec/static/js/fec.js
fec/home/templates/home/home_page.html

This implements the content from https://github.com/18F/fec-cms/issues/694 and animates the scroll so when clicking "Learn more" on the home page it scrolls down rather than jumping down.

Updating copy and animating scroll on home page

---

fec/home/templates/home/latest_updates.html

Per @emileighoutlaw and @AmyKort ’s edits.

[MERGE WITH GIT FLOW] Hotfix/Fixing typos

---

fec/home/templates/home/home_page.html

Minor design updates to the Citizen Information section on the Homepage.
Relies on https://github.com/18F/fec-style/pull/603

Homepage Citizen Information design updates

---

fec/home/templates/home/commissioner_page.html

Per our sentence case guidance.
Content only. Calling in my favorite editor, Jen!

Lowercase S

---

README.md

deploy disclaimer

---

fec/home/templates/home/collection_page.html

This correctly updates the variable for body content for collection pages in the template.

Collection page intro fix

---

fec/home/templates/partials/commissioner.html
fec/home/templates/partials/current-commissioners.html

Remove nested template logic for Commissioner grids so HTML shows up cleanly.

Commissioner template logic

---

fec/home/templates/home/latest_updates.html
fec/home/views.py

And moving the backend logic behind its own feature flag:

Adding select option for tips for treasurers

---

fec/fec/settings/base.py

Looked at the env in the production cms and fixed the variables accoddingly
I feel like it is easier to change here since we have to replace the whole thing in the env.

Variable names to match the env vars

---

manifest_stage.yml

make staging use the umbrella

---

fec/home/templates/home/home_page.html

"Learn more about enforcement »" link fixed on homepage.

fixed enforcement link on betaFEC homepage

---

README.md

Resolves https://github.com/18F/fec-cms/issues/796

Adding instructions for restoring

---

fec/fec/settings/base.py
fec/fec/templates/base.html

So we don't forget to add this when the site flips, I have made these changes under an `FEC_ETHNIO` feature flag. We can play around with placement and look and feel of the drawer inside of the ethnio admin too.

added ethnio script with feature flag

---

fec/fec/static/css/customize-editor.css
fec/fec/static/js/hallo-blockquote.js
fec/fec/wagtail_hooks.py

Implementation of issue https://github.com/18F/fec-style/issues/632

Added blockquote functionality for wagtail editor

---

fec/home/templates/home/contact.html

This PR makes the contact page more consistent, by adding:
- Missing 1-800 and 202- phone numbers
- Info Division's email
h/t to @FECHoosier for suggesting these edits.
Content only— anyone can review.

Adds additional contact info

---

fec/home/templates/home/legal/legal_resources_landing.html

- Adds links to court cases, policy, legislation and regulation to the legal landing page
- Re-orders the sections
Resolves https://github.com/18F/fec-cms/issues/824

Updating legal landing page

---

fec/fec/templates/partials/meta-tags.html

This adds the verification to allow us to use the Google Search Console.

Adding verification for search console

---

fec/fec/static/js/vendor/beautify-html.js
fec/fec/wagtail_hooks.py
package.json

This went into `develop` but we want to also include it in this release.

Fix html edit

---

fec/fec/settings/base.py
fec/fec/templates/uaa_client/login_error.html
fec/fec/urls.py
requirements.txt

Currently working on getting Django to redirect to CF login.  Once that done should be close to being done.

Enable 2FA [WIP]

---

fec/fec/urls.py

@ccostino @LindsayYoung Well, turns out we did have people doing local environment!!  Hooray for rapid iterations.  This disables the redirect for local dev.

Disables redirect in case environment is local

---

fec/home/templates/home/legal/legal_resources_landing.html

Resolves https://github.com/18F/openFEC-web-app/issues/1901

Adding link to FECA brochure

---

fec/fec/templates/partials/meta-tags.html

This enables the use of Bing's webmaster search tools.

Adding Bing webmaster verification

---

fec/fec/static/js/upcoming-events.js
fec/home/templates/partials/candidate_committee_services.html

Adds the blurb for the PACs section:
And makes few other copy edits requested by @emileighoutlaw

Copy updates to help section of home page

---

bin/run.sh
requirements.txt

This changeset makes a few improvements to the web server tooling we have in place.  It adds gevent for async request support in gunicorn and bumps the number of gunicorn workers up to 2.  It also updates the newrelic agent to the latest version.

Update web server tooling

---

README.md
fec/fec/settings/base.py
fec/fec/settings/production.py
fec/home/models.py
tasks.py

The receiver as defined as been tested and currently successfully receives changes to a user, pages I'm not too sure (as there are multiple page models so maybe just figure out which are needed).  Logging statement needs to be formalized too (time/date, specific action).

Logging feature for ATO

---

fec/home/templates/home/contact.html

Public Records Division --> Public Records Office
Content only; anyone can review.

Updates name

---

fec/home/templates/home/home_page.html

Copy and link updates for https://github.com/18F/fec-cms/issues/976

Update Citizen Info on Homepage

---

fec/fec/templates/partials/navigation.html
fec/home/templates/home/home_page.html
fec/home/templates/partials/candidate_committee_services.html

Ran the home page and related pages on the CMS through HTML_CodeSniffer and Chrome Accessibility Audit. Resolved severe errors and warnings about labels, unique IDs, and aria labeling.

Home Page Accessibility Updates

---

fec/home/templates/partials/current-commissioners.html
fec/home/templatetags/commissioners.py

Automatically show vacant seats on current commissioner's block including Vacant Chair or Vacant Vice Chair

Vacant commissioners

---

fec/fec/templates/partials/navigation.html

Same as https://github.com/18F/fec-style/pull/688

Adding tab index

---

package.json

This changeset updates fec-style to the latest version.

Update fec-style to 10.1.1

---

fec/home/templates/home/updates/digest_page.html
fec/home/templates/home/updates/press_release_page.html
fec/home/templates/home/updates/record_page.html
fec/home/templates/home/updates/tips_for_treasurers.html

Removes the disabled share buttons from the record, press release, tips, and digest pages.

Removing share buttons

---

fec/fec/settings/base.py
fec/fec/templates/base.html

We are not using ethnio but taking the references out to be clear

Remove ethnio reference

---

fec/home/templatetags/home_page.py

This fixes the What's Happening section on home page to show missing pinned items. It was only fetching the latest 4 updates before, therefore missing any older pinned posts. This fix will grab and show all pinned items regardless of date.
Bug: https://github.com/18F/fec-cms/issues/1047

Homepage Pin Fix

---

fec/home/templates/partials/candidate_committee_services.html

Fixing the YouTube links on the home page to go to the correct videos per tab.

Fixing youtube links

---

fec/gulpfile.js
package.json

This minifies the `fec.js` file.

HOTFIX: Uglify JS

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
tasks.py

we will want to do this later in the day

[MERGE WITH GITFLOW] Hotfix/www in manifest

---

fec/home/templates/home/contact.html

Efiling noticed their email missing, this adds it.

Added electronic filing email

---

fec/home/templates/home/contact.html

For option 2 on https://github.com/18F/fec-cms/issues/1159#issuecomment-319652593

New contact info for info division

---

fec/home/templates/home/contact-form.html

Requested hotfix from Rebecca and Paul (cannot wait until next release)
Slack:
Paul Clark [1:52 PM] 
Hey, John can you make changes to the contact page>
[1:53] 
The 1-800 number is incorrect on this page:
[1:53] 
https://www.fec.gov/help-candidates-and-committees/question-rad/

[MERGE WITH GITFLOW] hotfix/ fix phone number on contact form

---

fec/home/templates/home/contact-form.html
fec/home/templates/home/contact.html

Resolves https://github.com/18F/fec-cms/issues/1234

[MERGE WITH GITFLOW] Hotfix - RAD form link fixes

---

fec/home/templates/home/contact.html

`Teletypwriter` 👉  `Teletypewriter`
Content change only.
Resolves https://github.com/18F/fec-cms/issues/1245

Fixes typo on contact page

---

fec/home/templates/blocks/mur_search.html

Adds link to adv search & MUR number search

---

manifest_base.yml
manifest_dev.yml

Making the debug false explicit in all environments

---

fec/fec/templates/partials/navigation/nav-about.html

resolves https://github.com/18F/fec-cms/issues/1293
Added contact menu item to About menu.

Added contact link to about

---

fec/home/templates/home/meeting_page.html

https://github.com/18F/fec-cms/issues/1342

fixed draft minutes tag in meeting_page.html template

---

fec/home/templates/home/contact.html

Fixes spelling correction on contact page as outlined in this ticket: https://github.com/18F/fec-cms/issues/1245

Spelling correction on contact page

---

fec/home/templates/home/home_page_banner_announcement.html
fec/home/templates/partials/draft-home-page-banner-announcement.html
fec/home/templatetags/home_page.py

New branch based on release/public-20171011

changes for previewing homepage banner announcements

---

fec/fec/static/js/data/terms.json

new glossary terms added by @dorothyyeager

new glossary terms

---

fec/home/templates/home/contact-form.html

Text change for : https://github.com/18F/fec-cms/issues/1259

edits to rad contact form language

---

fec/data/templates/layouts/main.jinja
fec/fec/static/js/modules/feedback.js
fec/fec/templates/base.html

This changeset addresses an issue with the Feedback form and a missing CSRF token.  See PR #1397 for more details.

[MERGE WITH GIT FLOW] Fix missing CSRF token for Feedback form

---

fec/data/templates/partials/warnings.jinja
fec/data/templatetags/filters.py

This changeset addresses an issue where the environment the application is running in was not being checked for correctly in the data portion of the app since the merge.  This is fixed by creating a new global template tag function that returns the current environment value so that it can be checked in the templates.

[MERGE WITH GIT FLOW] Fix for warning banner in data portion of site

---

fec/legal/templates/legal-advisory-opinions-landing.jinja

modified /fec/legal/templates/legal-advisory-opinions-landing.jinja
#1420

[MERGE WITH GIT FLOW] Hotfix- Fix AO broken button

---

fec/data/templates/macros/entity-pages.jinja
fec/data/templates/partials/committee/filings.jinja
fec/data/utils.py
fec/data/views.py

Resolves https://github.com/18F/fec-cms/issues/1421
Fixed so that the min_receipt_date could be pulled into the API call and displayed on the jinja template. 
Note that there was also a requested change in the time interval from 2 to 3 days. Code has been updated accordingly.

[MERGE WITH GIT FLOW] Raw efile fix

---

fec/data/constants.py

Updating Senate classes and upcoming election years with correct information. Original issue was to fix states and associated classes - discovered incorrect upcoming elections in testing

[MERGE WITH GITFLOW] Hotfix/correct senate classes

---

fec/data/views.py

Addresses https://github.com/18F/openFEC/issues/2730
Fix broken redirects by importing redirect from django.shortcuts package

[MERGE WITH GIT FLOW] Hotfix/fix redirects

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Part of #1451 
- Adds a pull request template so that any time a new PR is filed, team members are prompted to fill in helpful information for observers and reviewers
- Specifies some language in the CONTRIBUTING.md file related to https://github.com/18F/fec-cms/pull/1454 (Added when I thought this PR would have more to do with the changes to CONTRBUTING, but we are making that a separate PR.)
- Repository only

Adds pull request template

---

fec/fec/static/scss/components/_type-styles.scss
fec/home/templates/home/home_page.html

@jenniferthibault realized that we need to have h4 headings in the Get started section of the homepage. This adds this refinement.
-  Homepage

Get started homepage edits

---

fec/data/api_caller.py

This changeset adds logging to the API caller so we have a bit more visibility into things when an error occurs.  The logging takes place in the underlying `_call_api` method that serves as the backbone for all API requests made by the CMS.
There are several formatting improvements included in this changeset to help improve readability as well.
h/t to @LindsayYoung, who originally did this work!

Add logging to the API caller

---

package.json

- Addresses #1624 
Updates Moment version as found in weekly security check 12/6/17 https://gemnasium.com/github.com/18F/fec-cms/alerts#alert-6591671
[JavaScript package](https://momentjs.com/) used in most front-end pages: https://github.com/18F/fec-cms/search?utf8=%E2%9C%93&q=moment&type=

Security patch: update Moment from 2.17.1 to 2.19.3

---

fec/data/templates/layouts/main.jinja
fec/fec/settings/base.py
fec/fec/static/js/data-init.js

- Addresses # https://github.com/18F/fec-cms/issues/1623
Added analytics code back into data pages. 
- Data section

[MERGE WITH GITFLOW HOTFIX] Adding analytics to data main.jinja template

---

fec/fec/static/js/data/terms.json

Updating to add one missing term
- Addresses # [_1633_]
- Adding "non-contribution account"

Update terms.json to add one missing term

---

fec/data/api_caller.py

Issue:
https://github.com/18F/fec-cms/issues/1508
Addresses suggestions by @ccostino in this review: 
https://github.com/18F/fec-cms/pull/1471#pullrequestreview-77592982

Refactor senate specials work to improve error handling

---

README.md
tasks.py

Adds additional functionality to support automated deploy of feature space. Cheers to @LindsayYoung for working with me on this!
https://github.com/18F/fec-cms/pull/1700

Added automated deploy instructions and deploy rules

---

fec/home/templates/home/contact-form.html

Needed to add the shutdown link to the Contact analyst page.
-  https://www.fec.gov/help-candidates-and-committees/question-rad/

Adding shutdown link

---

fec/home/templates/home/contact-form.html

After shutdown is over, this will restore the analyst look up and contact forms for RAD. 
-  https://www.fec.gov/help-candidates-and-committees/question-rad/

[HOTFIX Merge with GITFLOW] Restores rad contact form after shutdown passes

---

fec/home/templates/home/home_page.html

Remove Commissioner Goodman from home page, add vacant seat
- Addresses issue: https://github.com/18F/fec-cms/issues/1758
Remove Commissioner Goodman from home page, add vacant seat
**For next release**

Remove Commissioner Goodman from home page, add vacant seat

---

package-lock.json
package.json

Updated the fullcalendar dependency package **` moment`** from 2.17.1  to 2.19.3

update moment package

---

README.md

- Addresses #1836 
Updated references to fecgov organization after repo transfer

[HOTFIX - MERGE WITH GITFLOW] Update fec-cms references to fecgov

---

fec/data/constants.py
fec/data/templates/macros/tables.jinja
fec/data/templates/partials/party-coordinated-expenditures-filter.jinja

Addresses: https://github.com/18F/fec-cms/issues/1821
This PR fixes API call for Coordinated party expenditure. Test link: http://localhost:8000/data/committee/C00003418/

Fix Party Coordinated Expenditure year filters

---

fec/home/templates/home/latest_updates.html

Quick fix for language on govdelivery email signup accordion. 
This is a follow on to the merged PR  https://github.com/fecgov/fec-cms/pull/1890

GovDelivery-changed language on signup-accordion

---

fec/home/templates/home/latest_updates.html

Revert "GovDelivery-changed language on signup-accordion"

---

.circleci/config.yml
README.md
runtime.txt

Modified .circleci/config.yml to include python:3.6.5-jessie-node and postgres:9.6.8
Modified README.md and runtime.txt to include python-3.6.x

Update our infrastructure to use latest version of Python 3.6

---

fec/data/templates/committees-single.jinja
fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/templates/partials/committee/about-committee.jinja
fec/data/views.py
fec/fec/static/scss/components/_buttons.scss

- Addresses #1476 
- Added [callout](https://fec-pattern-library.app.cloud.gov/components/detail/callout.html) card with candidate information to the `About this committee` page for all authorized candidate committee pages. The candidate name text should link to the applicable candidate profile pages. 
- Add the [button (call-to-action basic)](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html) to the left-nav to direct users back to the applicable candidate committee profile pages
- Remove "Political party" line from `About this committee` section. This information, which is relevant to the candidate, will now be found in the card.
- On candidate profile pages, in the `About this candidate` section, switch the `Committees` section with the `Other documents filed` …

Add authorized candidate to authorized committee profile page

---

fec/fec/static/js/data/terms.json

Putting in changes to glossary requested by OGC
- Addresses # [_2026_]
Adjusts definitions of super PAC and Independent expenditure only committee to correspond to each other

Update terms.json - June

---

.github/PULL_REQUEST_TEMPLATE.md

- Resolves #2059
_Using the keyword "resolves" to automatically close the referenced issue upon PR merge._

Closing issue using keyword "resolves" in PR

---

README.md

Update ecosystem guide links - links to 18F's JavaScript and Python ecosystem guides were broken

Update ecosystem guide links on README

---

fec/data/templates/partials/elections/about-this-election-tab.jinja

- Addresses #2120 
_Specific text needed to be added for the presidential office._
-  Presidential election profile page

Text for presidential state election offices

---

requirements.txt

- Resolves #2182 
_Remove bandit - unused package with vulnerability._
-  None

Remove bandit - unused package with vulnerability

---

fec/checkweb/admin.py
fec/checkweb/apps.py
fec/checkweb/templates/checkweb.jinja
fec/checkweb/templates/macros/page-header-checkweb.jinja
fec/checkweb/templates/partials/api-info.jinja
fec/checkweb/templates/partials/check-export.jinja
fec/checkweb/templates/partials/checkweb-sidebar-nav.jinja
fec/checkweb/templates/partials/election-candidate-totals.jinja
fec/checkweb/tests.py
fec/checkweb/urls.py
fec/checkweb/views.py
fec/fec/settings/base.py
fec/fec/urls.py

This is a new Django app : checkweb
Which can check some fec website functions and display some information.
(1)check export(download) function (pick up a small data set to export)
(2)get api information
1)checkout branch: feature/create-checkweb-app
2) `npm run build`
3) test url: [http://127.0.0.1:8000/checkweb/](http://127.0.0.1:8000/checkweb/)
(1)Click **Export** button to test download.
(2)display which api your fec-cms points to now:

New app checkweb to check website status and get some information

---

fec/data/tests/test_candidate.py
fec/data/views.py

Add tests for candidate view

---

fec/data/templates/macros/cycle-select.jinja
fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/templates/partials/candidate/financial-summary.jinja
fec/data/templates/partials/candidate/other-spending-tab.jinja
fec/data/templates/partials/candidate/raising.jinja
fec/data/templates/partials/candidate/spending.jinja
fec/data/templates/partials/committee/about-committee.jinja
fec/data/templates/partials/committee/filings.jinja
fec/data/templates/partials/committee/financial-summary.jinja
fec/data/templates/partials/committee/raising.jinja
fec/data/templates/partials/committee/spending.jinja
fec/data/tests/test_candidate.py
fec/data/views.py

Revert "Refactor candidate view, fix 404's for future candidates"

---

fec/fec/static/js/modules/filters/filter-tags.js
fec/fec/static/js/modules/tables.js

- Resolves #2366 
Remove data table counts at the top of each table, as well as filter count updates on left sidebar until we can address all the existing count issues (https://github.com/fecgov/openFEC/issues/3104, etc)
Receipts
-  http://localhost:8000/data/receipts/
- http://localhost:8000/data/receipts/individual-contributions/
Disbursements
- http://localhost:8000/data/disbursements/
- http://localhost:8000/data/independent-expenditures/
- http://localhost:8000/data/party-coordinated-expenditures/
- http://localhost:8000/data/electioneering-communications/
- http://localhost:8000/data/communication-costs/
Loans
- http://localhost:8000/data/loans/
Candidates
- http://localhost:8000/data/candidates/
- …

[MERGE WITH GIT FLOW] Remove datatable counts

---

.eslintrc
fec/data/templates/layouts/main.jinja
fec/data/templates/macros/reaction-box.jinja
fec/data/views.py
fec/fec/settings/base.py
fec/fec/static/js/data-init.js
fec/fec/static/js/init.js
fec/fec/static/js/modules/feedback.js
fec/fec/static/js/modules/reaction-box.js
fec/fec/static/js/pages/data-advanced.js
fec/fec/static/js/pages/data-landing.js
fec/fec/static/js/templates/feedback.hbs
fec/fec/templates/base.html
fec/fec/tests/js/feedback.js

- Resolves #2205 
Use invisible RECAPTCHA to safeguard against bots submitting to our global feedback drawer form on the website. 
This uses invisible reCAPTCHA, which requires no additional work on the user's side to submit a form. The reCAPTCHA will only be invoked after the user clicks on the submit/post button. By default only the most suspicious traffic will be prompted to solve a captcha. Read more here: https://developers.google.com/recaptcha/docs/versions#invisible
This PR utilizes the "automatically bind the challenge to a button" to invoke the invisible reCAPTCHA: https://developers.google.com/recaptcha/docs/invisible#auto_render. This is used for the feedback drawer, since it is used on every page on our site and can be easily invoked with the `submitFeedback`callback function. …

Feedback drawer RECAPTCHA implementation

---

fec/data/templates/election-lookup.jinja
fec/fec/static/js/modules/election-form.js
fec/fec/static/js/modules/election-search.js
fec/fec/static/js/pages/election-lookup.js
fec/fec/static/js/templates/upcomingPresidential.hbs
fec/fec/static/scss/components/_search-controls.scss
fec/fec/static/scss/components/_search-results.scss

Election search page redesign after additional grooming. 
This PR replaces : [WIP] Election search page redesign #2409 
- Resolves #2353
This PR replaces : [WIP] Election search page redesign #2409
Design and Functionality changes to the  /data/elections (elections search page) as outlined mockup and in last conversation in PR 2409 : https://github.com/fecgov/fec-cms/pull/2409#issuecomment-426711308
This includes changes to SCSS and JS files.

NEW Election search redesign

---

fec/data/templates/partials/advanced/bulk-data.jinja

- Resolves #2473 
_Fixed broken links as specified in the above referenced ticket._
-  Advanced data, download bulk data tab

Fixed links to efiling and paper filed formats under bulk downloads

---

fec/fec/templates/partials/footer-navigation.html

- Resolves part of #2360 
_Updates IG link in footer to new wagtail page._
-  IG footer link

update IG link in footer

---

fec/data/templates/macros/entity-pages.jinja
fec/fec/static/js/pages/committee-single.js

- Resolves #2476
- Committee filings page:
**In Production:**
**After Fix(local):**
- checkout the branch`feature/add-imagenumber-to-committee-filings-table`
- in cms terminal `export FEC_API_URL` to `dev` or `prod` api
- start server
- open this link on a browser  : http://127.0.0.1:8000/data/committee/C00630426/?tab=filings
___

Add imagenumber column to the committee filing tables

---

fec/data/templates/partials/advanced/raising.jinja

Resolves outstanding text edit left out of  original PR #2495 for `Raising` per @llienfec's comment :
https://github.com/fecgov/fec-cms/issues/2426#issuecomment-436782270
- Resolves #2426
modified:   data/templates/partials/advanced/raising.jinja_
#2495
____

Correct Raising text-datatable descriptions

---

requirements.txt

- Resolves #2456 
Snyk alert: https://app.snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435
Requests version history: https://pypi.org/project/requests/#history
Most of the application. A sampling: 
/fec-cms/fec/data/api_caller.py
/fec-cms/fec/data/views.py
/fec-cms/fec/fec/forms.py
/fec-cms/fec/fec/tests/test_form.py
/fec-cms/fec/home/templatetags/open_jobs.py
/fec-cms/fec/home/views.py
/fec-cms/fec/search/management/commands/
/fec-cms/fec/search/tests/test_indexing.py
/fec-cms/fec/search/tests/test_views.py
/fec-cms/fec/search/utils/search_indexing.py
/fec-cms/fec/search/views.py
- Requests is a highly maintained library unlikely to have breaking changes
- Automated tests rely heavily on `requests`
- Candidate/Committee profile …

Upgrade requests to 2.20.1

---

fec/home/views.py

fixed undefined 'paginator' in views.py
- Resolves #2493 
update 'paginator' to corresponding defined paginator: meetings_paginator, hearings_paginator, exectutive_paginator
fev.gov/about: commission meetings page
-  
branch | PR
This might include:
- links to sample pages to test
- Any local environmental setup that is different than the usual …

Feature/cms 2493: fix a non-defined variable bug in home/views.py in cms

---

fec/fec/tests/js/date-filter.js
fec/search/management/instructions.md
fec/search/templates/search/search.html
requirements.txt

- Resolves #2573 
- Update lxml package for security vulnerability
- Fix broken 18F repo links
- Update test to dynamically generate start of previous year
- Scraping management tasks - we're not sure whether these need to be changed/updated but we may need to run them in the future, so we're leaving them here for now.

[MERGE WITH GIT FLOW] Update lxml package

---

fec/home/templates/home/home_page.html

[MERGE WITH GITFLOW] Update Commissioners on homepage for 2019

---

fec/home/templates/home/home_page.html

_Update from `Vice Chair` to `Vice Chairman`._

[Hotfix - Merge with GITFLOW] Update homepage vice chairman

---

fec/data/templates/partials/browse-data/bulk-data.jinja
fec/data/templates/partials/browse-data/candidates.jinja
fec/data/templates/partials/browse-data/committees.jinja
fec/data/templates/partials/browse-data/filings-reports.jinja
fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja

- Resolves #2705
_Updated datasets as specified in #2705 ._
-  Browse-data pages: bulk data, candidates, committees, filings, raising, and spending.
- Run branch locally
- Look at connected issue to make sure data sets have been added as specified

added 2019-2020 datasets as specified in fec-cms #2705

---

fec/fec/static/js/legal/LegalSearch.js
fec/home/templates/blocks/mur_search.html
fec/home/templates/home/commission_meetings.html
fec/legal/templates/legal-advisory-opinions-landing.jinja
fec/legal/templates/legal-search-results-adrs.jinja
fec/legal/templates/legal-search-results-afs.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/legal-search-results.jinja
fec/legal/templates/partials/legal-search-results-advisory-opinion.jinja

- Resolves #2661 
_Updates saos, sers, and eqs links to point to https._
-  AOs landing: http://localhost:8000/data/legal/advisory-opinions/
- Enforcement landing: http://localhost:8000/legal-resources/enforcement/
- Meeting hearings tab: http://localhost:8000/meetings/?tab=hearings

Update saos, sers, and eqs links to be https

---

fec/data/templates/partials/meta-tags.jinja
fec/fec/templates/partials/meta-tags.html
tasks.py

- Resolves #2778 
_Default to IE 11 browsers to resolve datatable issues._
-  Datatable related pages
- Go to the dev site, this branch is currently deployed there, data pages should function

[HOTFIX - Merge with gitflow] Default to IE11

---

fec/data/templates/partials/meta-tags.jinja
fec/fec/templates/partials/meta-tags.html

Revert "[HOTFIX - Merge with gitflow] Default to IE11"

---

fec/home/templates/home/home_page.html

***This is V2 since we needed to branch from master***
- Resolves #2779 
Add back a script previously lost from home/templates/home/home_page.html
Just the homepage Events and deadlines section
They're back!
none
- Check the homepage
- Make sure the events and deadlines load (a couple seconds after the rest of the page)
____

[HOTFIX - Merge with gitflow] Re-activate Events and deadlines on homepage (v2)

---

README.md

Copied from https://github.com/fecgov/FEC/blob/master/README.md

Include all repos in README

---

.github/ISSUE_TEMPLATE/feature_req.md
.github/ISSUE_TEMPLATE/issue_template.md
.github/PULL_REQUEST_TEMPLATE.md

- Resolves #2820 
I've added a first-pass of a template for new issues.
Should only affect when creating a new issue.
None. I don't think I can preview it ahead of time.
None.
1. Push the template to Git
1. Start to enter a new ticket
…
1. Adjust template as needed

Create v1 of a template for new issues

---

fec/home/templates/home/latest_updates.html

Updated the no-results language for updates.
- Resolves #2889 
Only the latest_updates.html template has been changed.
The new language in place:
None
- May need to re-launch runserver (`./manage.py runserver`)
- Go to http://localhost:8000/updates
- Search for something that won't be found
- Scrutinize each character
- Check other search results pages to make sure they're unaffected
____

2889 Update 'No Results' message for Updates

---

fec/data/templates/macros/filters/date.jinja
fec/data/templates/macros/filters/years.jinja

- Resolves #2936 
_Updated report time period filter tooltip to be more accurate._
-  Disbursements datatable: http://localhost:8000/data/disbursements/
- Go to the Disbursements datatable: http://localhost:8000/data/disbursements/
- Check to make sure the REPORT TIME PERIOD filter tooltip has the correct text as indicated in the screenshot above.
____

updated Report time period filter tooltip

---

fec/data/templates/partials/candidate/other-spending-tab.jinja
fec/data/templates/partials/committee/spending.jinja
fec/fec/static/js/modules/filters/filter-set.js
fec/fec/static/js/modules/filters/filter-typeahead.js

Reverts fecgov/fec-cms#2955, merged too soon

Revert ""Filter this data" button link to regularly scheduled reports"

---

manifest_feature.yml

- Resolves https://github.com/fecgov/fec-cms/issues/2984
Updated the API url in `manifest_feature.yml` file to point to stage api
-  cms feature space (https://fec-feature-cms.app.cloud.gov/)
- do a manual deploy of `feature/change-cms-feature-space-to-point-stage-db` to `feature` space by modifying here: https://github.com/fecgov/fec-cms/blob/develop/tasks.py#L79
- let the circle build finish
- Pick any endpoint on cms `feature` and `stage` space and compare the  data counts. they should be same. 
For example : raw efiling data counts on` feature` vs `stage` spaces. …

Update the API url in feature manifest file to point to stage api.

---

README.md

- Resolves None
Changed some punctuation in the Readme.

[MERGE WITH GITFLOW] Hotfix/trivial punctuation change

---

requirements.txt

- Resolves #3023 and #2944 
- Update `requirements.txt` from `django@1.11.20`-->~`django@1.11.22`~ `django@1.11.23`
-  cms, wagtail

upgrade to django@1.11.23

---

fec/data/templates/partials/meta-tags.jinja
fec/home/templates/blocks/mur_search.html
fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
fec/home/templates/home/legal/legal_resources_landing.html
fec/legal/templates/layouts/legal-doc-search-results.jinja
fec/legal/templates/legal-search-results-murs.jinja
fec/legal/templates/legal-search-results.jinja
fec/legal/templates/macros/legal.jinja

- Resolves #3083 
_Adds `closed` text to all references of MURs or Matters under review._
- Help for candidates and committees landing page
- Legal resources landing page
- MURs search page
- Legal search results page (MUR category, description, and left nav)
- Global legal search options
- MUR search box on enforcement page
- Look at screenshots above and click on localhost links to make sure changes match screenshots
- For content staff - check that the screenshots are ok and that casing for changes are correct

Updating title for MUR searches 

---

fec/fec/static/js/widgets/contributions-by-state-box.js

- Partial resolution for https://github.com/fecgov/fec-cms/issues/3203
Update error message to include 'itemized'
Where contributions come from

Update error message to include 'itemized'

---

fec/data/templates/partials/browse-data/filings-reports.jinja

Add link on /data/browse-data/?tab=filings to e-filing form which is published on production at https://www.fec.gov/fec-electronic-filing-report-retrieval/
- Resolves #3493 
/data/browse-data/filings-reports.jinja
This might include:
- See link on http://127.0.0.1:8000/data/browse-data/?tab=filings
____

[HOTFIX - MERGE-WITH-GITFLOW] Link to e-filing form

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/task-issue.md
.github/PULL_REQUEST_TEMPLATE.md

- Resolves [no ticket]
- Simplifying our issue templates
- Massaging the PR template to soothe linter warnings
All of our Github templates
None
None
I don't think we can test them until we merge them. But they're don't affect anything after Git.
They're only changes to text and markdown, though, so they can be pretty well tested by reviewing this PR.
____

Simplify template language

---

.circleci/config.yml
requirements.txt

1. Update the CircleCI configuration version from 2.0 to 2.1 to enable pipelines.
2. Update Git Python pkg to latest v3.1.0 to fix the build errors (gitpython-developers/GitPython#983) 
- Resolves #3578 
- Update circleci configuration to v2.1 in circleci/config.yml file
- Update Git Python pkg in requirements.txt file
- update the tasks.py with the `feature/3578-enable-circleci-pipeline` branch and deploy to `dev` space.
**CircleCI dashboard _without_ pipeline:**
**CircleCI dashboard _with_ pipeline:**

 [fec-cms] Enable circleci pipeline

---

requirements.txt

I cherry-picked c042e92ba6ea91de406e5b6e30b56c9b0b8991c8 into a branch off the release branch

Add GitPython update to release

---

package-lock.json
package.json

Resolves #3605
- Fix acorn vulnerability
- Run `npm audit fix`
I tested this with a manual deploy to `dev` and testing locally
- run `npm i`
- run `npm run build`
- test locally

Fix acorn vulnerability

---

fec/data/templates/pres-finance-map.jinja
fec/fec/static/scss/base.scss
fec/fec/static/scss/widgets/pres-finance-map.scss

- Resolves #3646 by implementing the reaction box for the presidential map
- Brings commits from https://github.com/fecgov/fec-cms/pull/3636 into this branch with `git cherry-pick`
Submitting the reaction won't work locally unless you have recapcha and github tokens set up - I deployed this to `feature` for easier testing. https://fec-feature-cms.app.cloud.gov/data/candidates/president/presidential-map/
-  https://www.fec.gov/data/candidates/president/presidential-map/
- Make sure you have `FEC_FEATURE_PRESIDENTIAL_MAP` env var set
- Run this branch
- http://localhost:8000/data/candidates/president/presidential-map/
- Test actually submitting a reaction on …

[MERGE WITH GIT FLOW][HOTFIX] Add reaction box to presidential map, IE fixes

---

.circleci/config.yml
README.md
package.json
requirements.txt
runtime.txt

- Resolves #3640
Include a summary of proposed changes.
- Upgrade `gevent` pkg to resolve issue while installing the requirements.
- Update python version 3.7 in 
-  circleci/config.yml
- README.md
- runtime.txt
- Update the `fec-cms` **github url** to `fecgov` org in `package.json`
- checkout `feature/upgrade-python-3.7`
- run `pip install  -r requirements.txt`
- run `pytest` 
- run `npm run test-single`
- run `./manage.py runserver` and test datatables, presidential map and few endpoints to make sure data loads OK

update python to v3.7

---

README.md

 [MERGE WITH GITFLOW]Hotfix/fix empty tag

---

requirements.txt

upgrade psycopy2 from 2.7.3.2 to 2.8.5

[MERGE WITH GITFLOW] Upgrade Psycopg 2.8.5

---

.circleci/config.yml
README.md
fec/fec/settings/base.py
fec/fec/static/js/widgets/pres-finance-map-box.js
fec/fec/templates/partials/breadcrumbs.html
fec/fec/urls.py
fec/home/templates/home/feed_base.html
fec/search/templates/search/policy_guidance_search_page.html
fec/search/views.py
package.json
requirements.txt
runtime.txt
tasks.py

Add changes from `release/public 20200414` back to `develop`

Add changes from `release/public 20200414` back to `develop`

---

fec/data/templates/macros/filters/typeahead-filter.jinja
fec/data/templates/partials/disbursements-filter.jinja
fec/data/templates/partials/independent-expenditures-filter.jinja
fec/data/templates/partials/individual-contributions-filter.jinja
fec/data/templates/partials/receipts-filter.jinja
fec/fec/static/js/modules/tables.js
fec/fec/tests/js/tables.js

- Resolves #3779 
_Adds additional item limits for the following fields:_
**Individual contributions and Receipts datatable**
Recipient name or ID - committee_id
Name - contributor_name
Zip - contributor_zip
City - contributor_city
Occupation - contributor_employer
Employer - contributor_occupation
**Disbursements datatable**
Spender name or ID - committee_id
Recipient name or ID - recipient_name
City - recipient_city
**Independent expenditures datatable**
Spender name or ID - committee_id
Candidate name or ID - candidate_id
- Receipts datatable
- Individual contributions datatable
- Disbursements datatable
- Independent expenditures datatable
branch | PR …

Add additional limits to fields in Receipts, Individual contributions, and Disbursements datatable

---

fec/search/management/data/sitemap_pdf.xml

Updated the mod date from April to June 5, 2020
- Resolves #3793

Update Sitemap for Campaign Congressional Guide

---

fec/data/views.py

_Fixes formatting issues due to flake8 tests._
branch | PR
feature/4292-fix-candidate-transfer-committee | [link](https://github.com/fecgov/fec-cms/pull/3814)
Run pytest and make sure everything passes
____

fix flake8 formatting errors

---

fec/home/templates/home/contact-form.html
fec/home/views.py

- Resolves https://github.com/fecgov/fec-accounts/issues/286
_Add reCAPTCHA to the RAD contact form._
-  RAD Contact Form: http://localhost:8000/help-candidates-and-committees/question-rad/
These instructions will be added here: https://github.com/fecgov/fec-accounts/issues/286#issuecomment-677690073
____

[HOTFIX - MERGE WITH GITFLOW] Add recaptcha and additional logging to RAD contact form

---

fec/fec/static/js/templates/feedback.hbs

- Resolves #3985
_Modified the text to include additional information on which details are posted publicly when a user submits feedback._
-  https://github.com/fecgov/fec-cms/issues/3985
- Required reviewer: One front-end developer
Check to make sure the new language is there:
- `npm run build` and then runserver
- Check the language
____

Update feedback box language

---

fec/data/views.py

- Partial resolution for #4012
Add one PCC -> PAC conversion
-  Add more candidates to manual conversion list
- Committee and candidate profile pages should have explanatory text:
https://www.fec.gov/data/committee/C00723338
https://www.fec.gov/data/candidate/H0CO03157
- One approval needed
- Committee and candidate profile pages should have explanatory text:
http://localhost:8000/data/committee/C00723338
http://localhost:8000/data/candidate/H0CO03157

[Before release] Add one PCC -> PAC conversion

---

fec/data/views.py

- Partial resolution for #4012
Add one PCC -> PAC conversion
-  Add more candidates to manual conversion list
- Committee and candidate profile pages should have explanatory text:
https://www.fec.gov/data/committee/C00733261
https://www.fec.gov/data/candidate/S0KY00420
- One approval needed
- Committee and candidate profile pages should have explanatory text:
http://localhost:8000/data/committee/C00733261
**example**
http://localhost:8000/data/candidate/S0KY00420
**example**

Add one PCC -> PAC conversion

---

fec/fec/templates/partials/usa-banner.html

- Resolves #3940 
_Updated language for .gov banner on our website._
-  .gov banner at the top of all pages
- `npm run build` just in case for styles
- Click on the "Here's how you know ^" banner up at the top to expand it. The language should be updated as specified in the ticket.
____

Update .gov banner with revised text

---

requirements.txt

Pins greenlet@0.4.16 to fix build problem.

Pin greenlet@0.4.16 to fix build problem

---

fec/fec/middleware.py

- Resolves #[_Issue number_]
-  
- _Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface or front-end change, include both Before and After screenshots._
branch | PR
_This might include:_
- links to sample pages to test
- Any local environmental setup that is unusual (env vars, API version to point to, etc)
____

[Suggestion] Reformat CSP as data structure

---

README.md
code-gov-config.json
fec/fec/templates/code.json

- Resolves #4102
Regenerate code.json, add config file, update README.md
-  code.json metadata for code.gov
branch | PR
Add code.json file to root directory for code.gov | https://github.com/fecgov/fec-cms/pull/2260
- Make sure json structure hasn't changed
- Make sure json is valid: https://jsonlint.com/
- code.gov seems to have moved/removed its validator https://github.com/GSA/code-gov/issues/134

Regenerate code.json, add config file

---

fec/data/views.py

- Resolves #4081 
_Added committee C00705483 and candidate H0NM03110 to PCC to PAC converted list._
- http://localhost:8000/data/candidate/H0NM03110/
- http://localhost:8000/data/committee/C00705483/
- Checkout and test these two pages that the PCC to PAC conversion message is there:
- http://localhost:8000/data/candidate/H0NM03110/
- http://localhost:8000/data/committee/C00705483/
____

added committee C00705483 to converted list

---

.circleci/config.yml
README.md
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml
tasks.py

- Resolves #4138
- Resolves #3153 
- At least two reviewers please
**Through CircleCI**
- Make your own copy of this branch (please don't commit to this branch)
- Modify deploy task to deploy to a space of your choice
- Push to Github, make sure build works
**Locally:**
- Install cf cli version [following this guide](https://github.com/cloudfoundry/cli/wiki/Version-Switching-Guide) or:
```
brew install cf-cli@7
brew install cf-cli@6
brew unlink cf-cli@6 && brew unlink cf-cli@7 && brew link cf-cli@7 && cf version
```
- Set the env var `DJANGO_SECRET_KEY`
- Test with bad requirements.txt, like `Flask=2222`, make sure build fails
- Test with crashing app - add 5 instances,  at the top of `run.sh`, add:
```
rand_mod=$(expr $RANDOM % 5)
if [ $rand_mod -eq 0 ]; then
echo "Starting divisible by …
```

Implement rolling deployment

---

fec/data/templates/macros/missing-transferred.jinja
fec/data/templates/partials/candidate/financial-summary.jinja
fec/data/tests/test_committee.py
fec/data/views.py

- Resolves #3896 
_Retrieves and displays information for committees who have converted from a PCC to a PAC._
See samples from [this spreadsheet](https://docs.google.com/spreadsheets/d/1VypSyRziT-_bgf9PslVNCkVUZ15GovF33AshZ9-f-4s/edit#gid=0) 🔒 
- Committee profile pages that converted from PCC to PAC 
- Candidate profile pages that had a PCC converted to a PAC
If there's no committee name change, the last sentence "The previous name for the principal campaign committee was [former_committee_name]." will not appear.
branch | PR
feature/4292-fix-candidate-transfer-committee | [link](https://github.com/fecgov/fec-cms/pull/3814)
- Checkout this branch and run the …

Automate using API for PCC to PAC conversion committees

---

fec/data/templates/partials/browse-data/bulk-data.jinja
fec/data/templates/partials/browse-data/candidates.jinja
fec/data/templates/partials/browse-data/committees.jinja
fec/data/templates/partials/browse-data/filings-reports.jinja
fec/data/templates/partials/browse-data/raising.jinja
fec/data/templates/partials/browse-data/spending.jinja

- Resolves #4293
Update bulk data links for 2022
http://localhost:8000/data/browse-data/?tab=bulk-data
- All candidates `/files/bulk-downloads/2022/weball22.zip`
- Candidate master `/files/bulk-downloads/2022/cn22.zip`
- Candidate-committee linkages `/files/bulk-downloads/2022/ccl22.zip`
- House/Senate current campaigns `/files/bulk-downloads/2022/webl22.zip`
- Committee master `/files/bulk-downloads/2022/cm22.zip`
- PAC summary `/files/bulk-downloads/2022/webk22.zip`
- Contributions by individuals `/files/bulk-downloads/2022/indiv22.zip`
- Contributions from committees to candidates & independent expenditures `/files/bulk-downloads/2022/pas222.zip`
- Any transaction from one committee to another `/files/bulk-downloads/2022/oth22.zip`
- Operating expenditures …

[Before release] Update bulk data links for 2022

---

fec/data/templates/partials/candidate/about-candidate.jinja
fec/data/templates/partials/committee/about-committee.jinja
fec/data/tests/test_candidate.py

This PR is based on release/public-20210302 branch.
Fix some syntax and clean code.

Fix syntax and clean code

---

fec/fec/templates/home_base.html

- Previous #4462 issue was merged into release. This will merge into develop.
Closing an include
Homepage
No real visual changes, apart from the homepage isn't an error message if this works
#4463 is the same but merges into the release branch. This will merge into develop.
- If the [homepage](http://127.0.0.1:8000) isn't an error message, 🎉
____

Add apostrophe

---

fec/data/views.py
fec/legal/templates/legal-archived-mur.jinja

This is the undo PR.
The reason is I that merge the code by mistake without crating feature branch and PR. we should put back the origin code.
How to test:
follow this compare the change: [https://github.com/fecgov/fec-cms/commit/738fe60ecdb0fd3ad8bc9ac895a079ed107acdc7#](https://github.com/fecgov/fec-cms/commit/738fe60ecdb0fd3ad8bc9ac895a079ed107acdc7#)
make sure the origin code back.
one person review.

4448_undo_committee_terminated_bug

---

fec/fec/static/js/modules/column-helpers.js
fec/fec/static/js/modules/election-map.js
fec/fec/static/js/modules/maps.js
package-lock.json
package.json

- Resolves #4523
2 front end reviewers
maps.js
package.json
How to test:
checkout branch
npm i
npm run build
Test committee single page lto make sure filings table is populated:
http://127.0.0.1:8000/data//candidate/P80003338/?tab=filings
Check presidential election page too
http://127.0.0.1:8000/data/elections/president/2012/?tab=election-data#individual-contributions

[MERGE WITH GITFLOW- HOTFIX] Underscore upgrade and template syntax change

---

requirements.txt

- Resolves #4509 
Snyk reported a vulnerability inside lxml while scrubbing user input. The [release notes](https://pypi.org/project/lxml/4.6.3/) from 4.6.2 to 4.6.3 list only this fix.
One front-end and one back-end? (Feel free to edit the list)
Anything that uses the lxml package which, for us, is only the scraping and search scripts.
None
- `pytest` just in case
- I'd welcome your insight on how to test this when it's only used inside
- fec/search/management/commands/scrape_cms_pages.py
- fec/search/management/commands/scrape_transition_pages.py
- fec/search/management/commands/scrape_web_app_pages.py
- fec/search/utils/search_indexing.py

4509 SNYK LXML

---

fec/home/templates/home/commissioners.html

- Resolves #4679 4679
Update link to court case to point to new www location
1 content reviewer
-  All Commissioners page

Fix link on All Commissioners page

---

requirements.txt

- Resolves #4701 
Upgrading Django to address vulnerabilities
2 reviewers
The entire site, but only a couple of security patch levels
3.1.12 addressed two vulnerabilities:
- Directory Traversal via `admindocs`, `TemplateDetailView`
-  Improper Input Validation via `URLValidator`
None
None
-  pull the branch
- `npm run build` just in case
- check that the site's working as expected (a thorough test would include trying to break url fields with invalid/suspect characters)
Thanks Laura for the pairing and thanks Robert for the example PR!

4701 - Upgrade Django to 3.1.12

---

fec/data/templates/partials/browse-data/candidates.jinja

Test Explore presidential matching funds submission link
- Resolves #4594 
one front-end reviewer 
-  Candidate's browse data page

Update presidential candidate matching funds

---

fec/data/templates/partials/browse-data/committees.jinja

- Resolves #4765 
Update text for link to PAC and party datatable
1 content
-  Committees browse data page (http://localhost:8000/data/browse-data/?tab=committees)
- Check screenshot for content change and ensure it matches the [text here](https://github.com/fecgov/fec-cms/issues/4765#issuecomment-883683211)

Update Committees browse data text for pac and party datatable

---

requirements.txt

Release branch for Innovation sprint 16. @pkfec will deploy the release on 01/25/2022

[MERGE WITH GITFLOW] Release/public 20220125

---

fec/fec/static/js/data/terms.json

Adds two terms to glossary
https://docs.google.com/spreadsheets/d/1iSHhncHt8JCzYrh_UEHmyhoy3sKEpAnNNspCYdS188g/edit#gid=0 (see highlighted terms)
- #5042

Update glossary to add foreign national terms

---

fec/data/templates/landing.jinja

This is for the sprint (17.5) release. @fec-jli will deploy this on 04/05/2022.

[MERGE WITH GITFLOW] Release/public 20220405

---

package-lock.json
package.json

- Resolves #5150 
Upgrades moment to 2.29.2 to fix Directory Traversal vulnerability
1-2 devs
##Related PRs against other branches:
package library https://github.com/fecgov/fec-pattern-library/pull/189
- rm -rf node_modules
- npm i
- npm run build 
- pytest

5150-SNYK upgrade moment

---

requirements.txt

Upgrade gitpython to the latest version 3.1.27 
- Resolves #5081
- Update gitpython version in requirements.txt
one developer
**Before**:
- After:
- checkout branch: `git checkout feature/upgrade-gitpython`
-  create 3.8.x virtualenv: `pyenv virtualenv 3.8.12 venv-cms3812`
- install requirements: `pip install -r requirements.txt`
- run snyk test on requirements file: `snyk test --file=requirements.txt` (gitpython ReDos  vulnerability is resolved)
-  start server: `./manage.py runserver`
- test cms application

upgrade gitpython

---

fec/data/templates/election-lookup.jinja

- Resolves #5191 
Following mockup on #5191 
One developer
Election search page census accordion edited.
Also made "congressional" lower case (GPO style).
On #5191

Update census accordion language on election search page

---

fec/fec/settings/base.py
requirements.txt

This is the PR for the PI 17 innovation release. @lbeaufort will deploy the release on 5/10.

[MERGE WITH GIT FLOW] Release/public 20220510

---

fec/data/templates/partials/house-senate-overview/election-data.jinja
fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
fec/fec/settings/base.py

feature flag all-totals tables on https://fec.gov/data/elections/house/, https://fec.gov/data/elections/senate
one frontend
modified:   data/templates/partials/house-senate-overview/election-data.jinja
modified:   data/templates/partials/house-senate-overview/sidebar-nav.jinja
modified:   fec/settings/base.py
More to come...
export FEC_FEATURE_HOUSE_SENATE_OVERVIEW=TRUE
export FEC_CMS_ENVIRONMENT=prod
Make sure Totals table does not show

[MERGE WITH GIT FLOW ]Hotfix/feature flag all h-s totals

---

requirements.txt

- Resolves #5329
update lxml package to remove NULL Pointer Dereference vulnerability
1-2 devs
-  Affected versions of this package are vulnerable to NULL Pointer Dereference in the iterwalk() function (used by canonicalize) that can be triggered by malicious input.
NOTE: This only applies when lxml is used together with libxml2 2.9.10 through 2.9.14.
- `rm -rf node_modules`
- `npm i &&  run build`
-  run `snyk test --file=requirements.txt --package-manager=pip`  (confirm vulnerability is …

5329-upgrade lxml 4.9.1

---

package.json

- Resolves #5339 
Upgrades moment to 2.29.4 to fix Directory Traversal vulnerability
1-2 devs
##Related PRs against other branches:
package library TBD
- Run `snyk test` to see the vulnerability on dev
- rm -rf node_modules
- npm i
- npm run build 
- Run `snyk test` to ensure the vulnerability is now gone
- pytest

5339-Upgrade moment 2.29.4

---

fec/legal/templates/partials/legal-search-results-mur.jinja

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)
-  
branch | PR
(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point …

HOTFIX[ MERGE WITH GITFLOW] fix archive MUR name and election cycle to whitespace for archive murs

---

package.json

Sprint 18 Innovation release branch. @cnlucas will deploy this release on 08/23/2022

[MERGE WITH GITFLOW] Release/public 20220823

---

.circleci/config.yml
README.md
fec/data/templates/committees-single.jinja
fec/data/templates/partials/committee/spending.jinja
requirements.txt
runtime.txt

Sprint 19.2 release branch. @pkfec will deploy this release on Sept 20th

[MERGE WITH GITFLOW] Release/public-20220920

---

package-lock.json
package.json

Fixes failed builds with chromeheadless browser failing to start
1 developer
-  puppeteer
-Run in circleci again before merge https://github.com/fecgov/fec-cms/commit/45ed0b669008ad126ef2688e97b2a593c8497d2f

upgrade puppeteer to 18.2.1

---

requirements.txt

- Resolves #5497
Upgrade pillow to address security vulnerability
1-2 devs
-  Images, pillow is an image handler
-  checkout this branch
- `pip freeze` and make sure that pillow version 9.3.0 is installed
- Go to your [local wagtail images](http://localhost:8000/admin/images/)
- Try uploading an image, there should be no issues and upload should be successful.
- OR deploy to dev

5497 upgrade pillow

---

fec/fec/static/js/modules/table-columns.js

This is for the sprint (20.2) release.
@fec-jli will deploy this 1/10

[MERGE WITH GITFLOW] Release/public 20230110

---

requirements.txt

- Resolves #5603 
Upgrades django to remediate snyk vulnerability
1 dev
-  Django
-  check out this branch
- rm -rf node_modules
- npm i &&  npm run build
- snyk test --file=requirements.txt --package-manager=pip (confirm vulnerability is removed)
- pytest
- cd fec && ./manage.py runserver

upgrade django 3.2.18

---

.circleci/config.yml
fec/data/constants.py
fec/data/templates/pres-finance-map.jinja
fec/data/templates/widgets/pres-finance-map.jinja
fec/fec/static/js/widgets/pres-finance-map-box.js
fec/fec/static/scss/widgets/pres-finance-map.scss
requirements.txt
tasks.py

- Resolves #5641 
- Resolves #5666 
Updated the presidential finance map to get ready for 2024 and include previous years (if API will support it)
- 1 front-end
- 1 UX
- 1 back-end/db?
- 1 product owner?
Only the presidential map is affected
Initial `feature/` PR: #5648 
- npm i
- Check the [presidential map](http://127.0.0.1:8000/data/candidates/president/presidential-map/)
- **Known issues**
- At this point, 2024 data doesn't exist so
- the map default to 2020.
- At this point, data before 2016 doesn't exist (not sure whether it will)

[HOTFIX] 5666 2024 presidential map

---

fec/data/templates/partials/browse-data/candidates.jinja
fec/data/views.py

Revert "Hotfix/5701 add 2024 pres export links"

---

manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml

- Resolves #5727 
This ticket upgrades the stack to cflinuxfs4. 
-  manifests 
- Deploy this branch to dev (will do on Monday)

upgrade stack to use cflinuxfs4

---

requirements.txt

- Resolves #5726 and #5749
Small upgrades to requests and django to remove vulnerabilities and match our current eregs versions.
1 dev
-django 
-    check out this branch
-    pip install -r requirements.txt
-    rm -rf node_modules
-    npm i && npm run build
-    snyk test --file=requirements.txt --package-manager=pip (confirm both vulnerabilities are removed)
-    pytest
-    cd fec && ./manage.py runserver

5726-upgrade django and requests

---

requirements.txt

Sprint 22.2 release branch. @pkfec will deploy on Aug 8th
Notes:
- Upgrade django to v3.2.20

[MERGE WITH GITFLOW] Release/public 20230808

---

fec/data/templates/layouts/main.jinja
fec/fec/static/scss/components/_contact-items.scss
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/home/blocks.py
fec/home/templates/home/commission_meetings.html
fec/home/templates/home/meeting_page.html
fec/home/templates/purgecss-homepage/full.html
fec/home/templates/purgecss-homepage/navs.html

- Resolves #5838 
Hotfix PR for the work over on PR #5841

[HOTFIX - MERGE WITH GITFLOW] 5838 addresses

---

fec/fec/templates/robots_prod.txt

- Last minute fix for wrong domain in robots.txt
one developer
robots.txt

change to www domain on robots.txt

---

fec/data/templates/partials/browse-data/filings-reports.jinja

- Resolves #5802 
Changed unverified filers to false and fictitious filings everywhere except file names. That change is TBD currently.
- 1, front-end or content 
-  filings-reports.jinja
branch | PR
- Look at filings-reports.jinja and make sure everything still looks good

Update filings-reports.jinja for false and fictitious filings

---

fec/fec/static/js/pages/statistical-summary.js

- Resolves #5902
[PACS Statistical summary data](https://www.fec.gov/campaign-finance-data/political-action-committee-data-summary-tables/) will have additional rows added to table for for 2023-2024 (12a-14d).
- In `fec/static/js/pages/statistical-summary.js`,  add the conditional switch statement to use a new table (`id="type_3"`) for years greater than or equal to 2023-2024.
- **Add-on:** Also noticed broken functionality with the latestAvailableOption function where links and display text were not correct after user-interaction fires that function.
- Once we get the new table and upload XLS and PDFs ,follow  steps in the [issue's Action items](https://github.com/fecgov/fec-cms/issues/5902#issue-1887792002) to edit in Wagtail.
one team-member
modified: …

Add new statistical summary table for PACS

---

fec/search/management/data/sitemap_pdf.xml

Updates guidance search code for updated forms on 9/21/2023
Resolves #5846
1 content to doublecheck file names are in alphabetical order by section (we can't use the ### to show the sections so it's rough) and form file names follow this convention
fecfrm#.pdf
fecfrm#i.pdf
1 front end to doublecheck code
Guidance documents search

Update sitemap_pdf.xml for revised forms

---

fec/home/templates/home/home_page.html
fec/home/templates/purgecss-homepage/full.html

- Resolves #5953 
Updating the slug/url for the page for election (results) and voting information
1xContent
Only this one link (I updated it in the purgecss optimizer files for consistency but the content there is irrelevant)
- Check the updated code

5953 - Homepage, update election and voting info url

---

fec/fec/settings/base.py
tasks.py

- Resolves (no ticket number)
We'd merged into `develop` code that would have deployed a non-existent debts branch to Feature. This will fix that
Site deployment, but this makes it normal
- 1 front- or back-end dev (go ahead and merge right away)
None

Debts - fixing deployment

---

tasks.py

- Inadvertently merged branch with feature deploy task in https://github.com/fecgov/fec-cms/pull/5975, this reverts it.
one developer
modified tasks.py

rm feature deploy task

---

fec/fec/static/scss/components/_mega-menu.scss

- Resolves #6002 
Fixing the main nav layout, mostly for Safari
UX
Front-end
The main nav, site-wide
Fixed in Safari
Not broken in Chrome
Not broken in Firefox
None
- `npm i`
- Test any page

6002 - Main nav layout

---

fec/fec/static/js/data/terms.json

Adding the term "compensation" to the json glossary
Resolves #6120 
Please review, Pat, John and/or Dorothy 
-  
branch | PR
- 
(If this pull request changes our [current system diagram](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram), include a description of those changes here and create a new ticket to update …

Update the term compensation to json ticket #6120

---

tasks.py

This will remove the feature branch from the release.

remove feature branch

---

fec/fec/static/js/data/terms.json

Updated tech modernization glossary terms 
- Date made
- Date received 
- Earmarked contribution
- Filing
- Joint contribution 
- Promoted for a fee (new) 
- Public communication 
- Refunded contribution
- Written instrument
- Resolves #6136 
Content review Dorothy  and frontend Pat 
#

Update terms.json for Tech Modernization

---

fec/data/api_caller.py
fec/home/blocks.py
fec/home/templates/blocks/adr_search.html
fec/legal/templates/legal-adr.jinja
fec/legal/templates/legal-search-results-adrs.jinja
fec/legal/templates/macros/legal.jinja
fec/legal/templates/partials/legal-search-results-adrs.jinja

Several modifications have been made. Refer to this [document](https://docs.google.com/document/d/1erAdHB95nsyo9vXIreuDEbB9y6YrbSnwiJkOsdGRjpY/edit#heading=h.uz3b152fzpqu) for modifications.
1 front end, 1 UX
- http://localhost:8000/legal-resources/enforcement/
- http://localhost:8000/data/legal/search/adrs/
- Run this branch
- It's currently deployed to dev.fec.gov as well, so you can test components there.

Update ADR feature

---

fec/data/templates/layouts/main.jinja
fec/fec/static/scss/components/_footer.scss
fec/fec/templates/base.html
fec/fec/templates/home_base.html
fec/fec/templates/partials/footer-navigation.html
fec/home/templates/purgecss-homepage/full.html
fec/home/templates/purgecss-homepage/navs.html
package-lock.json
package.json

- Resolves #6098 
Added the taxpayer statement to the footer, and added a footer link to the accessibility statement
- UX
Changed the site footer links and added the taxpayer statement to the footer, site-wide
| Footer link layouts | Taxpayer statement |
| :---: | :---: |
| ![image](https://github.com/fecgov/fec-cms/assets/26720877/3f90b4f5-91c4-4a33-b195-c51636c2e138) ⬅️ www — local ➡️ | ![image](https://github.com/fecgov/fec-cms/assets/26720877/288088c4-98d3-479e-bab5-df8ed7f8a37b) ⬅️ www — local ➡️ |
| ![image](https://github.com/fecgov/fec-cms/assets/26720877/a70ea4dd-e75d-4289-b073-fcf3cce85da8) ⬆️ www — local ⬇️ | ![image](https://github.com/fecgov/fec-cms/assets/26720877/85d450c8-3295-416a-9db1-4c1932798a3f) ⬆️ www — local ⬇️ |
None
- pull the PR
- `npm i`
- …

PR: 6098 - footer work

---

fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
fec/fec/static/js/templates/debts.hbs
fec/fec/static/js/templates/disbursements.hbs
fec/fec/static/js/templates/independent-expenditures.hbs
fec/fec/static/js/templates/loans.hbs
fec/fec/static/js/templates/national-party-account-disbursements.hbs
fec/fec/static/js/templates/national-party-account-receipts.hbs
fec/fec/static/js/templates/party-coordinated-expenditures.hbs
fec/fec/static/js/templates/receipts.hbs
fec/fec/static/scss/components/_datatable-panel.scss

- Resolves #6292 
- Resolves #6293 
Updating the details panels' ZIP Codes for consistency, using "City, state and ZIP code" and the ZIP+4 if it's available.
- UX
- front-end
| Page  | ZIP Code format | ZIP Code label |
| :----- | :---: |  :---: | 
| [Allocated federal non-federal disbursements](http://127.0.0.1:8000/data/allocated-federal-nonfederal-disbursements/) | | 2 |
| [Debts](http://127.0.0.1:8000/data/debts/)  | 1 | 2 |
| [Disbursements](http://127.0.0.1:8000/data/disbursements/)  | | 2 |
| [Loans](http://127.0.0.1:8000/data/loans/)  | | 1 |
| [National party disbursements](http://127.0.0.1:8000/data/national-party-account-disbursements/)  | 1 | 1 |
| [National party …

6292, 6293 ZIP Codes in details panels

---

requirements.txt

- Resolves #6285 
upgrades requests to remove snyk vulnerability
1-2 reviewers
-api calls, ecfr logic, rad forms...
- pyenv activate yourvenv
- pytest
- cd fec
- test some api calls, link to ecfr
- http://127.0.0.1:8000/data/legal/search/regulations/
- cd ..
- snyk test --file=requirements.txt --package-manager=pip
(ensure the requests vuln is no longer showing up)

6258-upgrade requests

---

fec/fec/templates/home_base.html

Removed the temp test
- one?
Only the homepage

Outdated browsers banner - fix the homepage

---

manifest_prod.yml

- Increases CMS instances 
1-2 devs
-  CMS instances

[MERGE WITH GITFLOW] increase prod instances

---

fec/data/api_caller.py
fec/legal/templates/legal-admin_fine.jinja

- Front-end component of https://github.com/fecgov/openFEC/pull/6023
2-3 devs
-  legal search
https://github.com/fecgov/openFEC/pull/6023
- Dev has been re-indexed with the API changes, push this branch to dev or rebuild [here](https://app.circleci.com/pipelines/github/fecgov/fec-cms?branch=deploy-FE-changes-dev)
https://dev.fec.gov/data/legal/administrative-fine/4698/
https://dev.fec.gov/data/legal/alternative-dispute-resolution/1168/
https://dev.fec.gov/data/legal/matter-under-review/2534/

Switch af_dispositions and adr_dispositions to dispositions 

---

fec/legal/templates/legal-search-results-advisory_opinions.jinja
fec/legal/templates/legal-search-results-murs.jinja

- Resolves #6649 
(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)
-  
branch | PR
(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, …

6649 AOs & MURs Fixes

---

requirements.txt

- Resolves #6617
This PR upgrades jinja2 to remediate a snyk vulnerability.
-  templates
1. Checkout this branch 
2. Activate your virtualenv 
3. `pip install -r requirements.txt`
4. Check that vulnerability is gone: `snyk test --file=requirements.txt --package-manager=pip`
5. `cd fec/`
6.  `./manage.py runserver`
7.  Test several types of pages to make sure they render correctly (homepage, legal pages, datatables etc.)

Update jinja to a minor patch version to fix snyk vulnerability

---

fec/fec/templates/partials/footer-navigation.html
fec/home/templates/purgecss-homepage/full.html
fec/home/templates/purgecss-homepage/navs.html

- Resolves #6698 
Protected Voices removed from footer
1 engineer
-  Footer
- Check footer and make sure link is removed

[HOTFIX - MERGE WITH GITFLOW] Update footer

---

fec/home/models.py

- Resolves #6712
Add CustomPage to    `parent_page_types` for PressReleasePage so an instance of that  page-type  can be created as a child of `/updates` 
one dev
- Login to Wagtail
- Navigate to Pages > Home > Updates
- Add child page of type PressReleasePage

[MERGE WITH GIT FLOW]Hotfx to make CustomPage a parent-type for PressReleasePage

---

requirements.txt

upgrade jijna2 to fix template injection vulnerability
- Resolves # https://github.com/fecgov/fec-cms/issues/6708
1 developer
**Before: On develop branch**
- on develop branch run: `snyk test --all-projects` (snyk flag jinja2 v3.1.5  as vulnerable )
- checkout this branch:   `git checkout feature/6708-upgrade-jinja2`
- create a new virtual env: `pyenv virtualenv <new env name>`
- activate new virtual env: `pyenv activate <new env name>`
- install requirements: `pip install -r requirements.txt` and `pip install -r requirements-dev.txt`
- run: `snyk test --all-projects` (snyk NO longer flags jinja2 as vulnerable pkg)
- start server: `cd fec` and `./manage.py runserver`
- test the cms app : http://localhost:8000/

upgrade jijna2 

---

requirements.txt

- Resolves #6800 
upgrades requests to remove snyk vulnerability
1-2 reviewers
-api calls, ecfr logic, rad forms...
- pyenv activate yourvenv
- pytest
- cd fec
- test some api calls, link to ecfr
- http://127.0.0.1:8000/data/legal/search/regulations/
- cd ..
- snyk test --file=requirements.txt --package-manager=pip
(ensure the requests vuln is no longer showing up)

6800-upgrade requests

---

fec/data/constants.py
fec/data/templates/datatable.jinja
fec/data/templates/macros/page-header.jinja
fec/data/templates/partials/rulemakings-filter.jinja
fec/data/urls.py
fec/data/views_datatables.py
fec/fec/settings/base.py
fec/fec/static/js/modules/columns.js
fec/fec/static/js/modules/dropdowns.js
fec/fec/static/js/modules/tables.js
fec/fec/static/js/pages/datatable-rulemakings.js
fec/fec/static/js/templates/tables/exportWidget.hbs
fec/fec/static/scss/components/_datatables.scss
fec/fec/static/scss/components/_filters.scss
fec/legal/templates/macros/legal.jinja
fec/legal/urls.py

- Resolves #6849
- Rulemakings datatable using jQuery datatables
- Customized JS to handle the keyword modal and proximity searches
one dev, one content
New rulemakings datatable
-  
branch | PR
- Test  http://127.0.0.1:8000/legal-resources/rulemakings/
- boolean keyword searches
- proximity searches
- combined keyword and proximity searches
- combined keyword and/o proximity searches with deocument_type filter
- Pagination
- Sort

Rulemakings datatable
